Solving discover server issues on participant drop.
eProsima/Fast-DDS pull request #1267
Opened 2020-06-26 11:09 UTC by MiguelBarro

This is a backport from master to solve a client-server discovery issue.

When a client was dropped the server reported it to all other clients but didn't remove the demise client information from the PDP and EDP history. This commit fixes this issue.

2020-06-26 14:19 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2246)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2246/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2053)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2053/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2245)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2245/)

2020-07-01 15:15 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2269)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2269/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2070)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2070/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2262)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2262/)

2020-07-20 13:39 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2370)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2370/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2170)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2170/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2361)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2361/)

2020-07-20 16:52 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2371)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2371/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2171)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2171/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2362)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2362/)

2020-08-05 07:43 UTC, MiguelBarro commented on src/cpp/rtps/builtin/discovery/endpoint/EDPServer.cpp
> +        for (auto iE : readers)
👍

2020-08-06 10:46 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2476)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2476/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2289)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2289/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2480)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2480/)

2020-09-04 07:22 UTC, MiguelCompany requested changes
@MiguelBarro please rebase this and fix conflicts

2020-09-07 12:28 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2552)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2552/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2362)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2362/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2559)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2559/)

2020-09-11 05:51 UTC, MiguelCompany approved these changes

2020-09-11 05:52 UTC, merged

2020-09-11 14:25 UTC, hidmic commented
@MiguelCompany this may have broke our Windows builds.