Log - StdoutErrConsumer with tests
eProsima/Fast-DDS pull request #1340
Opened 2020-08-07 11:12 UTC by EduPonz

Signed-off-by: EduPonz <eduardoponz@eprosima.com>

2020-08-07 19:12 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2490)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2490/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2304)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2304/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2497)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2497/)

2020-08-25 07:04 UTC, LuisGP requested changes

2020-10-22 13:17 UTC, JLBuenoLopez-eProsima commented on test/unittest/rtps/writer/CMakeLists.txt
> +# Copyright 2016, 2017, 2018, 2019, 2020 Proyectos y Sistemas de Mantenimiento SL (eProsima).
It seems to be enough to keep the year of first publication. It has been fixed in all the files.

2020-10-22 15:01 UTC, MiguelCompany requested changes

2020-10-22 15:01 UTC, MiguelCompany commented on test/unittest/xmlparser/log_stdouterr_wrong_property_name.xml
> +                <name>threshold</name>
```suggestion
                <name>wrong_property_name</name>
```

2020-10-22 21:06 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2962)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2962/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=225)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/225/)
* Mac ![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=under%20maintenance&color=bbb)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2974)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2974/)

2020-10-23 10:15 UTC, JLBuenoLopez-eProsima commented on src/cpp/fastdds/log/Log.cpp
> +    resources_.consumers.emplace_back(new StdoutErrConsumer);
A new CMake option is going to be implemented to allow the user to choose the default Log Consumer without having to change his application code. By default, this option will use the current default Log Consumer (StdoutConsumer) ensuring backwards compatibility.

2020-10-26 12:15 UTC, JLBuenoLopez-eProsima commented on src/cpp/rtps/xmlparser/XMLParser.cpp
> +                        root->addChild(std::move(types_node));
Comments have been added to the code addressing this questions. It is a workaround to propagate the XML return codes upstream. Only the child type is checked in `XMLProfileManager::loadXMLFile(const std::string& filename)` so the object does not need to be populated.

2020-10-26 12:15 UTC, JLBuenoLopez-eProsima commented on src/cpp/rtps/xmlparser/XMLParser.cpp
> +                        root->addChild(std::move(log_node));
See answer above.

2020-10-26 15:15 UTC, MiguelCompany requested changes

2020-10-26 15:15 UTC, MiguelCompany commented on CMakeLists.txt
> +set(STDOUTERR_LOG_CONSUMER OFF CACHE BOOL "StdoutErr LogConsumer as default" FORCE)
I don't think we need these to be on CACHE. Could be just normal variables.

```suggestion
```

2020-10-26 15:15 UTC, MiguelCompany commented on CMakeLists.txt
> +endif()
In fact, only one of them is necessary

```suggestion
if(LOG_CONSUMER_DEFAULT STREQUAL "STDOUTERR")
    set(STDOUTERR_LOG_CONSUMER ON)
endif()
```

2020-10-26 18:50 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2996)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2996/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=243)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/243/)
* Mac ![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=under%20maintenance&color=bbb)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3007)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3007/)

2020-10-27 09:06 UTC, MiguelCompany approved these changes

2020-10-27 14:45 UTC, JLBuenoLopez-eProsima commented
Documentation pull request: eProsima /Fast-RTPS-docs#201

2020-10-27 17:59 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3001)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3001/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=246)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/246/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2691)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2691/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3012)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3012/)

2020-10-28 06:25 UTC, merged