Support colon in type name for dynamic data types
eProsima/Fast-DDS pull request #1345
Opened 2020-08-17 15:56 UTC by mdnasr

To solve #1342
This PR add support for colon ":" to data type name, to make it compatible with `module` keyword in FastDDS generator and works perfectly with ROS messages.

For example, The following XML dynamic data types will work now.

```
<types>
  <type>
    <struct name="sensor_msgs::msg::Image">
      <member name="height" type="uint32"/>
      <member name="width" type="uint32"/>
      ...
    </struct>
  </type>
</types>

```

2020-08-20 06:38 UTC, jwillemsen commented on src/cpp/dynamic-types/TypeDescriptor.cpp
>      if (sName.length() > 0 && std::isalpha(sName[0]))
``` suggestion
    if (!sName.empty() > 0 && std::isalpha(sName[0]))
```

2020-08-20 06:38 UTC, jwillemsen commented on src/cpp/dynamic-types/TypeDescriptor.cpp
>      if (sName.length() > 0 && std::isalpha(sName[0]))
std::isalpha takes current C locale into account, that doesn't seem correct at this point?

2020-08-20 06:39 UTC, jwillemsen commented on src/cpp/dynamic-types/TypeDescriptor.cpp
>          for (uint32_t i = 1; i < sName.length(); ++i)
``` suggestion
        for (size_t i = 1; i < sName.length(); ++i)
```

2020-08-20 06:39 UTC, jwillemsen commented on src/cpp/dynamic-types/TypeDescriptor.cpp
>              {
Also std::isalnum takes current C locale into account https://en.cppreference.com/w/cpp/string/byte/isalnum

2020-12-04 16:44 UTC, MiguelCompany requested changes
Changes look good to me, but could you please fix DCO and apply our [uncrustify config](https://github.com/eProsima/cpp-style/blob/master/uncrustify.cfg) to the whole file?

2021-06-07 11:14 UTC, MiguelCompany commented
Closing in favor of #1831

2021-06-07 11:14 UTC, closed without merging