Refs 9117. Initialize serialized payload buffer on realloc
eProsima/Fast-DDS pull request #1348
Opened 2020-08-27 10:23 UTC by IkerLuengo

This prevents memcheck complaining about uninitialized memory access
if the serialization skips writing some bytes due to memory alignment.

Also modified a couple of alignment paddings on the serialization of
parameters.

2020-08-27 10:26 UTC, IkerLuengo commented
This solves the uninitialized memory access reported on #1346

2020-08-27 13:35 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2492)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2492/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2306)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2306/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2499)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2499/)

2020-09-01 05:50 UTC, MiguelCompany requested changes

2020-09-01 05:50 UTC, MiguelCompany commented on src/cpp/fastdds/core/policy/ParameterSerializer.hpp
> +    valid &= fastrtps::rtps::CDRMessage::addUInt16(cdr_message, 0); //padding
This is writing on cdr_message, but this is a `read` method (same below)

2020-09-01 07:25 UTC, MiguelCompany approved these changes
LGTM

2020-09-01 09:38 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2503)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2503/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2317)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2317/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2510)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2510/)

2020-09-02 07:22 UTC, merged