Refs: #9126 Update CMakeLists.txt not setting C++11 compiler flag.
eProsima/Fast-DDS pull request #1349
Opened 2020-08-28 09:54 UTC by JLBuenoLopez-eProsima

Update CMakeLists.txt not setting C++11 compiler flag.
Update Examples README.txt

Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>

2020-08-28 13:27 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2493)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2493/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2307)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2307/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2500)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2500/)

2020-09-03 09:42 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2532)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2532/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2343)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2343/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2539)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2539/)

2020-09-04 11:01 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2543)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2543/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2354)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2354/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2550)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2550/)

2020-09-18 09:02 UTC, laura-eprosima requested changes

2020-09-18 09:02 UTC, laura-eprosima commented on examples/C++/DDS/Keys/README.txt
> +To launch this test execute './DDSKeys' (or DDSKeys.exe on windows).
It also allows the execution of publisher and subscriber separately

2020-09-18 09:02 UTC, laura-eprosima commented on examples/C++/SampleConfig_Events/README.txt
> +To launch this test execute: './sampleconfig_events' (or DDSSampleConfigEvents.exe on windows).
```suggestion
To launch this test execute: './sampleconfig_events' (or sampleconfig_events.exe on windows).
```

2020-09-18 09:02 UTC, laura-eprosima commented on examples/C++/SampleConfig_Multimedia/README.txt
> +To launch this test execute: './sampleconfig_multimedia' (or DDSSampleConfigMultimedia.exe on windows).
```suggestion
To launch this test execute: './sampleconfig_multimedia' (or sampleconfig_multimedia.exe on windows).
```

2020-09-18 11:05 UTC, laura-eprosima approved these changes

2020-09-18 13:55 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2641)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2641/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=53)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/53/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2456)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2456/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2651)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2651/)

2020-09-18 14:05 UTC, merged