Feature/skip xml [9139]
eProsima/Fast-DDS pull request #1350
Opened 2020-08-28 10:36 UTC by imontesino

Added environment variable SKIP_DEFAULT_XML_FILE to skip over searching for the default file. Also added a unit test for it.

2020-08-28 11:03 UTC, EduPonz requested changes
Partial review

2020-08-28 11:03 UTC, EduPonz commented on src/cpp/rtps/xmlparser/XMLProfileManager.cpp
> +    if (!std::getenv("SKIP_DEFAULT_XML_FILE"))
On `WIN32` you are checking whether the value of the variable is `1`, however there is no check in Linux. I'd add the same for consistency

2020-08-28 14:03 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2495)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2495/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2309)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2309/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2502)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2502/)

2020-08-31 08:55 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2497)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2497/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2311)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2311/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2504)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2504/)

2020-08-31 12:56 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2500)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2500/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2314)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2314/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2507)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2507/)

2020-09-24 10:42 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2657)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2657/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=69)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/69/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2470)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2470/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2667)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2667/)

2020-09-24 10:43 UTC, MiguelCompany commented
New tests failing on two platforms. I canceled the jobs for the other two

2020-09-24 22:57 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2672)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2672/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=75)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/75/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2476)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2476/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2682)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2682/)

2020-09-25 05:12 UTC, MiguelCompany commented
Seems the unit tests have been fixed. We need a PR against docs adding the new environment variable before merging this one.

2020-09-25 08:50 UTC, imontesino commented
Addded documentation in eProsima/Fast-RTPS-docs#195

2020-09-28 06:57 UTC, merged