Return false if type not found unregistering type
eProsima/Fast-DDS pull request #1355
Opened 2020-09-01 07:24 UTC by IkerLuengo

Return `false` if the type is not registered.
This is in line with the registration, that returns `false` if the type is already registered.

2020-09-01 11:11 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2507)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2507/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2320)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2320/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2514)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2514/)

2020-09-02 06:18 UTC, MiguelCompany approved these changes
LGTM

2020-09-02 07:31 UTC, MiguelCompany requested changes
I would refactor this so the method starts with `retValue = false` and we only set it to `true` after line 456.

2020-09-02 11:03 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2514)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2514/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2327)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2327/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2521)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2521/)

2020-09-02 12:27 UTC, MiguelCompany approved these changes

2020-09-02 12:28 UTC, merged