fixed warnings
eProsima/Fast-DDS pull request #1357
Opened 2020-09-01 08:44 UTC by MiguelCompany

Port of #1290 

* fixed warnings

Signed-off-by: ahcorde <ahcorde@gmail.com>

* Added cosmetic suggestions

Signed-off-by: ahcorde <ahcorde@gmail.com>

2020-09-01 12:07 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2508)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2508/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2321)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2321/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2515)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2515/)

2020-09-01 16:35 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2509)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2509/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2322)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2322/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2516)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2516/)

2020-09-03 13:41 UTC, IkerLuengo submitted a review, later dismissed
LGTM

2020-09-16 09:54 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2601)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2601/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2417)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2417/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2611)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2611/)

2020-10-16 07:11 UTC, IkerLuengo requested changes

2020-10-16 07:11 UTC, IkerLuengo commented on include/fastrtps/utils/collections/ResourceLimitedVector.hpp
> +    }
```suggestion
    operator const collection_type& () const noexcept
    {
        return collection_;
    }
```

2020-10-16 07:41 UTC, IkerLuengo submitted a review, later dismissed
LGTM

2020-10-16 11:44 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2910)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2910/)
* Linux aarch64![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=not%20run&color=bbb)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2662)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2662/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2921)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2921/)

2020-11-03 15:03 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3050)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3050/)
* Linux aarch64![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=not%20run&color=bbb)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2733)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2733/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3061)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3061/)

2020-11-05 06:46 UTC, IkerLuengo approved these changes
LGTM

2020-11-05 06:56 UTC, merged