[9137] Removing C++17 warnings from sources
eProsima/Fast-DDS pull request #1359
Opened 2020-09-02 05:33 UTC by MiguelBarro

This pull request addresses the issue #1275.

C++ 17 deprecated classes were removed and replaced with compliant code:
- std::iterator and std::unary_function as base classes.
- std::wstring_convert as string conversion utility.

Note that Fast-DDS is not yet fully complaint because the boost sources introduced for shared memory transport sake are not. In order to avoid the use of boost sources:
- cmake variable `SHM_TRANSPORT_DEFAULT=OFF`
- set only /std:c++17 for the Fast-DDS sources only by adding to the CMakeLists.txt:
```cmake
 target_compile_options(${PROJECT_NAME} PRIVATE /std:c++17)
```

2020-09-02 06:36 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2511)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2511/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2324)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2324/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2518)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2518/)

2020-09-02 13:56 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2520)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2520/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2333)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2333/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2527)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2527/)

2020-09-02 20:16 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2528)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2528/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2339)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2339/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2535)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2535/)

2020-09-03 09:50 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2533)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2533/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2344)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2344/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2540)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2540/)

2020-09-16 16:41 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2606)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2606/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2422)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2422/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2616)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2616/)

2020-09-24 17:54 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2667)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2667/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=72)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/72/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2473)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2473/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2677)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2677/)

2020-10-01 05:31 UTC, EduPonz requested changes
Please uncrustify

2020-10-05 11:19 UTC, MiguelCompany commented
@imontesino  This has to be rebased

2020-10-05 19:35 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2806)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2806/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=151)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/151/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2576)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2576/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2818)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2818/)

2020-10-06 05:29 UTC, MiguelCompany requested changes

2020-10-06 05:29 UTC, MiguelCompany commented on include/fastrtps/utils/fixed_size_bitmap.hpp
> +#include <cstdint>
This line is duplicated. Please remove it.

2020-10-06 22:43 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2816)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2816/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=158)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/158/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2586)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2586/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2828)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2828/)

2020-10-07 06:33 UTC, MiguelCompany approved these changes

2020-10-07 06:34 UTC, MiguelCompany commented
Not waiting for tests, since there have only been linter changes after the last ones, which were OK.

2020-10-07 06:35 UTC, merged