Added target reference instead of library path [9204]
eProsima/Fast-DDS pull request #1366
Opened 2020-09-03 07:45 UTC by imontesino

Tested with tinyxml2 versions >=2.0.1

Signed-off-by: imontesino <monte.igna@gmail.com>

2020-09-07 13:20 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2555)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2555/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2365)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2365/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2562)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2562/)

2020-09-07 14:05 UTC, MiguelBarro submitted a review, later dismissed
All possible cases (external repo, thirdparty and framework dependency) run well on windows.
LGTM

2020-09-21 06:38 UTC, laura-eprosima requested changes

2020-09-21 06:38 UTC, laura-eprosima commented on src/cpp/CMakeLists.txt
> +        message("You are using CMake version less than 3.13.0. This may cause linking problems when cross compiling")
```suggestion
        message("You are using CMake version lower than 3.13.0. This may cause linking problems when cross-compiling")
```

2020-09-21 07:08 UTC, laura-eprosima approved these changes

2020-09-21 10:09 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2644)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2644/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=56)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/56/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2459)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2459/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2654)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2654/)

2020-10-21 09:36 UTC, MiguelCompany requested changes
Fails when building on Windows with `-DEPROSIMA_BUILD=OFF` and TinyXML2 installed via chocolatey.

```
[0.219s] Invoking command in 'C:\eProsima\colcon_test_master\build\fastrtps': CMAKE_PREFIX_PATH=C:\eProsima\colcon_test_master\install\foonathan_memory_vendor;C:\eProsima\colcon_test_master\install\fastcdr PKG_CONFIG_PATH=C:\eProsima\colcon_test_master\install\foonathan_memory_vendor\lib\pkgconfig Path=C:\eProsima\colcon_test_master\install\foonathan_memory_vendor\bin;C:\eProsima\colcon_test_master\install\fastcdr\bin;%Path% C:\Program Files\CMake\bin\cmake.EXE C:\eProsima\colcon_test_master\src\fastrtps -T v142 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSECURITY=ON -DEPROSIMA_BUILD=OFF -DINTERNAL_DEBUG=ON -DGTEST_INDIVIDUAL=ON -DFASTRTPS_API_TESTS=ON -DFASTDDS_PIM_API_TESTS=ON -DPERFORMANCE_TESTS=OFF -DNO_TLS=ON -DMEMORYCHECK_COMMAND_OPTIONS=-q --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=50 --xml=yes --xml-file=test_%p_memcheck.xml -DMEMORYCHECK_SUPPRESSIONS_FILE=../../src/fastrtps/valgrind.supp -DCMAKE_INSTALL_PREFIX=C:\eProsima\colcon_test_master\install\fastrtps
[0.250s] -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
[0.282s] -- Configuring Fast RTPS
[0.282s] -- Version: 2.1.0
[0.282s] -- To change the version modify the file configure.ac
[0.282s] -- Found fastcdr
[0.297s] -- Found Asio
[0.297s] -- Found Asio
[0.641s] -- Found TinyXML2: C:/ProgramData/chocolatey/lib/tinyxml2/share/cmake
[0.641s] -- Found TinyXML2
[0.641s] -- Found foonathan_memory: C:/eProsima/colcon_test_master/install/foonathan_memory_vendor/share/foonathan_memory/cmake
[4.141s] -- Thirdparty/boost compiled OK
[4.141s] -- OpenSSL library 1.1.1f found...
[4.422s] CMake Error at src/cpp/CMakeLists.txt:400 (get_filename_component):
[4.422s]   get_filename_component unknown component
[4.422s]   C:/ProgramData/chocolatey/lib/tinyxml2/lib/tinyxml2d.lib
[4.422s] 
[4.422s] 
[4.422s] CMake Error at src/cpp/CMakeLists.txt:401 (get_filename_component):
[4.422s]   get_filename_component unknown component
[4.422s]   C:/ProgramData/chocolatey/lib/tinyxml2/lib/tinyxml2d.lib
[4.422s] 
[4.422s] 
[5.485s] -- Configuring incomplete, errors occurred!
[5.485s] See also "C:/eProsima/colcon_test_master/build/fastrtps/CMakeFiles/CMakeOutput.log".
[5.485s] See also "C:/eProsima/colcon_test_master/build/fastrtps/CMakeFiles/CMakeError.log".
[5.485s] Invoked command in 'C:\eProsima\colcon_test_master\build\fastrtps' returned '1': CMAKE_PREFIX_PATH=C:\eProsima\colcon_test_master\install\foonathan_memory_vendor;C:\eProsima\colcon_test_master\install\fastcdr PKG_CONFIG_PATH=C:\eProsima\colcon_test_master\install\foonathan_memory_vendor\lib\pkgconfig Path=C:\eProsima\colcon_test_master\install\foonathan_memory_vendor\bin;C:\eProsima\colcon_test_master\install\fastcdr\bin;%Path% C:\Program Files\CMake\bin\cmake.EXE C:\eProsima\colcon_test_master\src\fastrtps -T v142 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSECURITY=ON -DEPROSIMA_BUILD=OFF -DINTERNAL_DEBUG=ON -DGTEST_INDIVIDUAL=ON -DFASTRTPS_API_TESTS=ON -DFASTDDS_PIM_API_TESTS=ON -DPERFORMANCE_TESTS=OFF -DNO_TLS=ON -DMEMORYCHECK_COMMAND_OPTIONS=-q --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=50 --xml=yes --xml-file=test_%p_memcheck.xml -DMEMORYCHECK_SUPPRESSIONS_FILE=../../src/fastrtps/valgrind.supp -DCMAKE_INSTALL_PREFIX=C:\eProsima\colcon_test_master\install\fastrtps
```

2023-06-20 09:06 UTC, EduPonz commented
I'm going to close this PR ad no one has complained since. The problem likely remains, but we simply cannot tackle it for now.

2023-06-20 09:06 UTC, closed without merging