Enforce use of libraries in thirdparty with option THIRDPARTY_FORCE
eProsima/Fast-DDS pull request #1375
Opened 2020-09-07 07:19 UTC by EduPonz

This PR:

* Adds cmake option `THIRDPARTY_FORCE` to force the use of third party packages, regardless of whether they are installed elsewhere.
* Unifies behaviour of `eprosima_find_package` and `eprosima_find_thirdparty`, that is:
    1. Force use of third party packages if `THIRDPARTY_FORCE`
    1. In the case of just `THIRDPARTY`, only use the third party packages if they could not be found elsewhere.
    1. Only update sub-modules if `THIRDPARTY_UPDATE`
* Improves cmake traces.
* Improvement of `FindTinyXML2.cmake`, which now checks for `THIRDPARTY OR THIRDPARTY_FORCE OR THIRDPARTY_TinyXML2`, instead of just `THIRDPARTY`.

Please, do not merge until a related PR in https://github.com/eProsima/Fast-RTPS-docs is also ready to merge. I'll only address that when this PR is approved.

2020-09-07 09:43 UTC, MiguelCompany requested changes
Apart from my comments below, I think that instead of adding a new option `THIRDPARTY_FORCE` it would be better to have three possible values (`OFF`, `ON` and `FORCE`) for both `THIRDPARTY` and `THIRDPARTY_${package}`

2020-09-07 09:43 UTC, MiguelCompany commented on cmake/common/eprosima_libraries.cmake
> +        # if if was not found but it was not required show a warning.
```suggestion
        # If the package was found we have already shown a status message.
        # if it was not found and it was required, throw a fatal error.
        # if it was not found but it was not required, show a warning.
```

2020-09-07 09:43 UTC, MiguelCompany commented on cmake/common/eprosima_libraries.cmake
> +#   :THIRDPARTY_FORCE: Force the use of internal thirdparties [Defaults: OFF]. Set to ON if EPROSIMA_BUILD is set to ON.
Looking at the code below, I see that `EPROSIMA_BUILD` sets `THIRDPARTY` to ON, not `THIRDPARTY_FORCE`. Either change the behavior or the documentation.

2020-09-07 09:43 UTC, MiguelCompany commented on cmake/common/eprosima_libraries.cmake
> +#   :THIRDPARTY: Activate the use of internal thirdparties if external packges is not found [Defaults: OFF]
```suggestion
#   :THIRDPARTY: Activate the use of internal thirdparties if external packges are not found [Defaults: OFF]
```

2020-09-07 09:43 UTC, MiguelCompany commented on cmake/common/eprosima_libraries.cmake
> +#   :THIRDPARTY_FORCE: Force the use of internal thirdparties [Defaults: OFF]. Set to ON if EPROSIMA_BUILD is set to ON.
Looking at the code below, I see that `EPROSIMA_BUILD` sets `THIRDPARTY` to ON, not `THIRDPARTY_FORCE`. Either change the behavior or the documentation.

2020-09-07 09:43 UTC, MiguelCompany commented on cmake/common/eprosima_libraries.cmake
> +        option(THIRDPARTY "Activate the use of internal thirdparties if external packges is not found" OFF)
```suggestion
        option(THIRDPARTY "Activate the use of internal thirdparties if external packages are not found" OFF)
```

2020-09-07 09:43 UTC, MiguelCompany commented on cmake/common/eprosima_libraries.cmake
> +            # Try to quetly find the package outside thridparty first.
```suggestion
            # Try to quietly find the package outside thridparty first.
```

2020-09-07 09:43 UTC, MiguelCompany commented on cmake/common/eprosima_libraries.cmake
> +    option(THIRDPARTY "Activate the use of internal thirdparties if external packges is not found" OFF)
```suggestion
    option(THIRDPARTY "Activate the use of internal thirdparties if external packages are not found" OFF)
```

2020-09-07 09:43 UTC, MiguelCompany commented on cmake/common/eprosima_libraries.cmake
> +        # Try to quetly find the package outside thridparty first.
```suggestion
        # Try to quietly find the package outside thridparty first.
```

2020-09-07 10:59 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2551)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2551/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2361)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2361/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2558)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2558/)

2020-09-09 09:57 UTC, EduPonz commented
I have taken upon your suggestion of having a three-value option for `THIRDPARTY` and `THIRDPARTY_${package}`. The possible values are `ON`, `OFF` and `FORCE`. `THIRDPARTY_${package}` is set to `THIRDPARTY` unless user specifies otherwise.

2020-09-09 13:30 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2561)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2561/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2371)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2371/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2568)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2568/)

2020-09-21 08:30 UTC, IkerLuengo requested changes
Just some mods to make branches easier to read

2020-09-24 07:48 UTC, EduPonz commented on cmake/modules/FindTinyXML2.cmake
>          find_path(TINYXML2_INCLUDE_DIR NAMES tinyxml2.h)
:+1:

2020-09-24 07:48 UTC, EduPonz commented on cmake/common/eprosima_libraries.cmake
> +    # if if was not found but it was not required show a warning.
:+1:

2020-09-24 07:49 UTC, EduPonz commented on cmake/common/eprosima_libraries.cmake
> +        message(STATUS "${package} package NOT found")
:+1

2020-09-24 09:18 UTC, IkerLuengo approved these changes
LGTM

2020-09-24 12:46 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2659)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2659/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=70)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/70/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2471)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2471/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2669)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2669/)

2020-09-24 13:28 UTC, MiguelCompany commented
Failed test being marked flaky on #1411

2020-09-24 13:29 UTC, merged