Feature/discovery server/data structures
eProsima/Fast-DDS pull request #1406
Opened 2020-09-23 14:56 UTC by jparisu

All interface DDB to PDPServer2
new directory discovery/database
change in CMakeList to not force c++11

2020-09-23 19:05 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2655)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2655/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=67)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/67/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2468)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2468/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2665)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2665/)

2020-09-24 08:14 UTC, EduPonz requested changes
Some minor things

2020-09-24 08:14 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataQueueInfo.cpp
> +} /* namespace eprosima */
Please, add blank line at the end of the file

2020-09-24 08:14 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataQueueInfo.cpp
> +} /* namespace eprosima */
In general, please add a blank line to the end of the file

2020-09-24 08:17 UTC, EduPonz requested changes

2020-09-24 08:17 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
> +        eprosima::fastrtps::rtps::CacheChange_t* cache_;
I think `change` is clearer. Update in cpp.
```suggestion
        eprosima::fastrtps::rtps::CacheChange_t* change_;
```

2020-09-24 09:02 UTC, EduPonz approved these changes
LGTM. Please uncrustify

2020-09-24 09:16 UTC, merged