Deprecate methods on History [9476]
eProsima/Fast-DDS pull request #1438
Opened 2020-10-01 05:58 UTC by MiguelCompany

2020-10-01 17:29 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2761)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2761/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=129)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/129/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2540)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2540/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2773)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2773/)

2020-10-05 06:09 UTC, IkerLuengo requested changes
More than deprecate, this removes the functionality.
We should mark the methods as deprecated, but keep the functionality until it is finally removed.

2020-10-05 12:46 UTC, IkerLuengo approved these changes
LGTM

2020-10-05 12:46 UTC, IkerLuengo commented on include/fastdds/rtps/history/History.h
>      //!Print the seqNum of the changes in the History (for debuggisi, mng purposes).
I'm not going to ask for a change due to this, but if another commit is necessary for some reason, can we take the opportunity to correct this documentation here?

2020-10-05 14:36 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2801)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2801/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=148)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/148/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2571)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2571/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2813)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2813/)

2020-10-06 11:03 UTC, merged