Server dedicated thread for routine processing
eProsima/Fast-DDS pull request #1440
Opened 2020-10-01 14:47 UTC by rsanchez15

2020-10-01 21:47 UTC, EduPonz requested changes
Please rebase to testing

2020-10-01 21:47 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +    return data_queue_.Empty();
I think this returns whether the Foreground queue is empty, where the Server pushes changes to the background queue. Foreground queue will always be empty after `process_data_queue()`. I think the easiest would be to check if both foreground and background are empty.
```suggestion
    return data_queue_.BothEmpty();
```

2020-10-01 21:47 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/participant/PDPServer2.hpp
> +    void awakeServerThread(
I'd call this function with snake case: `awake_server_thread()`

2020-10-01 21:47 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/participant/PDPServer2.hpp
> +    eprosima::fastrtps::rtps::ResourceEvent& getResouceEventThread();
Same here

2020-10-01 21:47 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/participant/PDPServerListener2.cpp
>                  // Ensure processing time for the cache by triggering the Server thread (which process the updates
Merge this two comments

2020-10-01 21:47 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
> +        result = pending_ack();                           // all server
I think we need to explain why `result` comes from this function and what does it mean. Probably we can rename `result` to `pending_work` to make it clearer

2020-10-01 21:47 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
> +    while (!discovery_db_.data_queue_empty());
Explain why we need the `do-while`

2020-10-01 21:47 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
> +eprosima::fastrtps::rtps::ResourceEvent& PDPServer2::getResouceEventThread()
snake case?

2020-10-01 21:47 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
>      awakeServerThread();
I'd leave the first awaken for the first data received/added to the database, either by listeners or `PDPServer2::announceParticipantState()`

2020-10-02 04:25 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2764)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2764/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=131)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/131/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2543)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2543/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2776)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2776/)

2020-10-06 07:04 UTC, jparisu approved these changes
LGTM

2020-10-06 07:05 UTC, merged