Use new IPayloadPool API on processDataMsg
eProsima/Fast-DDS pull request #1461
Opened 2020-10-06 11:19 UTC by MiguelCompany

2020-10-07 06:03 UTC, IkerLuengo requested changes

2020-10-07 06:03 UTC, IkerLuengo commented on src/cpp/rtps/reader/StatefulReader.cpp
> +                        << m_guid << " is " << fixed_payload_size_);
```suggestion
                logWarning(RTPS_MSG_IN, IDSTRING "Problem copying CacheChange, received data is: "
                        << change->serializedPayload.length << " bytes and max size in reader "
                        << m_guid << " is " << (fixed_payload_size_ > 0 ? fixed_payload_size_ : std::numeric_limits<uint32_t>::max());
```

2020-10-07 14:08 UTC, IkerLuengo approved these changes
:+1:

2020-10-08 13:37 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2843)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2843/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=170)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/170/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2607)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2607/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2860)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2860/)

2020-10-08 14:21 UTC, merged