Backport #1457 into 2.0.x [9545]
eProsima/Fast-DDS pull request #1469
Opened 2020-10-08 07:00 UTC by imontesino

Backport support for new [foonathan_memory](https://github.com/foonathan/memory) API.

2020-10-08 07:12 UTC, MiguelCompany requested changes

2020-10-08 07:12 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ProxyHashTables.hpp
> +        : block_size_(allocator_type::min_block_size(node_size, nodes_to_allocate ? nodes_to_allocate : 1))
Children classes already take into account that nodes_to_allocate should be greater than 0
```suggestion
        : block_size_(allocator_type::min_block_size(node_size, nodes_to_allocate))
```

2020-10-08 08:32 UTC, MiguelCompany approved these changes

2020-10-09 09:15 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2851)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2851/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=173)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/173/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2613)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2613/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2868)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2868/)

2020-10-09 09:18 UTC, merged