RTPS reader creation with custom payload pool [9494]
eProsima/Fast-DDS pull request #1476
Opened 2020-10-09 07:10 UTC by MiguelCompany

2020-10-09 12:34 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2868)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2868/)
* Linux aarch64![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=not%20run&color=bbb)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2626)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2626/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2882)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2882/)

2020-10-13 05:50 UTC, MiguelCompany commented
Launched Linux CI with ` -R RTPSCustomPools` to check leaks on new tests:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2874)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2874/)

2020-10-13 07:16 UTC, IkerLuengo requested changes

2020-10-13 09:10 UTC, IkerLuengo approved these changes
LGTM

2020-10-13 09:22 UTC, merged