[Discovery Server] Reset and destroy database
eProsima/Fast-DDS pull request #1478
Opened 2020-10-09 13:08 UTC by EduPonz

This PR provides a mechanism to cleanly resetting or destroying `DiscoveryDatabase`
1. Provides `DiscoveryDatabase::disable()`. If the database is disabled, it cannot be updated.
1. Provides `DiscoveryDatabase::clear()` to correctly clear the database, emptying all the collections. This functions returns the set of `CacheChange_t` that the database owned, thus passing the ownership to the caller.
1. Extends `~PDPServer2()` to disable and clear `DiscoveryDatabase`, releasing the `CacheChange_t` changes that were onwed by the database

Merge after #1473

2020-10-13 14:46 UTC, jparisu requested changes
fix minor issues

2020-10-13 14:46 UTC, jparisu commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
>          const eprosima::fastrtps::rtps::GUID_t& reader_guid) const
It does not look like it, but we must be sure that is_relevant (and the rest of public API) will not break the program in a disabled state.

2020-10-13 14:46 UTC, jparisu commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +        unmatch_writer_(writers_it->first);
there is not need to unmatch writer

2020-10-13 14:46 UTC, jparisu commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +        unmatch_reader_(readers_it->first);
same as with writer

2020-10-13 14:46 UTC, jparisu commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +        unmatch_participant_(participant.first);
same as with writer

2020-10-13 14:46 UTC, jparisu commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +    std::vector<fastrtps::rtps::CacheChange_t*> changes_to_release = changes_to_release_;
I would change the name of the variable to make it more reader friendly

2020-10-13 15:43 UTC, jparisu requested changes
Function `add_ack_` in DDB needs as well to be protected in case of disabled.

2020-10-13 15:43 UTC, jparisu commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +        logError(DISCOVERY_DATABASE, "Discovery Database is disabled");
Warning was ok. With multiple threads it could happen, the important fact is that we do not process it if disabled.

2020-10-13 15:43 UTC, jparisu commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
>  bool DiscoveryDataBase::pdp_is_relevant(
is_relevant functions must also check if ddb is disabled.

2020-10-13 15:43 UTC, jparisu commented on src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
> +    discovery_db_.disable();
before disabled the DDB, the PDPServer must stop the routine thread (`cancel_timer()`)

2020-10-15 16:26 UTC, EduPonz commented
Close in favor of #1485 and #1473

2020-10-15 16:26 UTC, closed without merging