Added methods to get qos defined in XML Profile [9607]
eProsima/Fast-DDS pull request #1482
Opened 2020-10-13 10:56 UTC by imontesino

2020-10-13 13:45 UTC, JLBuenoLopez-eProsima requested changes
There are a couple of things that should be done for all the methods. I have not written a comment every time a change should be made.

The review is summed up in:
* Use RETCODE_BAD_PARAMETER when the profile is not found. Do not return RETCODE_OK always.
* Modify the Impl methods to use the same signature as the non-Impl methods.
```
ReturnCode_t get_[ENTITY]_qos_from_profile(
        const std::string& profile_name,
        [ENTITY]Qos& qos) const;
```

2020-10-13 13:45 UTC, JLBuenoLopez-eProsima commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +{
Change the method signature as explained above (apply also to `get_subscriber_qos_from_profile` and `get_topic_qos_from_profile`.
Follow the same logic used in `DomainParticipantFactory::get_participant_qos_from_profile`

2020-10-13 13:45 UTC, JLBuenoLopez-eProsima commented on src/cpp/fastdds/domain/DomainParticipant.cpp
> +    qos = impl_->get_publisher_qos_from_profile(profile_name);
```suggestion
    return impl_->get_publisher_qos_from_profile(profile_name, qos);
```

2020-10-13 14:14 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2879)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2879/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=182)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/182/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2634)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2634/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2890)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2890/)

2020-10-13 15:04 UTC, imontesino commented on src/cpp/fastdds/domain/DomainParticipantFactory.cpp
> +using eprosima::fastrtps::rtps::RTPSParticipantAttributes;
No, it was from an earlier version of this functionality.

2020-10-13 17:47 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2882)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2882/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=184)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/184/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2637)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2637/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2893)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2893/)

2020-10-14 05:45 UTC, JLBuenoLopez-eProsima reviewed
Please, update Doxygen documentation taking into account that the methods could also return RETCODE_BAD_PARAMETER

2020-10-14 05:45 UTC, JLBuenoLopez-eProsima commented on include/fastdds/dds/domain/DomainParticipant.hpp
> +     * @return RETCODE_OK
Please, update Doxygen documentation for all the previous methods explaining the return RETCODEs.

2020-10-15 06:44 UTC, JLBuenoLopez-eProsima submitted a review, later dismissed
LGTM. Please add tests to this new feature and update the documentation.

2020-10-15 10:28 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2897)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2897/)
* Linux aarch64![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=not%20run&color=bbb)
* Mac ![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=not%20run&color=bbb)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2907)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2907/)

2020-10-16 09:56 UTC, JLBuenoLopez-eProsima requested changes
Consider the following points:
* Check after creation of each entity that it has been correctly created (as it is done in other tests)
* Maybe you can use EXPECT_* instead of ASSERT_*. EXPECT makes the test fail too but it continues the test until the end. Only use EXPECT when the test could not keep running (i.e. Use ASSERT to check the creation of the entities, because if the entity is not created the test could not keep going)

2020-10-16 09:56 UTC, JLBuenoLopez-eProsima commented on test/unittest/dds/participant/ParticipantTests.cpp
> +    // Extract ParticipantQos form profile
```suggestion
    // Extract ParticipantQos from profile
```

2020-10-16 09:56 UTC, JLBuenoLopez-eProsima commented on test/unittest/dds/participant/ParticipantTests.cpp
> +    // Clean up
This comment should be after this instruction. Here something like
`// Test return when a non-existent profile is used`
should be.

2020-10-16 09:56 UTC, JLBuenoLopez-eProsima commented on test/unittest/dds/participant/ParticipantTests.cpp
> +
You should check that the subscriber has been correctly created

2020-10-16 09:56 UTC, JLBuenoLopez-eProsima commented on test/unittest/dds/participant/ParticipantTests.cpp
> +
Same as above: check that it has been correctly created

2020-10-16 09:56 UTC, JLBuenoLopez-eProsima commented on test/unittest/dds/participant/ParticipantTests.cpp
> +    // Clean up
This comment should be after this instruction

2020-10-16 09:56 UTC, JLBuenoLopez-eProsima commented on test/unittest/dds/participant/ParticipantTests.cpp
> +    Topic* topic = participant->create_topic("footopic", type.get_type_name(), qos);
Check that it has been created correctly

2020-10-16 09:56 UTC, JLBuenoLopez-eProsima commented on test/unittest/dds/participant/ParticipantTests.cpp
> +    // Clean up
Move comment after following instruction

2020-10-16 09:56 UTC, JLBuenoLopez-eProsima commented on test/unittest/dds/publisher/PublisherTests.cpp
> +    Publisher* publisher = participant->create_publisher(PUBLISHER_QOS_DEFAULT);
Check all entities are correctly created as it is done in other tests

2020-10-16 09:56 UTC, JLBuenoLopez-eProsima commented on test/unittest/dds/subscriber/SubscriberTests.cpp
> +    DomainParticipant* participant =
Same comments as in other tests

2020-10-16 09:56 UTC, JLBuenoLopez-eProsima commented on test/unittest/dds/participant/ParticipantTests.cpp
> +    check_subscriber_with_profile(default_subscriber, "test_subscriber_profile");
Why have you change this test?

2020-10-16 10:48 UTC, imontesino commented on test/unittest/dds/participant/ParticipantTests.cpp
> +    check_subscriber_with_profile(default_subscriber, "test_subscriber_profile");
It is a mistake, it has now been reset.

2020-10-16 11:27 UTC, JLBuenoLopez-eProsima approved these changes
LGTM

2020-10-17 10:59 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2920)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2920/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=203)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/203/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2670)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2670/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2931)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2931/)

2020-10-21 08:16 UTC, merged