Use topic payload pool on user created endpoints [9605]
eProsima/Fast-DDS pull request #1488
Opened 2020-10-14 13:04 UTC by MiguelCompany

2020-10-14 16:15 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2894)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2894/)
* Linux aarch64![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=not%20run&color=bbb)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2647)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2647/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2904)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2904/)

2020-10-15 07:01 UTC, IkerLuengo requested changes

2020-10-15 07:01 UTC, IkerLuengo commented on src/cpp/rtps/history/PoolConfig.h
> +                    history_attr.maximumReservedCaches <= 0 ? 0 : history_attr.maximumReservedCaches + 1)
I miss a comment explaining why this `+1` is necessary

2020-10-15 09:32 UTC, IkerLuengo approved these changes
LGTM

2020-10-15 09:40 UTC, merged