Keep pending security messages directed for each local endpoint [9621]
eProsima/Fast-DDS pull request #1490
Opened 2020-10-15 10:05 UTC by IkerLuengo

`VolatileSecureMessage`s received for local endpoints that still didn't discover the remote endpoint are stored to be processed when the local endpoint discovers the remote one. The `SecurityManager` keeps them on a map keyed by the remote endpoint GUID.

But if the remote endpoint matches with multiple local endpoints, multiple `VolatileSecureMessage` will be received, one per match. However, all of them share the same origin GUID, so only a single copy will be stored on the map. Once the first local endpoint discovers the remote and completes the security processing, it will remove the message from the map of pendings, leaving the rest of the local endpoints without the required information to complete the matching.

Instead of using the remote GUID as key, we should be using the combination of the remote GUID and the GUID of the local endpoint to which the message was sent. Then each local endpoint will be able to find its copy of the message.

2020-10-15 10:44 UTC, MiguelCompany requested changes
Would be nice to have a blackbox test with several secure endpoints on the same participant

2020-10-16 08:22 UTC, MiguelCompany approved these changes
LGTM

2020-10-16 11:07 UTC, MiguelCompany approved these changes
LGTM

2020-10-16 19:03 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2911)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2911/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=198)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/198/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2663)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2663/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2922)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2922/)

2020-10-19 05:13 UTC, merged