Fix transient local retransmission after participant drop [9630]
eProsima/Fast-DDS pull request #1497
Opened 2020-10-16 10:46 UTC by MiguelCompany

2020-10-16 13:40 UTC, richiware requested changes

2020-10-16 13:40 UTC, richiware commented on include/fastdds/rtps/builtin/discovery/endpoint/EDP.h
> +            bool removed_by_lease);
Doxygen documentation.

2020-10-16 13:40 UTC, richiware commented on include/fastdds/rtps/reader/RTPSReader.h
> +            bool removed_by_lease = false) = 0;
Doxygen documentation.

2020-10-16 13:40 UTC, richiware commented on include/fastdds/rtps/reader/RTPSReader.h
> +            bool removed_by_lease);
Doxygen documentation.

2020-10-17 08:10 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2916)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2916/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=202)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/202/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2668)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2668/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2927)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2927/)

2020-10-20 05:47 UTC, richiware submitted a review, later dismissed

2020-10-20 05:48 UTC, richiware commented
Please, rebase this PR

2020-10-20 05:55 UTC, MiguelCompany commented
> Please, rebase this PR

done

2020-10-26 06:56 UTC, richiware approved these changes

2020-10-26 13:20 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2983)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2983/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=238)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/238/)
* Mac ![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=under%20maintenance&color=bbb)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2993)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2993/)

2020-10-26 14:38 UTC, merged