[Discovery Server] Send new updates
eProsima/Fast-DDS pull request #1499
Opened 2020-10-16 14:59 UTC by jparisu

Fix a bug that the new updates weren't sent before when arriving.
Also fix repetition of set dirty topics.

2020-10-16 19:13 UTC, EduPonz requested changes
Typos

2020-10-16 19:13 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +            //  else, it needs to be send in case it has unacked participants
```suggestion
            // Else, it needs to be sent in case it has unacked participants
```

2020-10-16 19:13 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +            if (change_guid.guidPrefix != server_guid_prefix_ &&
Update comment saying that this server has no virtual endpoint

2020-10-16 19:13 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +            // It needs to be send in case it has unacked participants
```suggestion
            // It needs to be sent in case it has unacked participants
```

2020-10-16 19:13 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +            // It needs to be send in case it has unacked participants
```suggestion
            // It needs to be sent in case it has unacked participants
```

2020-10-16 20:02 UTC, EduPonz approved these changes
LGTM

2020-10-16 20:03 UTC, merged

2020-10-17 17:10 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2925)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2925/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=205)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/205/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2675)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2675/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2936)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2936/)