Add support for XML environmental variables parsing
eProsima/Fast-DDS pull request #1517
Opened 2020-10-23 13:53 UTC by mauropasse

This commit would allow to use OS environmental variables in XML profiles. For example:
```
# In bash terminal
export ROBOT_IP_ADDRESS=192.168.0.1

# In XML profile
<?xml version="1.0" encoding="UTF-8" ?>
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <participant profile_name="env_var_parsing_example">
        <rtps>
            <builtin>
                <initialPeersList>
                    <locator>
                        <udpv4>
                            <address>ROBOT_IP_ADDRESS</address>
                        </udpv4>
                    </locator>
                </initialPeersList>
            </builtin>
        </rtps>
    </participant>
</profiles>
```

2020-10-24 12:12 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=2976)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2976/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=234)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/234/)
* Mac ![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=under%20maintenance&color=bbb)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=2987)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2987/)

2021-02-25 16:52 UTC, irobot-ros commented
Hi, sorry for resurrecting this old PR.
Is there anything that is preventing it to be merged?

2021-02-26 08:42 UTC, MiguelCompany commented
@irobot-ros Just that we did not have time to review it. Will do it now.

2021-02-26 09:34 UTC, MiguelCompany requested changes
Even though this is a nice-to-have feature, it cannot be merged as-is.

First, it is only adding the possibility to use an environmental variable on pure string values. I think we should replace every `tinyxml2::XMLElement::GetText` method call with a call to an auxiliary method receiving a `tinyxml2::XMLElement*` and returning a `const char*`, that will be the one performing the environmental variable access.

Methods `XMLParser::getXMLInt`, `XMLParser::getXMLUint`, and `XMLParser::getXMLBool` should also include environmental variable support.

I also think that using a special character (like `$`) to clearly indicate the environmental variable should be used is desirable.

Using method `std::getenv` gives a warning on Windows about that method being unsafe.

Finally, adding this new feature should add tests and documentation for it. I suggest extending the unit tests on [this file](https://github.com/eProsima/Fast-DDS/blob/master/test/unittest/xmlparser/XMLElementParserTests.cpp), and adding the corresponding PR to the [documentation repo](https://github.com/eProsima/Fast-DDS-docs)

2022-02-22 10:08 UTC, JLBuenoLopez-eProsima commented
Hi @irobot-ros,

The base branch for this PR (`2.0.x`) is becoming EOL (end of life) this very month (see [release support document](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md)). This is not going to be merged into this branch because there is still [work pending](https://github.com/eProsima/Fast-DDS/pull/1517#pullrequestreview-599401028). If you want to keep this PR open, you can change the base branch to one of the branches still alive and rebase it: `2.1.x` used in ROS 2 Foxy, `2.3.x` used in ROS 2 Galactic, or directly to `master`.

Sorry for the inconvenience!

2022-02-22 10:36 UTC, alsora commented
Sure, sorry for keeping this PR open for so long but we didn't have time to fully implement it as requested.
Will close this PR.

2023-03-16 13:38 UTC, JLBuenoLopez-eProsima commented
I am closing this PR, though the feature is something which will be interesting to have in Fast DDS. I have opened #3377 to keep track of this feature. This PR can be reopened in the future.

2023-03-16 13:38 UTC, closed without merging

2023-09-15 11:42 UTC, mauropasse commented
https://github.com/eProsima/Fast-DDS/pull/3841
This PR should add support for this feature