Solved possible CMake variable shadowing issue
eProsima/Fast-DDS pull request #1519
Opened 2020-10-26 10:01 UTC by MiguelBarro

2020-10-26 10:28 UTC, richiware requested changes

2020-10-26 10:28 UTC, richiware commented on cmake/common/gtest.cmake
> +                set(GTEST_ENVIRONMENT "")
Always `unset` the variable.

2020-10-26 10:28 UTC, richiware commented on cmake/common/gtest.cmake
> +        set(GTEST_ENVIRONMENT "")
Always `unset` the variable

2020-10-27 13:49 UTC, MiguelBarro commented on cmake/common/gtest.cmake
> +                set(GTEST_ENVIRONMENT "")
👍

2020-10-27 13:49 UTC, MiguelBarro commented on cmake/common/gtest.cmake
> +        set(GTEST_ENVIRONMENT "")
👍

2020-10-27 14:24 UTC, richiware approved these changes

2020-10-27 15:29 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3011)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3011/)
* Linux aarch64![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?status=not%20run&color=bbb)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2698)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2698/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3022)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3022/)

2020-10-27 15:30 UTC, merged