Backport/discovery server/participant type version/2.0.x
eProsima/Fast-DDS pull request #1521
Opened 2020-10-27 14:35 UTC by EduPonz

Backport of #1512. Merge after #1516

2020-11-05 15:18 UTC, rsanchez15 requested changes

2020-11-05 15:18 UTC, rsanchez15 commented on tools/fds/server.cpp
>      fastdds::dds::Log::SetCategoryFilter(
Remove log filter and log verbosity in fast-discovery-server tool.

2020-11-05 15:27 UTC, rsanchez15 submitted a review, later dismissed

2020-11-06 07:28 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3084)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3084/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=301)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/301/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2760)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2760/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3106)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3106/)

2020-11-06 12:18 UTC, rsanchez15 approved these changes

2020-11-06 19:38 UTC, EduPonz commented
Close in favor of #1555

2020-11-06 19:38 UTC, closed without merging