bugfix for security handshake race condition [9779]
eProsima/Fast-DDS pull request #1532
Opened 2020-10-30 12:02 UTC by IkerLuengo

2020-10-30 16:17 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3041)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3041/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=267)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/267/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2726)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2726/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3052)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3052/)

2020-11-03 09:37 UTC, MiguelCompany requested changes

2020-11-03 09:37 UTC, MiguelCompany commented on src/cpp/rtps/security/SecurityManager.cpp
> +    remote_participant_info->event_.reset();
Do we have to be constantly destroying and creating the timed event?
Could we always create it on the constructor of `AuthenticationInfo`, and just cancel it here, and restart it below?

2020-11-03 10:04 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3043)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3043/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=269)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/269/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2728)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2728/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3054)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3054/)

2020-11-03 14:55 UTC, MiguelCompany approved these changes

2020-11-03 18:51 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3055)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3055/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=278)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/278/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2738)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2738/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3066)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3066/)

2020-11-10 14:58 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3103)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3103/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=322)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/322/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2775)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2775/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3134)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3134/)

2020-11-11 17:44 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3107)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3107/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=327)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/327/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2777)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2777/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3139)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3139/)

2020-11-12 06:49 UTC, merged