Backup mode to Discovery-Server
eProsima/Fast-DDS pull request #1533
Opened 2020-10-30 12:20 UTC by jparisu

Do not merge before pr #1528
Do not merge before branch: hotfix/discovery-server/remove-servers

This changes implement the Backup mode to the Discovery-Server.

2020-11-03 13:38 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3045)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3045/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=271)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/271/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2730)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2730/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3056)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3056/)

2020-11-05 23:44 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3082)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3082/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=299)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/299/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2758)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2758/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3104)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3104/)

2020-11-06 10:11 UTC, rsanchez15 requested changes
Partial review after rebase `hotfix/discovery-server/remove-servers`

2020-11-06 10:11 UTC, rsanchez15 commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +            (std::istringstream) it.key() >> prefix_aux;
In general, I would use the function notation (`std::istringstream(x)`) rather than the c-like cast notation (`(std::istringstream) x`)

2020-11-06 10:11 UTC, rsanchez15 commented on src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
> +                fastrtps::rtps::CacheChange_t* change_aux = new fastrtps::rtps::CacheChange_t();
Duplicate declaration of `change_aux` which raise a warning (first declaration in line 1466).

2020-11-06 10:11 UTC, rsanchez15 commented on src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
> +                fastrtps::rtps::CacheChange_t* change_aux = new fastrtps::rtps::CacheChange_t();
Same as before. Duplicate declaration of `change_aux`.

2020-11-06 10:11 UTC, rsanchez15 commented on src/cpp/rtps/builtin/discovery/endpoint/EDPServer2.hpp
> +    fastrtps::rtps::DurabilityKind_t _durability;
And change it wherever is called.
```suggestion
    fastrtps::rtps::DurabilityKind_t durability_;
```

2020-11-06 11:31 UTC, rsanchez15 requested changes

2020-11-12 16:55 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3116)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3116/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=335)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/335/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2783)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2783/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3148)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3148/)

2020-11-12 17:58 UTC, jparisu commented
Uncrustify breaks because of the _header only_ `json.hpp` file.
This file must be moved into thirdparty.

2020-11-12 21:08 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3121)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3121/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=340)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/340/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2786)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2786/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3153)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3153/)

2020-11-13 09:36 UTC, MiguelCompany commented
@jparisu Now that #1545 has been merged, this needs a rebase.

2020-11-13 15:24 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3125)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3125/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=343)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/343/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2789)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2789/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3157)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3157/)

2020-11-16 06:30 UTC, MiguelCompany commented
All failures seem unrelated, and uncrustify is ok except for the new thirdparty file. One approval and I will merge

2020-11-16 09:31 UTC, MiguelBarro approved these changes
LGTM

2020-11-16 10:48 UTC, merged