Fixed resource limits on keyed topics
eProsima/Fast-DDS pull request #1535
Opened 2020-11-03 07:42 UTC by MiguelCompany

This PR fixes RTPS writers and so they correctly handle infinite resource limits

2020-11-03 10:05 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3044)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3044/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=270)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/270/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2729)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2729/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3055)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3055/)

2020-11-03 14:53 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3049)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3049/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=273)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/273/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2732)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2732/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3060)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3060/)

2020-11-05 06:28 UTC, richiware requested changes

2020-11-05 06:28 UTC, richiware commented on src/cpp/fastrtps_deprecated/publisher/PublisherHistory.cpp
> +                    if (mp_writer->wait_for_acknowledgement(change_to_remove, max_blocking_time, lock))
It would be more secure if this function receives a SequenceNumber_t instead of a CacheChange_t pointer.

2020-11-05 06:28 UTC, richiware commented on src/cpp/fastrtps_deprecated/publisher/PublisherHistory.cpp
> +                        add = remove_change_pub(vit->second.cache_changes.front());
Before removing `front()` element, check it is the expected one. Maybe it is not for example because lifespan.

2020-11-05 11:52 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3070)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3070/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=290)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/290/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2751)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2751/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3087)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3087/)

2020-11-22 08:08 UTC, richiware submitted a review, later dismissed

2020-11-22 11:41 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3141)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3141/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=359)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/359/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2804)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2804/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3173)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3173/)

2020-11-24 10:54 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3152)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3152/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=370)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/370/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2814)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2814/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3184)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3184/)

2020-11-24 15:27 UTC, MiguelCompany commented
@richiware On the last commit I have fixed an infinite loop. Calling `check_acked_status` may trigger history removals (specially on volatile writers), which then triggered `change_removed_by_history`, which then triggered `check_acked_status` again.

2020-11-24 17:31 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3156)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3156/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=374)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/374/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2817)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2817/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3188)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3188/)

2020-11-27 07:43 UTC, richiware approved these changes

2020-11-27 11:37 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3192)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3192/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=409)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/409/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2853)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2853/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3225)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3225/)

2020-11-30 06:24 UTC, merged