Fix Discovery-Server v2 bugs
eProsima/Fast-DDS pull request #1545
Opened 2020-11-05 10:13 UTC by rsanchez15

This PR fix the following errors in Discovery-Server v2:
* Remove virtual readers and writers from all topics.
* Fix find in map without verification
* Only assign remote endpoints to local participants.
* Replace `aux` namespace by the full namespace.
* Remove own DATA(p) from servers history.
* Do not send virtual changes.
* Fix double disposal error and change log priority
* Fixed client servers dispose by adding a final heartbeat to the packet with the server DATA(Up).

2020-11-06 09:10 UTC, MiguelBarro commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +                if (reader_proxy->guid().guidPrefix == *(it.base()))
We are not using **reverse_iterator**s thus `base()` is no longer required.

2020-11-06 11:24 UTC, MiguelCompany requested changes
Fix uncrustify issues

2020-11-06 11:35 UTC, MiguelBarro requested changes
LGTM

2020-11-06 11:35 UTC, MiguelBarro commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +    if (topic_name.compare(virtual_topic_) == 0)
I think using operator == will make it clearer.

2020-11-06 11:35 UTC, MiguelBarro commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +    if (topic_name.compare(virtual_topic_) == 0)
I think using operator == will make it clearer.

2020-11-06 12:00 UTC, MiguelCompany requested changes

2020-11-06 12:00 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/participant/PDPServerListener2.cpp
> +    {:
What happened here?

2020-11-06 12:07 UTC, rsanchez15 commented on src/cpp/rtps/builtin/discovery/participant/PDPServerListener2.cpp
> +    {:
Solved

2020-11-06 12:29 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3096)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3096/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=315)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/315/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2770)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2770/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3122)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3122/)

2020-11-10 11:28 UTC, MiguelBarro approved these changes
LGTM

2020-11-10 14:17 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3101)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3101/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=320)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/320/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2773)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2773/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3132)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3132/)

2020-11-10 15:10 UTC, jparisu commented
Windows issue:
Error in test: `BlackboxTests_DDS_PIM.Security.BuiltinAuthenticationAndAccessAndCryptoPlugin_governance_rule_order.NonIntraprocess`
Not related with this PR.

2020-11-12 08:44 UTC, MiguelCompany approved these changes

2020-11-12 11:55 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3111)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3111/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=330)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/330/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2780)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2780/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3143)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3143/)

2020-11-12 14:34 UTC, merged