Fix IPv6 to_string
eProsima/Fast-DDS pull request #1594
Opened 2020-11-24 16:40 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

2020-11-24 19:52 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3161)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3161/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=379)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/379/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2821)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2821/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3193)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3193/)

2020-11-25 06:45 UTC, MiguelCompany requested changes
This would have been detected if we had unit tests for IPLocator. Would you mind adding it?

2020-11-30 12:04 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3202)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3202/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=416)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/416/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2867)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2867/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3234)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3234/)

2020-12-01 11:47 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3206)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3206/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=419)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/419/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2874)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2874/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3238)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3238/)

2020-12-02 10:14 UTC, EduPonz requested changes

2020-12-02 10:14 UTC, EduPonz commented on test/unittest/utils/IPLocatorTests.cpp
> +    // TODO
Please address all TODOs

2020-12-02 10:14 UTC, EduPonz commented on test/unittest/utils/IPLocatorTests.cpp
> +TEST_F(IPLocatorTests, setPhysicalPort)
```suggestion
TEST_F(IPLocatorTests, PhysicalPort)
```

2020-12-02 10:45 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3215)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3215/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=427)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/427/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2879)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2879/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3247)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3247/)

2020-12-02 11:38 UTC, jparisu commented on src/cpp/utils/IPLocator.cpp
> +        // ERROR
It is an API method and I think it should not change the output.
In last implementation, and IPv4 does not send an Error message.

2020-12-03 09:00 UTC, imontesino commented on src/cpp/utils/IPLocator.cpp
> +        }
The memory cleaning should only apply to the  last 4 octets, those corresponding to the IPv4 adress

2020-12-04 11:17 UTC, MiguelCompany commented
@imontesino 400 warnings on windows and 3 on Mac

Only lines 307 and 308 on Locator.h are relevant

2020-12-04 11:22 UTC, MiguelCompany requested changes
This seems to work (at least on windows)

2020-12-04 11:22 UTC, MiguelCompany commented on include/fastdds/rtps/common/Locator.h
> +        unsigned int bracket_index;
```suggestion
```

2020-12-04 11:22 UTC, MiguelCompany commented on include/fastdds/rtps/common/Locator.h
> +            bracket_index = str_locator.find(']');
```suggestion
            auto bracket_index = str_locator.find(']');
```

2020-12-04 11:29 UTC, MiguelCompany commented on include/fastdds/rtps/common/Locator.h
> +        std::string address;
I also think this local is never used

```suggestion
```

2020-12-04 11:30 UTC, MiguelCompany commented on include/fastdds/rtps/common/Locator.h
> +        std::string str_locator;
And this one could be declared inside the `try {}` block

2020-12-04 13:01 UTC, MiguelCompany approved these changes

2020-12-04 17:30 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3256)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3256/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=467)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/467/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2908)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2908/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3288)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3288/)

2020-12-09 16:33 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3279)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3279/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=491)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/491/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2930)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2930/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3312)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3312/)

2020-12-10 15:05 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3287)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3287/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=499)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/499/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2935)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2935/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3320)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3320/)

2020-12-11 10:48 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3292)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3292/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=503)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/503/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2939)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2939/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3324)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3324/)

2020-12-11 11:14 UTC, MiguelCompany commented
Failures seem unrelated.

2020-12-15 11:29 UTC, MiguelCompany requested changes

2020-12-15 14:20 UTC, jparisu commented on src/cpp/utils/IPLocator.cpp
> -
`IPLocator` only consist on `static` functions. Default constructor will be left for API's sake, but will be mark as deprecated.

2020-12-15 14:57 UTC, MiguelCompany commented on src/cpp/utils/IPLocator.cpp
> -
🤔 Hmmm. I see. You're right. They can be removed then.

2020-12-15 15:12 UTC, MiguelCompany approved these changes

2020-12-15 15:12 UTC, MiguelCompany approved these changes
LGTM 🏅

2020-12-15 19:11 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3319)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3319/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=530)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/530/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2970)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2970/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3351)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3351/)

2020-12-16 08:15 UTC, merged

2020-12-16 16:09 UTC, RFRIEDM commented on src/cpp/utils/IPLocator.cpp
> +    // proper number of :
Is it intended to follow the RFC? https://tools.ietf.org/html/rfc4291