Remove unnecessary waiting in ResourceEvent loop
eProsima/Fast-DDS pull request #1597
Opened 2020-11-25 17:03 UTC by sfod

There is some kind of race condition in ResourceEvent class.
When timer put into pending list, its execution might be delayed depending on what step is being executed in `ResourceEvent::event_service` loop.

### Details of fixed issue
For StatefulReader there are two timers that fire periodically and use the same ResourceEvent. One timer is in WriterProxy (`heartbeat_response_`), another is in PDP (`resend_participant_info_event_`).

Thread 1: calls `heartbeat_response_->restart()`
Thread 1: successfully locks `ResourceEvent::mutex_`.
Thread 2: `ResourceEvent::event_service` waits on `ResourceEvent::mutex_`.
Thread 1: puts `heartbeat_response_` in pending list
Thread 1: releases lock
Thread 2: `ResourceEvent::event_service` calculates the next trigger time as the trigger time of `resend_participant_info_event_` timer.
As a result, data transferring freezes on about `m_discovery.discovery_config.leaseDuration_announcementperiod` as there are no answers to heartbeat messages from writer.

This issue appeared on large data (>20 MB) - the larger data the more probability that this issue arises. For example, for 200 MB data chunk it appears in ~90%.
But it seems that it might appear for any kind of data.

The issue this PR fixes looks similar to the following issues:
https://github.com/eProsima/Fast-DDS/issues/1107
https://github.com/eProsima/Fast-DDS/issues/1120
https://github.com/eProsima/Fast-DDS/issues/1062

2020-11-25 20:43 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3164)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3164/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=382)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/382/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2824)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2824/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3196)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3196/)

2020-11-26 10:30 UTC, MiguelCompany approved these changes
Firstly, thank you very much for the analysis you have done!

I have fixed the linter issues and refactored the solution to early continue the loop. I have also added a condition for a possible race when stopping the thread.

It would be great to have a regression test added, but I don't know if it could be done without flakiness. What do you think?

2020-11-26 12:15 UTC, MiguelCompany submitted a review, later dismissed
I managed to create a test that reproduces the issue.

2020-11-26 12:16 UTC, MiguelCompany commented
Waiting for more approvals on this one. @IkerLuengo @richiware

2020-11-26 12:42 UTC, IkerLuengo requested changes
@MiguelCompany just a very minor cosmetic change in the name of the event, to be consistent with the rest of the names used in the test.

2020-11-26 12:42 UTC, IkerLuengo commented on test/unittest/rtps/resources/timedevent/TimedEventTests.cpp
> +    main_event.restart_timer();
``` suggestion
    TimedEvent periodic_event(*env->service_, periodic_callback, 1.0 * periodic_ms.count());

    // Let the periodic event run for several periods
    periodic_event.restart_timer();
```

2020-11-26 13:26 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3178)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3178/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=396)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/396/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2837)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2837/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3210)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3210/)

2020-11-26 13:51 UTC, sfod commented
Thanks, Miguel, I didn't expect so fast reaction!
I wasn't sure if I should fix linter errors in the affected source file. I'll keep it in mind for the future.
With changes you made the code became much easier to understand, thanks for that.
And as for the test, I couldn't think of a reliable test because of a random nature of the issue. But your test apparently catches it well, very cool.

2020-11-26 14:19 UTC, IkerLuengo approved these changes
LGTM

2020-11-26 18:57 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3189)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3189/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=407)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/407/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2848)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2848/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3221)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3221/)

2020-11-27 07:14 UTC, MiguelCompany commented
Current CI looks good to me. I will merge this.

@sfod Thank you very much again!

2020-11-27 07:14 UTC, merged