DataSharing
eProsima/Fast-DDS pull request #1607
Opened 2020-11-27 22:04 UTC by IkerLuengo

2020-11-28 03:21 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3198)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3198/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=413)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/413/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2863)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2863/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3230)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3230/)

2020-11-30 14:31 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3204)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3204/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=417)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/417/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2871)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2871/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3236)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3236/)

2020-12-01 11:51 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3207)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3207/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=420)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/420/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2876)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2876/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3239)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3239/)

2020-12-04 01:30 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3240)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3240/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=451)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/451/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2897)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2897/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3272)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3272/)

2020-12-09 14:57 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3277)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3277/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=488)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/488/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2928)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2928/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3309)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3309/)

2020-12-09 19:41 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3281)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3281/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=493)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/493/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2932)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2932/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3314)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3314/)

2020-12-11 03:45 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3291)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3291/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=502)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/502/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2938)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2938/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3323)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3323/)

2020-12-16 14:30 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3325)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3325/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=534)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/534/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2978)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2978/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3357)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3357/)

2020-12-18 07:26 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3350)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3350/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=555)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/555/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3002)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3002/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3382)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3382/)

2020-12-19 03:21 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3372)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3372/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=572)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/572/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3021)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3021/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3404)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3404/)

2020-12-21 15:17 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3385)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3385/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=583)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/583/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3035)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3035/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3417)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3417/)

2020-12-22 17:08 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3406)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3406/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=600)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/600/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3052)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3052/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3438)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3438/)

2020-12-24 07:44 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3440)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3440/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=633)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/633/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3065)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3065/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3474)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3474/)

2021-01-13 20:31 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3514)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3514/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=704)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/704/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3125)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3125/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3546)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3546/)

2021-01-14 22:42 UTC, MiguelBarro approved these changes
LGTM

2021-01-18 13:18 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3551)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3551/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=741)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/741/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3151)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3151/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3583)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3583/)

2021-01-19 20:26 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3567)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3567/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=757)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/757/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3162)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3162/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3599)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3599/)

2021-01-20 16:56 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3579)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3579/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=769)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/769/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3171)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3171/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3611)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3611/)

2021-01-20 21:51 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3585)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3585/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=775)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/775/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3175)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3175/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3617)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3617/)

2021-01-21 07:39 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3587)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3587/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=777)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/777/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3177)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3177/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3619)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3619/)

2021-01-21 17:12 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3593)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3593/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=783)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/783/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3183)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3183/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3625)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3625/)

2021-01-22 17:22 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3603)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3603/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=793)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/793/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3191)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3191/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3635)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3635/)

2021-01-25 09:39 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3612)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3612/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=801)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/801/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3198)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3198/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3643)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3643/)

2021-01-26 08:32 UTC, MiguelCompany requested changes

2021-01-26 08:32 UTC, MiguelCompany commented on src/cpp/rtps/reader/StatelessReader.cpp
> +        datasharing_listener_->change_removed_with_timestamp(c_RTPSTimeInfinite.to_ns());
This should be the timestamp of the last change + 1

2021-01-26 08:32 UTC, MiguelCompany commented on src/cpp/utils/collections/FixedSizeQueue.hpp
> +    class iterator : public std::iterator<std::bidirectional_iterator_tag, difference_type, value_type, pointer,
We removed inheritance from `std::iterator` on #1359 to avoid warnings on C++17

2021-01-26 08:32 UTC, MiguelCompany commented on test/blackbox/common/DDSBlackboxTestsDataSharing.cpp
> +    // Doing a secong read on the same history, the application will see only the last samples
```suggestion
    // Doing a second read on the same history, the application will see only the last samples
```

2021-01-26 08:32 UTC, MiguelCompany commented on test/blackbox/common/DDSBlackboxTestsDataSharing.cpp
> +    // Doing a secong read on the same history, the application will see only the last samples
```suggestion
    // Doing a second read on the same history, the application will see only the last samples
```

2021-01-26 14:45 UTC, MiguelCompany submitted a review, later dismissed
LGTM with a minor change

2021-01-26 14:45 UTC, MiguelCompany commented on src/cpp/utils/collections/FixedSizeQueue.hpp
> +                //reference>
```suggestion
    class iterator
```

2021-01-26 14:56 UTC, MiguelCompany approved these changes
LGTM now

2021-01-27 08:00 UTC, MiguelCompany approved these changes

2021-01-27 12:08 UTC, MiguelCompany submitted a review, later dismissed

2021-01-27 17:02 UTC, MiguelCompany approved these changes

2021-01-27 20:38 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3661)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3661/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=841)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/841/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3225)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3225/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3684)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3684/)

2021-01-28 06:23 UTC, merged