Added tests for XMLProfileManager
eProsima/Fast-DDS pull request #1616
Opened 2020-12-02 11:16 UTC by imontesino

Merge after #1612

Added unit tests for the `XMLProfileManager` classes' public methods

2020-12-02 14:34 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3219)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3219/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=430)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/430/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2884)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2884/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3251)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3251/)

2020-12-03 11:18 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3222)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3222/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=433)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/433/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2886)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2886/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3254)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3254/)

2020-12-03 15:00 UTC, rsanchez15 requested changes
Apply also all format suggestions from the review of #1605

2020-12-09 13:40 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3274)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3274/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=485)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/485/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2925)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2925/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3306)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3306/)

2020-12-21 15:53 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3387)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3387/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=585)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/585/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3037)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3037/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3419)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3419/)

2021-01-13 08:22 UTC, rsanchez15 requested changes

2021-01-13 08:22 UTC, rsanchez15 commented on src/cpp/rtps/xmlparser/XMLProfileManager.cpp
> -XMLP_ret XMLProfileManager::extractDynamicTypes(
`extractDynamicTypes()` is still declared in `XMLProfileManager.h` but I can't find its definition.

2021-01-13 08:22 UTC, rsanchez15 commented on test/unittest/xmlparser/XMLProfileParserTests.cpp
> + * 1. Check error return
```suggestion
 * 2. Check error return
```

2021-01-13 08:22 UTC, rsanchez15 commented on test/unittest/xmlparser/XMLProfileParserTests.cpp
> + *  1. An incorrect profile element is parsed, return value of XMLP_ret::XML_ERROR is expected
```suggestion
 *  2. A corrrect rooted profile element is parsed, return value of XMLP_ret::XML_OK is expected
 *  3. An incorrect profile element is parsed, return value of XMLP_ret::XML_ERROR is expected
```

2021-01-13 08:22 UTC, rsanchez15 commented on test/unittest/xmlparser/XMLProfileParserTests.cpp
> +    {
Add a brief comment in each block explaining which case you are testing.

2021-01-13 08:22 UTC, rsanchez15 commented on test/unittest/xmlparser/XMLProfileParserTests.cpp
> +    {
Same as before. Brief comment for each block. You can copy and paste the comments above in its corresponding block

2021-01-13 08:22 UTC, rsanchez15 commented on include/fastrtps/xmlparser/XMLProfileManager.h
>          subscriber_profiles_.clear();
Missing negative test for `CreateDynamicPubSubType()` (line 242).

2021-01-14 13:49 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3526)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3526/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=716)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/716/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3134)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3134/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3558)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3558/)

2021-01-14 13:50 UTC, rsanchez15 approved these changes

2021-01-14 14:08 UTC, merged