Loanable sequence template
eProsima/Fast-DDS pull request #1619
Opened 2020-12-03 15:21 UTC by MiguelCompany

This PR adds basic support for loanable sequences, which are required for the implementation of DDS compliant read / take

Iterators support is still pending, but we can add them on a follow-up PR.

2020-12-03 19:37 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3238)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3238/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=449)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/449/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2895)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2895/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3270)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3270/)

2020-12-04 12:15 UTC, IkerLuengo approved these changes
LGTM.

Please, can you clarify if my understanding on the LoanableCollection::loan is correct?

2020-12-04 12:40 UTC, MiguelCompany commented on include/fastdds/dds/core/LoanableCollection.hpp
> +        if (has_ownership_ && maximum_ > 0)
Correct 😉

2020-12-04 13:35 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3252)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3252/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=463)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/463/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2905)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2905/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3284)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3284/)

2020-12-09 10:00 UTC, IkerLuengo requested changes

2020-12-09 10:46 UTC, IkerLuengo submitted a review, later dismissed
LGTM

2020-12-09 14:47 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3278)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3278/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=489)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/489/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2929)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2929/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3310)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3310/)

2020-12-10 18:31 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3290)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3290/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=501)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/501/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2937)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2937/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3322)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3322/)

2020-12-14 14:47 UTC, IkerLuengo approved these changes
👍🏼

2020-12-14 14:51 UTC, merged