[Discovery-Server] Fix timing errors [10081]
eProsima/Fast-DDS pull request #1620
Opened 2020-12-03 15:41 UTC by jparisu

With the new change of ResourceEvent, the DDB does not work properly due to it resends the data (this means it erases the old data and create send it with new sequence number). If this happens before the ack arrives (this happens now that the routine starts faster) the Discovery Server get stucked in an infinite loop.

2020-12-03 15:59 UTC, EduPonz requested changes
Just some typos.

2020-12-03 15:59 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +            // To account for that, we discard the DATA if the payload is exactly the same as what wee have.
```suggestion
            // To account for that, we discard the DATA if the payload is exactly the same as what we have.
```

2020-12-03 15:59 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +                // Update the change related to the participant and return the old change to the pool
This comment is not necessary, next one says the same. Also in create writer and reader

2020-12-03 15:59 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
> +                    logInfo(RTPS_PDP_SERVER, "Removingfix de DS change " << c->instanceHandle
Update log message

2020-12-03 15:59 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
> +        //  from different servers, and one of them could be in the history while the other arrive to ddb
```suggestion
        // from different servers, and one of them could be in the history while the other arrive to dd
```

2020-12-03 20:03 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3239)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3239/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=450)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/450/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2896)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2896/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3271)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3271/)

2020-12-04 06:39 UTC, EduPonz approved these changes
LGTM with green CI :robot:

2020-12-04 11:10 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3244)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3244/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=455)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/455/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2901)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2901/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3276)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3276/)

2020-12-04 11:37 UTC, MiguelCompany approved these changes
Only whitespace changes since last approval

2020-12-04 11:38 UTC, MiguelCompany commented
I don't think the failures are related, so merging this in!

2020-12-04 11:38 UTC, merged