Fixed the SHM segment smashing while reading with security
eProsima/Fast-DDS pull request #1644
Opened 2020-12-17 08:16 UTC by rsanchez15

This PR includes:
- Fix the shared memory segment writing access while reading when the RTPS message and sub-messages are encrypted.
- Communication tests

2020-12-17 12:28 UTC, MiguelCompany requested changes

2020-12-17 13:01 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3335)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3335/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=543)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/543/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2992)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2992/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3367)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3367/)

2020-12-17 16:17 UTC, MiguelCompany approved these changes

2020-12-18 05:37 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3347)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3347/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=552)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/552/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3001)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3001/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3379)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3379/)

2020-12-18 08:06 UTC, MiguelCompany requested changes
Two minor details only

2020-12-18 08:06 UTC, MiguelCompany commented on src/cpp/rtps/messages/MessageReceiver.cpp
> +        // This way each decoded submessage will be process using the crypto_submsg_ buffer.
```suggestion
        // This way each decoded sub-message will be processed using the crypto_submsg_ buffer.
```

2020-12-18 08:06 UTC, MiguelCompany commented on src/cpp/rtps/messages/MessageReceiver.cpp
>  } /* namespace rtps */
This one is missing again

2020-12-18 08:13 UTC, MiguelCompany approved these changes
LGTM

2020-12-18 11:33 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3358)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3358/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=561)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/561/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3007)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3007/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3390)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3390/)

2020-12-18 11:45 UTC, merged