Fixed the SHM segment smashing while reading with security <2.1.x>
eProsima/Fast-DDS pull request #1645
Opened 2020-12-17 09:26 UTC by rsanchez15

This is a port of PR #1644 from 2.0.x to 2.1.x

2020-12-17 14:24 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3336)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3336/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=544)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/544/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=2993)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2993/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3368)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3368/)

2020-12-18 17:52 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3366)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3366/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=568)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/568/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3014)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3014/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3398)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3398/)

2020-12-18 19:17 UTC, MiguelCompany requested changes

2020-12-18 19:17 UTC, MiguelCompany commented on src/cpp/rtps/messages/MessageReceiver.cpp
> +    , crypto_submsg_(participant->is_secure() ? rec_buffer_size : 0)
```suggestion
    , crypto_submsg_(participant->is_secure() ? rec_buffer_size : 0)
    , crypto_payload_(participant->is_secure() ? rec_buffer_size : 0)
```

2020-12-18 19:17 UTC, MiguelCompany commented on include/fastdds/rtps/messages/MessageReceiver.h
>      SerializedPayload_t crypto_payload_;
```suggestion
    CDRMessage_t crypto_submsg_;
    //!Buffer to process a decoded payload
    SerializedPayload_t crypto_payload_;
```

2020-12-21 11:11 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3377)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3377/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=577)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/577/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3029)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3029/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3409)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3409/)

2020-12-21 18:54 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3389)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3389/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=587)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/587/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3039)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3039/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3421)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3421/)

2020-12-21 21:09 UTC, MiguelCompany approved these changes

2020-12-23 14:34 UTC, EduPonz commented
@MiguelCompany what do you think?

2020-12-23 14:43 UTC, MiguelCompany commented
> what do you think?

I think we can merge this one

2020-12-23 15:01 UTC, merged