Changed the Asio linkage to fit the THIRDPARTY option and set a minimum version [10322]
eProsima/Fast-DDS pull request #1692
Opened 2021-01-19 09:44 UTC by rsanchez15

2021-01-19 10:12 UTC, EduPonz requested changes

2021-01-19 10:12 UTC, EduPonz commented on cmake/common/eprosima_libraries.cmake
> +    set(oneValueArgs VERSION)
Please document this argument

2021-01-19 10:12 UTC, EduPonz commented on cmake/modules/FindAsio.cmake
> +            message(SEND_ERROR "Not found a local version of Asio installed.")
I think these should be `FATAL_ERROR`

2021-01-19 10:39 UTC, EduPonz approved these changes
LGTM

2021-01-19 15:14 UTC, EduPonz approved these changes
LGTM 🤖

2021-01-19 23:16 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3569)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3569/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=759)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/759/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3164)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3164/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3601)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3601/)

2021-01-20 06:49 UTC, EduPonz requested changes
Please correct building errors in Windows

2021-01-20 13:55 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3573)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3573/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=763)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/763/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3168)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3168/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3605)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3605/)

2021-01-21 14:36 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3592)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3592/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=782)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/782/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3182)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3182/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3624)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3624/)

2021-01-22 11:38 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3599)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3599/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=789)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/789/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3188)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3188/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3631)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3631/)

2021-01-25 09:38 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3609)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3609/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=798)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/798/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3196)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3196/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3640)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3640/)

2021-01-27 15:06 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3658)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3658/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=838)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/838/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3222)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3222/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3681)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3681/)

2021-01-28 11:27 UTC, imontesino requested changes

2021-01-28 11:39 UTC, imontesino approved these changes
LGTM

2021-01-28 11:46 UTC, merged