New methods in Entity [10309]
eProsima/Fast-DDS pull request #1694
Opened 2021-01-19 09:46 UTC by jparisu

Merge after #1691 

New method : `get_statuscondition`

New unittest for every API method in `Entity`

2021-01-19 16:33 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3561)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3561/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=751)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/751/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3158)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3158/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3593)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3593/)

2021-01-21 10:08 UTC, imontesino requested changes

2021-01-21 15:13 UTC, IkerLuengo requested changes
Nothing to add to the previous comments

2021-01-22 06:34 UTC, jparisu commented on include/fastdds/dds/core/Entity.hpp
> +    StatusCondition status_condition_;
:+1:

2021-01-22 06:35 UTC, jparisu commented on include/fastdds/dds/core/condition/StatusCondition.hpp
> +            const StatusMask& mask);
This is a comment for PR #1691 .
I change it there.

2021-01-22 06:35 UTC, jparisu commented on include/fastdds/dds/core/condition/WaitSet.hpp
> + * has a trigger_value ofTRUE or else until the timeout expires.
Same as the previous one, I change it in #1691 .

2021-01-22 06:39 UTC, jparisu commented on include/fastdds/dds/core/condition/StatusCondition.hpp
> +            const StatusMask& mask);
Finally the signature was correct. The comment is the wrong one.

2021-01-22 10:22 UTC, IkerLuengo approved these changes
LGTM

2021-01-22 11:43 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3600)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3600/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=790)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/790/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3189)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3189/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3632)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3632/)

2021-01-26 07:39 UTC, imontesino approved these changes
LGTM

2021-01-26 07:42 UTC, merged