DataSharing communication tests
eProsima/Fast-DDS pull request #1703
Opened 2021-01-22 11:45 UTC by jparisu

Branch over : `feature/DataSharing-pools`

Changes:

1. One test has been added to `test/communication`:
New test using a `FixedSized` type instead of `HelloWorld` type.

2. Change names of `test/dds/communication`:
The only test in this directory was related just with dynamic types.
The files related with this test has been renamed with `Dynamic` addition to names

3. Implement `main` test executables:
Implement `Publisher|Subscriber Main.cpp|Module.hpp|Module.cpp` whit the Publisher and Subscriber implementations and parametrizations needed to check communication.

4. Python test generation:
`test_build.py` automaticly execute a communication test following a test definition given by a JSON file
`definitions_example.json` has an explanation of this JSON file fields.

2021-01-22 11:48 UTC, jparisu commented
New DDS communication tests are not yet working due to an error in QoS or Connectivity.
The Publisher and Subscriber are discovered by each other, and messages are written, but they are not beeing received by the Reader. Thus the test fails.

FUTURE WORK:

- Fix communication error in Publisher and Subscriber implementations.
- Add new .json and .xml files to generate new test cases

2021-01-25 10:56 UTC, jparisu commented
Each test implemented is run from a `.json` file with the participants specifications.
Tests implemented:

- `simple_communication.json` - default reliable publisher and default reliable subscriber
- `besteffort_communication.json` -  default best effort publisher and default best effort subscriber
- `mix_communication.json` - default reliable publisher and default reliable subscriber and a default PubSub reliable
- `simple_communication_fixed_type.json` - default reliable publisher and default reliable subscriber with `FixedSizedType` type.
- zero_copy_communication.json` - zero copy publisher and zero copy subscriber
- zero_copy_pub_communication.json` - zero copy publisher and default subscriber (both with `FixedSizedType` type).
- zero_copy_sub_communication.json` - default publisher and zero copy subscriber (both with `FixedSizedType` type).
- mix_zero_copy_communication.json` - default publisher and default subscriber and zero copy publisher and zero copy subscriber (all with `FixedSizedType` type).

2021-01-27 08:48 UTC, IkerLuengo requested changes

2021-01-27 08:48 UTC, IkerLuengo commented on test/dds/communication/test_build.py
> +
`pubisher` -> `publisher`

2021-01-28 08:18 UTC, MiguelCompany requested changes

2021-01-28 08:18 UTC, MiguelCompany commented on test/dds/communication/SubscriberModule.cpp
> +    // DomainParticipantFactory::get_instance()->set_qos(factory_qos);
Should we remove this code?

2021-01-28 08:18 UTC, MiguelCompany commented on test/dds/communication/definitions_example.json
> +            "kind" : "publisher",
As this is the example, I think it should reflect the default values.

2021-01-28 09:35 UTC, IkerLuengo commented on test/dds/communication/CMakeLists.txt
> +    target_include_directories(DDSCommunicationPublisher PRIVATE ${PROJECT_SOURCE_DIR}/test/blackbox)
For the data types headers

2021-01-28 09:35 UTC, IkerLuengo commented on test/dds/communication/CMakeLists.txt
> +    target_include_directories(DDSCommunicationSubscriber PRIVATE ${PROJECT_SOURCE_DIR}/test/blackbox)
For the data types headers

2021-01-28 13:05 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3666)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3666/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=846)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/846/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3230)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3230/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3689)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3689/)

2021-01-28 13:38 UTC, MiguelCompany commented on test/dds/communication/PubSubMain.cpp
>          eprosima::fastrtps::Domain::loadXMLProfilesFile(xml_file);
This line should be removed.

Applies to every DDS application.

2021-01-28 13:38 UTC, MiguelCompany commented on test/dds/communication/PubSubMain.cpp
> +        //DomainParticipantFactory::get_instance()->load_XML_profiles_file(xml_file);
The line was uncommented, but the previous line should be removed, as we are not using `eprosima::fastrtps` namespace

2021-01-28 13:56 UTC, MiguelCompany approved these changes
LGTM 🏅

2021-01-28 16:00 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3669)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3669/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=849)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/849/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3232)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3232/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3694)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3694/)

2021-01-29 06:34 UTC, MiguelCompany approved these changes

2021-01-29 10:02 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3673)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3673/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=853)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/853/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3235)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3235/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3698)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3698/)

2021-01-29 10:04 UTC, MiguelCompany commented
All the tests added/modified by this PR were passing.

2021-01-29 10:04 UTC, merged