Fix read_next_sample and take_next_sample
eProsima/Fast-DDS pull request #1732
Opened 2021-02-03 07:45 UTC by MiguelCompany

This PR adds new checks to `DataReaderTests.read_unread` and fixes the behavior of  `read_next_sample` and `take_next_sample`.

Depends on #1731

2021-02-03 11:02 UTC, IkerLuengo approved these changes
LGTM

2021-02-05 09:52 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3719)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3719/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=894)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/894/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3272)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3272/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3741)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3741/)

2021-02-17 11:24 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3803)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3803/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=965)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/965/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3346)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3346/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3829)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3829/)

2021-02-17 19:50 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3809)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3809/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=967)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/967/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3351)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3351/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3835)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3835/)

2021-02-18 08:19 UTC, IkerLuengo approved these changes
LGTM

2021-02-18 08:20 UTC, IkerLuengo requested changes
Please, correct linter errors

2021-02-18 13:53 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3813)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3813/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=971)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/971/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3355)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3355/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3839)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3839/)

2021-02-18 14:48 UTC, IkerLuengo requested changes

2021-02-18 14:48 UTC, IkerLuengo commented on test/blackbox/common/BlackboxTestsLifespanQoS.cpp
> +    EXPECT_EQ(reader.take_first_data(&msg), true);
```suggestion
    for (uint32_t i = 0; i < writer_samples; ++i)
    {
        EXPECT_EQ(reader.take_first_data(&msg), true);
    }
```

2021-02-18 14:48 UTC, IkerLuengo commented on test/blackbox/common/BlackboxTestsLifespanQoS.cpp
> +    EXPECT_EQ(reader.take_first_data(&msg), false);
```suggestion
    for (uint32_t i = 0; i < writer_samples; ++i)
    {
        EXPECT_EQ(reader.take_first_data(&msg), false);
    }

2021-02-18 14:50 UTC, MiguelCompany commented on include/fastdds/dds/core/UserAllocatedSequence.hpp
> +// Copyright 2020 Proyectos y Sistemas de Mantenimiento SL (eProsima).
🤦

2021-02-19 07:00 UTC, IkerLuengo submitted a review, later dismissed
LGTM

2021-02-19 07:41 UTC, IkerLuengo approved these changes
:+1:

2021-02-19 12:57 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3821)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3821/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=978)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/978/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3364)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3364/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3847)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3847/)

2021-03-04 08:23 UTC, MiguelCompany commented
@richiprosima Please test this.

2021-03-04 15:47 UTC, merged