Add reception timestamp to fastdds SampleInfo [10492]
eProsima/Fast-DDS pull request #1737
Opened 2021-02-04 09:00 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

2021-02-04 10:56 UTC, MiguelCompany requested changes
This introduces an ABI break, please add a note on versions.md

2021-02-04 10:56 UTC, MiguelCompany commented on src/cpp/fastdds/subscriber/DataReaderImpl.cpp
> +    dds_info->reception_timestamp = rtps_info.receptionTimestamp;
This should be also done on `ReadTakeCommand`

2021-02-04 11:34 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3708)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3708/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=885)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/885/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3262)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3262/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3731)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3731/)

2021-02-22 11:15 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3832)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3832/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=990)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/990/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3378)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3378/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3858)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3858/)

2021-03-01 09:10 UTC, MiguelCompany requested changes

2021-03-01 09:10 UTC, MiguelCompany commented on include/fastdds/dds/subscriber/SampleInfo.hpp
> +    //! time provided by the DataReader when the sample was read
```suggestion
    //! time provided by the DataReader when the sample was added to its history
```

2021-03-04 15:56 UTC, merged