Remove dependency between DataWriter tables in persistent writers
eProsima/Fast-DDS pull request #1740
Opened 2021-02-05 07:06 UTC by rsanchez15

The `writer_histories` table defines the DataWriter GUID of the `writer_states` table as a foreign key. This implies that when the `writer_states` table is updated a lookup is performed on the `writer_histories` table to maintain consistency between tables. This results in an increased write time in the `writer_states` table as the size of the `writer_histories` table increases. Since the GUID value in the `writer_states` table is never changed, it is not necessary to maintain this consistency.

2021-02-05 07:39 UTC, MiguelCompany approved these changes

2021-02-05 10:51 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3720)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3720/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=895)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/895/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3273)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3273/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3742)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3742/)

2021-02-17 09:05 UTC, MiguelCompany requested changes
We should consider increasing the version of the schema.

We have also identified additional issues with the lifespan and disable_positive_acks policies, that require the source timestamp to be persisted.

I think the whole WriterParams should be written to the database for each of the samples on the writer.

2021-03-29 06:42 UTC, closed without merging

2021-03-29 07:06 UTC, MiguelCompany commented
This was closed in favor of #1837