Update Performance Throughput Testing to support: data sharing, loans and zero copy
eProsima/Fast-DDS pull request #1759
Opened 2021-02-14 16:56 UTC by MiguelBarro

This pull request must be merge after #1753

2021-02-14 22:44 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3770)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3770/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=941)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/941/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3320)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3320/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3796)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3796/)

2021-02-15 23:57 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3789)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3789/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=951)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/951/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3335)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3335/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3815)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3815/)

2021-02-16 09:08 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3794)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3794/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=955)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/955/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3338)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3338/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3820)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3820/)

2021-02-16 12:23 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3798)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3798/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=959)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/959/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3342)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3342/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3824)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3824/)

2021-02-16 14:17 UTC, MiguelBarro commented
Linux aarch64 shows a non related issue. See a succesful run in [linux aarch 960](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/960/)

2021-02-18 14:52 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3816)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3816/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=974)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/974/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3358)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3358/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3842)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3842/)

2021-02-18 15:13 UTC, MiguelBarro commented
All test failures are unrelated but the Mac one. The `performance.throughput.intraprocess_reliable.data_loans_and_sharing` failed because cannot allocate the Shared memory segment in the second iteration (1kB, 1000). All other tests were able to make this allocation and the larger one (16kb, 1000).  I rerun Mac and pass without failures 
[Mac manual](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3360/)

2021-02-19 10:54 UTC, IkerLuengo requested changes

2021-02-19 10:54 UTC, IkerLuengo commented on test/performance/throughput/ThroughputTypes.hpp
> + * This type does not define a comparisson operator because the actual data size refernced
```suggestion
 * This type does not define a comparison operator because the actual data size referenced
```

2021-02-19 10:54 UTC, IkerLuengo commented on test/performance/throughput/ThroughputPublisher.cpp
> +// ********************************* DATA READER LISTENER ************************************
```suggestion
// ********************************* DATA WRITER LISTENER ************************************
```

2021-02-19 10:54 UTC, IkerLuengo commented on test/performance/throughput/ThroughputPublisher.cpp
> +// ********************************* DATA WRITER LISTENER ************************************
```suggestion
// ********************************* COMMAND READER LISTENER ************************************
```

2021-02-19 10:54 UTC, IkerLuengo commented on test/performance/throughput/ThroughputPublisher.cpp
> +    }
This is probably solved with #1771

2021-02-19 10:54 UTC, IkerLuengo commented on test/performance/throughput/CMakeLists.txt
> +        # Check if a test using data sharing and zero copy is required
```suggestion
        # Check if a test using data sharing and loans is required
```

2021-02-19 10:54 UTC, IkerLuengo commented on test/performance/throughput/CMakeLists.txt
> +        # Check if a data sharing test is required
```suggestion
        # Check if a loans test is required
```

2021-02-20 12:25 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3830)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3830/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=987)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/987/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3371)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3371/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3856)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3856/)

2021-02-22 08:07 UTC, IkerLuengo approved these changes
LGTM

2021-02-23 10:12 UTC, EduPonz approved these changes

2021-02-23 10:12 UTC, merged