Stop listener thread on reader destructor <master> [10618]
eProsima/Fast-DDS pull request #1771
Opened 2021-02-18 16:11 UTC by IkerLuengo

The listener thread is not being stopped when the reader is dismissed. This can lead to problems if the listener processes a notification while the reader is being destroyed, as it may end up calling methods already removed from the vtable.

2021-02-18 17:40 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3819)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3819/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=976)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/976/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3362)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3362/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3845)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3845/)

2021-02-19 05:58 UTC, MiguelCompany requested changes
Just one typo

2021-02-19 05:58 UTC, MiguelCompany commented on src/cpp/rtps/reader/RTPSReader.cpp
> +        // so no notification will occur until the the non-virtual instance is constructed.
```suggestion
        // so no notification will occur until the non-virtual instance is constructed.
```

2021-02-19 05:59 UTC, MiguelCompany approved these changes

2021-02-19 06:03 UTC, merged