Restore smart default logging for multiconfig generators
eProsima/Fast-DDS pull request #1775
Opened 2021-02-22 16:54 UTC by MiguelBarro

Prior to #1679 the default library behavior was:
- if not using **INTERNAL_DEBUG** never queue infos.
- if using **INTERNAL_DEBUG** on Debug config infos are queued but other configs don't queue them.
- if user defines **LOG_NO_INFO** no infos are queued regardless config or cmake options. 

For multiconfig generators like MSVC this was optimal because Release builds never queued infos and Debug builds may do it or not depending on **INTERNAL_DEBUG** or **LOG_NO_INFO** settings.

In order to allow testing to rely on logging regardless of configuration #1679 introduced new CMake options (**LOG_NO_INFO**, **LOG_NO_WARNING**, **LOG_NO_ERROR**). 

In order to enable info logging on debug builds **LOG_NO_INFO** option was set if **CMAKE_BUILD_TYPE** was debug.  Unfortunately this broke multiconfig generators usual behaviour because:
- they don't use **CMAKE_BUILD_TYPE** to specify the config (but is specified in a second build step by CMake cli).
- Fast-DDS defaults to **CMAKE_BUILD_TYPE=Release** if the variable is not provided.
thus: 
- multiconfig build never log infos by default.
- if logging was enforced by using **LOG_NO_INFO=OFF** then ALL configurations log ruining performance in Release.

To solve this issue:
 - **LOG_NO_INFO** falls back to its previous behavior. If option **LOG_NO_INFO=OFF** it doesn't force all configs to log infos but only debug if **INTERNAL_DEBUG=ON**.
 - **LOG_NO_INFO** fulfillment can be enforced using a new option **ENFORCE_LOG_INFO**. This reproduces #1679 option behavior and can be used for testing purposes.

2021-02-22 21:05 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux&build=3838)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3838/)
* Linux aarch64[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Linux%20aarch64&build=996)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/996/)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Mac&build=3384)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3384/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Manual%20Windows&build=3864)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3864/)

2021-02-23 08:00 UTC, MiguelBarro commented
Verified that commit **685a10d** solves build issues on raspbian stretch.

2021-02-23 10:43 UTC, MiguelCompany requested changes
In order to ease integration with other products, I would suggest renaming both the `#define` and the cmake option, prefixing them with `FASTDDS_`

2021-02-23 10:43 UTC, MiguelCompany commented on include/fastdds/dds/log/Log.hpp
> +    ( defined(ENFORCE_LOG_INFO) || \
```suggestion
    (defined(ENFORCE_LOG_INFO) || \
```

2021-02-23 12:27 UTC, MiguelCompany approved these changes

2021-02-23 14:02 UTC, MiguelCompany commented
@richiprosima Please test windows

2021-02-23 15:28 UTC, MiguelCompany commented
@richiprosima Please test this

2021-02-23 18:59 UTC, MiguelCompany commented
@richiprosima Please test mac

2021-02-23 19:03 UTC, MiguelCompany commented
@richiprosima please test this

2021-02-24 15:21 UTC, merged