Add support for getting static discovery info from a raw string
eProsima/Fast-DDS pull request #1818
Opened 2021-03-09 21:26 UTC by richiware

This PR adds the feature of support a static discovery XML read from a string.
An example:

```c++
participant_qos_.wire_protocol().builtin.discovery_config.setStaticEndpointXMLFilename("data://<staticdiscovery>...</staticdiscovery>");
```

2021-03-11 06:49 UTC, richiware commented
@richiprosima Please test this

2021-03-11 14:41 UTC, richiware commented
@richiprosima Please test this

2021-03-12 06:59 UTC, richiware commented
@richiprosima Please test this

2021-03-12 08:11 UTC, richiware commented
@richiprosima Please test this

2021-03-16 07:44 UTC, richiware commented
@richiprosima Please test this

2021-03-16 07:46 UTC, richiware commented
@richiprosima Please check style

2021-03-16 07:55 UTC, EduPonz requested changes
I think we should create and API so normal users can benefit from the feature as well. Furthermore, I'd like a related documentation PR. Kudos for the tests! 🚀

2021-03-29 13:28 UTC, EduPonz requested changes

2021-03-29 13:28 UTC, EduPonz commented on include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
> +    void static_edp_xml_content(
Knowing that you were not convinced with the name, I propose an alternative. Mind that you'd need to propagate the change
```suggestion
    void static_edp_xml_config(
```

2021-03-29 13:28 UTC, EduPonz commented on include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
> +        return static_edp_xml_content_.c_str();
I'd have the deprecated function calling the new one

2021-03-29 13:28 UTC, EduPonz commented on test/blackbox/common/BlackboxTestsDiscovery.cpp
> +TEST(Discovery, StaticDiscoveryFromString)
I'd like a description of the general purpose of the tests followed by a step by step guide on the actions taken

2021-03-29 14:29 UTC, EduPonz approved these changes
LGTM with green CI 🚀

2021-03-29 14:43 UTC, EduPonz requested changes

2021-03-29 14:43 UTC, EduPonz commented on test/blackbox/common/BlackboxTestsDiscovery.cpp
> + * configuration or passing directly the XML content. This tests tests the second way.
```suggestion
 * configuration or passing directly the XML content. This test tests the second way.
```

2021-03-29 14:43 UTC, EduPonz commented on test/blackbox/common/BlackboxTestsDiscovery.cpp
> + * discovery.
```suggestion
 * discover each other.
```

2021-03-29 14:49 UTC, EduPonz approved these changes
LGTM with green CI 🤖

2021-03-30 05:40 UTC, merged