Move RTPSDomain mutex lock to callers of find_local_participant
eProsima/Fast-DDS pull request #1823
Opened 2021-03-10 15:20 UTC by MiguelCompany

This prevents the race detected on #1819 by ensuring that the `RTPSDomain` mutex is taken when a new entry is added to `RTPSParticipant::m_allReaderList` or `RTPSParticipant::m_allWriterList`

2021-03-11 03:46 UTC, fujitatomoya reviewed
as far as i see, this makes sense to me.

2021-03-16 06:43 UTC, IkerLuengo submitted a review, later dismissed
:+1:

2021-03-30 02:48 UTC, VladimirVassiliev commented on src/cpp/rtps/RTPSDomain.cpp
> +            lock.unlock();
This lock cannot be released here, as it is protecting m_RTPSParticipants and the participant reference.

2022-02-16 06:20 UTC, JLBuenoLopez-eProsima requested changes
There are several build warnings. Some of them I think are due to not being rebased with the latest changes in `master` (for `2.5.0` the test types were updated). However, some of the warnings seems to be introduced by this PR. I suggest rebasing to `master`.

2022-02-16 06:20 UTC, JLBuenoLopez-eProsima commented on src/cpp/rtps/RTPSDomain.cpp
> +            lock.unlock();
The same issue also applies here.

2022-02-16 06:37 UTC, MiguelCompany commented
@JLBuenoLopez-eProsima This PR is not correct. What we should do is have another mutex on RTPSDomainParticipantImpl protecting the endpoint collections.

That would be easy to do. The difficult part comes in designing a regression test.

2022-02-16 11:55 UTC, JLBuenoLopez-eProsima commented
Close in favor #2506

2022-02-16 11:55 UTC, closed without merging