New flow controller public API
eProsima/Fast-DDS pull request #1839
Opened 2021-03-18 11:51 UTC by richiware

Declaration of new flow controller public API for Fast-DDS.

2021-03-18 14:16 UTC, rsanchez15 requested changes
Please double check the CI jobs as there are some warnings in all of them.

2021-03-18 14:41 UTC, richiware commented on include/fastdds/rtps/flowcontrol/FlowControllerDescriptor.hpp
> +#include "FlowControllerDefs.hpp"
There is no coding style for this right now, and using \" in this case will be faster for the preprocessor.

2021-03-18 14:47 UTC, richiware commented on include/fastdds/dds/domain/qos/DomainParticipantQos.hpp
> +    std::vector<std::shared_ptr<fastdds::rtps::FlowControllerDescriptor>>& flow_controllers()
✅

2021-03-18 14:47 UTC, richiware commented on include/fastdds/rtps/flowcontrol/FlowControllerDefs.hpp
> +extern const char* const DEFAULT_FLOW_CONTROLLER_NAME;
✅

2021-03-18 14:47 UTC, richiware commented on include/fastdds/rtps/flowcontrol/FlowControllerDefs.hpp
> + * Supported scheduler plans by a flow controller.
✅

2021-03-18 14:47 UTC, richiware commented on include/fastdds/rtps/flowcontrol/FlowControllerDefs.hpp
> + * Fast-DDS flow controller supports several scheduler plans listed in this enumeration.
✅

2021-03-18 14:47 UTC, richiware commented on include/fastdds/rtps/flowcontrol/FlowControllerDescriptor.hpp
> +    //! Scheduler plan used by the flow controller.
✅

2021-03-18 14:48 UTC, richiware commented on include/fastdds/rtps/flowcontrol/FlowControllerDescriptor.hpp
> +    //! Period time in milliseconds.
✅

2021-03-18 14:48 UTC, richiware commented on include/fastdds/rtps/flowcontrol/FlowControllerDefs.hpp
> +enum class FlowControllerScheduler : int32_t
✅

2021-03-22 06:46 UTC, rsanchez15 approved these changes
Failed tests are not related to this PR.
Approved pending include header files style resolution.

2021-03-22 10:02 UTC, MiguelCompany commented on include/fastdds/rtps/flowcontrol/FlowControllerDescriptor.hpp
> +#include "FlowControllerDefs.hpp"
As we do not have a rule yet, we can admit it by now.

2021-03-22 10:08 UTC, merged