[10799] NACKFRAG_COUNT callback implementation
eProsima/Fast-DDS pull request #1915
Opened 2021-04-14 13:09 UTC by MiguelBarro

In order to test the callback the test fixture was updated to use a special transport with leaks.
An ABBA deadlock was detected and solved.
This pull request must be merged after https://github.com/eProsima/Fast-DDS/pull/1911

2021-04-21 05:50 UTC, JLBuenoLopez-eProsima requested changes

2021-04-21 05:50 UTC, JLBuenoLopez-eProsima commented on test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
> +            uint32_t fragmentNum, old_pos = msg.pos;
Each variable should be declared in its own line.

2021-04-21 09:41 UTC, MiguelBarro commented on src/cpp/rtps/participant/RTPSParticipantImpl.h
> +            msg->length);
let's unlock the mutex when is no longer needed

2021-04-21 09:44 UTC, MiguelBarro commented on test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
> +    // There are specific gee
no clue 🤣

2021-04-23 06:00 UTC, JLBuenoLopez-eProsima commented on test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
> +#include <map>
The headers are not ordered alphabetically nor the private headers are after the public ones.

2021-04-23 06:00 UTC, JLBuenoLopez-eProsima reviewed
Please, fix linters and header include order in `RTPSStatisticsTests.cpp`

2021-04-26 06:51 UTC, JLBuenoLopez-eProsima approved these changes
LGTM

2021-04-26 06:52 UTC, merged