Fix statistics header file inclusion
eProsima/Fast-DDS pull request #1983
Opened 2021-05-21 07:34 UTC by richiware

Depending on the order of header file inclusion could be a linkage error. This is because `StatisticsBase.hpp` always includes `StatiticsCommon.hpp`, with statistics enable or not. This PR moves content of `StatisticsCommonEmpty.hpp` into `StatisticsCommon.hpp` and uses the `FASTDDS_STATISTICS` define to select implementation.

2021-05-21 08:02 UTC, MiguelBarro requested changes
LGTM and to Github actions
Please note the comment

2021-05-21 08:31 UTC, richiware commented on include/fastdds/statistics/rtps/StatisticsCommon.hpp
> +#else
done

2021-05-21 08:42 UTC, MiguelBarro approved these changes
LGTM

2021-05-24 10:21 UTC, richiware commented
Failed tests not related. Merging...

2021-05-24 10:21 UTC, merged