Add readmes for performance tests
eProsima/Fast-DDS pull request #2000
Opened 2021-06-07 10:55 UTC by richiware

2021-06-07 12:29 UTC, rsanchez15 requested changes
Throughput test review

2021-06-07 12:29 UTC, rsanchez15 commented on test/performance/throughput/README.md
> +time. While the test doesn't exceed the test time, the publication node will try in a loop to send a burst of nth samples and
```suggestion
time. While the test does not exceed the test time, the publication node will try in a loop to send a burst of `n` samples and
```

2021-06-07 12:29 UTC, rsanchez15 commented on test/performance/throughput/README.md
> +Our utility is able to execute at the same time several tests with different setups.
```suggestion
The throughput test application is able to execute at the same time several tests with different setups.
```

2021-06-07 12:29 UTC, rsanchez15 commented on test/performance/throughput/README.md
> +These are the elements you can configure:
```suggestion
The elements that can be configured are the following:
```

2021-06-07 12:29 UTC, rsanchez15 commented on test/performance/throughput/README.md
> +At the end of the testing the utility will show a table with the test results.
```suggestion
At the end of the execution the utility will show a table with the test results. Below is an example of these test results.
```

2021-06-07 12:29 UTC, rsanchez15 commented on test/performance/throughput/README.md
> +Columns shows next information:
```suggestion
The columns show the next information:
```

2021-06-07 12:29 UTC, rsanchez15 commented on test/performance/throughput/README.md
> +You can enable the compilation of the utility using the CMake option `PERFORMANCE_TESTS`.
```suggestion
This utility can be enabled by using the CMake option `PERFORMANCE_TESTS`.
```

2021-06-07 12:29 UTC, rsanchez15 commented on test/performance/throughput/README.md
> + you may compile Fast-DDS and this utility using next command.
```suggestion
Following the Fast DDS [*Installation from sources* guide](https://fast-dds.docs.eprosima.com/en/latest/installation/sources/sources_linux.html),
 Fast-DDS and this utility can be compiled executing the next command.
```

2021-06-07 12:29 UTC, rsanchez15 commented on test/performance/throughput/README.md
> +You can find this utility executable in the building directory.
```suggestion
The throughput test executable can be found in the `build` directory.
```

2021-06-07 12:29 UTC, rsanchez15 commented on test/performance/throughput/README.md
> +Also it is able to have both roles, useful for testing special Fast-DDS mechanisms such as *intraprocess communication*
```suggestion
Also it is able to have both roles, useful for testing special Fast DDS mechanisms such as *intraprocess communication*
```

2021-06-07 12:29 UTC, rsanchez15 commented on test/performance/throughput/README.md
> +, other seding bursts of 100 samples of 32 bytes and the last one sending bursts of 1000 samples of 32 bytes.
```suggestion
, and other seding bursts of 100 samples of 32 bytes and the last one sending bursts of 1000 samples of 32 bytes.
```

2021-06-07 12:29 UTC, rsanchez15 commented on test/performance/throughput/README.md
> +The directory also comes with a python script which automates the execution of the test nodes.
```suggestion
The directory also comes with a Python script which automates the execution of the test nodes.
```

2021-06-07 13:01 UTC, richiware commented on test/performance/throughput/README.md
> +[compiled](#compilation) with Fast-DDS.
Done

2021-06-07 13:01 UTC, richiware commented on test/performance/throughput/README.md
> +time. While the test doesn't exceed the test time, the publication node will try in a loop to send a burst of nth samples and
Done

2021-06-07 13:21 UTC, rsanchez15 approved these changes

2021-06-08 05:15 UTC, richiware commented
Failed tests not related.

2021-06-08 05:15 UTC, merged