Validate sequence range on CDRMessage::readSequenceNumberSet
eProsima/Fast-DDS pull request #2035
Opened 2021-07-02 06:25 UTC by MiguelCompany

As a follow-up of #2027, this PR adds a validation check to avoid overflowing the high part of the sequence number.

2021-07-02 07:28 UTC, richiware requested changes

2021-07-02 07:28 UTC, richiware commented on include/fastdds/rtps/messages/CDRMessage.hpp
> +        numBits = (std::min)(numBits, std::numeric_limits<uint32_t>::max() - seqNum.high);
```suggestion
        numBits = (std::min)(numBits, std::numeric_limits<uint32_t>::max() - seqNum.low);
```

2021-07-02 07:46 UTC, MiguelCompany commented on include/fastdds/rtps/messages/CDRMessage.hpp
> +        numBits = (std::min)(numBits, std::numeric_limits<uint32_t>::max() - seqNum.high);
Ups!

2021-07-02 08:07 UTC, richiware approved these changes

2021-07-05 07:21 UTC, MiguelCompany commented
@richiprosima Please test this

2021-07-06 05:44 UTC, MiguelCompany commented
@richiprosima Please test discovery-server

2021-07-06 10:50 UTC, merged