Fix wrong usage of condition_variable
eProsima/Fast-DDS pull request #2039
Opened 2021-07-02 06:54 UTC by richiware

2021-07-02 07:26 UTC, MiguelCompany requested changes

2021-07-02 07:26 UTC, MiguelCompany commented on test/blackbox/api/dds-pim/PubSubReader.hpp
> +                std::unique_lock<std::mutex> lock(reader_.message_receive_mutex_);
```suggestion
                std::lock_guard<std::mutex> guard(reader_.message_receive_mutex_);
```

2021-07-02 08:02 UTC, MiguelCompany approved these changes
LGTM

2021-07-05 05:43 UTC, richiware commented
Tests were passed in #2047.

2021-07-05 05:43 UTC, merged