Status condition blackbox [11834]
eProsima/Fast-DDS pull request #2052
Opened 2021-07-07 07:20 UTC by IkerLuengo

2021-07-08 12:24 UTC, MiguelCompany commented
@IkerLuengo Please rebase. Also fix warnings on mac and windows.

2021-07-08 14:39 UTC, MiguelCompany requested changes
Partial review

2021-07-08 14:39 UTC, MiguelCompany commented on test/blackbox/api/dds-pim/PubSubWriter.hpp
> +                    }
```suggestion
                    // did we wake up for some reason other than calling stop?
                    if (!guard_condition_.get_trigger_value())
                    {
                        ASSERT_FALSE(active_conditions_.empty());
                        EXPECT_EQ(active_conditions_[0], &writer_.datawriter_->get_statuscondition());
                        process(&writer_.datawriter_->get_statuscondition());
                    }
```

2021-07-08 14:39 UTC, MiguelCompany commented on test/blackbox/api/dds-pim/PubSubWriter.hpp
> +        bool running_;
```suggestion
        bool running_ = false;
```

2021-07-08 14:39 UTC, MiguelCompany commented on test/blackbox/api/dds-pim/PubSubWriter.hpp
> +        unsigned int times_liveliness_lost_;
```suggestion
        //! The number of times deadline was missed
        unsigned int times_deadline_missed_ = 0;

        //! The number of times liveliness was lost
        unsigned int times_liveliness_lost_ = 0;
```

2021-07-08 14:39 UTC, MiguelCompany commented on test/blackbox/api/dds-pim/PubSubReader.hpp
> +        bool running_;
```suggestion
        bool running_ = false;
```

2021-07-08 14:39 UTC, MiguelCompany commented on test/blackbox/api/dds-pim/PubSubReader.hpp
> +        unsigned int times_deadline_missed_;
```suggestion
        unsigned int times_deadline_missed_ = 0;
```

2021-07-09 05:40 UTC, MiguelCompany requested changes

2021-07-09 05:40 UTC, MiguelCompany commented on test/blackbox/common/DDSBlackboxTestsListeners.cpp
> +    EXPECT_FALSE(writer2.is_matched());
```suggestion
    EXPECT_EQ(writer3.times_incompatible_qos(), 2u);
    EXPECT_FALSE(writer3.is_matched());
```

2021-07-09 08:39 UTC, IkerLuengo commented on test/blackbox/api/dds-pim/PubSubReader.hpp
> +                    }
I still wanted to check the other conditions, in case several were triggered (most unlikely, but still)

2021-07-09 09:30 UTC, MiguelCompany requested changes

2021-07-09 09:30 UTC, MiguelCompany commented on test/blackbox/api/dds-pim/PubSubWriter.hpp
> +                        process(dynamic_cast<eprosima::fastdds::dds::StatusCondition*>(condition));
```suggestion
                        process(&writer_.datawriter_->get_statuscondition());
```

2021-07-09 09:54 UTC, MiguelCompany commented
@mergifyio rebase

2021-07-09 10:13 UTC, MiguelCompany approved these changes
LGTM with green CI.

2021-07-10 15:09 UTC, merged