Fix error in read_sample()/take_sample() operations with Datasharing
eProsima/Fast-DDS pull request #2070
Opened 2021-07-15 08:46 UTC by richiware

The bug was reproduced when reader's history is 1 depth and while read_sample()/take_sample() operation is deserializing the data, the data  is overwritten by the datawriter. The `ReadTakeCommand` returned OK and the code tries to access a 0 length vector.

Also the code was changed to return NO_DATA if the operation will return no data.

2021-07-15 09:21 UTC, MiguelCompany requested changes

2021-07-15 09:21 UTC, MiguelCompany commented on test/unittest/dds/subscriber/DataReaderTests.cpp
> +        // With length == 0 the returned code should be okNO_DATA
```suggestion
        // With length == 0 the returned code should be NO_DATA
```

2021-07-15 09:21 UTC, MiguelCompany commented on src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
>          // Mark that some data is available
Move this comment below

2021-07-15 09:21 UTC, MiguelCompany commented on src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
> +                return_value_ = ReturnCode_t::RETCODE_OK;
```suggestion
                // Mark that some data is available
                return_value_ = ReturnCode_t::RETCODE_OK;
```

2021-07-15 09:50 UTC, MiguelCompany commented
> Also the code was changed to return NO_DATA if the operation will return no data.

Instead of doing this, we could add the following lines on `DataReaderImpl::read_or_take_next_sample`, right after `ReturnCode_t code = cmd.return_value();`

```
    if ((ReturnCode_t::RETCODE_OK == code) && (0 == sample_infos.length()))
    {
        code = ReturnCode_t::RETCODE_NO_DATA;
    }
```

2021-07-15 09:58 UTC, MiguelCompany commented
@richiware I would also add a regression test for `read_next_sample`

2021-07-16 06:17 UTC, richiware commented on src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
>          // Mark that some data is available
Done

2021-07-16 06:21 UTC, richiware commented
@MiguelCompany Regression test was implemented.

About your conditional statement suggestion in the `read_or_take_next_sample()`, I'm not sure. It will only fix the error in the `read_next_sample/take_next_sample`functions.
In case of calling `read/take` function with one sample in the history and the deserialization of that change fails, the function will return OK.

2021-07-16 08:30 UTC, MiguelCompany requested changes

2021-07-16 08:30 UTC, MiguelCompany commented on test/unittest/dds/subscriber/DataReaderTests.cpp
> +        // With length == 0 the returned code should be NO_DATA
```suggestion
        //  The standard is not clear on what should be done if max_samples is 0. NO_DATA? OK with length = 0?
        // We have assumed the correct interpretation is the first one.
        // This test should change whenever this interpretation becomes invalid.
```

2021-07-16 09:37 UTC, MiguelCompany approved these changes
LGTM with green CI

2021-07-16 10:48 UTC, MiguelCompany approved these changes

2021-07-19 06:00 UTC, MiguelCompany commented
@richiware This needs a rebase

2021-07-19 06:20 UTC, richiware commented
Rebase was done.

2021-07-19 06:31 UTC, MiguelCompany approved these changes
LGTM with green CI

2021-07-19 07:46 UTC, merged