Avoid a volatile datasharing reader blocks a writer
eProsima/Fast-DDS pull request #2090
Opened 2021-07-23 10:07 UTC by richiware

2021-07-23 11:17 UTC, MiguelCompany requested changes

2021-07-23 11:17 UTC, MiguelCompany commented on test/blackbox/common/BlackboxTestsPubSubHistory.cpp
> +                break;
```suggestion
            case rtps::PREALLOCATED_MEMORY_MODE:
            case rtps::PREALLOCATED_WITH_REALLOC_MEMORY_MODE:
                will_use_datasharing = enable_datasharing;
                break;
```

2021-07-23 11:17 UTC, MiguelCompany commented on test/blackbox/common/BlackboxTestsPubSubHistory.cpp
> +    if (enable_datasharing && will_use_datasharing)
```suggestion
    if (will_use_datasharing)
```

2021-07-23 11:17 UTC, MiguelCompany commented on test/blackbox/common/BlackboxTestsPubSubHistory.cpp
> +    if (enable_datasharing && will_use_datasharing)
```suggestion
    if (will_use_datasharing)
```

2021-08-30 10:19 UTC, MiguelCompany approved these changes
LGTM

2021-08-30 10:20 UTC, MiguelCompany commented
@richiprosima Please test this

2021-09-02 08:38 UTC, richiware commented
@MiguelCompany Fixed compilation error

2021-09-02 09:32 UTC, MiguelCompany submitted a review, later dismissed
LGTM with green CI!

2021-09-06 13:50 UTC, MiguelCompany approved these changes
LGTM. Failures seem unrelated.

2021-09-06 13:50 UTC, richiware commented
Failed tests not related

2021-09-06 13:51 UTC, MiguelCompany commented
@mergifyio backport 2.3.x

2021-09-06 13:51 UTC, merged