Move optionparser to thirdparty
eProsima/Fast-DDS pull request #2123
Opened 2021-08-06 06:08 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

2021-12-15 11:48 UTC, JLBuenoLopez-eProsima requested changes
LGTM though Windows CI is issuing a lot of warnings that should be fixed before considering merging.

Also, fix please the uncrustify in those files that are not external.

2021-12-15 11:48 UTC, JLBuenoLopez-eProsima commented on thirdparty/optionparser/optionparser.h
> +      const char* optarg;
Windows CI is complaining about this variables being uninitialized. I think we should revert these two changes.

2021-12-15 14:00 UTC, JLBuenoLopez-eProsima approved these changes
LGTM with greenish CI

2021-12-15 14:16 UTC, jparisu commented
Uncrustify fails in thirdparty file `optionparser.h`

2021-12-16 06:53 UTC, juanlofer-eprosima approved these changes
LGTM, although I am not sure whether Linux tests are expected to fail. Also, perhaps we might want to preserve thirdparties in every example so they can be run as standalone programs.

2022-02-17 15:38 UTC, closed without merging