Separate initialization and enabling of BuiltinProtocols
eProsima/Fast-DDS pull request #2171
Opened 2021-08-30 06:56 UTC by richiware

The goal is to improve bandwidth network when using Static Discovery. Currently when the `RTPSParticipant` is created, BuiltinProtocols are initialized and enabled at same time. Using Static Discovery provokes each time a DDS entity is enabled a new DATA(p) is sent adding this entity into the property list.

With this PR the enabling of BuiltinProtocols is done after the enabling of DDS entities. Using Static Discovery only one DATA(p) is sent with all entities information.

2021-12-13 11:29 UTC, richiware commented on include/fastdds/rtps/builtin/discovery/participant/PDP.h
> +    bool is_enable()
Done

2022-01-03 15:15 UTC, MiguelCompany requested changes
Apart from my small suggestion below, this needs a rebase

2022-01-03 15:15 UTC, MiguelCompany commented on include/fastdds/rtps/builtin/discovery/participant/PDP.h
> +    //!Tell if object is enable
```suggestion
    //!Tell if object is enabled
```

2022-01-10 13:27 UTC, MiguelCompany approved these changes
LGTM with green CI

2022-02-16 06:23 UTC, JLBuenoLopez-eProsima commented
@richiprosima test this

2022-02-16 11:21 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2022-02-17 06:48 UTC, JLBuenoLopez-eProsima commented
CI failures seem unrelated (aarch64 has not run)

2022-02-17 08:11 UTC, JLBuenoLopez-eProsima commented
Maybe it should be considered if this PR should be moved to `2.6.0`. There is a new public method `enable` added to `BuiltinProtocols`. Even though this class should be private, right now is public...

2022-03-03 05:46 UTC, MiguelCompany commented
@richiprosima Please test this

2022-03-08 06:26 UTC, JLBuenoLopez-eProsima commented
CI failures seem unrelated. Ready to merge!

2022-03-08 06:27 UTC, merged