Fix statistics writers sometimes uses the user's publisher
eProsima/Fast-DDS pull request #2172
Opened 2021-08-30 10:22 UTC by richiware

This can lead to an error. If the user's publisher is configured with a partition, there will no matching with statistics_backend

2021-08-30 10:32 UTC, MiguelCompany requested changes
The changes look good to me, but we need a regression test for this.

2021-11-12 10:05 UTC, richiware commented on test/blackbox/common/DDSBlackboxTestsStatistics.cpp
> +    p_qos.transport().use_builtin_transports = false;
I've tested removing this and regression test still fails

2021-11-12 10:05 UTC, richiware commented on test/blackbox/common/DDSBlackboxTestsStatistics.cpp
> +    user_pub_1->enable();
I've tested removing this and regression test still fails

2021-11-12 10:26 UTC, jsantiago-eProsima commented on test/blackbox/common/DDSBlackboxTestsStatistics.cpp
> +    p_qos.transport().use_builtin_transports = false;
Probably not needed since the issue appears to be related to the Participant-created entities' Qos, regardless of transport.

2021-11-17 10:20 UTC, richiware reviewed
LGTM

2021-11-17 10:23 UTC, MiguelCompany submitted a review, later dismissed
LGTM

2021-11-19 09:54 UTC, MiguelCompany commented
Running Linux job with DDSStatistics tests enabled:

[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=fastdds_linux&build=1452)](http://jenkins.eprosima.com:8080/job/fastdds_linux/1452)

2021-11-19 17:34 UTC, MiguelCompany approved these changes

2021-11-22 06:29 UTC, merged