Changes to facilitate bindings to python
eProsima/Fast-DDS pull request #2195
Opened 2021-09-07 10:55 UTC by IkerLuengo

2021-09-14 09:04 UTC, MiguelCompany requested changes

2021-09-14 09:04 UTC, MiguelCompany commented on include/fastdds/rtps/common/Time_t.h
> +     * Comparison assignment
Comparison assignment?

2021-09-14 13:07 UTC, IkerLuengo commented on include/fastdds/dds/topic/TypeSupport.hpp
According to the standard, operators are inherited (except for the assignment operator).
And according to the CI, everything is working

2021-09-14 13:30 UTC, IkerLuengo commented on include/fastdds/rtps/common/EntityId_t.hpp
> +    /**
Undid these changes to avoid API break.
We should deal with this on the binding without affecting Fast DDS

2021-09-14 13:32 UTC, IkerLuengo commented on include/fastdds/dds/topic/TypeSupport.hpp
> +#include <fastdds/rtps/common/InstanceHandle.h>
Sure.

2021-09-14 15:04 UTC, MiguelCompany requested changes

2021-09-14 15:04 UTC, MiguelCompany commented on include/fastdds/rtps/common/Time_t.h
> +     * Comparison assignment
```suggestion
     * Comparison operator
```

2021-09-14 15:04 UTC, MiguelCompany commented on include/fastdds/rtps/common/Time_t.h
> +     * Comparison assignment
```suggestion
     * Comparison operator
```

2021-09-15 06:00 UTC, MiguelCompany commented on include/fastdds/dds/topic/InstanceHandle.hpp
> +extern RTPS_DllAPI const InstanceHandle_t HANDLE_NIL;
And I also think this file should be on `include/fastdds/dds/common` (remember to update the header guard)

2021-09-15 10:46 UTC, MiguelCompany requested changes

2021-09-15 10:46 UTC, MiguelCompany commented on include/fastdds/dds/common/InstanceHandle.hpp
> +#define _FASTDDS_DDS_INSTANCE_HANDLE_HPP_
```suggestion
#ifndef _FASTDDS_DDS_COMMON_INSTANCEHANDLE_HPP_
#define _FASTDDS_DDS_COMMON_INSTANCEHANDLE_HPP_
```

2021-09-15 10:46 UTC, MiguelCompany commented on include/fastdds/dds/common/InstanceHandle.hpp
> +#endif // _FASTDDS_DDS_INSTANCE_HANDLE_HPP_
```suggestion
#endif // _FASTDDS_DDS_COMMON_INSTANCEHANDLE_HPP_

```

2021-09-15 10:46 UTC, MiguelCompany commented on include/fastdds/dds/topic/TypeSupport.hpp
I would still feel better if we build and run the examples on all platforms first.

2021-09-16 08:28 UTC, IkerLuengo commented on include/fastdds/dds/topic/TypeSupport.hpp
**LINUX:**
I modified a HelloWorldExample as below to test these three operators. Compiled fast and then compiled the example as stand-alone. Checked that it was linking to the library version in the current pull request. Everything worked as expected.

```
--- a/examples/C++/DDS/HelloWorldExample/HelloWorldPublisher.cpp
+++ b/examples/C++/DDS/HelloWorldExample/HelloWorldPublisher.cpp
@@ -55,6 +55,12 @@ bool HelloWorldPublisher::init()
     //REGISTER THE TYPE
     type_.register_type(participant_);
 
+    std::cout << type_->getName() << std::endl;
+    std::cout << (*type_).getName() << std::endl;
+    std::cout << (type_ ? "yes" : "no") << std::endl; // expected to print 'yes'
+    TypeSupport newType;
+    std::cout << (newType ? "yes" : "no") << std::endl; // expected to print 'no'
+
     //CREATE THE PUBLISHER
     publisher_ = participant_->create_publisher(PUBLISHER_QOS_DEFAULT, nullptr);
```

2021-09-17 05:12 UTC, MiguelCompany commented
@richiprosima Please test mac

2021-09-17 06:20 UTC, MiguelCompany commented on include/fastdds/dds/topic/TypeSupport.hpp
Checked the same on Windows

2021-09-17 07:14 UTC, MiguelCompany approved these changes
LGTM

2021-09-17 07:17 UTC, MiguelCompany commented
@richiprosima Please test this

2021-09-17 08:42 UTC, MiguelCompany approved these changes
LGTM with green CI

2021-09-17 11:12 UTC, MiguelCompany commented
All failures unrelated.

2021-09-17 11:12 UTC, merged