Discovery Server fix reconnection
eProsima/Fast-DDS pull request #2246
Opened 2021-10-04 12:25 UTC by jparisu

Merge after https://github.com/eProsima/Fast-DDS/pull/2244

2021-11-02 11:41 UTC, jparisu commented
Test with discovery server PR https://github.com/eProsima/Discovery-Server/pull/45

2021-11-02 11:44 UTC, jparisu commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> +    for (auto& participant_it : participants_)
:+1:

2021-11-02 14:53 UTC, MiguelCompany submitted a review, later dismissed
Code looks good to me, but I still have to verify with the new tests.

2021-11-03 06:46 UTC, MiguelCompany commented
Discovery Server CI:
[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=discovery_server_linux&build=1372)](http://jenkins.eprosima.com:8080/job/discovery_server_linux/1372)

2021-11-03 07:16 UTC, jparisu commented
It seems like some tests are failing due to time limits, because executing (`with SHM` and `without SHM`) one of them fails and the other don't.
Let me check in my local and change the times for a wider timeout.

2021-11-03 09:03 UTC, jparisu commented
The time has been slightly increased, it should be enough.
Please @MiguelCompany could you launch the tests again?

2021-11-03 11:00 UTC, MiguelCompany commented
Discovery Server CI *with new timeouts*:
[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=discovery_server_linux&build=1376)](http://jenkins.eprosima.com:8080/job/discovery_server_linux/1376)

2021-11-03 13:12 UTC, MiguelCompany commented
> Discovery Server CI _with new timeouts_: [![Build Status](https://camo.githubusercontent.com/3b1f37e8b892af4220b5020a58306c083ffd51cbbd7f504de64bda2768709885/687474703a2f2f6a656e6b696e732e6570726f73696d612e636f6d3a383038302f6275696c645374617475732f69636f6e3f6a6f623d646973636f766572795f7365727665725f6c696e7578266275696c643d31333736)](http://jenkins.eprosima.com:8080/job/discovery_server_linux/1376)

This is just failing setting a PR status, as it was not launched from a PR.

2021-11-11 09:27 UTC, EduPonz commented
@richiprosima please test this

2021-11-11 09:34 UTC, EduPonz commented
CI with corresponding Discovery Server tests
[![Build Status](http://ci.intranet.eprosima.com:8080/job/discovery_server_linux/1397/badge/icon)](http://ci.intranet.eprosima.com:8080/job/discovery_server_linux/1397/)

2021-11-11 14:47 UTC, EduPonz requested changes

2021-11-11 14:47 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
>      }
I think this find is not necessary

2021-11-15 08:12 UTC, EduPonz approved these changes
LGTM, I'll run a CI just in case

2021-11-15 08:16 UTC, EduPonz commented
Discovery Server tests with eProsima/Discovery-Server#45:

[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=discovery_server_linux&build=1403)](http://jenkins.eprosima.com:8080/job/discovery_server_linux/1403)

2021-11-16 06:09 UTC, EduPonz commented
> [![Build Status](https://camo.githubusercontent.com/824e9640b8f7ce26f0867a79cb3f958bfe0e0ea6170cac3695d600377c38afdf/687474703a2f2f6a656e6b696e732e6570726f73696d612e636f6d3a383038302f6275696c645374617475732f69636f6e3f6a6f623d646973636f766572795f7365727665725f6c696e7578266275696c643d31343033)](http://jenkins.eprosima.com:8080/job/discovery_server_linux/1403)

I'm concerned about the `test_39_trivial_reconnect.SHM_ON` failure. What do you think @jparisu

2021-11-16 08:39 UTC, jparisu commented
> > [![Build Status](https://camo.githubusercontent.com/824e9640b8f7ce26f0867a79cb3f958bfe0e0ea6170cac3695d600377c38afdf/687474703a2f2f6a656e6b696e732e6570726f73696d612e636f6d3a383038302f6275696c645374617475732f69636f6e3f6a6f623d646973636f766572795f7365727665725f6c696e7578266275696c643d31343033)](http://jenkins.eprosima.com:8080/job/discovery_server_linux/1403)
> 
> I'm concerned about the `test_39_trivial_reconnect.SHM_ON` failure. What do you think @jparisu?

I could replicate the error in local, and it is due to time limit inside the test. Server B dies before Server A Data(Up) could arrive (this could happen because they are different processes and the time could not fit correctly).
Commit https://github.com/eProsima/Discovery-Server/pull/45/commits/d72162fab6bc0e982b53bf457d3db70f3d021178 in tests extends the time of the test. This should not fail again.

2021-11-16 09:12 UTC, EduPonz commented
Nice! One more CI run then with eProsima/Discovery-Server#45:

[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=discovery_server_linux&build=1407)](http://jenkins.eprosima.com:8080/job/discovery_server_linux/1407)

2021-11-22 08:44 UTC, EduPonz commented
CI run with updated eProsima/Discovery-Server#45:

[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=discovery_server_linux&build=1421)](http://jenkins.eprosima.com:8080/job/discovery_server_linux/1421)

2021-11-22 11:34 UTC, merged

2022-03-22 13:51 UTC, EduPonz commented
@Mergifyio backport 2.1.x

2022-03-22 14:05 UTC, rsanchez15 commented
@Mergifyio backport 2.3.x