Reservation of EntityId in DDS layer [12669]
eProsima/Fast-DDS pull request #2258
Opened 2021-10-11 13:29 UTC by richiware

Currently when the user creates a Datawriter or Datareader not enabled, the `get_guid()` functions return `GUID_t::unknown()`.

This PR fixes this and improve DDS API generating the GUID in the entity creation instead of in the enabling.

2021-12-13 10:39 UTC, richiware commented on test/unittest/dds/publisher/DataWriterTests.cpp
> +    }
done

2021-12-13 10:39 UTC, richiware commented on test/unittest/dds/subscriber/DataReaderTests.cpp
> +    }
done

2021-12-14 13:15 UTC, JLBuenoLopez-eProsima requested changes
Only some small nitpicks

2021-12-14 13:23 UTC, JLBuenoLopez-eProsima commented
Uncrustify is failing.

Also, the tests being based on discovery, I would randomize the domain ID where the tests are run to prevent spurious discoveries of other application entities that are running in the same domain.

2021-12-14 15:09 UTC, richiware commented on test/unittest/dds/publisher/DataWriterTests.cpp
> +TEST(DataWriterTests, get_guid)
Done

2021-12-14 15:09 UTC, richiware commented on test/unittest/dds/subscriber/DataReaderTests.cpp
> +TEST_F(DataReaderTests, get_guid)
Done

2021-12-17 09:08 UTC, MiguelCompany commented
> the tests being based on discovery, I would randomize the domain ID where the tests are run to prevent spurious discoveries of other application entities that are running in the same domain

@richiware This comment has not been addressed.

What I would do, instead of using a random domain id, is to use [ignoreParticipantFlags](https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/general_disc_settings.html#discovery-ignore-flags) with `FILTER_DIFFERENT_HOST | FILTER_DIFFERENT_PROCESS`, so only participants on the same process are considered

2021-12-17 09:28 UTC, richiware commented
> > the tests being based on discovery, I would randomize the domain ID where the tests are run to prevent spurious discoveries of other application entities that are running in the same domain
> 
> @richiware This comment has not been addressed.
> 
> What I would do, instead of using a random domain id, is to use [ignoreParticipantFlags](https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/general_disc_settings.html#discovery-ignore-flags) with `FILTER_DIFFERENT_HOST | FILTER_DIFFERENT_PROCESS`, so only participants on the same process are considered

Ok. I will do it

2021-12-17 09:59 UTC, richiware commented
> > > the tests being based on discovery, I would randomize the domain ID where the tests are run to prevent spurious discoveries of other application entities that are running in the same domain
> > 
> > 
> > @richiware This comment has not been addressed.
> > What I would do, instead of using a random domain id, is to use [ignoreParticipantFlags](https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/general_disc_settings.html#discovery-ignore-flags) with `FILTER_DIFFERENT_HOST | FILTER_DIFFERENT_PROCESS`, so only participants on the same process are considered
> 
> Ok. I will do it

Done

2021-12-17 10:06 UTC, MiguelCompany approved these changes
LGTM

2021-12-20 09:00 UTC, JLBuenoLopez-eProsima submitted a review, later dismissed
LGTM

Tests do not seem to be flakey anymore. Thanks!

2021-12-20 09:17 UTC, JLBuenoLopez-eProsima approved these changes
:ok_hand:

2021-12-20 13:46 UTC, merged