Add participant locators if new network interfaces are found
eProsima/Fast-DDS pull request #2310
Opened 2021-11-10 14:43 UTC by JLBuenoLopez-eProsima

Currently only network interfaces found when launching Fast DDS are taken into account. This PR adds new participant locators if new network interfaces are detected. In order to trigger the check, the user must call `DomainParticipant::set_qos`. If some user is using the RTPS layer directly, the feature can also be triggered by calling `RTPSParticipant::update_attributes`.

This PR only includes the implementation. Another PR to the same intermediary branch will also include the tests.

2021-11-30 15:45 UTC, MiguelCompany requested changes
Two minor comments

2021-11-30 15:45 UTC, MiguelCompany commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +            rtps_participant_->update_attributes(rtps_participant_->getRTPSParticipantAttributes());
```suggestion
            // Trigger update of network interfaces by calling update_attributes
            rtps_participant_->update_attributes(rtps_participant_->getRTPSParticipantAttributes());
```

2021-11-30 15:45 UTC, MiguelCompany commented on src/cpp/rtps/participant/RTPSParticipantImpl.cpp
> +    // Check if new interfaces has been added
```suggestion
    // Check if new interfaces have been added
```

2021-12-14 14:00 UTC, EduPonz commented
Close in favor of #2336

2021-12-14 14:00 UTC, closed without merging