Fix InstanceHandle_t issues [13111]
eProsima/Fast-DDS pull request #2334
Opened 2021-12-01 08:28 UTC by MiguelCompany

This is a follow-up to #2316, that should fix the build errors on [Win32](http://jenkins.eprosima.com:8080/job/nightly_fastdds_sec_master_windows/896/label=windows-secure,platform=Win32,toolset=v142/)

2021-12-01 08:31 UTC, MiguelCompany commented
Note to the reviewer: I've just realized that 755338c can be reverted, as with the changes on edb21e4 the compiler will take care of the implicit conversions.

2021-12-01 10:02 UTC, EduPonz requested changes
This LGTM, although I'd like a Win32 CI run on this

2021-12-02 07:08 UTC, MiguelCompany commented
> This LGTM, although I'd like a Win32 CI run on this

Running [here](http://jenkins.eprosima.com:8080/view/Nightly/job/nightly_fastdds_sec_master_windows/898/)

2021-12-02 08:05 UTC, richiware approved these changes

2021-12-02 09:10 UTC, merged