Updating content filter interfaces
eProsima/Fast-DDS pull request #2351
Opened 2021-12-15 13:54 UTC by MiguelCompany

After some internal discussions about the design, this PR updates the following interfaces:

**IContentFilterFactory**
* Method `create_content_filter` receives `TopicDataType` instead of `TopicDescriptor`

2021-12-15 13:55 UTC, MiguelCompany commented
@richiprosima Please test this

2021-12-15 14:07 UTC, EduPonz requested changes

2021-12-15 15:36 UTC, EduPonz approved these changes
LGTM

2021-12-16 06:18 UTC, MiguelCompany commented
@richiprosima Please test windows

2021-12-16 07:42 UTC, merged