[13563] Release lifecycle
eProsima/Fast-DDS pull request #2459
Opened 2022-02-02 08:50 UTC by JLBuenoLopez-eProsima

Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>

2022-02-02 08:50 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2022-02-02 11:47 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2022-02-03 08:52 UTC, EduPonz requested changes

2022-02-03 08:52 UTC, EduPonz commented on RELEASE_SUPPORT.md
> +Latest major release is v2.0.0 (June 2020) which introduced DDS compliant API.
I'd add a link to the versioning policy document somewhere here

2022-02-03 08:52 UTC, EduPonz commented on RELEASE_SUPPORT.md
> +Each quarter, a new Fast DDS minor version is released, including new features.
```suggestion
Each quarter, a new Fast DDS minor version with new features is released.
```

2022-02-03 08:52 UTC, EduPonz commented on RELEASE_SUPPORT.md
> +By default, *eProsima Fast DDS* minor releases have a lifecycle of 6 months.
```suggestion
By default, *eProsima Fast DDS* minor releases have a lifecycle of **6 months**.
```

2022-02-03 08:52 UTC, EduPonz commented on RELEASE_SUPPORT.md
> +However, the life of certain branches can be extended depending on costumer needs.
```suggestion
However, the life of certain branches can be extended depending on costumer and user needs.
```

2022-02-03 08:52 UTC, EduPonz commented on RELEASE_SUPPORT.md
> +Within the support period of any minor version, there can be patch releases that either add new fuctionalities in an
```suggestion
Within the support period of any minor version, there may be several patch releases that either add new functionalities in an
```

2022-02-03 08:52 UTC, EduPonz commented on RELEASE_SUPPORT.md
> +ABI compatible way, or fix possible issues.
In general, only break lines after period in md

2022-02-03 08:52 UTC, EduPonz commented on RELEASE_SUPPORT.md
> +Before the minor release end of life (EOL), a final patch release including the latest fixes will be done if there are
```suggestion
Before the minor release end of life (EOL) date, a final patch release including the latest fixes will be make available if there are any
```

2022-02-03 08:52 UTC, EduPonz commented on RELEASE_SUPPORT.md
> +changes not included previously in any other patch release.
```suggestion
changes not included any previous patch release of the same minor version.
```

2022-02-03 08:52 UTC, EduPonz commented on RELEASE_SUPPORT.md
> +|v2.6.x|March 2022|May 2023 [^*]|
I'd order this from most recent to oldest

2022-02-03 08:52 UTC, EduPonz commented on RELEASE_SUPPORT.md
> +[^*]: This release support could be extended.
```suggestion
[^*]: Support may be extended.
```

2022-02-03 15:25 UTC, EduPonz requested changes

2022-02-03 15:25 UTC, EduPonz commented on RELEASE_SUPPORT.md
> +Latest major release is v2.0.0 (June 2020) which introduced DDS compliant API.
```suggestion
Latest major release is v2.0.0 (June 2020), which introduced the DDS compliant API.
```

2022-02-03 15:25 UTC, EduPonz commented on RELEASE_SUPPORT.md
> +Within the support period of any minor version, there may be several patch releases that either add new functionalities in an ABI compatible way, or fix possible issues.
```suggestion
Within the support period of any minor version, there may be several patch releases that either add new functionalities in an ABI compatible way or fix possible issues.
```

2022-02-04 07:49 UTC, EduPonz approved these changes
LGTM

2022-02-04 07:55 UTC, MiguelCompany requested changes
Just a grammar issue.

2022-02-04 07:55 UTC, MiguelCompany commented on RELEASE_SUPPORT.md
> +Before the minor release end of life (EOL) date, a final patch release including the latest fixes will be make available if there are any changes not included in any previous patch release of the sam
```suggestion
Before the minor release end of life (EOL) date, a final patch release including the latest fixes will be made available if there are any changes not included in any previous patch release of the same minor version.
```

2022-02-07 06:47 UTC, richiware submitted a review, later dismissed

2022-02-07 06:53 UTC, MiguelBarro approved these changes
LGTM

2022-02-07 07:11 UTC, EduPonz approved these changes

2022-02-07 07:51 UTC, MiguelCompany approved these changes

2022-02-09 06:30 UTC, merged