[10843] Correctly protect endpoints collections
eProsima/Fast-DDS pull request #2506
Opened 2022-02-16 11:54 UTC by JLBuenoLopez-eProsima

This PR closes #1819. It also replaces #1823.

I have tried the regression test proposed in that PR but it does not seem to provoke the data race condition and the segmentation fault. However, the test is prone to failure due to discovery issues. Thus, I have not introduced it in this PR (if the reviewer considers it is of interest I can update this PR). There is no regression test because forcing the failure is not straight forward nor easy. However, the benefits of correctly protecting the access to the collections are too great compare to a regression test. My opinion is that this fix should be merged.

2022-02-17 06:35 UTC, JLBuenoLopez-eProsima commented
CI failures seem unrelated

2022-02-18 06:42 UTC, MiguelCompany requested changes

2022-02-18 06:42 UTC, MiguelCompany commented on src/cpp/rtps/writer/StatefulWriter.cpp
> +    RTPSReader* reader = reader_proxy->local_reader();
I think this should be left untouched.

There is a corner case where the proxy could still have a pointer to an already deleted reader.

2022-02-18 10:06 UTC, MiguelCompany approved these changes

2022-02-20 12:58 UTC, MiguelCompany commented
@richiprosima Pleas test aarch64

2022-02-21 06:57 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test aarch64

2022-02-21 07:04 UTC, merged