[13521] Deprecate rtps security properties
eProsima/Fast-DDS pull request #2577
Opened 2022-03-15 15:00 UTC by MiguelCompany

## Description
This PR deprecates the following properties:
* `rtps.participant.rtps_protection_kind`
* `rtps.endpoint.submessage_protection_kind`
* `rtps.endpoint.payload_protection_kind`

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- *N/A* Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [x] Documentation builds and tests pass locally. 
- [x] New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation.
  https://github.com/eProsima/Fast-DDS-docs/pull/512

## Reviewer Checklist
- [x] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-03-16 06:27 UTC, JLBuenoLopez-eProsima requested changes
Changes LGTM though there are some tests that seem to have been broken by these changes (probably because they checked the deprecated properties):

* BuiltinAuthenticationAndCryptoPlugin_rtps_ok_same_participant.Datasharing
* BuiltinAuthenticationAndCryptoPlugin_submessage_ok_same_participat.Datasharing
* BuiltinAuthenticationAndCryptoPlugin_payload_ok_same_participant.Datasharing

Also, I am concerned about removing the properties functionality without having formally deprecated them. I think we can argue the point by stating it is a Security vulnerability. But it must be clearly explained so if some user has been using these properties, it is clear that upgrading to Fast DDS v2.6.0 will make that security is not well configured and most probably not used.

2023-06-20 09:46 UTC, JesusPoderoso commented
It seems that a QoS missconfiguration plus datasharing performance led on Reader receiving only part of the sent messages.
Adjusting both reader and writer qos made test pass for datasharing transport.

2023-06-20 10:36 UTC, JesusPoderoso commented
@richiprosima Please test this

2023-06-20 10:52 UTC, JesusPoderoso commented
@richiprosima please test this

2023-06-20 14:10 UTC, JLBuenoLopez-eProsima requested changes
A couple of nitpicks

2023-06-20 14:10 UTC, JLBuenoLopez-eProsima commented on src/cpp/rtps/security/SecurityManager.cpp
> +                        logInfo(SECURITY, msg);
```suggestion
                        EPROSIMA_LOG_INFO(SECURITY, msg);
```

Use the new log macros instead of the legacy ones.

2023-06-20 14:22 UTC, JesusPoderoso commented
@richiprosima please test this

2023-06-20 14:27 UTC, JLBuenoLopez-eProsima approved these changes
LGTM with green CI

2023-06-21 05:01 UTC, merged