Add const to DataReader::guid()
eProsima/Fast-DDS pull request #2590
Opened 2022-03-22 08:43 UTC by pablogs9

## Description

Adding `const` to `guid()` method in DataReader

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-03-22 09:15 UTC, MiguelCompany requested changes

2022-03-23 13:46 UTC, pablogs9 commented on include/fastdds/dds/subscriber/DataReader.hpp
> +    RTPS_DllAPI const fastrtps::rtps::GUID_t& guid() const;
Done in b4c515824c860e86a7b428044e0c84501a9c0053

2022-03-24 12:46 UTC, MiguelCompany approved these changes

2022-03-25 10:39 UTC, merged

2022-03-25 10:39 UTC, MiguelCompany commented
@mergifyio backport 2.5.x 2.4.x 2.3.x 2.1.x