[14012, 14171] Implement RTPS extensions for writer-side filtering
eProsima/Fast-DDS pull request #2620
Opened 2022-04-01 07:28 UTC by MiguelCompany

## Description
Just what the title says.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [x] **N/A** Documentation builds and tests pass locally. 
- [x] **N/A** New feature has been added to the `versions.md` file (if applicable).
- [x] **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

2022-04-01 10:56 UTC, JLBuenoLopez-eProsima commented
Linters have failed so I have unchecked the code style checkbox. Please, recheck after fixing.

2022-04-05 10:28 UTC, JLBuenoLopez-eProsima requested changes
CI failures seem unrelated.

2022-04-06 08:32 UTC, MiguelCompany commented on include/fastdds/dds/core/policy/ParameterTypes.hpp
> +    /* From Table 9.18 of DDS-RTPS 2.5 */
The uncrustify job seems to be happy with the current changes, so I guess I can ignore this comment?

2022-04-06 09:35 UTC, JLBuenoLopez-eProsima commented on include/fastdds/dds/core/policy/ParameterTypes.hpp
> +    /* From Table 9.18 of DDS-RTPS 2.5 */
Yes, I think the indentation was the reason but it seems there was something else.

2022-04-06 10:56 UTC, MiguelCompany commented
@JLBuenoLopez-eProsima I applied the suggestions on the src files. The tests are still pending.

2022-04-06 12:32 UTC, MiguelCompany commented on test/blackbox/common/RTPSBlackboxTestsDiscovery.cpp
> +        ASSERT_EQ(0, content_filter_property.content_filtered_topic_name.size());
I think `0` is a special case. I have never seen it on warnings. Specially when compared with a `size_t`.

2022-04-06 12:55 UTC, MiguelCompany commented on test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
> +        ASSERT_EQ(0, out.content_filter().expression_parameters.size());
See 291f426

2022-04-06 13:01 UTC, MiguelCompany commented on test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
> + * \test RTPS-CFT-CFP-07 Tests serialization of `ContentFilterProperty_t` when `filterClassName` is empty.
Added to the doxydoc of the fields on d5ddcd2

2022-04-06 13:13 UTC, MiguelCompany commented on test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
> + * \test RTPS-CFT-CFP-03 Tests serialization of `ContentFilterProperty_t` fails with a wrong `contentFilteredTopicName`.
The test plan is using the names on the RTPS standard. I think we should stick to them in the comments. Same elsewhere.

2022-04-06 14:33 UTC, JLBuenoLopez-eProsima approved these changes
LGTM :+1:

2022-04-07 05:39 UTC, JLBuenoLopez-eProsima commented
CI failures seem unrelated. The tests that need to be introduced I think they are being done in #2621. Consequently, I think this PR is ready to be merged in the intermediary branch.

2022-04-07 06:39 UTC, merged