[14285] Add sanitizer workflow
eProsima/Fast-DDS pull request #2622
Opened 2022-04-04 06:10 UTC by MiguelBarro

Signed-off-by: Miguel Barro <miguelbarro@eprosima.com>

## Description

The sanitizer fixes go into the intermediate branch `features/tsan/fixes`. The github action must run whenever a *push* or *pull request* is performed against this intermediate branch.

Note that once the  `features/tsan/fixes` branch is merge into master the workflow must be modified to reference `master` changes as trigger.

The action will run on the Ubuntu host using the *apt* provided g++ (thread sanitizer is not yet available on other platforms).

The action's workflow:
- build from sources Fast-DDS and all the dependencies setting the sanitizer flags. 
- run the testing specifying a per-test sanitizer log.
- parsing the result log in order to: identify the issues, sort them by frequency, and filter out duplicates.
- generate a spreadsheet friendly output and a summary of the issues logs (one single report per issue)

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ]NA Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ]NA Any new/modified methods have been properly documented using Doxygen. 
- [ ]NA Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ]NA Documentation builds and tests pass locally. 
- [ ]NA New feature has been added to the `versions.md` file (if applicable).
- [ ]NA New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-04-04 06:58 UTC, MiguelCompany commented
@richiprosima Please test this

2022-04-06 18:25 UTC, rsanchez15 requested changes

2022-04-06 18:25 UTC, rsanchez15 commented on .github/workflows/thread-sanitizer.yaml
> +  push:
Set this so we can launch it manually at any time
```suggestion
  workflow_dispatch:
  push:
```

2022-04-06 18:25 UTC, rsanchez15 commented on .github/workflows/thread-sanitizer.yaml
> +          gci $exports | Compress-Archive -DestinationPath ./ws/artifact.zip
```suggestion
          gci $exports | Compress-Archive -DestinationPath ./ws/tsan_reports.zip 
```

2022-04-06 18:25 UTC, rsanchez15 commented on .github/workflows/thread-sanitizer.yaml
> +            path: /home/runner/work/ws/artifact.zip
```suggestion
            path: /home/runner/work/ws/tsan_reports.zip
```

2022-04-06 18:31 UTC, rsanchez15 commented
I ran this action on a Fast DDS fork repository and [here](https://github.com/rsanchez15/Fast-DDS/actions/runs/2102497837) are the results.

Please check also that almost all Fast DDS tests fail.

2022-04-10 11:46 UTC, MiguelBarro commented
As it is the workflow never fails. It runs all the tests and files the reports. In the future, when we manage to clear all the reports, we may enforce failure if new reports appear. Currently doesn't make much sense.

2022-04-11 05:14 UTC, rsanchez15 approved these changes

2022-04-11 05:20 UTC, merged