[14470] Improve doxygen documentation related to Locator classes.
eProsima/Fast-DDS pull request #2672
Opened 2022-05-09 08:49 UTC by JLBuenoLopez-eProsima

## Description

This PR improves doxygen documentation related to Locator classes improving thus the API reference.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
* **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [x] Any new/modified methods have been properly documented using Doxygen. 
* **N/A** Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [x] Documentation builds and tests pass locally. 
* **N/A** New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-05-09 08:55 UTC, JLBuenoLopez-eProsima commented
@richiprosima please check style

2022-05-09 12:17 UTC, MiguelCompany requested changes

2022-05-09 12:17 UTC, MiguelCompany commented on include/fastdds/rtps/common/LocatorList.hpp
> +     * @param loc locator to be appended.
We should document that `loc` will not be added if it is already present

2022-05-09 12:17 UTC, MiguelCompany commented on include/fastdds/rtps/common/LocatorList.hpp
> +     */
Same here

2022-05-19 09:10 UTC, MiguelCompany requested changes

2022-05-19 09:10 UTC, MiguelCompany commented on include/fastdds/rtps/common/LocatorList.hpp
> + *        Each individual locator within the list must follow the serialization format explained in the locator insertion
Please mention the separator used between locators

2022-05-19 09:10 UTC, MiguelCompany commented on include/fastdds/rtps/common/LocatorList.hpp
> + *        Each individual locator within the list must follow the deserialization format explained in the locator
Please mention the separator used between locators

2022-05-20 06:51 UTC, MiguelCompany commented
@richiprosima Please test this

2022-05-20 06:52 UTC, MiguelCompany approved these changes
LGTM. I've triggered a build-only CI just in case.

2022-05-20 08:39 UTC, MiguelCompany commented
Documentation job failed due to doxygen comments here:

```
fastdds/api_reference/rtps/common/Locator/operators.rst:None: (locatorN)  Insertion operator: serialize a locator list. The deserialization format is [locator1,locator2,...,locatorN]. Each individual locator within the list must follow the serialization format explained in the locator insertion operator. 
fastdds/api_reference/rtps/common/Locator/operators.rst:None: (locatorN)  Extraction operator: deserialize a list of locators. The serialization format is [locator1,locator2,...,locatorN]. Each individual locator within the list must follow the deserialization format explained in the locator extraction operator. 
```

2022-05-20 08:58 UTC, JLBuenoLopez-eProsima commented
Thanks @MiguelCompany! Fixed already in eProsima/Fast-DDS-docs#367

2022-05-20 09:42 UTC, merged