[14539] Reorganization of examples and dir name changes
eProsima/Fast-DDS pull request #2675
Opened 2022-05-11 10:30 UTC by antonrv

## Description
This PR deprecates the examples of the previous PubSub interface and changes the names of the directories 

- C++/ -> cpp/
- DDS/ -> dds/
- new folder rtps/ with RTPSTest_* examples
- Renaming of examples RTPSTest_* -> RTPS_*

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-06-22 13:05 UTC, MiguelBarro requested changes
Some issues:
+ Modify the project name in files:
```
        examples\cpp\dds\SampleConfig_Multimedia\CMakeLists.txt
        examples\cpp\dds\SampleConfig_Events\CMakeLists.txt
        examples\cpp\dds\SampleConfig_Controller\CMakeLists.txt
        examples\cpp\dds\Keys\CMakeLists.txt
        examples\cpp\dds\HistoryKind\CMakeLists.txt
```
+ Some examples have been removed:
  - `examples/C++/UserDefinedTransportExample` That's ok because HelloWorldExampleSharedMem replicates behavior.
  -  `examples/C++/XMLProfiles` That's wrong because there is no DDS example that shows this feature. A workaround may be to modify the `HelloWorldExample` cli to admit profiles. This requires discussion on *The Council of Elbrus*.
+ There is a faulty example:
👍 DDSWriterLoansExample
👍 DDSZeroCopyExample
👍 DDSHelloWorldExampleDataSharing 
👍 DDSHelloWorldExampleSharedMem
👍 DDSHelloWorldExampleTCP
👍 DDSSecureHelloWorldExample
👍 DDSBenchmark
👍 DDSClientServerTest
👍 DDSDeadlineQoSExample
👍 DDSDisablePositiveACKs
👍 DDSDynamicHelloWorldExample
👍 DDSFiltering
👍 DDSFlowControlExample
👍 DDSLifespanQoSExample
👍 DDSLivelinessQoS
👍 DDSOwnershipStrengthQoSExample
❌ DDSStaticHelloWorldExample 💨 HelloWorldSubscriber.xml is not installed (`update examples/cpp/dds/StaticHelloWorldExample/CMakeLists.txt`)
👍 DDSConfigurability (former DDSUseCase)
👍 DDSHistoryKind
👍 DDSKeys
👍 DDSLateJoiners
👍 DDSSampleConfig_Controller
👍 DDSSampleConfig_Events
👍 DDSSampleConfig_Multimedia
👍 DDSCustomListenerExample
👍 TypeLookupExample
👍 TypeLookupExample

2022-06-22 13:11 UTC, MiguelCompany commented
The issue with the XML on the StaticHelloWorld is already reported on internal ticket 13328

2022-06-23 14:24 UTC, MiguelBarro commented
*The Council of Elbrus* decided the `examples/C++/XMLProfiles` will be removed and the HelloWorldExample cli would be extended with an option that allows loading *xml* profiles.

2022-07-04 04:58 UTC, EduPonz commented
@richiprosima please test this

2022-07-04 07:38 UTC, MiguelCompany commented
@richiprosima Please test this

2022-07-04 09:28 UTC, MiguelBarro approved these changes

2022-07-04 10:32 UTC, MiguelCompany commented
@richiprosima Please test mac

2022-07-04 10:52 UTC, MiguelCompany requested changes
Three nits

2022-07-04 10:52 UTC, MiguelCompany commented on examples/cpp/dds/HelloWorldExample/HelloWorld_main.cpp
> +            print_error("Option '", option, "' requires a numeric argument\n");
requires a**n** ~~numeric~~ argument

2022-07-04 10:52 UTC, MiguelCompany commented on examples/cpp/dds/HelloWorldExample/README.txt
> +    - called it DEFAULT_FASTRTPS_PROFILES.xml and make sure the file is besides the DDSHelloWorldExample binary.
name it

2022-07-04 10:52 UTC, MiguelCompany commented on examples/cpp/dds/HelloWorldExample/HelloWorld_main.cpp
> +    // Decide among the old and new syntax
~~among~~ -> between

2022-07-04 10:55 UTC, MiguelBarro commented on examples/cpp/dds/HelloWorldExample/HelloWorld_main.cpp
> +            print_error("Option '", option, "' requires a numeric argument\n");
ack

2022-07-04 10:56 UTC, MiguelBarro commented on examples/cpp/dds/HelloWorldExample/README.txt
> +    - called it DEFAULT_FASTRTPS_PROFILES.xml and make sure the file is besides the DDSHelloWorldExample binary.
ack

2022-07-04 10:56 UTC, MiguelBarro commented on examples/cpp/dds/HelloWorldExample/HelloWorld_main.cpp
> +    // Decide among the old and new syntax
ack

2022-07-04 11:01 UTC, MiguelCompany approved these changes
LGTM

2022-07-04 12:12 UTC, merged