[14681] Fixing thread sanitizer issue 4169
eProsima/Fast-DDS pull request #2704
Opened 2022-05-27 08:55 UTC by MiguelBarro

## Description

This pull request addresses the following family of deadlocks `A => B => C => A` where:

+ A  `RecursiveTimedMutex& Endpoint::getMutex()` Endpoint is EDP DataWriter in Participant 2.
+ B  Participant 1. `std::recursive_mutex RTPSParticipantImpl::getParticipantMutex()`
+ C  Participant 2. `std::recursive_mutex RTPSParticipantImpl::getParticipantMutex()`

It involves a test case where two participants are destroyed from the Main Thread.
The execution sequence that leads to deadlocks:

+ `A=>B` Flow controller thread for EDP DataWriter in Participant 2.
     EDP DataWriter sending messages through its flow controller, that is, flow controller's asynchronous thread
     (`FlowControllerImpl::run()`). The asynchronous thread takes the DataWriter mutex (A).  
     Later it delivers the sample via intraprocess to EDPDataReader in participant 2 which takes the participant
     mutex (B) to traverse endpoint collections and do matching.

+ `B=>C` Main Thread.
     On test destruction comes participant 1 removal.
     Participant 1 calls `RTPSParticipantImpl::disable()` which takes mutex B to traverse it's endpoint list for
     removal. Here the EDP demise notifications go via intraprocess  and ends up in `EDP::unpairWriterProxy()`
     call that requires C (participant 2 mutex) for unmatching.

+ `C=>A` Main Thread
     On test destruction comes participant 2 removal.
     Participant 2 calls `RTPSParticipantImpl::disable()` which takes mutex C to traverse it's endpoint list for
     removal. In order to send `DATA[U]R` message it requires mutex (A) to allocate a new CacheChange (single mutex for
     history and endpoint).

In order to solve the deadlock, the participant's endpoint collections will no longer be protected by the general
participant mutex but by a devoted one (this was partially done before but the refactor extends it to all collections).

```
    mutable shared_mutex endpoints_list_mutex;

    std::vector<RTPSWriter*> m_allWriterList;
    std::vector<RTPSReader*> m_allReaderList;
    std::vector<RTPSWriter*> m_userWriterList;
    std::vector<RTPSReader*> m_userReaderList;
```

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] NA Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] NA Documentation builds and tests pass locally. 
- [ ] NA New feature has been added to the `versions.md` file (if applicable).
- [ ] NA New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-06-01 10:25 UTC, MiguelBarro commented
@richiprosima Please pal be so gentle to test Mac for me 😎

2022-06-10 10:12 UTC, jsantiago-eProsima requested changes
Just some minor typos

2022-06-10 10:20 UTC, MiguelBarro commented on src/cpp/rtps/participant/RTPSParticipantImpl.h
> +        RTPSParticipantImpl* previous_onwer = collections_mutex_owner_;
acknowledge

2022-06-10 10:20 UTC, MiguelBarro commented on src/cpp/rtps/participant/RTPSParticipantImpl.h
> +        std::swap(collections_mutex_owner_, previous_onwer);
acknowledge

2022-06-10 10:20 UTC, MiguelBarro commented on src/cpp/rtps/participant/RTPSParticipantImpl.h
> +        RTPSParticipantImpl* previous_onwer = collections_mutex_owner_;
acknowledge

2022-06-10 10:20 UTC, MiguelBarro commented on src/cpp/rtps/participant/RTPSParticipantImpl.h
> +        std::swap(collections_mutex_owner_, previous_onwer);
acknowledge

2022-06-10 10:27 UTC, jsantiago-eProsima approved these changes
LGTM

2022-06-10 10:31 UTC, merged