[14630] Adding configuration data for external locators feature
eProsima/Fast-DDS pull request #2748
Opened 2022-06-13 07:02 UTC by MiguelCompany

## Description

This PR adds `metatraffic_external_unicast_locators`, `default_external_unicast_locators`, and `ignore_non_matching_locators` to the participant configuration structures.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- **N/A** Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-06-24 11:23 UTC, MiguelCompany commented
@richiprosima Please test this

2022-07-01 04:56 UTC, MiguelCompany commented
@richiprosima Please test this

2022-07-01 05:20 UTC, EduPonz requested changes
Nits

2022-07-01 05:20 UTC, EduPonz commented on include/fastdds/rtps/attributes/EndpointAttributes.h
> +    //!The collection of external locators to use for communication.
Nit:
```suggestion
    //! The collection of external locators to use for communication.
```

2022-07-01 05:20 UTC, EduPonz commented on include/fastdds/rtps/attributes/EndpointAttributes.h
> +    //!Whether locators that don't match with the announced locators should be kept.
Nit:
```suggestion
    //! Whether locators that don't match with the announced locators should be kept.
```

2022-07-01 05:20 UTC, EduPonz commented on include/fastdds/dds/core/policy/QosPolicies.hpp
> +    //!The collection of external locators to use for communication.
```suggestion
    //! The collection of external locators to use for communication.
```

2022-07-01 05:20 UTC, EduPonz commented on include/fastdds/dds/core/policy/QosPolicies.hpp
> +    //!Whether locators that don't match with the announced locators should be kept.
```suggestion
    //! Whether locators that don't match with the announced locators should be kept.
```

2022-07-01 05:20 UTC, EduPonz commented on include/fastrtps/attributes/PublisherAttributes.h
> +    //!The collection of external locators to use for communication.
```suggestion
    //! The collection of external locators to use for communication.
```

2022-07-01 05:20 UTC, EduPonz commented on include/fastrtps/attributes/PublisherAttributes.h
> +    //!Whether locators that don't match with the announced locators should be kept.
```suggestion
    //! Whether locators that don't match with the announced locators should be kept.
```

2022-07-01 05:20 UTC, EduPonz commented on include/fastrtps/attributes/SubscriberAttributes.h
> +    //!Topic Attributes
Everywhere here
```suggestion
    //! Topic Attributes
```

2022-07-01 05:20 UTC, EduPonz commented on include/fastrtps/attributes/SubscriberAttributes.h
> +    fastdds::rtps::ExternalLocators external_unicast_locators;
Please update the design with this modification

2022-07-01 05:20 UTC, EduPonz commented on include/fastrtps/attributes/PublisherAttributes.h
> +    //!The collection of external locators to use for communication.
Please update design with this modification

2022-07-01 06:15 UTC, MiguelCompany commented
@EduPonz This is ready for another review

2022-07-01 06:42 UTC, EduPonz approved these changes

2022-07-01 08:01 UTC, merged