TypeIntrospection example implementation [14797]
eProsima/Fast-DDS pull request #2752
Opened 2022-06-15 05:54 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

Implement a new "generic" Type Introspection example.

## Description

This new example added in `examples/C++/DDS` is able to:
- Create a DomainParticipant with a Publisher and a DataWriter with different types depending on the arguments of the process. These datatypes are different from each other. These are :
  - Created by FastDDSGen and with TypeObject information
  - Created dynamically by an xml
  - Created dynamically by DynamicTypes
- Create a DomainParticipant that, when discover and endpoint in the topic specificed (by argument) it creats a Subscriber and a DataReader in that topic and with the data type registered dynamically. This Reader is able to decode the message and print it in `stdout` with the name of each variable and its value.

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-06-30 15:57 UTC, jparisu commented
@richiprosima Please test this

2023-01-25 13:47 UTC, irenebm commented on examples/cpp/dds/TypeIntrospectionExample/README.md
> +# Basic Configuration Example
```suggestion
# Basic Configuration Example
# Type Introspection Example
```

2023-01-25 13:51 UTC, irenebm commented on examples/cpp/dds/TypeIntrospectionExample/CMakeLists.txt
> +# file(GLOB DATATYPE_HELLOWORLD_SOURCES_CPP "types/hello_world/**/*.cpp")
Remove commented lines?

2023-01-25 14:08 UTC, irenebm commented on examples/cpp/dds/TypeIntrospectionExample/README.md
> +  -w <num>        --wait=<num>
Remove

2023-01-25 14:14 UTC, irenebm commented on examples/cpp/dds/TypeIntrospectionExample/README.md
> +TODO
TODO

2023-01-26 09:02 UTC, jparisu reviewed
Changes requested

2023-01-26 09:02 UTC, jparisu commented on examples/cpp/dds/TypeIntrospectionExample/arg_configuration.h
> +constexpr const char* SIMPLELARGE_DATA_TYPE_ARG = "simple";
Let`s use consistent names and call them equal to their folders 
```suggestion
constexpr const char* SIMPLELARGE_DATA_TYPE_ARG = "simple_large";
```

2023-03-21 07:07 UTC, JLBuenoLopez-eProsima commented
Milestone updated to v2.11.0 because the example fails with current dynamic types implementation.

2023-03-21 07:14 UTC, juanlofer-eprosima requested changes

2023-03-21 07:14 UTC, juanlofer-eprosima commented on examples/cpp/dds/TypeIntrospectionExample/arg_configuration.h
> +    { TYPE_INFORMATION_DISABLE, 0, "i", "type-information-disable",              Arg::None,
Please check this works as expected: verify if enumeration should coincide and/or second argument should be 0 or 1. Also, perhaps one of them should not use `-i`.

2023-06-02 07:30 UTC, juanlofer-eprosima requested changes

2023-06-02 07:30 UTC, juanlofer-eprosima commented on examples/cpp/dds/TypeIntrospectionExample/TypeIntrospectionSubscriber.cpp
> +        }
```suggestion
        if (subscriber_ != nullptr)
        {
            if (reader_ != nullptr)
            {
                subscriber_->delete_datareader(reader_);
            }
            participant_->delete_subscriber(subscriber_);
        }
        if (topic_ != nullptr)
        {
            participant_->delete_topic(topic_);
        }
```

2023-06-06 13:27 UTC, juanlofer-eprosima requested changes

2024-05-07 08:29 UTC, closed without merging