Add interfaces for ReadCondition
eProsima/Fast-DDS pull request #2778
Opened 2022-06-24 08:58 UTC by MiguelCompany

## Description

This PR adds the necessary changes to the public API in order to support ReadCondition.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. <-- Note: we are breaking the API on unsupported methods
- [ ] Documentation builds and tests pass locally. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-06-24 09:13 UTC, MiguelCompany commented
@richiprosima Please test this

2022-06-29 12:40 UTC, MiguelBarro commented
According with **DDS 1.4 2.2.2.5.3.10** the following `DataReader` methods should fail if the given condition is not attach to the reader. Thus, they cannot neither default nor accept a `nullptr`:
+ read_w_condition()
+ take_w_condition()
+ read_next_instance_w_condition()
+ take_next_instance_w_condition()

2022-06-29 15:01 UTC, MiguelCompany commented
@richiprosima Please test this

2022-06-29 15:12 UTC, MiguelBarro requested changes
Keep the reasonable defaults

2022-06-29 15:12 UTC, MiguelBarro commented on include/fastdds/dds/subscriber/DataReader.hpp
> -            const InstanceHandle_t& previous_handle = HANDLE_NIL,
These defaults are acceptable and desirable

2022-06-29 15:12 UTC, MiguelBarro commented on include/fastdds/dds/subscriber/DataReader.hpp
> -            int32_t max_samples = LENGTH_UNLIMITED,
This default is acceptable and desirable

2022-06-29 15:12 UTC, MiguelBarro commented on include/fastdds/dds/subscriber/DataReader.hpp
> -            const InstanceHandle_t& previous_handle = HANDLE_NIL,
These defaults are acceptable and desirable

2022-06-30 05:51 UTC, MiguelBarro approved these changes
LGTM
It's a pity to be forced to remove all default argument values to keep the standard parameter order 🙄

2022-06-30 06:53 UTC, MiguelCompany commented
@richiprosima Please test mac

2022-06-30 07:29 UTC, merged