Fix resetting of `LivelinessLostStatus::total_changes`
eProsima/Fast-DDS pull request #2782
Opened 2022-06-27 13:17 UTC by richiware

## Description

RTPS layer always reset `LivelinessLostStatus::total_changes` after calling the `on_liveliness_lost()` listener callback.
This PR fixes this adding its own `LivelinessLostStatus` to `DataWriterImpl`.

@Mergifyio backport 2.5.x

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-06-28 05:48 UTC, EduPonz requested changes

2022-06-28 05:48 UTC, EduPonz commented on src/cpp/fastdds/publisher/DataWriterImpl.cpp
> +            listener->on_liveliness_lost( data_writer_->user_datawriter_, status);
Shouldn't we use the DW status?
```suggestion
            listener->on_liveliness_lost(data_writer_->user_datawriter_, callback_status);
```

2022-06-28 05:48 UTC, EduPonz commented on src/cpp/fastdds/publisher/DataWriterImpl.cpp
> +    liveliness_lost_status_.total_count_change += liveliness_lost_status.total_count;
I think this is rather brittle as it very much relies on the implementation details on WLP, but I do not know what to do about that

2022-06-28 05:57 UTC, EduPonz requested changes

2022-06-28 05:57 UTC, EduPonz commented on src/cpp/fastdds/publisher/DataWriterImpl.cpp
> +    liveliness_lost_status_.total_count_change += liveliness_lost_status.total_count;
```suggestion
    liveliness_lost_status_.total_count_change += liveliness_lost_status.total_count_change;
```

2022-07-13 05:25 UTC, EduPonz approved these changes

2022-07-13 05:26 UTC, merged

2022-07-13 05:26 UTC, MiguelCompany commented
@mergifyio backport 2.6.x 2.3.x 2.1.x