Added missing protection during liveliness assertion
eProsima/Fast-DDS pull request #2794
Opened 2022-06-30 08:49 UTC by jsantiago-eProsima

Signed-off-by: Javier Santiago <javiersantiago@eprosima.com>

## Description

Added missing protection during liveliness assertion. This may cause erroneous memory access in some cases.

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-06-30 08:53 UTC, MiguelBarro submitted a review, later dismissed
LGTM

2022-06-30 09:00 UTC, MiguelCompany requested changes

2022-06-30 09:00 UTC, MiguelCompany commented on src/cpp/rtps/writer/LivelinessManager.cpp
> +    std::unique_lock<std::mutex> lock(mutex_);
```suggestion
    std::lock_guard<std::mutex> lock(mutex_);
```

2022-07-08 06:45 UTC, MiguelCompany commented
@jsantiago-eProsima I think we can close this since #2801 has already been merged into master

2022-07-08 06:48 UTC, jsantiago-eProsima commented
Agreed. Closing.

2022-07-08 06:48 UTC, closed without merging