Adding check_xml_static_discovery UNSUPPORTED
eProsima/Fast-DDS pull request #2795
Opened 2022-06-30 09:08 UTC by adriancampo

## Description
This PR adds the check_xml_static_discovery method without implementation and returning RETCODE_UNSUPPORTED

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-06-30 15:22 UTC, jsantiago-eProsima requested changes

2022-06-30 15:22 UTC, jsantiago-eProsima commented on include/fastdds/dds/domain/DomainParticipantFactory.hpp
> +     * Check xml file for static discovery
```suggestion
     * Check the validity of the provided static discovery XML file
```

2022-06-30 15:22 UTC, jsantiago-eProsima commented on include/fastdds/dds/domain/DomainParticipantFactory.hpp
> +     * Not supported yet
```suggestion
```
This can be stated in the documentation.

2022-06-30 15:22 UTC, jsantiago-eProsima commented on include/fastdds/dds/domain/DomainParticipantFactory.hpp
> +     * @return RETCODE_UNSUPPORTED.
```suggestion
     * @return RETCODE_OK if the validation is successful, RETCODE_ERROR otherwise.
```

2022-07-01 08:13 UTC, MiguelCompany commented
@adriancampo Please fix uncrustify

2022-07-01 09:19 UTC, jsantiago-eProsima commented on test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
> +}
Upon further review, this test is fine where it is. Resolved.

2022-07-01 10:14 UTC, jsantiago-eProsima approved these changes
LGTM.

2022-07-01 11:08 UTC, MiguelCompany commented
@richiprosima Please test mac

2022-07-04 06:37 UTC, merged