[15017] External locators implementation
eProsima/Fast-DDS pull request #2822
Opened 2022-07-07 11:34 UTC by MiguelCompany

## Description

Adds implementation for the external locators feature.
WIP because we should add tests first.

Built on top of #2815 

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-07-08 05:22 UTC, MiguelCompany commented
@richiprosima Please test this

2022-07-08 05:33 UTC, MiguelCompany commented
@richiprosima Please test mac

2022-07-22 07:25 UTC, MiguelCompany commented
@richiprosima Please test this

2022-09-28 16:38 UTC, MiguelCompany commented
@richiprosima Please test this

2022-09-28 21:39 UTC, jsantiago-eProsima requested changes
Just two little comments regarding some asserts.

2022-09-28 21:45 UTC, jsantiago-eProsima commented
`ExternalLocatorsProcessorTests` are passing. CI failures unrelated.

2022-09-29 05:31 UTC, MiguelCompany commented on src/cpp/rtps/network/ExternalLocatorsProcessor.cpp
> +                assert(32 >= local_locator.mask());
Just read it from right to left. 😉

2022-09-29 05:31 UTC, MiguelCompany commented on src/cpp/rtps/network/ExternalLocatorsProcessor.cpp
> +                assert(128 >= local_locator.mask());
Just read it from right to left. 😉

2022-09-29 05:47 UTC, jsantiago-eProsima approved these changes

2022-09-29 06:32 UTC, MiguelCompany commented
@richiprosima Please test this

2022-09-29 06:35 UTC, MiguelCompany commented
@richiprosima Please test this

2022-09-29 07:59 UTC, merged