[15119] Clarified CacheChange reservation failure message
eProsima/Fast-DDS pull request #2824
Opened 2022-07-08 08:27 UTC by jsantiago-eProsima

Signed-off-by: Javier Santiago <javiersantiago@eprosima.com>

## Description

Currently, a trace with Error severity is shown during a change reception when trying to reserve a CacheChange but being unable to due so during to QoS constraints. This log trace should be a Warning instead, since there's no actual error, just expected behaviour. Also, modify the message shown so it better shows the actual issue.

@Mergifyio backport 2.6.x

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-07-08 08:32 UTC, MiguelCompany requested changes

2022-07-08 08:32 UTC, MiguelCompany commented on src/cpp/rtps/reader/StatefulReader.cpp
> +                        IDSTRING "Reached the specified maximum number samples allowed by this DataReader QoS. Rejecting change for reader: " <<
```suggestion
                        IDSTRING "Reached the maximum number of samples allowed by this reader's QoS. Rejecting change for reader " <<
```

2022-07-08 08:32 UTC, MiguelCompany commented on src/cpp/rtps/reader/StatelessReader.cpp
> +                        IDSTRING "Reached the specified maximum number samples allowed by this DataReader QoS. Rejecting change for reader: " <<
```suggestion
                        IDSTRING "Reached the maximum number of samples allowed by this reader's QoS. Rejecting change for reader " <<
```

2022-07-26 10:10 UTC, JLBuenoLopez-eProsima commented
@richiprosima Please test this

2022-07-27 09:31 UTC, EduPonz approved these changes

2022-07-27 09:31 UTC, merged

2022-09-05 06:06 UTC, MiguelCompany commented
@mergifyio backport 2.6.x