Add API to createRTPSWriter with a custom change pool [14951]
eProsima/Fast-DDS pull request #2841
Opened 2022-07-14 08:19 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

Some API is missing in order to create a RTPSWriter with a custom ChangePool

## Description

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-07-18 07:56 UTC, juanlofer-eprosima requested changes

2022-07-18 07:56 UTC, juanlofer-eprosima commented on include/fastdds/rtps/RTPSDomain.h
> +     * @param hist Pointer to the WriterHistory.
Missing docstring for new parameter.

2022-07-18 07:56 UTC, juanlofer-eprosima commented on src/cpp/rtps/RTPSDomain.cpp
> +        }
```suggestion
```

2022-07-18 13:43 UTC, juanlofer-eprosima submitted a review, later dismissed
LGTM

2022-07-20 06:18 UTC, rsanchez15 commented
@richiprosima Please test this

2022-07-29 06:31 UTC, MiguelCompany commented on include/fastdds/rtps/RTPSDomain.h
> +    RTPS_DllAPI static RTPSWriter* createRTPSWriter(
Could we also have an overload of this receiving a `const EntityId_t&`, it will just forward the call to `RTPSDomainImpl::create_rtps_writer`

2022-07-29 08:18 UTC, MiguelCompany requested changes

2022-07-29 08:18 UTC, MiguelCompany commented on src/cpp/rtps/RTPSDomain.cpp
> +    return nullptr;
```suggestion
    return RTPSDomainImpl::create_rtps_writer(p, entity_id, watt, payload_pool, change_pool, hist, listen);
```

2022-07-29 09:08 UTC, MiguelCompany commented
@richiprosima Please test this

2022-07-29 09:09 UTC, MiguelCompany approved these changes
LGTM, but we will need a follow-up PR adding tests for the new APIs

2022-07-29 11:34 UTC, merged