[15174] Add new CMake option to allow users to enforce use of our third party shared_mutex
eProsima/Fast-DDS pull request #2846
Opened 2022-07-15 10:23 UTC by MiguelBarro

## Description

The CMake option **USE_THIRDPARTY_SHARED_MUTEX** is added as **OFF** by default.
By turning it on users can enforce the use of our boost-like implementation of shared_mutex.
Otherwise, the third-party implementation will be used only if the build framework lacks a shared_mutex.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] NA Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [x] Documentation builds and tests pass locally. 
- [x] New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation. 

https://github.com/eProsima/Fast-DDS-docs/pull/384

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-07-15 10:38 UTC, jsantiago-eProsima requested changes
Small nitpick

2022-07-15 10:39 UTC, jsantiago-eProsima requested changes

2022-07-15 10:39 UTC, jsantiago-eProsima commented on versions.md
> +* Added a new CMake option to allow users to enforce use of our third party shared_mutex
```suggestion
* Added a new CMake option to allow users to force the use of our third party shared_mutex
```

2022-07-15 13:08 UTC, jsantiago-eProsima commented
@richiprosima please test this

2022-07-18 10:55 UTC, MiguelBarro commented
@richiprosima Please test this

2022-07-21 15:05 UTC, jsantiago-eProsima approved these changes

2022-07-21 15:05 UTC, jsantiago-eProsima commented
LGTM

2022-07-21 15:18 UTC, merged