Exclusive Ownership QoS
eProsima/Fast-DDS pull request #2856
Opened 2022-07-20 10:58 UTC by richiware

## Description

Implementation of Exclusive Ownership QoS.

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-08-12 12:24 UTC, richiware commented
@richiprosima Please test this

2022-08-13 15:46 UTC, richiware commented
@richiprosima Please test this

2022-08-14 09:30 UTC, richiware commented
@richiprosima Please test windows

2022-08-16 12:31 UTC, MiguelBarro commented
@richiprosima Please test windows

2022-08-16 23:35 UTC, jsantiago-eProsima commented
@richiprosima please test this

2022-08-17 07:28 UTC, MiguelBarro commented
@richiprosima please test this

2022-08-18 07:26 UTC, jsantiago-eProsima requested changes
PARTIAL REVIEW

2022-08-18 08:21 UTC, jsantiago-eProsima requested changes
Partial Review.

2022-09-12 13:04 UTC, jparisu commented
Example implemented in Fast DDS: https://github.com/eProsima/Fast-DDS/pull/2947

2022-09-15 06:11 UTC, MiguelBarro commented on src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
>      change->reader_info.no_writers_generation_count = vit->second->no_writers_generation_count;
It must be so to keep consistency with the the associated `RTPSReader` count. See `DataReaderHistory::get_unread_count`.

2022-09-15 06:15 UTC, MiguelBarro commented on src/cpp/fastdds/subscriber/history/DataReaderInstance.hpp
> +                    }
That is consistent with the DDS standard 2.2.3.9.2.  Improving it will require workaround transport lack of sequential sample reception capabilities.

2022-09-15 06:16 UTC, MiguelBarro approved these changes
LGTM

2022-09-15 14:28 UTC, MiguelBarro approved these changes
LGTM

2022-09-16 07:24 UTC, MiguelBarro commented
@richiprosima Please test this for me 😴

2022-09-16 07:24 UTC, jsantiago-eProsima commented
@richiprosima please test this

2022-09-16 07:29 UTC, jsantiago-eProsima approved these changes

2022-09-19 06:59 UTC, merged