Set WAN address API
eProsima/Fast-DDS pull request #2877
Opened 2022-07-26 06:57 UTC by rsanchez15

Signed-off-by: RaulSanchez <raul@eprosima.com>

## Description

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-08-08 06:38 UTC, rsanchez15 commented
@richiprosima Please test this

2022-08-08 08:48 UTC, EduPonz requested changes
Please add new API to versions.md. Other than that LGTM with green CI

2022-08-08 09:28 UTC, jparisu submitted a review, later dismissed
LGTM

2022-08-10 05:31 UTC, rsanchez15 commented
@richiprosima Please test this

2022-08-11 05:58 UTC, merged