[15250] Fixing datarace on listener callbacks
eProsima/Fast-DDS pull request #2889
Opened 2022-07-28 06:40 UTC by MiguelBarro

Signed-off-by: Miguel Barro <miguelbarro@eprosima.com>

## Description

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-07-28 09:35 UTC, MiguelBarro commented
@richiprosima Please test this for me 🤯

2022-07-28 09:39 UTC, MiguelBarro commented
@richiprosima Please test this

2022-07-28 13:44 UTC, MiguelBarro commented
@richiprosima Please test this

2022-07-28 16:47 UTC, MiguelBarro commented
@richiprosima Please test this

2022-07-28 21:58 UTC, MiguelBarro commented
@richiprosima Please test this

2022-07-29 01:09 UTC, MiguelBarro commented
@richiprosima Please test this

2022-07-29 10:01 UTC, rsanchez15 commented
The TSan workflow does not merge the PR branch into `master` before running the tests. I'd suggest to run the tests over the `master` branch to check that there are indeed no more data races than before. 

Therefore, rebase this branch to `master` until we can refactor the TSan workflow.

2022-08-01 05:11 UTC, EduPonz commented
@richiprosima please test windows

2022-08-01 05:45 UTC, rsanchez15 commented
Locally checked that dataraces 

- [ ] #15250: Disabling participant while raising a callback
- [ ] #15251 - Setting listener to nullptr at deleting participant while raising a callback
- [ ] #15252 - Setting listener while reading listener from RTPSParticipantImpl

are solved.

2022-08-01 09:13 UTC, MiguelCompany requested changes

2022-08-01 09:13 UTC, MiguelCompany commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
>          RTPSDomain::removeRTPSParticipant(rtps_participant_);
Call `get_rtps_participant()` once into local variable and use it later.

2022-08-01 09:13 UTC, MiguelCompany commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +        rtps_participant_ = part;
From this point on, we could use `part`  instead of `rtps_participant_` / `get_rtps_participant()`

2022-08-01 09:13 UTC, MiguelCompany commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +    bool enabled = (get_rtps_participant() != nullptr);
Call `get_rtps_participant()` once into local variable and use it later ?

Perhaps even taking `mtx_gs_` and using `rtps_participant_` directly ?

2022-08-01 09:13 UTC, MiguelCompany commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +    if (related_topic->get_participant() != this->get_participant())
```suggestion
    if (related_topic->get_participant() != get_participant())
```

2022-08-01 09:13 UTC, MiguelCompany commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +    if (get_rtps_participant() == nullptr)
Call `get_rtps_participant()` once into local variable and use it later

2022-08-01 09:13 UTC, MiguelCompany commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +        participant_->get_listener()->on_type_dependencies_reply(
```suggestion
        listener->on_type_dependencies_reply(
```

2022-08-01 09:13 UTC, MiguelCompany commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +    if (get_rtps_participant() == nullptr)
Call `get_rtps_participant()` once into local variable and use it later ?

2022-08-01 09:54 UTC, MiguelCompany commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +    if (get_rtps_participant() == nullptr)
I don't think is worth it in this case

2022-08-01 09:55 UTC, MiguelCompany commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +    bool enabled = (get_rtps_participant() != nullptr);
Solved by taking `mtx_gs_` for most of the method, except the call to `update_attributes`

2022-08-01 09:57 UTC, MiguelCompany commented
@richiprosima Please test this

2022-08-01 12:08 UTC, jsantiago-eProsima requested changes

2022-08-01 12:08 UTC, jsantiago-eProsima commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
>          return listener_;
This return call is still a data race with set_listener.

2022-08-01 12:30 UTC, MiguelCompany commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +    return get_rtps_participant()->get_resource_event();
I think we have no way of returning an invalid `ResourceEvent&` in this case, so I guess we cannot have a protection, other than inform of the pre-condition, and asserting on the implementation.

This is what I've done in 9cbc89c.

2022-08-01 12:31 UTC, MiguelCompany commented
@richiprosima Please test this

2022-08-01 12:32 UTC, jsantiago-eProsima approved these changes
LGTM

2022-08-01 12:32 UTC, jsantiago-eProsima commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +    return get_rtps_participant()->get_resource_event();
Sounds reasonable.

2022-08-02 05:15 UTC, MiguelCompany commented
> Please check if dataraces 1140, 1142 and 1152 (from [this sanitation-report](https://github.com/eProsima/Fast-DDS/actions/runs/2774818747)) can be solved with this changes.

Those will be fixed in a follow-up PR

2022-08-02 05:16 UTC, merged

2022-08-02 05:34 UTC, jsantiago-eProsima commented
1140 and 1142 are indeed fixed by this PR.