Implement Discovery Server Example [Meta]
eProsima/Fast-DDS pull request #2924
Opened 2022-08-19 09:20 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

## Description

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-01-26 08:29 UTC, jparisu reviewed
Requested changes

2023-01-26 08:29 UTC, jparisu commented on examples/cpp/dds/DiscoveryServerExample/arg_configuration.h
> +      "  -t <trans>\t--transport <trans> \tUse Transport Protocol [udpv4|udpv6] (UDPv6 by default)."
Please, update the example to use UDPv4 by default. This implies:
- Change in main the default arguments
- Change this help messages

2023-01-26 11:41 UTC, jparisu commented on examples/cpp/dds/DiscoveryServerExample/arg_configuration.h
> +      "  -t <trans>\t--transport <trans> \tUse Transport Protocol [udpv4|udpv6] (UDPv6 by default)."
It must change also de default value (and its messages) for the listening and connection address:
`::1` -> `127.0.0.1`

2023-02-07 11:44 UTC, EduPonz requested changes

2023-02-07 11:44 UTC, EduPonz commented on versions.md
> +
Normally we do not include examples in the versions.md. I think you can just mark that check as *N/A*

```suggestion
```

2023-03-16 14:22 UTC, JLBuenoLopez-eProsima commented
@jparisu @irenebm Does this PR supersedes #2178? If so, can you close it?

2023-03-16 15:03 UTC, juanlofer-eprosima commented
After merging this PR, add reference to documentation (https://github.com/eProsima/Fast-DDS-docs/pull/288).

2023-06-13 08:07 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2023-06-13 12:44 UTC, jparisu reviewed
@irenebm please apply changes

2023-06-13 12:44 UTC, jparisu commented on examples/cpp/dds/DiscoveryServerExample/README.md
> +Usage: DiscoveryServerExample <publisher|subscriber|server>
Update

2023-06-13 12:44 UTC, jparisu commented on examples/cpp/dds/DiscoveryServerExample/DiscoveryServer_main.cpp
> +                    connection_port = strtol(opt.arg, nullptr, 10);
`'=': conversion from 'long' to 'uint16_t', possible loss of data`

2023-06-13 12:44 UTC, jparisu commented on examples/cpp/dds/DiscoveryServerExample/DiscoveryServer_main.cpp
> +                    connection_ds_id = strtol(opt.arg, nullptr, 10);
`'=': conversion from 'long' to 'uint16_t', possible loss of data`

2023-06-13 12:44 UTC, jparisu commented on examples/cpp/dds/DiscoveryServerExample/DiscoveryServer_main.cpp
> +                    listening_port = strtol(opt.arg, nullptr, 10);
`'=': conversion from 'long' to 'uint16_t', possible loss of data`

2023-06-13 12:44 UTC, jparisu commented on examples/cpp/dds/DiscoveryServerExample/DiscoveryServer_main.cpp
> +                    listening_ds_id = strtol(opt.arg, nullptr, 10);
`'=': conversion from 'long' to 'uint16_t', possible loss of data`

2023-06-13 13:33 UTC, JesusPoderoso commented
@richiprosima please test this

2023-06-13 14:11 UTC, jparisu reviewed
@irenebm please check this

2023-06-13 14:11 UTC, jparisu commented on examples/cpp/dds/DiscoveryServerExample/DiscoveryServer_main.cpp
> +                    connection_port = static_cast<uint16_t>strtol(opt.arg, nullptr, 10);
```
connection_port = static_cast<uint16_t>(strtol(opt.arg, nullptr, 10));
```
Please, compile in local before upload a commit

Same error is repeated in other casts

2023-06-14 06:42 UTC, jparisu commented on examples/cpp/dds/DiscoveryServerExample/README.md
> +  -c <IPaddress>  --connection-address=<IPaddress[:port number]>
Not correctly done. This readme is finally a copy of the args set in `arg_configuration.h`

2023-06-14 10:19 UTC, irenebm approved these changes
LGTM

2023-06-14 10:19 UTC, jparisu commented
@richiprosima please test this

2023-06-15 08:46 UTC, merged