Improve GUID_t operator< performance
eProsima/Fast-DDS pull request #2955
Opened 2022-09-16 11:05 UTC by jparisu

## Description

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-09-19 06:49 UTC, MiguelCompany requested changes

2022-09-19 06:49 UTC, MiguelCompany commented on include/fastdds/rtps/common/EntityId_t.hpp
> +     * @return True if other is higher or equal this
```suggestion
     * @return True if @c other is higher than this
```

2022-09-19 06:49 UTC, MiguelCompany commented on include/fastdds/rtps/common/EntityId_t.hpp
>  #ifndef DOXYGEN_SHOULD_SKIP_THIS_PUBLIC
It would be great if we also update `==` and `!=` operators on lines 238-270

2022-09-19 06:49 UTC, MiguelCompany commented on include/fastdds/rtps/common/Guid.h
>          const GUID_t& g1,
Please add Doxygen documentation to this method

2022-09-19 06:49 UTC, MiguelCompany commented on include/fastdds/rtps/common/GuidPrefix_t.hpp
> +     * @return True if prefix is higher or equal this
```suggestion
     * @return True if @c prefix is higher than this
```

2022-09-19 10:04 UTC, MiguelCompany submitted a review, later dismissed
LGTM with green CI

2022-09-19 10:22 UTC, MiguelCompany commented
@jparisu Please uncrustify

2022-09-19 10:39 UTC, MiguelCompany approved these changes
LGTM with green CI

2022-09-21 08:25 UTC, EduPonz commented
@richiprosima please test this

2022-09-28 05:14 UTC, merged

2022-09-28 05:16 UTC, MiguelCompany commented
@mergifyio backport 2.7.x 2.6.x 2.3.x 2.1.x