[15628] XML configuration for Ownership QoS
eProsima/Fast-DDS pull request #2967
Opened 2022-09-22 11:50 UTC by MRicoIE2C

This PR Adds the possibility to configure Ownership and Ownership Strength QoS from XML.

## Description

This PR covers the following tasks:

- Creation of two new tests, to check the configuration of Ownership and Ownership Strength QoS in XML profile.
- Uncomment the already developed functions `getXMLOwnershipQos()` and `getXMLOwnershipStrengthQos()`.
- Arrange the correct call to those two methods from `getXMLWriterQosPolicies()`.
- Erase previous logs and comments that stated ownership was not supported.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
- [N/A] Changes are ABI compatible. 
- [N/A] Changes are API compatible. 
- [N/A] Documentation builds and tests pass locally. 
- [N/A] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-09-22 13:20 UTC, jsantiago-eProsima requested changes

2022-09-22 13:20 UTC, jsantiago-eProsima commented on src/cpp/rtps/xmlparser/XMLElementParser.cpp
> +        }
I think we are not handling this case properly. With this implementation we may end up with WriterQos policies that have both SHARED_OWNERSHIP and Ownership strength defined. As seen here, the strength is used to determine if we are using exclusive or shared Ownership there:

 https://github.com/eProsima/Fast-DDS/blob/78473a0de3d878a71565ee5d6c8e1e01c34beb70/src/cpp/fastdds/subscriber/history/DataReaderInstance.hpp#L198
 
 Maybe we should force that if the Ownership kind has not been explicitly set to EXCLUSIVE_OWNERSHIP the Ownership strength is discarded.

2022-09-27 10:11 UTC, richiware submitted a review, later dismissed
XSD file should be updated

2022-09-28 06:16 UTC, MRicoIE2C commented
> XSD file should be updated

XSD already contains instructions to check ownership QoS definition. I have tried it and works as expected.

2022-09-28 10:18 UTC, jsantiago-eProsima submitted a review, later dismissed

2022-09-28 10:24 UTC, EduPonz requested changes

2022-09-28 10:24 UTC, EduPonz commented on test/unittest/xmlparser/XMLElementParserTests.cpp
> +        EXPECT_EQ(ownership_strength_policy.value, 0);
```suggestion
        EXPECT_EQ(ownership_strength_policy.value, 0u);
```

2022-09-28 10:24 UTC, EduPonz commented on test/unittest/xmlparser/XMLElementParserTests.cpp
> +        EXPECT_EQ(ownership_strength_policy.value, 100);
```suggestion
        EXPECT_EQ(ownership_strength_policy.value, 100u);
```

2022-09-28 10:47 UTC, EduPonz commented
@richiprosima please test windows

2022-09-28 10:48 UTC, EduPonz submitted a review, later dismissed

2022-09-28 14:21 UTC, EduPonz commented
@richiprosima please test windows

2022-09-28 17:51 UTC, EduPonz approved these changes

2022-09-28 17:51 UTC, merged