[WIP] Fix tests failing with subprocess aborted error [16199]
eProsima/Fast-DDS pull request #3094
Opened 2022-11-15 14:47 UTC by rsanchez15

## Description

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-11-16 07:01 UTC, rsanchez15 commented
@richiprosima please test this

2022-11-17 13:43 UTC, rsanchez15 commented
@richiprosima please test this

2022-11-18 07:47 UTC, rsanchez15 commented
@richiprosima please test this

2022-11-18 10:36 UTC, jparisu requested changes
Please check the following test, that did not fail before.
If it is flaky, it should be labeled as so.

845 | BlackboxTests_DDS_PIM.DDSStatus.IncompatibleQosConditions.Datasharing

2022-11-18 10:36 UTC, jparisu commented on test/unittest/dds/topic/DDSSQLFilter/DDSSQLFilterTests.cpp
> +static const std::vector<std::string> operators
Is static required here?
Also, I would encapsulate those elements that are only for test propose in `test` namespace

2022-11-23 11:30 UTC, jparisu commented on test/unittest/dds/topic/DDSSQLFilter/DDSSQLFilterTests.cpp
> +static const std::vector<std::string> operators
Refactor for other PR

2022-11-23 11:30 UTC, jparisu approved these changes
LGTM

2022-11-23 13:16 UTC, merged