Fix datarace on WriterProxy stop while TimedEvent being triggered
eProsima/Fast-DDS pull request #3097
Opened 2022-11-18 08:32 UTC by juanlofer-eprosima

## Description

This PR is a revision of #3046, in which the data race between `WriterProxy::stop` and `perform_initial_acknack` was addressed by forcing the thread invoking the former to wait for the completion of the latter. However, a deadlock may occur as the reader waiting for the event to end does so with `Endpoint::mp_mutex` locked, which is also locked when sending an acknack at `perform_initial_acknack`.

Two different solutions are suggested:
- Introducing a new mutex in `StatefulReader` which is taken before reader's, and released after modifying the writer proxy's state and before waiting for the executing event to finish.
- Releasing reader's mutex before stopping a `WriterProxy`, and locking it again after doing so. This solution implies that `StatefulReader::matched_writer_add` and `StatefulReader::matched_writer_remove` may no longer be executed "atomically", a relevant change that should be carefully analyzed.

In addition, this PR also addresses the potential (rarely or never seen in our tests) datarace that may occur between `WriterProxy::stop` and `perform_heartbeat_response`, as `StatefulReader::send_acknack` reads attributes from `WriterProxy` which are modified when being stopped.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [x] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-12-07 06:37 UTC, jsantiago-eProsima requested changes

2022-12-07 12:10 UTC, jsantiago-eProsima commented on src/cpp/rtps/resources/TimedEvent.cpp
> +    impl_->go_cancel();
Answering my own question. Not needed since the timer is no longer on the internal collections.

2022-12-07 13:51 UTC, jsantiago-eProsima commented
@richiprosima please test this

2022-12-09 12:35 UTC, jsantiago-eProsima approved these changes

2022-12-10 20:34 UTC, EduPonz commented
@richiprosima please test this

2022-12-12 07:56 UTC, MiguelCompany commented
CI for 2.9.0-rc:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=fastdds_linux&build=3187)](http://jenkins.eprosima.com:8080/job/fastdds_linux/3187)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=fastdds_mac&build=2944)](http://jenkins.eprosima.com:8080/job/fastdds_mac/2944)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=fastdds_windows&build=3349)](http://jenkins.eprosima.com:8080/job/fastdds_windows/3349/)
* Discovery server [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=discovery_server_linux&build=3131)](http://jenkins.eprosima.com:8080/job/discovery_server_linux/3131/)

2022-12-13 09:24 UTC, merged