Datarace/boost named mutex
eProsima/Fast-DDS pull request #3104
Opened 2022-11-21 12:08 UTC by juanlofer-eprosima

## Description

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-12-05 08:47 UTC, jsantiago-eProsima requested changes
Some minor changes. Also, please uncrustify.

2022-12-07 11:37 UTC, jsantiago-eProsima commented
@richiprosima please test this

2022-12-09 08:54 UTC, MiguelCompany requested changes
Fix warnings on windows with my suggestions

2022-12-09 08:54 UTC, MiguelCompany commented on test/unittest/transport/SharedMemTests.cpp
> +                if ((locked = port_mutex->try_lock()))
```suggestion
                bool locked = port_mutex->try_lock();
                if (locked)
```

2022-12-09 08:54 UTC, MiguelCompany commented on test/unittest/transport/SharedMemTests.cpp
> +    if ((locked = port_mutex->try_lock()))
```suggestion
    bool locked = port_mutex->try_lock();
    if (locked)
```

2022-12-09 11:17 UTC, MiguelCompany commented
@richiprosima Please test this

2022-12-09 12:35 UTC, jsantiago-eProsima approved these changes

2022-12-10 20:34 UTC, EduPonz commented
@richiprosima please test this

2022-12-12 07:57 UTC, MiguelCompany commented
CI for 2.9.0-rc:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=fastdds_linux&build=3187)](http://jenkins.eprosima.com:8080/job/fastdds_linux/3187)
* Mac [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=fastdds_mac&build=2944)](http://jenkins.eprosima.com:8080/job/fastdds_mac/2944)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=fastdds_windows&build=3349)](http://jenkins.eprosima.com:8080/job/fastdds_windows/3349/)
* Discovery server [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=discovery_server_linux&build=3131)](http://jenkins.eprosima.com:8080/job/discovery_server_linux/3131/)

2022-12-13 09:41 UTC, merged