[16284] Avoid statistics calculations for not enabled statistics DataWriters
eProsima/Fast-DDS pull request #3109
Opened 2022-11-23 13:51 UTC by EduPonz

## Description

This PR prevents the calculation of any statistics measurements if the corresponding DataWriter is not enabled.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- *N/A*: New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-11-24 11:50 UTC, jsantiago-eProsima requested changes

2022-11-24 11:50 UTC, jsantiago-eProsima commented on test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
> +    //               GAP_COUNT, DATA_COUNT, SAMPLE_DATAS & PHYSICAL_DATA
GAP_COUNT does not seem to be tested.

2022-11-24 11:57 UTC, jsantiago-eProsima requested changes

2022-11-24 11:57 UTC, jsantiago-eProsima commented on test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
> +    //     EventKind::RESENT_DATAS;
Remove commented lines

2022-11-24 13:38 UTC, jsantiago-eProsima requested changes

2022-11-24 13:38 UTC, jsantiago-eProsima commented on src/cpp/statistics/rtps/reader/StatisticsReaderImpl.cpp
> +#include "../../types/types.h"
Maybe this could point to <statistics/types/types.h> instead of a relative path

2022-11-24 13:38 UTC, jsantiago-eProsima commented on src/cpp/statistics/rtps/writer/StatisticsWriterImpl.cpp
> +#include "../../types/types.h"
Same comment

2022-11-24 13:46 UTC, jsantiago-eProsima requested changes

2022-11-24 13:46 UTC, jsantiago-eProsima commented on src/cpp/statistics/rtps/StatisticsBase.hpp
> +#include <atomic>
Alphabetical order

2022-11-24 13:46 UTC, jsantiago-eProsima commented on src/cpp/statistics/fastdds/domain/DomainParticipantStatisticsListener.hpp
> +#include <atomic>
Alphabetical order.

2022-11-24 14:03 UTC, EduPonz commented
@richiprosima please test this

2022-11-24 14:11 UTC, jsantiago-eProsima commented
LGTM with green CI

2022-11-24 14:11 UTC, jsantiago-eProsima approved these changes

2022-11-25 06:49 UTC, EduPonz commented
@richiprosima please test this

2022-11-25 10:59 UTC, EduPonz commented
@richiprosima please test this

2022-11-28 15:30 UTC, EduPonz commented
@richiprosima please test windows

2022-11-29 06:56 UTC, jsantiago-eProsima commented
CI failures seem unrelated.

2022-11-29 09:49 UTC, jsantiago-eProsima approved these changes

2022-11-29 11:43 UTC, MiguelCompany requested changes
This is changing the behavior of the statistics module, so I think that should be reflected on versions.md

2022-11-30 10:57 UTC, MiguelCompany requested changes

2022-11-30 10:57 UTC, MiguelCompany commented on versions.md
> +* Statistics metric are only calculated/accumulated when their corresponding DataWriter is enabled (behaviour change)
```suggestion
* Statistics metrics are only calculated/accumulated when their corresponding DataWriter is enabled (behaviour change)
```

2022-11-30 10:59 UTC, MiguelCompany approved these changes

2022-11-30 11:25 UTC, merged