Fix failed tests when compiling with statistics enabled
eProsima/Fast-DDS pull request #3110
Opened 2022-11-23 14:10 UTC by rsanchez15

This PR covers the fix of the following tests:

  - BlackboxTests_DDS_PIM.PubSubBasic.ReceivedPropertiesDataWithinSizeLimit.Transport (Failed)
  - BlackboxTests_DDS_PIM.PubSubBasic.ReceivedPropertiesDataWithinSizeLimit.Intraprocess (Failed)
  - BlackboxTests_DDS_PIM.PubSubBasic.ReceivedPropertiesDataWithinSizeLimit.Datasharing (Failed)
  - UDPv4Tests.send_to_wrong_interface (Subprocess aborted)
  - UDPv6Tests.send_to_wrong_interface (Subprocess aborted)

## Description

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-11-24 17:09 UTC, rsanchez15 commented
@richiprosima please test this

2022-11-25 06:18 UTC, rsanchez15 commented
@richiprosima Please test this

2022-11-25 08:30 UTC, MiguelCompany requested changes
Just some nits on the current changes.

Would be great if you could also solve the link errors on Windows for StatisticsQosTests.

2022-11-25 08:30 UTC, MiguelCompany commented on test/blackbox/common/BlackboxTestsPubSubBasic.cpp
> +    // Set statistics properties manually to ensure a fix size of participant properties
```suggestion
    // Set statistics properties manually to ensure a fixed size of participant properties
```

2022-11-25 08:30 UTC, MiguelCompany commented on test/blackbox/common/BlackboxTestsPubSubBasic.cpp
> +    // The calculation of exact maximum properties size has been done according to the following table
```suggestion
    // The calculation of the exact maximum properties size has been done according to the following table
```

2022-11-25 08:30 UTC, MiguelCompany commented on test/unittest/transport/UDPv6Tests.cpp
>      std::vector<octet> message = { 'H', 'e', 'l', 'l', 'o' };
```suggestion
    std::vector<octet> message = { 'H', 'e', 'l', 'l', 'o' };
```

2022-11-25 09:24 UTC, MiguelCompany commented
@richiprosima Please test this

2022-11-25 09:25 UTC, MiguelCompany approved these changes
LGTM with green CI

2022-11-25 15:12 UTC, merged