[16363] Ensure samples are not removed from reader history on participant drop
eProsima/Fast-DDS pull request #3121
Opened 2022-11-29 08:39 UTC by MiguelCompany

## Description

This PR adds a regression test to check that samples are not removed from reader history on participant drop, and fixes old PubSub API SubscriberHistory behavior.

@Mergifyio backport 2.7.x 2.6.x 2.1.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
    - Only the new test has been checked.
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- *N/A* Documentation builds and tests pass locally. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [x] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2022-11-29 16:21 UTC, MiguelCompany commented
@richiprosima Please test this

2023-06-13 12:34 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2023-06-13 13:24 UTC, JLBuenoLopez-eProsima requested changes

2023-06-13 13:24 UTC, JLBuenoLopez-eProsima commented on test/blackbox/common/BlackboxTestsDiscovery.cpp
> +    // Writer will send 2 samples, but the reader will not take them
This test is passing if cherry-picked into master so it is not properly testing the regression (I have run the `BlackboxTests_FastRTPS.Discovery.EndpointRediscoveryWithTransientLocalData_2` using the FastRTPS API)

2023-06-13 14:46 UTC, MiguelCompany commented
@richiprosima Please test this

2023-06-20 06:07 UTC, JLBuenoLopez-eProsima commented
Closing this PR because the regression test is not really testing a regression and changes are related to the already deprecated and non-maintained Fast RTPS API.

2023-06-20 06:07 UTC, closed without merging