[16647] Use shared_ptr for internal singletons
eProsima/Fast-DDS pull request #3185
Opened 2023-01-04 07:21 UTC by MiguelCompany

## Description

The changes include using shared pointers for the internal singletons of RTPSDomainImpl and LogResources, and keeping a reference to both on DomainParticipantFactory.

I consider the changes ABI safe, because the only ABI incompatibility is on the size of DomainParticipantFactory, where two shared pointers are added at the end. Since the factory cannot be directly constructed by the user (and thus cannot be instantiated on the stack), there's no way of having ABI issues. I already checked that by building the examples before the changes, and updating the shared library after the changes.

This is related to #2537, and can be considered a follow-up of #2894.

@Mergifyio backport 2.8.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-01-05 14:22 UTC, MiguelCompany commented
@richiprosima Please test this.

2023-01-12 14:32 UTC, MiguelCompany commented
@richiprosima Please test this

2023-01-13 08:11 UTC, MiguelCompany commented
@richiprosima Please test this

2023-01-13 08:14 UTC, MiguelCompany commented
@richiprosima Please test this

2023-01-13 08:51 UTC, MiguelCompany commented
@richiprosima Please test this

2023-01-13 11:11 UTC, MiguelCompany commented
@richiprosima Please test this

2023-01-13 15:10 UTC, MiguelCompany commented
@richiprosima Please test this

2023-01-13 19:50 UTC, MiguelCompany commented
@richiprosima Please test this

2023-01-13 19:54 UTC, MiguelCompany commented
@richiprosima Please test this

2023-01-16 11:31 UTC, jsantiago-eProsima requested changes

2023-01-16 13:10 UTC, jsantiago-eProsima commented on src/cpp/utils/shared_memory/BoostAtExitRegistry.hpp
> +        std::vector<void (*)()> collection;
After reviewing the behavior when registering a function via std::atexit from insida a function registered previously, it seems that it is allowed, with the functions being stored in a stack.

2023-01-16 13:26 UTC, MiguelCompany commented on src/cpp/rtps/RTPSDomainImpl.hpp
> +    FileWatchHandle file_watch_handle_;
The whole point of this PR is to remove static objects to avoid destruction order fiascos

2023-01-16 13:47 UTC, jsantiago-eProsima approved these changes
LGTM

2023-01-16 13:48 UTC, jsantiago-eProsima commented
@richiprosima please test this

2023-01-16 14:26 UTC, jsantiago-eProsima approved these changes
This still LGTM.

2023-01-17 08:43 UTC, merged

2023-01-17 08:43 UTC, MiguelCompany commented
@Mergifyio backport 2.8.x