[16608] total_unread_ consistent with reader's history upon get_first_untaken_info()
eProsima/Fast-DDS pull request #3203
Opened 2023-01-11 12:01 UTC by Mario-DL

## Description

`mp_reader->nextUntakenCache()` in `get_first_untaken_info()` is removing the change (`it->remove_change()`) if `matched_writer_lookup()` returns false. This, in turn calls `change_removed_by_history()` but `get_last_notified()` returns always false in that case because no writerGUID is found, hence a sequence number of 0.0 is returned. 

This situation causes that `total_unread_` is not decremented despite removing the change, so the history size and `total_unread_` variable are inconsistent and the issue arises. 

When user calls `take_next_sample()`,  `Ret::NO_DATA` is returned despite `reader->get_unread_count()` is different from 0.

## Proposed solution
`get_first_untaken_info()` should be a read-only API and `mp_reader->nextUntakenCache()` should not be called from inside because it modifies the history in certain cases.

@Mergifyio backport 2.8.x 2.7.x 2.6.x

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [X] Fast DDS test suite has been run locally. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- **N/A** Documentation builds and tests pass locally. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 

- [X] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-01-15 21:33 UTC, Mario-DL commented
@richiprosima please test this

2023-01-16 12:05 UTC, MiguelCompany requested changes

2023-01-16 12:05 UTC, MiguelCompany commented on test/blackbox/common/DDSBlackboxTestsDataReader.cpp
> +    pubsub_reader->wait_writer_undiscovery();
I've given this a deeper thought, and I think these lines could be simplified:

```suggestion
    pubsub_writer->send(data);
    EXPECT_TRUE(data.empty());
    
    pubsub_reader->block_for_unread_count_of(3);

    pubsub_writer->removePublisher();
    pubsub_reader->wait_writer_undiscovery();
```

2023-01-16 14:37 UTC, MiguelCompany submitted a review, later dismissed
LGTM

2023-01-16 14:38 UTC, MiguelCompany commented
@richiprosima Please test this

2023-01-17 10:34 UTC, MiguelCompany approved these changes
👍

2023-01-17 10:34 UTC, MiguelCompany commented
@richiprosima Please test this

2023-01-17 13:11 UTC, merged

2023-01-17 13:17 UTC, MiguelCompany commented
@Mergifyio backport 2.8.x 2.7.x 2.6.x

2023-01-17 20:52 UTC, fujitatomoya commented on src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
> +        auto item = instance_changes.cbegin();
this item could be NULL? see https://github.com/ros2/rmw_fastrtps/issues/659