[16736] On unacknowledged sample removed tests
eProsima/Fast-DDS pull request #3210
Opened 2023-01-13 12:36 UTC by JLBuenoLopez-eProsima

## Description

This PR adds the tests for the new `DataWriterListener::on_unacknowledged_sample_removed`.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
**N/A** Any new/modified methods have been properly documented using Doxygen. 
**N/A** Fast DDS test suite has been run locally. 
**N/A** Changes are ABI compatible. 
**N/A** Changes are API compatible. 
**N/A** Documentation builds and tests pass locally. 
**N/A** New feature has been added to the `versions.md` file (if applicable).
**N/A** New feature has been documented/Current behavior is correctly described in the documentation. 

**N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-01-16 06:41 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2023-01-31 14:32 UTC, MiguelCompany requested changes

2023-01-31 14:32 UTC, MiguelCompany commented on test/blackbox/api/dds-pim/PubSubWriter.hpp
> +            writer_.instances_removed_unack_.push_back(handle);
We should be consistent and keep both data inside the listener. This means you would need to add a getter for `instances_removed_unack_`.

2023-01-31 15:21 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2023-01-31 15:40 UTC, MiguelCompany approved these changes

2023-01-31 17:40 UTC, merged