[16739] Operative SecureDS-SecureDS
eProsima/Fast-DDS pull request #3212
Opened 2023-01-16 11:02 UTC by Mario-DL

## Description

This PR intends to add necessary fixes to have a successful Secure DIscovery Server - Secure DIscovery Server interaction. Punctual changes on PDP Clients are also considered.
The example scenario in whoch fixes have been tested has been:
SimpleSecurePublisher - SDS1 - SDS2 - SImpleSecureSubscriber

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
**N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [] Fast DDS test suite has been run locally. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- **N/A** Documentation builds and tests pass locally. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 

- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-01-18 11:23 UTC, MiguelCompany commented
@richiprosima Please test discovery-server

2023-01-18 12:08 UTC, MiguelCompany requested changes
Two nits apart from what we have talked offline

2023-01-18 12:08 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/endpoint/EDPServer.hpp
> +            const bool& is_remote_participant = false);
No need for a const reference here:

```suggestion
            bool is_remote_participant = false);
```

2023-01-18 12:08 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/endpoint/EDPServer.cpp
> +        const bool& is_remote_participant)
I think we can rename the parameter to show its true purpose.

```suggestion
        bool release_from_reader)
```

2023-01-19 10:58 UTC, Mario-DL commented
@richiprosima Please test discovery-server

2023-01-19 11:01 UTC, Mario-DL commented
Just a detail to note. On [PDPServer.cpp lines 1438, 1450](https://github.com/eProsima/Fast-DDS/blob/feature/secure-discovery-server-poc/main/src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp) we were relasing the change in the same `remove_change_from_writer_history()` (passaing the `true` final parameter in the call), and if it failed, we then force the release. In our version, we always remove the change without relasing and then, we always call to release.

2023-01-20 10:54 UTC, MiguelCompany requested changes
Some small requests

2023-01-20 10:54 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
> +                if (!ret || (ret && !edp->process_and_release_change(ch)))
Operator `||` has short-circuit mechanisms, so no need to check `ret` again:
```suggestion
                if (!ret || !edp->process_and_release_change(ch, false))
```

2023-01-20 10:54 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/endpoint/EDPServer.hpp
> +            bool release_from_reader = false);
I like to force the users of an API to be explicit:
```suggestion
            bool release_from_reader);
```

2023-01-20 10:54 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
> +                if (!ret || (ret && !edp->process_and_release_change(ch, true)))
```suggestion
                if (!ret || !edp->process_and_release_change(ch, true))
```

2023-01-20 11:14 UTC, MiguelCompany approved these changes

2023-01-20 11:14 UTC, merged