[16910] Remove check 'Documentation builds and test pass locally' from pull request template
eProsima/Fast-DDS pull request #3267
Opened 2023-02-02 14:17 UTC by JesusPoderoso

…' from github PR template

Signed-off-by: JesusPoderoso <jesuspoderoso@eprosima.com>

This PR just removes the check from the template

## Description

## Contributor Checklist
- **N/A** Commit messages follow the project guidelines. 
- **N/A** The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- **N/A** Changes are ABI compatible. 
- **N/A** Changes are API compatible. 
- **N/A** Documentation builds and tests pass locally. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 

- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-02-14 15:05 UTC, EduPonz requested changes

2023-02-14 15:05 UTC, EduPonz commented on .github/workflows/documentation-tests.yaml
> +          git checkout ${__ACTION_BRANCH_NAME}
I don't think it's likely that a branch with name `refs/pull/<pr_number>/merge`. Instead, we would normally do:

1. Checkout a branch named as the target of the PR; else
1. Checkout a branch named as the base of the PR; else
1. Checkout the default branch

2023-02-14 15:05 UTC, EduPonz commented on .github/workflows/documentation-tests.yaml
> +          colcon build
You'd need to add the `--metas` option here
```suggestion
          colcon build --event-handlers=console_direct+
```

2023-02-14 15:05 UTC, EduPonz commented on .github/workflows/documentation/ci-documentation.repos
> +repositories:
As I said, I think we can remove this file altogether

2023-02-14 15:27 UTC, JesusPoderoso commented on .github/workflows/documentation/ci-documentation.repos
> +        version: master
In order to keep foonathan, lets use the .repos file in the repository instead of this one.

2023-02-16 13:54 UTC, EduPonz approved these changes

2023-02-16 13:55 UTC, EduPonz approved these changes

2023-02-16 13:55 UTC, merged