Implement a validity check for firstSN
eProsima/Fast-DDS pull request #3274
Opened 2023-02-07 00:57 UTC by squizz617

This commit suggests a fix for issue #3236.

## Description

As per 8.3.8.6.3 of DDS-RTPS 2.5, "Heartbeat submessage is invalid if firstSN.value is zero or negative". However, a check for this property is missing. This leads to an assertion failure when an invalid firstSN is provided (see issue #3236).

@Mergifyio backport 2.9.x

Fixes #3236 

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally -> 
- (N/A) Any new/modified methods have been properly documented using Doxygen. 
- (N/A) Changes are ABI compatible. 
- (N/A) Changes are API compatible. 
- (N/A) Documentation builds and tests pass locally. 
- (N/A) New feature has been added to the `versions.md` file (if applicable).
- (N/A) New feature has been documented/Current behavior is correctly described in the documentation. 

- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-02-07 06:27 UTC, MiguelCompany requested changes
@squizz617 Thank you for your contribution!

This is not building (see my comment below).

2023-02-07 06:27 UTC, MiguelCompany commented on src/cpp/rtps/messages/MessageReceiver.cpp
> +    if (fisrtSN <= zeroSN)
This is not building
```suggestion
    if (firstSN <= zeroSN)
```

2023-02-07 14:08 UTC, squizz617 commented
Sorry, made a mistake while moving stuffs into the pr branch :(
Fixed and pushed!

2023-03-15 02:31 UTC, squizz617 commented
Hi @MiguelCompany, I'm just wondering if you've looked at the changes. Thank you.

2023-03-15 07:48 UTC, MiguelCompany commented
> Hi @MiguelCompany, I'm just wondering if you've looked at the changes. Thank you.

@squizz617 Changes look good to me. Is it possible that you could add a regression test for this?

I think that adding a new file [here](https://github.com/eProsima/Fast-DDS/tree/master/fuzz/C%2B%2B/fuzz_processCDRMsg/fuzz_processCDRMsg_seed_corpus) would be enough

2023-03-15 14:00 UTC, squizz617 commented
@MiguelCompany Done! I temporarily named the file `input_issue3236`, but please change if needed.

2023-03-15 14:49 UTC, MiguelCompany approved these changes

2023-03-15 14:49 UTC, MiguelCompany commented
@richiprosima Please test this

2023-03-16 15:36 UTC, MiguelCompany commented
@mergifyio backport 2.9.x 2.8.x 2.6.x

2023-03-16 15:36 UTC, merged