[15565] Feature: new on_unacknowledged_sample_removed callback in DataWriterListener
eProsima/Fast-DDS pull request #3275
Opened 2023-02-07 06:28 UTC by JLBuenoLopez-eProsima

## Description

This PR includes the new `DataWriterListener::on_unacknowledged_sample_removed` callback tests and implementation.
Documentation PR: eProsima/Fast-DDS-docs#439.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- Changes are **NOT** ABI compatible. 
- [x] Changes are API compatible. 
- [x] Documentation builds and tests pass locally. 
- [x] New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation. 

**N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-02-07 08:10 UTC, MiguelCompany requested changes

2023-02-07 11:55 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2023-02-07 11:57 UTC, JLBuenoLopez-eProsima commented on src/cpp/rtps/writer/StatelessWriter.cpp
> +    if (getMatchedReadersSize() > 0)
A test case has been included in commit 3eba6b8 and a fix in b89b1b8

2023-02-07 11:57 UTC, JLBuenoLopez-eProsima commented on src/cpp/fastdds/publisher/DataWriterImpl.cpp
> +            [&](
Applied in 1c020b6

2023-02-07 11:57 UTC, JLBuenoLopez-eProsima commented on src/cpp/rtps/writer/StatefulWriter.cpp
> +    if (seq_num > (mp_history->next_sequence_number() - 1))
Applied in 1c020b6

2023-02-07 14:58 UTC, MiguelCompany approved these changes

2023-02-08 06:33 UTC, MiguelCompany requested changes

2023-02-08 06:33 UTC, MiguelCompany commented on include/fastdds/rtps/writer/RTPSWriter.h
> +     * @param change Pointer to the CacheChange to check.
This is making the documentation build fail.

```suggestion
     * @param seq_num Sequence number of the change to check.
```

2023-02-08 06:37 UTC, MiguelCompany approved these changes

2023-02-08 10:20 UTC, merged