Fix load profiles TSAN issue
eProsima/Fast-DDS pull request #3281
Opened 2023-02-08 08:18 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

## Description

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- N/A Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [x] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 

- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-04-28 10:50 UTC, MiguelCompany requested changes
This needs a regression test.

```
    PubSubWriter<HelloWorldPubSubType> participant_1(TEST_TOPIC_NAME);
    participant_1.init();

    auto second_participant_creation = []()
            {
                PubSubReader<HelloWorldPubSubType> participant_2(TEST_TOPIC_NAME);
                participant_2.init();
                participant_2.wait_discovery();
            };

    // Start thread creating second participant
    std::thread thr(second_participant_creation);

    participant_1.wait_discovery();
    thr.join();
```

2023-04-28 12:18 UTC, MiguelCompany commented
@richiprosima Please test this

2023-05-02 12:26 UTC, EduPonz commented
@jparisu the new test is failing in both windows pipelines, please take a look whenever you have time

2023-05-03 09:13 UTC, jparisu commented
Some issues have been encountered adding this test:

1. ASAN fails randomly because of Dynamic Types
2. Windows fails randomly with this error `Assertion failed: open_or_created && winapi::get_last_error() != winapi::error_already_exists, file C:\Users\eProsima\paris_release_debug\src\fastdds\thirdparty\boost\include\boost/interprocess/sync/windows/mutex.hpp, line 65`

These errors are not introduced (at least it does not look like) but this PR, but they arise because there weren't previous tests with parallel creation of Domain Participants

2023-05-03 09:20 UTC, jparisu commented
@richiprosima please test windows

2023-05-10 05:25 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test windows

2023-05-10 05:25 UTC, JLBuenoLopez-eProsima commented
@jparisu uncrustify job is failing in this PR

2023-05-10 05:44 UTC, jparisu commented
> @jparisu uncrustify job is failing in this PR

@JLBuenoLopez-eProsima test introduce in this PR produces several ASAN errors due to not related issues. Do you still want to merge it?

2023-05-11 05:22 UTC, JLBuenoLopez-eProsima commented
@jparisu, as far as I understand the test introduced in this PR is flaky because the strategy followed in the test has not been used previously. So the test is surfacing some other issue that will have to be deal with at some point. As the CI runs several times the failing tests to check if they are flaky, I am not really concerned about the test failing randomly. @EduPonz, what do you think?

2023-05-11 09:10 UTC, EduPonz commented
> @jparisu, as far as I understand the test introduced in this PR is flaky because the strategy followed in the test has not been used previously. So the test is surfacing some other issue that will have to be deal with at some point. As the CI runs several times the failing tests to check if they are flaky, I am not really concerned about the test failing randomly. @EduPonz, what do you think?

We may merge this if we exclude this new test from the TSAN analysis until we fix it

2023-05-11 09:17 UTC, jparisu commented
It produces ASAN errors, not TSAN errors (that are also produced, but not new ones).

2023-06-13 09:04 UTC, JLBuenoLopez-eProsima commented
@jparisu, it has been decided that this is going to be merged and afterwards the ASAN errors will be fixed. Can you please fix the uncrustify job so we can proceed? Thanks!

2023-06-21 05:45 UTC, Mario-DL commented
@richiprosima please test this

2023-06-22 07:23 UTC, MiguelCompany commented
@richiprosima Please test windows

2023-06-22 07:26 UTC, MiguelCompany approved these changes
LGTM with green CI

2023-06-22 07:35 UTC, MiguelCompany commented
@mergifyio rebase

2023-06-22 13:55 UTC, merged

2024-02-27 13:17 UTC, SunnyNetX commented
> Some issues have been encountered adding this test:
> 
> 1. ASAN fails randomly because of Dynamic Types
> 2. Windows fails randomly with this error `Assertion failed: open_or_created && winapi::get_last_error() != winapi::error_already_exists, file C:\Users\eProsima\paris_release_debug\src\fastdds\thirdparty\boost\include\boost/interprocess/sync/windows/mutex.hpp, line 65`
> 
> These errors are not introduced (at least it does not look like) but this PR, but they arise because there weren't previous tests with parallel creation of Domain Participants

Have you solved this problem?how？