[17515] Use standard value for PID_RELATED_SAMPLE_IDENTITY
eProsima/Fast-DDS pull request #3345
Opened 2023-03-06 16:32 UTC by MRicoIE2CS

## Description

The value for PID_RELATED_SAMPLE_IDENTITY enum definition is changed to (`0x0083`) the one defined in the document `Remote Procedure Call over DDS`, document reference `ptc/2016-03-19`, V1.0.
The legacy value used is now defined under PID_CUSTOM_RELATED_SAMPLE_IDENTITY.
The definitions for the values `0x0080` to `0x0082` have been added as well.

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [N/A] Any new/modified methods have been properly documented using Doxygen. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- [N/A] New feature has been added to the `versions.md` file (if applicable).
- [N/A] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [N/A] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-03-06 16:33 UTC, MRicoIE2CS commented
@richiprosima please test

2023-03-07 07:24 UTC, jsantiago-eProsima requested changes
We also need to send this new property ID along with the old one.

2023-03-07 12:47 UTC, MRicoIE2CS commented
@richiprosima please test

2023-03-07 15:58 UTC, MRicoIE2CS commented
@richiprosima please test

2023-03-08 10:25 UTC, jsantiago-eProsima commented
I think we should account for the added paremeter [in this size calculation](https://github.com/eProsima/Fast-DDS/blob/7fb237de47653bc2892dae68b29a111e2f7d111c/src/cpp/rtps/history/WriterHistory.cpp#L310)

2023-03-16 10:37 UTC, MRicoIE2CS commented
@richiprosima please test this

2023-03-16 14:08 UTC, jsantiago-eProsima requested changes

2023-03-16 14:08 UTC, jsantiago-eProsima commented on test/blackbox/common/DDSBlackboxTestsBasic.cpp
> +//#include "PubSubWriter.hpp"
Remove commented lines

2023-03-16 14:08 UTC, jsantiago-eProsima commented on test/blackbox/common/DDSBlackboxTestsBasic.cpp
> +    bool another_debug_bool_flag = false;
This does not seem to be used for anything other than passing it to the lambda which then does not use it.

2023-03-16 14:08 UTC, jsantiago-eProsima commented on test/blackbox/common/DDSBlackboxTestsBasic.cpp
> +                // Inside this filter, the two flags passed in register wether both PIDs are included in the msg to be sent.
```suggestion
                // Inside this filter, the two flags passed in register whether both PIDs are included in the msg to be sent.
```

2023-03-16 14:08 UTC, jsantiago-eProsima commented on test/blackbox/common/DDSBlackboxTestsBasic.cpp
> +                // The legacy value is overwritten in order to sent a msg with only the standard PID_RELATED_SAMPLE_IDENTITY as valid parameter,
```suggestion
                // The legacy value is overwritten in order to send a msg with only the standard PID_RELATED_SAMPLE_IDENTITY as valid parameter,
```

2023-03-16 14:08 UTC, jsantiago-eProsima commented on test/blackbox/common/DDSBlackboxTestsBasic.cpp
> +bool readParameterListfromCDRMsg(
Nitpick: I would change the name of the function to to reflect this just checks for related sample identity.

2023-03-16 16:26 UTC, MRicoIE2CS commented on test/blackbox/common/DDSBlackboxTestsBasic.cpp
> +bool readParameterListfromCDRMsg(
You are right with the name, but the doxygen description already stated that. Iguess you did the revision from an early commit.

2023-03-17 09:33 UTC, MRicoIE2CS commented
@richiprosima please test this

2023-03-23 10:03 UTC, MRicoIE2CS commented
@richiprosima please test this

2023-03-23 14:31 UTC, MRicoIE2CS commented
@richiprosima please test this

2023-03-24 06:29 UTC, jsantiago-eProsima commented
@richiprosima please test mac

2023-03-26 16:47 UTC, jsantiago-eProsima approved these changes

2023-03-27 05:31 UTC, merged