[17509] Feature: Ignore empty API
eProsima/Fast-DDS pull request #3354
Opened 2023-03-10 10:06 UTC by JLBuenoLopez-eProsima

## Description

This PR introduces the required API to implement the ignore DDS entity feature.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [N/A] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [NO] Changes are ABI compatible. 
- [NO] Changes are API compatible. 
- [x] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [N/A] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-03-10 10:22 UTC, JLBuenoLopez-eProsima commented
Uncrustify fails because it tries to remove a required `;` from an `enum` declaration.

2023-03-10 10:23 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2023-03-10 12:28 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test mac

2023-03-10 12:49 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2023-03-10 12:53 UTC, JLBuenoLopez-eProsima commented
Running the test suite because one mock has been modified in order to fix a Mac warning.

@richiprosima please test this

2023-03-10 12:54 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2023-03-13 06:57 UTC, JLBuenoLopez-eProsima commented
Test failure does not seem related.

2023-03-16 14:09 UTC, MRicoIE2CS requested changes

2023-03-16 14:09 UTC, MRicoIE2CS commented on include/fastdds/dds/domain/DomainParticipantListener.hpp
Please, add `[in]` and `[out]` marks on the Doxygen parameters for any new/modified methods.

2023-03-16 14:09 UTC, MRicoIE2CS commented on include/fastdds/rtps/builtin/discovery/participant/PDP.h
Please, add `[in]` and `[out]` marks on the Doxygen parameters for any new/modified methods.

2023-03-16 14:09 UTC, MRicoIE2CS commented on include/fastdds/rtps/participant/RTPSParticipant.h
Please, add `[in]` and `[out]` marks on the Doxygen parameters for any new/modified methods.

2023-03-16 14:09 UTC, MRicoIE2CS commented on include/fastdds/rtps/participant/RTPSParticipantListener.h
Please, add `[in]` and `[out]` marks on the Doxygen parameters for any new/modified methods.

2023-03-16 14:09 UTC, MRicoIE2CS commented on src/cpp/rtps/participant/RTPSParticipantImpl.h
Please, add `[in]` and `[out]` marks on the Doxygen parameters for any new/modified methods.

2023-03-16 14:10 UTC, MRicoIE2CS requested changes
There are Uncrustify issues.

2023-03-16 15:19 UTC, JLBuenoLopez-eProsima commented
> There are Uncrustify issues.

Please, read [my comment](https://github.com/eProsima/Fast-DDS/pull/3354#issuecomment-1463589417) above about this issue.

2023-03-16 15:29 UTC, JLBuenoLopez-eProsima commented on include/fastdds/dds/domain/DomainParticipantListener.hpp
Not really required, but I agree that it is nice to have

2023-03-16 15:29 UTC, JLBuenoLopez-eProsima commented on include/fastdds/dds/domain/DomainParticipantListener.hpp
> +    virtual void on_subscriber_discovery(
I think it is!

2023-03-16 15:30 UTC, JLBuenoLopez-eProsima commented on include/fastdds/dds/domain/DomainParticipantListener.hpp
> +    virtual void on_publisher_discovery(
This one too!

2023-03-16 16:14 UTC, MRicoIE2CS approved these changes
LGTM

2023-03-17 07:25 UTC, MRicoIE2CS approved these changes
LGTM

2023-03-21 11:44 UTC, merged