[17138] Refactor of DynamicTypes
eProsima/Fast-DDS pull request #3392
Opened 2023-03-21 07:33 UTC by MiguelBarro

## Description

Several works aimed to fulfill latest [omg standard](https://www.omg.org/spec/DDS-XTypes/1.3/) and fix issues.
Among them:
+ Update the factories (`DynamicTypeBuildeFactory` and `DynamicTypeBuilder`) to enforced `shared_ptr` use and allocate in a single heap block.
+ Reorder class hierarchy (`TypeDescriptor`, `DynamicTypeBuilder` and `DynamicType`) to enforce `TypeDescriptor` as state holder and remove redundant references and members. Avoid API implementation duplicates.
+ Reduce the `friend` class device to a necessary basis and enforce class independence through APIs. This paves way to `DynamicData` class refactorization.
+ Comprehensive annotation support.
+ Enforce the use of static objects for primitive types as standard advices.
+ Move serialization implementation to `DynamicType` in order to:
  - Make serializatio independent from `DynamicData` internals.
  - Double check by asserting each member type is the expected one.
+ New test for primitives and complex aggregation types.
+ Tests fixes and enhanced gtest support for comparisons via proper traces of the `DynamicTypes`.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-03-21 13:19 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-03-21 15:17 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-03-22 15:22 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-03-25 16:54 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-03-25 16:57 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-03-25 21:55 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-03-27 06:44 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-04-04 09:00 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-04-04 13:39 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-04-05 15:09 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-04-05 22:32 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-04-07 15:04 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-04-12 11:39 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-04-14 06:25 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-04-19 06:26 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-04-19 09:16 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-04-19 15:39 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-04-20 06:33 UTC, MiguelBarro commented
@richiprosima Please be so gentle to test Mac for me

2023-04-21 09:28 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-04-21 11:39 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-04-22 12:14 UTC, MiguelBarro commented
@richiprosima Please be so gentle to test Mac for me

2023-04-22 14:19 UTC, MiguelBarro commented
@richiprosima Please test this for me

2023-05-02 15:57 UTC, richiware requested changes
Partial review in header files

2023-05-02 15:57 UTC, richiware commented on include/fastrtps/types/v1_3/TypeDescriptor.h
> +    RTPS_DllAPI TypeDescriptor() = default;
I will avoid the default one and force the user to set the kind

2023-05-02 15:57 UTC, richiware commented on include/fastrtps/types/v1_3/TypeDescriptor.h
> +    RTPS_DllAPI ~TypeDescriptor() noexcept;
why not set the class as `final`?

2023-05-02 15:57 UTC, richiware commented on include/fastrtps/types/v1_3/MemberDescriptor.h
> +    RTPS_DllAPI void set_id(
I think is easier to user to have getter and setter together in the header file.

2023-05-03 14:55 UTC, MiguelBarro commented on include/fastrtps/types/v1_3/DynamicTypeBuilderFactory.h
> +// Copyright 2018 Proyectos y Sistemas de Mantenimiento SL (eProsima).
right, I fix them all

2023-05-03 15:02 UTC, MiguelBarro commented on include/fastrtps/types/v1_3/DynamicTypeBuilderFactory.h
> +    RTPS_DllAPI DynamicTypeBuilder_ptr create_builder(
Ok, let the users figure this out 😅

2023-05-03 15:20 UTC, MiguelBarro commented on include/fastrtps/types/v1_3/DynamicTypeBuilderFactory.h
> +    RTPS_DllAPI DynamicTypeBuilder_ptr create_builder_copy(
This was introduced for backward compatibility with v1.1
Let's remove it.

2023-05-03 15:29 UTC, MiguelBarro commented on include/fastrtps/types/v1_3/DynamicTypeBuilderFactory.h
> +     * Retrieve the cached @ref DynamicType object associated to a given primitive
right

2023-05-03 15:40 UTC, MiguelBarro commented on include/fastrtps/types/v1_3/DynamicTypeBuilderFactory.h
> +    RTPS_DllAPI ReturnCode_t delete_builder(
It was kept for backward compatibility with v1.1.
Besides it allowed disable the memory tracking on specific builders.
Ok

2023-05-04 10:33 UTC, MiguelBarro commented on include/fastrtps/types/v1_3/DynamicTypeBuilderFactory.h
> +    RTPS_DllAPI DynamicTypeBuilder_cptr create_string_builder() noexcept;
ok, I rename it too acordingly.

2023-05-04 10:34 UTC, MiguelBarro commented on include/fastrtps/types/v1_3/DynamicTypeBuilderFactory.h
> +            uint32_t bound) noexcept;
Ok

2023-05-04 10:34 UTC, MiguelBarro commented on include/fastrtps/types/v1_3/DynamicTypeBuilderFactory.h
> +    RTPS_DllAPI DynamicTypeBuilder_cptr create_wstring_builder() noexcept;
Ok

2023-05-04 10:34 UTC, MiguelBarro commented on include/fastrtps/types/v1_3/DynamicTypeBuilderFactory.h
> +            uint32_t bound) noexcept;
Ok

2023-05-04 12:48 UTC, MiguelBarro commented on include/fastrtps/types/v1_3/DynamicTypeBuilderFactory.h
> +            uint32_t bound = MAX_ELEMENTS_COUNT) noexcept;
done

2023-05-04 14:18 UTC, MiguelBarro commented on include/fastrtps/types/v1_3/DynamicTypeBuilderFactory.h
> +    RTPS_DllAPI ReturnCode_t delete_builder(
According to today's meeting, we should reintroduce this one.

2023-05-04 14:19 UTC, MiguelBarro commented on include/fastrtps/types/v1_3/DynamicTypeBuilderFactory.h
> +            uint32_t bound = MAX_ELEMENTS_COUNT) noexcept;
done, and name fixed

2023-05-04 14:21 UTC, MiguelBarro commented on include/fastrtps/types/v1_3/DynamicTypeBuilderFactory.h
> +    RTPS_DllAPI DynamicTypeBuilder_cptr& create_primitive_builder(
because we may need a primitive type with another name. Let's rename it to `create_primitive_type` for consistency with the standard.

2023-05-04 14:33 UTC, MiguelBarro commented on include/fastrtps/types/v1_3/TypeDescriptor.h
> +    TypeDescriptor(
It was agreed in today's meeting that all members will be public and the class final.

2023-05-04 14:34 UTC, MiguelBarro commented on include/fastrtps/types/v1_3/DynamicTypeBuilderFactory.h
> +// You may obtain a copy of the License at
good point

2024-02-26 13:38 UTC, EduPonz commented
Closed in favor of #4190

2024-02-26 13:38 UTC, closed without merging