[17832] Initial acknack backoff
eProsima/Fast-DDS pull request #3419
Opened 2023-03-30 10:38 UTC by jsantiago-eProsima

## Description

This PR introduces an exponential backoff for the periodic sending of the initial acknack. 

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-03-30 10:41 UTC, jsantiago-eProsima commented
@richiprosima please test this

2023-03-30 12:40 UTC, jsantiago-eProsima commented
@richiprosima please test this

2023-04-03 07:31 UTC, jsantiago-eProsima commented
@richiprosima please test this

2023-04-03 08:53 UTC, MiguelCompany requested changes

2023-04-03 08:53 UTC, MiguelCompany commented on src/cpp/rtps/reader/WriterProxy.cpp
>                  ret_value = true;
```suggestion
                double time_ms = initial_acknack_->getIntervalMilliSec();
                constexpr double max_ms = 60 * 60 * 1000; // Limit to 1 hour
                if (time_ms < max_ms)
                {
                    initial_acknack_->update_interval_millisec(time_ms * 2);
                    ret_value = true;
                }
```

2023-04-03 08:53 UTC, MiguelCompany commented on test/unittest/rtps/reader/WriterProxyAcknackTests.cpp
> +
I think we should also check that receiving a heartbeat does not update the time interval

2023-04-03 08:53 UTC, MiguelCompany commented on test/unittest/rtps/reader/WriterProxyTests.cpp
> +    EXPECT_CALL(*wproxy.initial_acknack_, restart_timer()).Times(2u);
```suggestion
    EXPECT_CALL(*wproxy.initial_acknack_, restart_timer()).Times(1u);
```

2023-04-03 10:32 UTC, MiguelCompany approved these changes

2023-04-03 10:32 UTC, MiguelCompany commented
@richiprosima Please test this

2023-04-03 14:05 UTC, merged

2023-04-04 05:48 UTC, MiguelCompany commented
@Mergifyio backport 2.9.x 2.8.x 2.6.x