[18002] Internal refactor on port handling
eProsima/Fast-DDS pull request #3440
Opened 2023-04-06 20:03 UTC by MiguelCompany

## Description

This PR refactors the constructor of RTPSParticipantImpl, and changes the calculation of the ports used when set to 0 on the input locators.

@Mergifyio backport 2.13.x 2.10.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- *N/A* Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_: Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

2024-03-12 21:38 UTC, MiguelCompany commented
@richiprosima Please test this

2024-04-04 06:12 UTC, EduPonz requested changes

2024-04-04 10:36 UTC, EduPonz approved these changes

2024-04-04 10:36 UTC, EduPonz commented
@richiprosima please test this

2024-04-10 05:23 UTC, EduPonz commented
`BlackboxTests_DDS_PIM.SHM.SamePortUnicastMulticast` is failing in all platforms, @MiguelCompany can you take a look?

2024-04-10 11:17 UTC, MiguelCompany commented
> `BlackboxTests_DDS_PIM.SHM.SamePortUnicastMulticast` is failing in all platforms, @MiguelCompany can you take a look?

I rebased this, and fixed that test in 25db48b5cd5f8c07b0a9b180170e6995fe75d4da

2024-04-17 14:31 UTC, EduPonz approved these changes

2024-04-17 14:33 UTC, EduPonz commented
@Mergifyio backport 2.13.x 2.10.x 2.6.x

2024-04-17 14:33 UTC, merged