Fix segfault when creating two participant with same fixed id
eProsima/Fast-DDS pull request #3443
Opened 2023-04-10 10:24 UTC by richiware

## Description

Second participant creation fails, but when its `DomainParticipantImpl` will be removed from the factory, the code remove the one of the first participant. This is because they share the same GUID.

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-04-10 13:50 UTC, MiguelCompany requested changes

2023-04-10 13:50 UTC, MiguelCompany commented on test/unittest/dds/participant/ParticipantTests.cpp
> + * This tests tries to create two participant with the same fixed id.
```suggestion
 * This test tries to create two participants with the same fixed id.
```

2023-04-10 13:50 UTC, MiguelCompany commented on test/unittest/dds/participant/ParticipantTests.cpp
> +    ASSERT_EQ(DomainParticipantFactory::get_instance()->delete_participant(participant1), ReturnCode_t::RETCODE_OK);
```suggestion
    // Create the first participant
    DomainParticipant* participant1 =
            DomainParticipantFactory::get_instance()->create_participant(0, participant_qos);
    ASSERT_NE(participant1, nullptr);

    // Creating a second participant with the same fixed id should fail
    DomainParticipant* participant2 =
            DomainParticipantFactory::get_instance()->create_participant(0, participant_qos);
    ASSERT_EQ(participant2, nullptr);

    // Destroy the first participant
    ASSERT_EQ(DomainParticipantFactory::get_instance()->delete_participant(participant1), ReturnCode_t::RETCODE_OK);
```

2023-04-10 13:50 UTC, MiguelCompany commented on test/unittest/dds/participant/ParticipantTests.cpp
> +
It would be nice to also check the scenario where the participants are created disabled.

2023-04-10 13:50 UTC, MiguelCompany commented on src/cpp/rtps/RTPSDomain.cpp
> +    auto instance = get_instance();
I would prefer this method to be non-static...
```suggestion
```

2023-04-10 13:50 UTC, MiguelCompany commented on src/cpp/rtps/RTPSDomain.cpp
> +    bool ret_value = reserve_participant_id(participant_id);
... and then getting the instance here

```suggestion
    bool ret_value = get_instance()->reserve_participant_id(participant_id);
```

2023-04-10 14:34 UTC, MiguelCompany requested changes

2023-04-10 14:34 UTC, MiguelCompany commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +        EPROSIMA_LOG_ERROR(DOMAIN_PARTICIPANT, "Error generating GUID for participant");
```suggestion
        EPROSIMA_LOG_ERROR(DOMAIN_PARTICIPANT, "Error generating GUID for participant");
        return nullptr;
```

2023-04-10 14:34 UTC, MiguelCompany commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +
```suggestion
    // Should not have failed assigning the GUID
    assert (guid_ != GUID_t::unknown());

```

2023-04-10 14:34 UTC, MiguelCompany commented on test/unittest/dds/participant/ParticipantTests.cpp
> +        ASSERT_EQ(DomainParticipantFactory::get_instance()->delete_participant(participant2), ReturnCode_t::RETCODE_OK);
```suggestion
        ASSERT_EQ(participant2, nullptr);

        ASSERT_EQ(ReturnCode_t::RETCODE_OK, participant1->enable());

        // Destroy the first participant
        ASSERT_EQ(DomainParticipantFactory::get_instance()->delete_participant(participant1), ReturnCode_t::RETCODE_OK);

```

2023-04-11 06:04 UTC, MiguelCompany submitted a review, later dismissed

2023-04-11 11:02 UTC, MiguelCompany commented
@richiprosima Please test this

2023-04-11 11:03 UTC, MiguelCompany submitted a review, later dismissed
LGTM with green CI

2023-04-11 12:33 UTC, richiware commented
@richiprosima Please test this

2023-04-11 14:07 UTC, richiware commented
@richiprosima Please test this

2023-04-11 14:32 UTC, MiguelCompany approved these changes
LGTM with green CI

2023-04-12 06:00 UTC, richiware commented
@richiprosima Please test this

2023-04-12 06:27 UTC, MiguelCompany approved these changes
LGTM with green CI

2023-04-12 09:27 UTC, MiguelCompany commented
@richiprosima Please test windows

2023-04-12 13:14 UTC, richiware commented
@richiprosima Please test windows

2023-04-13 05:32 UTC, merged

2023-06-27 13:36 UTC, JLBuenoLopez-eProsima commented
@Mergifyio backport 2.9.x 2.6.x