[18673] Fix version and FastCDR patch file in QNX build files
eProsima/Fast-DDS pull request #3531
Opened 2023-05-23 08:28 UTC by jsantiago-eProsima

## Description

QNX compilation was broken by https://github.com/eProsima/Fast-CDR/pull/131 due to patch incompatibilities. This PR updates the patch file to match the current CMakeLists.txt and updates the common.mk file to reflect the latest FastDDS version.

@Mergifyio backport 2.10.x

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [NA] The code follows the style guidelines of this project. 
- [NA] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [NA] Any new/modified methods have been properly documented using Doxygen. 
- [NA] Changes are ABI compatible. 
- [NA] Changes are API compatible. 
- [NA] New feature has been added to the `versions.md` file (if applicable).
- [NA] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-05-30 09:02 UTC, MiguelCompany requested changes

2023-05-30 09:53 UTC, jsantiago-eProsima commented on build_qnx/common.mk
> +FAST-DDS_VERSION = .2.11.0
A bit verbose, but done.

2023-05-30 21:45 UTC, jsantiago-eProsima commented
Hi @chachoi, 

In this PR we are [adding on common.mk](https://github.com/eProsima/Fast-DDS/blob/e188ad21c2fed5f44e40b4bea38e224107436d57/build_qnx/common.mk#L15-L16) a way to dynamically generate Fast DDS version from the project's main CMakeLists.txt file instead of having it set statically.

Your input would be appreciated. Do you think this change would work for you?

2023-05-31 14:30 UTC, chachoi commented
Hi @jsantiago-eProsima,

That is a great idea. Your change looks good. As far as I know, using grep to extract version number is the only way to know get the version number dynamically in common.mk.

Also, thank you for maintaining the QNX related files.

2023-06-01 13:06 UTC, MiguelCompany approved these changes

2023-06-02 05:43 UTC, merged