Add configuration by profile to AdvanceConfigurationExample
eProsima/Fast-DDS pull request #3554
Opened 2023-05-31 06:09 UTC by jparisu

Add a new argument to AdvanceConfigurationExample that allows to configure a DomainParticipant from XML.

## Description

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-06-05 06:39 UTC, JLBuenoLopez-eProsima requested changes
1. I think some changes in your local repository have made it to this PR. The commit and PR title states that the goal is to introduce XML configuration support in the AdvanceConfigurationExample, but the SecureHelloWorldExample and the HelloWorldExample are also modified and I think that was not your intention.
1. Please, fix the uncrustify linter which is complaining in the AdvanceConfigurationExample main file.
1. README has not been updated with this new option.
1. Being an example, and thus oriented for user understanding, maybe we should add an XML configuration file so the user can check this functionality.

2023-06-05 06:39 UTC, JLBuenoLopez-eProsima commented on examples/cpp/dds/AdvancedConfigurationExample/arg_configuration.h
> +      "  -x <str> \t--xml-profile \tProfile name to configure DomainParticipant."},
The argument parser recognizes the `--profile` option and not the `--xml-profile` as it is printed. Please fix this inconsistency.

2023-06-13 13:38 UTC, jparisu commented
1. Fixed in https://github.com/eProsima/Fast-DDS/pull/3554/commits/626df5a444c07759ae117f4e891405b5f33976c2
2. https://github.com/eProsima/Fast-DDS/pull/3554/commits/7eed7f62aa7d79a333163ca53f4c20c6c024751e
3. https://github.com/eProsima/Fast-DDS/pull/3554/commits/1b36e045d40346d138f5630c71e2203e80322920
4. https://github.com/eProsima/Fast-DDS/pull/3554/commits/1b36e045d40346d138f5630c71e2203e80322920
5. :+1:

2023-06-13 13:44 UTC, JesusPoderoso commented
@richiprosima please test this

2023-06-13 13:48 UTC, JLBuenoLopez-eProsima requested changes

2023-06-13 13:48 UTC, JLBuenoLopez-eProsima commented on examples/cpp/dds/AdvancedConfigurationExample/README.md
> +To load XML files check [following documentation](https://fast-dds.docs.eprosima.com/en/latest/fastdds/xml_configuration/xml_configuration.html).
```suggestion
To load XML files check [Fast DDS documentation](https://fast-dds.docs.eprosima.com/en/latest/fastdds/xml_configuration/xml_configuration.html).
```

2023-06-13 13:48 UTC, JLBuenoLopez-eProsima commented on examples/cpp/dds/HelloWorldExample/HelloWorldPublisher.cpp
> +    participant_ = factory->create_participant(201, pqos);
This should not be here :smiling_face_with_tear:

2023-06-13 14:05 UTC, JLBuenoLopez-eProsima approved these changes
LGTM

2023-06-13 14:05 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2023-06-14 12:21 UTC, merged