[18763] Improve content filter expression parameters checks and verbosity.
eProsima/Fast-DDS pull request #3565
Opened 2023-06-02 09:15 UTC by jsantiago-eProsima

## Description

This PR adds an additional check to verify that the expression_parameters vector provided when creating a ContentFilteredTopic math with the limits established in the DomainParticipantQoS. It also fixes a wrong length comparison when deserializing that same vector.

@Mergifyio backport 2.10.x 2.9.x 2.6.x

Related documentation PR: eProsima/Fast-DDS-Docs#510

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [NA] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [NA] New feature has been added to the `versions.md` file (if applicable).
- [NA] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

2023-06-03 15:37 UTC, jsantiago-eProsima commented
@richiprosima please test this

2023-06-05 06:48 UTC, jsantiago-eProsima commented
@richiprosima please test this

2023-06-13 10:52 UTC, JLBuenoLopez-eProsima requested changes

2023-06-13 10:52 UTC, JLBuenoLopez-eProsima commented on src/cpp/fastdds/core/policy/ParameterSerializer.hpp
> +#include "fastdds/dds/log/Log.hpp"
This header is not being used. I think it can be safely removed.

2023-06-13 10:52 UTC, JLBuenoLopez-eProsima commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +    }
This limitation is not documented. We should add a documentation PR stating this limitation. I have added the corresponding label.

2023-06-13 10:52 UTC, JLBuenoLopez-eProsima commented on src/cpp/fastdds/topic/ContentFilteredTopicImpl.cpp
> +#include <fastdds/domain/DomainParticipantImpl.hpp>
This header is private so it should be after the public ones. However, I think this header is not being used and instead the DomainParticipantQos header should be included.

2023-06-13 10:52 UTC, JLBuenoLopez-eProsima commented on test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
> +#include "fastdds/dds/log/Log.hpp"
This header is not used directly in this source file, so I suggest removing it. If there is any build issue, then the proper file which is missing this include is the one to look for.

2023-06-13 10:52 UTC, JLBuenoLopez-eProsima commented on test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
> +TEST(BuiltinDataSerializationTests, contentfilterproperty_max_parameter_check)
Maybe a negative test case can be included testing what happens when trying to serialize more than 100 parameters.

2023-06-14 10:47 UTC, jsantiago-eProsima commented
@richiprosima please test this

2023-06-14 10:59 UTC, JLBuenoLopez-eProsima approved these changes
LGTM. Please remember to include a note in the documentation stating the limit in the number of parameters in the corresponding QoS: https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/eprosimaExtensions.html#contentfilterproperty-allocationconfiguration. Also, reading the CFT section I do not find any reference to this section so I suggest including it in the same PR.

2023-06-14 13:33 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2023-06-14 19:01 UTC, JesusPoderoso commented
@Mergifyio backport 2.10.x 2.9.x 2.6.x

2023-06-15 05:35 UTC, merged