[13608] Dynamic memory topic payload pool properly handle Zero sized payloads
eProsima/Fast-DDS pull request #3606
Opened 2023-06-16 15:09 UTC by Mario-DL

As a regression of #1929, this PR introduces a couple of unit tests, the regression BB test and proposes a fix for accepting zero sized payload allocations in the topic pool. 

In particular, this is interesting to properly add to the history the disposals of any endpoints in a remote Participant configured with DYNAMIC_*_MEMORY modes, as the payload size in that case is 0. Otherwise, the disposal CacheChanges are always discarded by remote participants and are not added to the history.

*Note: this PR should not be merged until 2.11 freeze is finished*

## Description

@Mergifyio backport 2.11.x 2.10.x 2.9.x 2.6.x

Fixes #1929

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-06-19 19:23 UTC, Mario-DL commented
@richiprosima please test this

2023-06-25 11:59 UTC, EduPonz requested changes

2023-06-25 11:59 UTC, EduPonz commented on test/blackbox/api/dds-pim/PubSubWriter.hpp
> +                    return matched_ == matched;
```suggestion
                    return matched_ <= matched;
```

2023-06-26 12:29 UTC, Mario-DL commented
@richiprosima please test this

2023-06-27 06:41 UTC, EduPonz approved these changes

2023-06-27 07:06 UTC, Mario-DL commented
@richiprosima please test this

2023-07-06 05:58 UTC, merged

2023-07-06 06:01 UTC, EduPonz commented
https://github.com/Mergifyio backport 2.11.x 2.10.x 2.9.x 2.6.x