[19166] Deserialization methods for Monitor Service
eProsima/Fast-DDS pull request #3684
Opened 2023-07-10 14:50 UTC by Mario-DL

## Description

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- **N/A** ? Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
-**N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-07-10 15:04 UTC, Mario-DL commented
@richiprosima please test this

2023-07-11 05:55 UTC, Mario-DL commented
@richiprosima please test this

2023-07-13 09:53 UTC, jsantiago-eProsima requested changes

2023-07-13 09:53 UTC, jsantiago-eProsima commented on src/cpp/statistics/fastdds/domain/DomainParticipantImpl.hpp
> +    RTPS_DllAPI ReturnCode_t fill_discovery_data_from_cdr_message(
This is an internal class. Exporting this symbol (and the ones below) is not needed. You are already exporting the ones in the API.

2023-07-13 09:53 UTC, jsantiago-eProsima commented on include/fastdds/rtps/participant/RTPSParticipant.h
> +     * Fills the in ParticipantProxyData from a MonitorService Message
```suggestion
     * Fills in the ParticipantProxyData from a MonitorService Message
```

2023-07-13 09:53 UTC, jsantiago-eProsima commented on include/fastdds/rtps/participant/RTPSParticipant.h
> +     * Fills the in WriterProxyData from a MonitorService Message
```suggestion
     * Fills in the WriterProxyData from a MonitorService Message
```

2023-07-13 09:53 UTC, jsantiago-eProsima commented on include/fastdds/rtps/participant/RTPSParticipant.h
> +     * Fills the in ReaderProxyData from a MonitorService Message
```suggestion
     * Fills in the ReaderProxyData from a MonitorService Message
```

2023-07-17 08:44 UTC, JesusPoderoso approved these changes

2023-07-17 08:45 UTC, merged