Fix real-time in Flow Controller
eProsima/Fast-DDS pull request #3735
Opened 2023-07-20 14:06 UTC by richiware

## Description

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-07-25 10:03 UTC, richiware commented
@richiprosima please test linux

2023-07-25 10:03 UTC, richiware commented
@richiware  please test mac

2023-07-25 10:03 UTC, richiware commented
@richiprosima please test mac

2023-08-30 12:03 UTC, richiware commented
@richiprosima please test this

2023-08-30 12:12 UTC, richiware commented
@richiprosima please test this

2023-08-31 07:20 UTC, richiware commented
@richiprosima please test this

2023-08-31 07:21 UTC, richiware commented
@richiprosima please test this

2023-08-31 11:26 UTC, richiware commented
@richiprosima please test this

2023-09-01 05:40 UTC, richiware commented
@richiprosima please test this

2023-09-01 07:28 UTC, richiware commented
@richiprosima please test mac

2023-09-06 08:02 UTC, MiguelCompany requested changes
Partial review: headers and source. Pending review of tests.

2023-09-11 12:14 UTC, richiware commented on include/fastdds/rtps/history/WriterHistory.h
> +    RTPS_DllAPI virtual bool remove_change_g(
I dont' think so. Any  user's thread call that function.

2023-09-11 12:20 UTC, richiware commented on src/cpp/fastdds/publisher/DataWriterHistory.cpp
>      std::lock_guard<RecursiveTimedMutex> guard(*this->mp_mutex);
Fix in aaea68156

2023-09-11 12:23 UTC, richiware commented on src/cpp/fastdds/publisher/DataWriterHistory.hpp
> +     * @param max_blocking_time
Done in be2c0860b

2023-09-11 12:28 UTC, richiware commented on src/cpp/rtps/history/History.cpp
>      std::lock_guard<RecursiveTimedMutex> guard(*mp_mutex);
Done in 95907f12f

2023-09-11 12:28 UTC, richiware commented on src/cpp/rtps/history/WriterHistory.cpp
>      std::lock_guard<RecursiveTimedMutex> guard(*mp_mutex);
Done in 95907f12f

2023-09-11 14:27 UTC, richiware commented on src/cpp/rtps/history/ReaderHistory.cpp
> +        bool release)
Done in db1bca5ec

2023-09-11 14:27 UTC, richiware commented on src/cpp/rtps/history/History.cpp
> +        bool release)
Done in db1bca5ec

2023-09-11 14:27 UTC, richiware commented on src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
> +        bool release)
Done in db1bca5ec

2023-09-12 05:35 UTC, richiware commented
@richiprosima please test this

2023-09-12 06:32 UTC, MiguelCompany approved these changes
LGTM with green CI

2023-09-13 06:21 UTC, merged