Replace uint64_t by 8 in alignas specifier
eProsima/Fast-DDS pull request #3752
Opened 2023-07-27 05:48 UTC by rsanchez15

Some android build targets cannot translate from `alignas(uint64_t)` to `alignas(8)`.

## Description

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-07-27 06:32 UTC, jsantiago-eProsima requested changes

2023-07-27 06:32 UTC, jsantiago-eProsima commented on src/cpp/rtps/DataSharing/DataSharingNotification.hpp
> +    struct alignas (8) Notification
Maybe using something like `alignas ( sizeof (uint64_t) )` would be cleaner and clearer.

2023-07-27 06:32 UTC, jsantiago-eProsima commented on src/cpp/rtps/DataSharing/DataSharingPayloadPool.hpp
> +    class alignas (8) PayloadNode
Same comment.

2023-07-27 06:32 UTC, jsantiago-eProsima commented on src/cpp/rtps/DataSharing/DataSharingPayloadPool.hpp
> +    struct alignas (8) PoolDescriptor
Same comment.

2023-07-27 07:16 UTC, jsantiago-eProsima approved these changes

2023-07-31 13:17 UTC, EduPonz commented
@Mergifyio backport 2.6.x 2.10.x 2.11.x

2023-08-01 05:41 UTC, merged