[19265] Custom pools on DDS layer feature
eProsima/Fast-DDS pull request #3755
Opened 2023-07-27 12:43 UTC by JesusPoderoso

## Description

This pull request aims to expose the usage of a custom payload pool implementation on the DDS layer

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [x] New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation. 
    Related documentation PR: eProsima/Fast-DDS-docs#514
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-07-31 09:11 UTC, jsantiago-eProsima requested changes

2023-07-31 09:11 UTC, jsantiago-eProsima commented on src/cpp/fastdds/publisher/DataWriterImpl.cpp
> +    }
I'm wondering if this couldn't be done outside of this function. check_datasharing_compatible is only used during the enable of the DataWriter, maybe we don't even need to check it if the payloadpool is a custom one.

This also applies to DataReaders but I don't see any check similar to this one being made there.

2023-08-01 09:46 UTC, MiguelCompany submitted a review, later dismissed

2023-08-01 09:46 UTC, MiguelCompany commented
@richiprosima Please test this

2023-08-01 11:19 UTC, MiguelCompany commented
The following AddressSanitizer error is relevant:
<details>
```
[1585.482s] 751: [ RUN      ] DDSBasic.endpoint_custom_payload_pools
[1587.521s] 751: =================================================================
[1587.521s] 751: ==43090==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs free) on 0x603000146140
[1588.081s] 751:     #0 0x7f5fd475c517 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:127
[1588.102s] 751:     #1 0x562e5c16453b in eprosima::fastrtps::rtps::SerializedPayload_t::empty() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/include/fastdds/rtps/common/SerializedPayload.h:158
[1588.103s] 751:     #2 0x562e5c164429 in eprosima::fastrtps::rtps::SerializedPayload_t::~SerializedPayload_t() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/include/fastdds/rtps/common/SerializedPayload.h:92
[1588.122s] 751:     #3 0x7f5fd269a6ef in eprosima::fastrtps::rtps::CacheChange_t::~CacheChange_t() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/include/fastdds/rtps/common/CacheChange.h:184
[1588.123s] 751:     #4 0x7f5fd269a70f in eprosima::fastrtps::rtps::CacheChange_t::~CacheChange_t() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/include/fastdds/rtps/common/CacheChange.h:184
[1588.124s] 751:     #5 0x7f5fd269abc2 in eprosima::fastrtps::rtps::CacheChangePool::destroy_change(eprosima::fastrtps::rtps::CacheChange_t*) const /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/rtps/history/CacheChangePool.h:110
[1588.124s] 751:     #6 0x7f5fd269717b in eprosima::fastrtps::rtps::CacheChangePool::~CacheChangePool() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/rtps/history/CacheChangePool.cpp:41
[1588.142s] 751:     #7 0x7f5fd260f151 in void __gnu_cxx::new_allocator<eprosima::fastrtps::rtps::CacheChangePool>::destroy<eprosima::fastrtps::rtps::CacheChangePool>(eprosima::fastrtps::rtps::CacheChangePool*) /usr/include/c++/11/ext/new_allocator.h:168
[1588.142s] 751:     #8 0x7f5fd260eedc in void std::allocator_traits<std::allocator<eprosima::fastrtps::rtps::CacheChangePool> >::destroy<eprosima::fastrtps::rtps::CacheChangePool>(std::allocator<eprosima::fastrtps::rtps::CacheChangePool>&, eprosima::fastrtps::rtps::CacheChangePool*) /usr/include/c++/11/bits/alloc_traits.h:535
[1588.142s] 751:     #9 0x7f5fd260eb8e in std::_Sp_counted_ptr_inplace<eprosima::fastrtps::rtps::CacheChangePool, std::allocator<eprosima::fastrtps::rtps::CacheChangePool>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/include/c++/11/bits/shared_ptr_base.h:528
[1588.145s] 751:     #10 0x7f5fd2471626 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/11/bits/shared_ptr_base.h:168
[1588.145s] 751:     #11 0x7f5fd2470d2f in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/11/bits/shared_ptr_base.h:705
[1588.145s] 751:     #12 0x7f5fd25ed263 in std::__shared_ptr<eprosima::fastrtps::rtps::IChangePool, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/11/bits/shared_ptr_base.h:1154
[1588.145s] 751:     #13 0x7f5fd25f1f30 in std::__shared_ptr<eprosima::fastrtps::rtps::IChangePool, (__gnu_cxx::_Lock_policy)2>::reset() /usr/include/c++/11/bits/shared_ptr_base.h:1272
[1588.145s] 751:     #14 0x7f5fd25ed44c in eprosima::fastrtps::rtps::Endpoint::~Endpoint() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/include/fastdds/rtps/Endpoint.h:71
[1588.154s] 751:     #15 0x7f5fd27dc7b1 in eprosima::fastrtps::rtps::RTPSReader::~RTPSReader() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/rtps/reader/RTPSReader.cpp:161
[1588.161s] 751:     #16 0x7f5fd27c71bf in eprosima::fastrtps::rtps::StatelessReader::~StatelessReader() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/rtps/reader/StatelessReader.cpp:53
[1588.161s] 751:     #17 0x7f5fd27c71df in eprosima::fastrtps::rtps::StatelessReader::~StatelessReader() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/rtps/reader/StatelessReader.cpp:53
[1588.179s] 751:     #18 0x7f5fd287a35e in eprosima::fastrtps::rtps::RTPSParticipantImpl::deleteUserEndpoint(eprosima::fastrtps::rtps::GUID_t const&) /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/rtps/participant/RTPSParticipantImpl.cpp:1866
[1588.190s] 751:     #19 0x7f5fd28cdc89 in eprosima::fastrtps::rtps::RTPSDomainImpl::removeRTPSReader(eprosima::fastrtps::rtps::RTPSReader*) /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/rtps/RTPSDomain.cpp:518
[1588.190s] 751:     #20 0x7f5fd28cda4f in eprosima::fastrtps::rtps::RTPSDomain::removeRTPSReader(eprosima::fastrtps::rtps::RTPSReader*) /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/rtps/RTPSDomain.cpp:502
[1588.208s] 751:     #21 0x7f5fd2a4bbf8 in eprosima::fastdds::dds::DataReaderImpl::stop() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/fastdds/subscriber/DataReaderImpl.cpp:311
[1588.208s] 751:     #22 0x7f5fd2a4bcd7 in eprosima::fastdds::dds::DataReaderImpl::~DataReaderImpl() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/fastdds/subscriber/DataReaderImpl.cpp:325
[1588.216s] 751:     #23 0x7f5fd32a52c2 in eprosima::fastdds::statistics::dds::DataReaderImpl::~DataReaderImpl() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/statistics/fastdds/subscriber/DataReaderImpl.hpp:43
[1588.217s] 751:     #24 0x7f5fd32a52e1 in eprosima::fastdds::statistics::dds::DataReaderImpl::~DataReaderImpl() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/statistics/fastdds/subscriber/DataReaderImpl.hpp:43
[1588.227s] 751:     #25 0x7f5fd2a2a1cf in eprosima::fastdds::dds::SubscriberImpl::delete_contained_entities() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/fastdds/subscriber/SubscriberImpl.cpp:640
[1588.232s] 751:     #26 0x7f5fd2a3e788 in eprosima::fastdds::dds::Subscriber::delete_contained_entities() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/fastdds/subscriber/Subscriber.cpp:187
[1588.255s] 751:     #27 0x7f5fd2adb56f in eprosima::fastdds::dds::DomainParticipantImpl::delete_contained_entities() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/fastdds/domain/DomainParticipantImpl.cpp:924
[1588.255s] 751:     #28 0x7f5fd329c7f6 in eprosima::fastdds::statistics::dds::DomainParticipantImpl::delete_contained_entities() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp:275
[1588.261s] 751:     #29 0x7f5fd2b2ef11 in eprosima::fastdds::dds::DomainParticipant::delete_contained_entities() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/src/cpp/fastdds/domain/DomainParticipant.cpp:305
[1588.280s] 751:     #30 0x562e5c159f43 in eprosima::fastdds::dds::DDSBasic_endpoint_custom_payload_pools_Test::TestBody() /home/runner/work/Fast-DDS/Fast-DDS/src/Fast-DDS/test/blackbox/common/DDSBlackboxTestsBasic.cpp:758
[1588.281s] 751:     #31 0x562e5cccf9e8 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/runner/work/Fast-DDS/Fast-DDS/build/fastrtps/test/blackbox/BlackboxTests_DDS_PIM+0xf339e8)
[1588.281s] 751:     #32 0x562e5ccc8824 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/runner/work/Fast-DDS/Fast-DDS/build/fastrtps/test/blackbox/BlackboxTests_DDS_PIM+0xf2c824)
[1588.282s] 751:     #33 0x562e5cca4b1f in testing::Test::Run() (/home/runner/work/Fast-DDS/Fast-DDS/build/fastrtps/test/blackbox/BlackboxTests_DDS_PIM+0xf08b1f)
[1588.282s] 751:     #34 0x562e5cca55f2 in testing::TestInfo::Run() (/home/runner/work/Fast-DDS/Fast-DDS/build/fastrtps/test/blackbox/BlackboxTests_DDS_PIM+0xf095f2)
[1588.282s] 751:     #35 0x562e5cca5f30 in testing::TestSuite::Run() (/home/runner/work/Fast-DDS/Fast-DDS/build/fastrtps/test/blackbox/BlackboxTests_DDS_PIM+0xf09f30)
[1588.283s] 751:     #36 0x562e5ccb6162 in testing::internal::UnitTestImpl::RunAllTests() (/home/runner/work/Fast-DDS/Fast-DDS/buil [...]

2023-08-01 18:33 UTC, MiguelCompany commented
@richiprosima Please test this

2023-08-03 12:00 UTC, merged