[19347] Fix encapsulation format in WLP
eProsima/Fast-DDS pull request #3784
Opened 2023-08-04 09:13 UTC by EduPonz

## Description

As #3782 points out, the encapsulation used for the ParticipantMessageData messages within the WLP was not correctly set. This PR:
* Sets the encapsulation to `CDR`
* Extends validation of WLP messages
* Fixes #3782 

@Mergifyio backport 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- *N/A*: New feature has been added to the `versions.md` file (if applicable).
- *N/A*: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-08-04 09:43 UTC, EduPonz commented
@richiprosima please test this

2023-08-04 09:50 UTC, EduPonz commented
@richiprosima please test mac

2023-08-04 11:07 UTC, MiguelCompany requested changes

2023-08-04 11:07 UTC, MiguelCompany commented on src/cpp/rtps/builtin/liveliness/WLPListener.cpp
> +        if (is_wlp_kind(&change->serializedPayload.data[16]))
Would be better if this method has an output argument that returns the liveliness kind.
We would then only have the failing validation condition:

```
if (!get_wlp_kind(&change->serializedPayload.data[16], livelinessKind))
{
    // logInfo + remove_change + return
}
```

2023-08-04 11:07 UTC, MiguelCompany commented on src/cpp/rtps/builtin/liveliness/WLPListener.cpp
> +        *liveliness = (LivelinessQosPolicyKind)key.value[15];
We should also subtract 1 here.

2023-08-05 07:36 UTC, EduPonz commented
@richiware please test this

2023-08-05 07:36 UTC, EduPonz commented
@richiprosima please test this

2023-08-05 13:59 UTC, EduPonz commented
@richiprosima please test this

2023-08-07 07:42 UTC, MiguelCompany requested changes

2023-08-07 07:42 UTC, MiguelCompany commented on include/fastdds/rtps/builtin/liveliness/WLPListener.h
> +            octet* serialized_kind,
```suggestion
            const octet* serialized_kind,
```

2023-08-07 07:42 UTC, MiguelCompany commented on src/cpp/rtps/builtin/liveliness/WLPListener.cpp
> +    const uint32_t guid_prefix_size = 12;
We already have constants for these two

2023-08-07 07:42 UTC, MiguelCompany commented on src/cpp/rtps/builtin/liveliness/WLPListener.cpp
> +    const uint32_t min_serialized_length = representation_header_size
I would use constexpr instead of const

2023-08-07 07:42 UTC, MiguelCompany commented on src/cpp/rtps/builtin/liveliness/WLPListener.cpp
> +            && CDRMessage::skip(&cdr_message, participant_msg_data_length_size)
```suggestion
            && CDRMessage::skip(&cdr_message, participant_msg_data_kind_size)
```

2023-08-07 07:42 UTC, MiguelCompany commented on src/cpp/rtps/builtin/liveliness/WLPListener.cpp
> +        const uint32_t participant_msg_data_pos = 16;
```suggestion
        const uint32_t participant_msg_data_kind_pos = 16;
```

2023-08-07 07:42 UTC, MiguelCompany commented on src/cpp/rtps/builtin/liveliness/WLPListener.cpp
> +        const uint32_t encapsulation_pos = 16;
```suggestion
        const uint32_t encapsulation_pos = 1;
```

2023-08-07 07:42 UTC, MiguelCompany commented on src/cpp/rtps/builtin/liveliness/WLPListener.cpp
> +            change->serializedPayload.encapsulation = (uint16_t)change->serializedPayload.data[encapsulation_pos];
Assign encapsulation before deserializing

2023-08-07 11:41 UTC, MiguelCompany approved these changes

2023-08-07 12:04 UTC, MiguelCompany commented
@richiprosima Please test this

2023-08-07 19:58 UTC, merged

2023-08-07 19:59 UTC, EduPonz commented
@Mergifyio backport 2.11.x 2.10.x 2.6.x