Change history remove change return statement
eProsima/Fast-DDS pull request #3858
Opened 2023-09-19 06:58 UTC by rsanchez15

## Description

`History::remove_change` return statement was based on the fact that `History::remove_change_nts` return a `History::iterator` different than `end` iteration. However, `History::remove_change_nts` was also calling `erase` method and this will return the iterator pointing to the next element of the collection or `end` if that was the last element. Therefore, `History::remove_change_nts` could return `end` iterator and still be the expected result. 

Applying this change, the following issue in Windows platforms when compiling in Debug mode is also resolved. 

```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\vector(192) : Assertion failed: vector iterators incompatible
```

This can be tested using any of the following tests in Fast DDS (only in Windows platforms and Debug cmake build type):

```
The following tests FAILED:
         88 - BlackboxTests_DDS_PIM.DDSBasic.MultithreadedPublisherCreation (Exit code 0xc0000409)
         89 - BlackboxTests_DDS_PIM.DDSBasic.MultithreadedReaderCreationDoesNotDeadlock (Exit code 0xc0000409)
         90 - BlackboxTests_DDS_PIM.DDSBasic.PidRelatedSampleIdentity (Exit code 0xc0000409)
         91 - BlackboxTests_DDS_PIM.DDSBasic.IgnoreParticipant (Exit code 0xc0000409)
         92 - BlackboxTests_DDS_PIM.DDSBasic.participant_ignore_local_endpoints (Exit code 0xc0000409)
         94 - BlackboxTests_DDS_PIM.DDSBasic.endpoint_custom_payload_pools (Exit code 0xc0000409)
```

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-09-19 15:03 UTC, rsanchez15 commented
@richiprosima please test this

2023-09-20 06:01 UTC, rsanchez15 commented
@richiprosima please test this

2023-09-20 07:12 UTC, richiware requested changes
`DataReaderHistory.cpp` implements `remove_change_nts` and uses it. Currently the function will never fail in the DataReader side, but it should be appreciated if you prepare these functions for this.

2023-09-20 07:12 UTC, richiware commented on src/cpp/rtps/history/WriterHistory.cpp
>      if ( removal == changesEnd())
The last `return` of this function should not be `changeEnd()`.

2023-09-21 12:18 UTC, richiware commented
@richiprosima please test this

2023-09-22 06:38 UTC, MiguelCompany requested changes

2023-09-22 06:38 UTC, MiguelCompany commented on src/cpp/rtps/history/History.cpp
> +    std::advance(it, std::distance<const_iterator>(it, c_it));
```suggestion
    std::advance(it, std::distance<const_iterator>(m_changes.cbegin(), c_it));
```

2023-09-22 06:38 UTC, MiguelCompany commented on test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
> +        std::advance(it, std::distance<const_iterator>(it, c_it));
```suggestion
        std::advance(it, std::distance<const_iterator>(m_changes.cbegin(), c_it));
```

2023-09-22 06:53 UTC, MiguelCompany approved these changes

2023-09-25 06:57 UTC, MiguelCompany commented
@richiprosima Please test this

2023-09-25 10:02 UTC, merged