[19490] Fix Github windows CI
eProsima/Fast-DDS pull request #3887
Opened 2023-09-28 08:39 UTC by EduPonz

## Description

This PR adds logic to the Windows CI workflow to cope with versions depending on different Fast CDR versions.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- *N/A*: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- *N/A*: Any new/modified methods have been properly documented using Doxygen. 
- *N/A*: Changes are ABI compatible. 
- *N/A*: Changes are API compatible. 
- *N/A*: New feature has been added to the `versions.md` file (if applicable).
- *N/A*: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- *N/A*: Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-09-28 14:58 UTC, MiguelCompany requested changes
The suggestions below should also be applied to the nightly_xxx repos

2023-09-28 14:58 UTC, MiguelCompany commented on .github/workflows/config/default_ci_2.6.x.repos
> +        version: 1.1.x
```suggestion
        version: 1.0.x
```

2023-09-28 14:58 UTC, MiguelCompany commented on .github/workflows/config/default_ci_2.6.x.repos
> +        version: master
```suggestion
        version: v1.2.1
```

2023-09-28 14:58 UTC, MiguelCompany commented on .github/workflows/config/nightly_2.10.x.repos
> +        version: 1.1.x
```suggestion
        version: 1.0.x
```

2023-09-28 14:58 UTC, MiguelCompany commented on .github/workflows/config/nightly_2.10.x.repos
> +        version: master
```suggestion
        version: v1.3.0
```

2023-09-28 14:58 UTC, MiguelCompany commented on .github/workflows/config/nightly_2.11.x.repos
> +        version: master
v1.3.1

2023-09-29 05:12 UTC, MiguelCompany approved these changes

2023-09-29 08:43 UTC, merged

2023-10-06 05:36 UTC, EduPonz commented
@mergifyio backport 2.11.x 2.10.x 2.6.x