[19048] Backport workflows from master
eProsima/Fast-DDS pull request #3967
Opened 2023-10-27 07:49 UTC by MiguelCompany

## Description

This copies the github workflows folder from master.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- **N/A** The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-11-13 09:49 UTC, EduPonz requested changes

2023-11-13 09:49 UTC, EduPonz commented on .github/workflows/reusable-windows-ci.yml
> +          cmakeVersion: '3.22.6'
Revoke this change. CMake version in 2.11.x is 3.16

2023-11-13 13:24 UTC, EduPonz requested changes

2023-11-13 13:24 UTC, EduPonz commented on .github/workflows/reusable-windows-ci.yml
> +          cmakeVersion: '3.22.6'
```suggestion
          cmakeVersion: '3.16.3'
```

2023-11-13 13:28 UTC, EduPonz submitted a review, later dismissed

2023-11-29 15:18 UTC, cferreiragonz commented
@richiprosima please test mac

2023-11-30 13:35 UTC, EduPonz approved these changes

2023-11-30 13:35 UTC, merged