[19354] Add XML parser bit_bound bounds check
eProsima/Fast-DDS pull request #3975
Opened 2023-10-31 13:17 UTC by JesusPoderoso

## Description

Bit mask's bit bound attribute can be set to values out of expected bounds (0 < bit_bound < 65) through XML configuration. This PR add a check in XML parser to avoid it.

@Mergifyio backport 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- **N/A**  New feature has been added to the `versions.md` file (if applicable).
- **N/A**  New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-10-31 18:39 UTC, JesusPoderoso commented
@richiprosima please test mac please test windows

2023-11-03 08:56 UTC, MiguelCompany requested changes

2023-11-03 08:56 UTC, MiguelCompany commented on src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
> +    }
```suggestion
        auto input_bit_bound = std::atoi(anno_bit_bound);
        if (input_bit_bound < 1 || input_bit_bound > 64)
        {
            return XMLP_ret::XML_ERROR;
        }
        bit_bound = static_cast<uint16_t>(input_bit_bound);
    }
```

2023-11-03 09:07 UTC, MiguelCompany approved these changes

2023-11-03 09:07 UTC, MiguelCompany commented
@richiprosima Please test this

2023-11-03 14:51 UTC, MiguelCompany commented
@richiprosima Please test mac

2023-11-03 16:25 UTC, JesusPoderoso commented
@richiprosima please test mac

2023-11-03 21:45 UTC, merged

2023-11-03 21:45 UTC, MiguelCompany commented
@Mergifyio backport 2.11.x 2.10.x 2.6.x