[19839] Fix flow controllers utests compilation when using Fast CDR from thirdparty
eProsima/Fast-DDS pull request #3979
Opened 2023-10-31 15:09 UTC by EduPonz

## Description

The Flow controllers unit test end up including `<fastcdr/cdr/fixed_size_string.hpp>` through the internal header `src/cpp/statistics/types/types.h`, but they do not link with Fast CDR. In a colcon context this is OK as Fast CDR will always be compiled and installed before compiling Fast DDS, so its header are in the include path when compiling the unit tests. However, when using the Fast CDR submodule, CMake may start by compiling the unit tests prior to Fast CDR and Fast DDS, and in that case the Fast CDR headers are not in the include path. This PR fixes this by explicitly linking with Fast CDR in those tests.

@Mergifyio backport 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- *N/A*: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- *N/A*: Any new/modified methods have been properly documented using Doxygen. 
- *N/A*: Changes are ABI compatible. 
- *N/A*: Changes are API compatible. 
- *N/A*: New feature has been added to the `versions.md` file (if applicable).
- *N/A*: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-10-31 15:28 UTC, richiware requested changes

2023-10-31 15:28 UTC, richiware commented on test/unittest/rtps/flowcontrol/CMakeLists.txt
> +target_link_libraries(FlowControllerFactoryTests GTest::gmock fastcdr)
```suggestion
target_link_libraries(FlowControllerFactoryTests 
    fastcdr
    GTest::gmock
    )
```

2023-10-31 15:28 UTC, richiware commented on test/unittest/rtps/flowcontrol/CMakeLists.txt
> +target_link_libraries(FlowControllerPublishModesTests GTest::gmock fastcdr)
```suggestion
target_link_libraries(FlowControllerPublishModesTests 
    fastcdr
    GTest::gmock
    )
```

2023-10-31 15:28 UTC, richiware commented on test/unittest/rtps/flowcontrol/CMakeLists.txt
> +target_link_libraries(FlowControllerSchedulersTests GTest::gmock fastcdr)
```suggestion
target_link_libraries(FlowControllerSchedulersTests 
    fastcdr
    GTest::gmock
    )
```

2023-11-02 07:34 UTC, richiware approved these changes

2023-11-02 08:12 UTC, merged

2023-11-02 08:12 UTC, EduPonz commented
@Mergifyio backport 2.11.x 2.10.x 2.6.x