[19851] Fix missing mandatory attribute check in XML parser struct type
eProsima/Fast-DDS pull request #3995
Opened 2023-11-07 13:50 UTC by JesusPoderoso

## Description

Struct's name attribute is mandatory to be set while configuring types through XML configuration. This PR add a check in XML parser to fail if no name was defined.

@Mergifyio backport 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [̶ ̶]̶ Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [̶ ̶]̶ New feature has been added to the `versions.md` file (if applicable).
- [̶ ̶]̶ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-11-07 13:51 UTC, JesusPoderoso commented
@Mergifyio backport 2.11.x 2.10.x 2.6.x

2023-11-08 07:07 UTC, Mario-DL requested changes
Good fix ! Just leaving a NIT

2023-11-08 07:07 UTC, Mario-DL commented on src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
> +    if (!name)
NIT, compare explicitly against nullptr for uniformity
```suggestion
    if (nullptr == name)
```

2023-11-08 08:01 UTC, JesusPoderoso commented
@richiprosima please test this

2023-11-08 11:46 UTC, Mario-DL approved these changes
LGTM with green CI

2023-11-10 09:53 UTC, JesusPoderoso commented
@richiprosima please test mac

2023-11-10 11:21 UTC, JesusPoderoso commented
@richiprosima please test mac

2023-11-11 09:28 UTC, JesusPoderoso commented
@richiprosima please test this

2023-11-13 08:26 UTC, merged