[20021] TCP support for Discovery server CLI and env. var.
eProsima/Fast-DDS pull request #4097
Opened 2023-12-04 14:51 UTC by cferreiragonz

## Description

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- [X] New feature has been documented/Current behavior is correctly described in the documentation.
    Related documentation PR: [eProsima/Fast-DDS-docs#](https://github.com/eProsima/Fast-DDS-docs/pull/599) (PR) 
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-12-05 16:10 UTC, elianalf commented on tools/fds/server.cpp
> +    Locator locator_tcp_4(4, rtps::DEFAULT_TCP_SERVER_PORT);
Locator locator_tcp_4(LOCATOR_KIND_TCPv4, rtps::DEFAULT_TCP_SERVER_PORT);

2023-12-05 16:11 UTC, elianalf commented on tools/fds/server.cpp
> +    Locator locator_tcp_6(8, rtps::DEFAULT_TCP_SERVER_PORT);
Locator locator_tcp_6(LOCATOR_KIND_TCPv6, rtps::DEFAULT_TCP_SERVER_PORT);

2023-12-07 11:57 UTC, elianalf requested changes

2023-12-11 08:23 UTC, cferreiragonz commented on tools/fds/server.cpp
> +    if (nullptr == pOp && (nullptr == options[XML_FILE] || nullptr != pO_port) && nullptr == pO_tcp)
If only a TCP port is set (f.e.: fastdds discovery -i 0 -q 12345), the default UDP locator listening on [0.0.0.0]:11811 will be initiated. So the code inside the if clause will be accessed. What happens is that the TCP port is ignored. The only possible way to create a Discovery Server using TCP transport right now is to set the argument "-t" with the corresponding IP address.
We could discuss about enabling the creation of the server just by adding the TCP port.

2023-12-11 10:20 UTC, cferreiragonz commented on tools/fds/server.cpp
> +    if (nullptr == pOp && (nullptr == options[XML_FILE] || nullptr != pO_port) && nullptr == pO_tcp)
We will enable the creation of a server just by specifying the TCP port. It will default to localhost.

2023-12-11 13:44 UTC, cferreiragonz commented
@richiprosima please test this

2023-12-11 15:38 UTC, cferreiragonz commented
@richiprosima please test this

2023-12-12 07:08 UTC, cferreiragonz commented
@richiprosima please test this

2023-12-12 10:04 UTC, cferreiragonz commented
@Mergifyio rebase

2023-12-12 15:03 UTC, elianalf approved these changes

2023-12-12 15:29 UTC, cferreiragonz commented
@richiprosima please test this

2023-12-13 06:52 UTC, cferreiragonz commented
@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

2023-12-13 07:14 UTC, cferreiragonz commented
@richiprosima please test this

2023-12-13 11:08 UTC, cferreiragonz commented
@richiprosima please test this

2023-12-14 06:33 UTC, elianalf approved these changes

2023-12-14 07:37 UTC, merged