[20086] Methods to configure transport scenarios
eProsima/Fast-DDS pull request #4098
Opened 2023-12-04 14:51 UTC by MiguelCompany

## Description

Open as draft:

- [x] Configure using code
- [x] Configure using environment variable
- [x] Configure using XML
- [x] Tests
- [x] Documentation

@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [x] New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation. 
    Related documentation PR: https://github.com/eProsima/Fast-DDS-docs/pull/619
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

2023-12-15 09:47 UTC, EduPonz requested changes

2023-12-15 15:07 UTC, cferreiragonz commented on test/blackbox/common/BlackboxTestsTransportCustom.cpp
> +    bt_list.push_back("participant_largedatav6");
Wrong configuration test has been added in the XML Parser unittest

2023-12-16 16:41 UTC, EduPonz submitted a review, later dismissed

2023-12-16 18:58 UTC, cferreiragonz commented
@richiprosima please test this

2023-12-16 19:01 UTC, cferreiragonz commented
@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

2023-12-18 09:50 UTC, cferreiragonz commented
@richiprosima please test this

2023-12-18 13:39 UTC, MiguelCompany commented
@richiprosima Please test windows

2023-12-18 13:40 UTC, cferreiragonz commented
@richiprosima please test mac

2023-12-18 13:58 UTC, cferreiragonz commented
@richiprosima please test mac

2023-12-18 14:15 UTC, EduPonz commented
@richiprosima please test windows test mac

2023-12-18 14:54 UTC, cferreiragonz commented
@richiprosima please test mac

2023-12-18 15:26 UTC, EduPonz approved these changes

2023-12-18 15:32 UTC, EduPonz requested changes

2023-12-18 15:55 UTC, cferreiragonz commented
@richiprosima please test windows test linux check style

2023-12-19 06:20 UTC, EduPonz commented
@richiprosima please test windows

2023-12-19 06:21 UTC, EduPonz approved these changes

2023-12-19 13:28 UTC, EduPonz approved these changes

2023-12-19 13:31 UTC, merged