[20167] Fix on_sample_lost notification on best-effort readers for framented samples
eProsima/Fast-DDS pull request #4187
Opened 2023-12-21 09:14 UTC by MiguelCompany

## Description

When some fragments are lost on every sample, best-effort readers were not notifying `on_sample_lost` events.

@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-12-24 19:33 UTC, JesusPoderoso commented
@richiprosima please test this

2024-01-22 15:45 UTC, JesusPoderoso commented
@richiprosima please test mac 🥲

2024-02-10 13:53 UTC, EduPonz requested changes
I have two minor suggestions that IMO can be done without running CI if that passes

2024-02-10 13:53 UTC, EduPonz commented on test/blackbox/common/DDSBlackboxTestsListeners.cpp
> +                EntityId_t readerID, writerID;
I'm okey with doing this with `skip-ci`
```suggestion
                EntityId_t readerID;
                EntityId_t writerID;
```

2024-02-10 13:53 UTC, EduPonz commented on test/blackbox/common/DDSBlackboxTestsListeners.cpp
> +    reader.socket_buffer_size(20 * 1024 * 1024);
Add a comment on this

2024-02-10 13:54 UTC, EduPonz commented
@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

2024-02-10 13:54 UTC, EduPonz commented
@Mergifyio rebase master

2024-02-10 13:59 UTC, EduPonz commented
@richiprosima please test mac test linux test discovery server

2024-02-12 07:17 UTC, MiguelCompany commented on test/blackbox/common/DDSBlackboxTestsListeners.cpp
> +                EntityId_t readerID, writerID;
6df3ea1

2024-02-12 07:18 UTC, MiguelCompany commented on test/blackbox/common/DDSBlackboxTestsListeners.cpp
> +    reader.socket_buffer_size(20 * 1024 * 1024);
6df3ea1

2024-02-14 07:09 UTC, JesusPoderoso commented
@richiprosima please test mac test linux test discovery server

2024-02-14 11:22 UTC, EduPonz approved these changes

2024-02-14 14:52 UTC, MiguelCompany commented
@richiprosima Please test mac

2024-02-14 15:58 UTC, MiguelCompany commented
@richiprosima Please test mac

2024-02-21 07:20 UTC, MiguelCompany commented
@mergifyio rebase

2024-02-21 07:25 UTC, MiguelCompany commented
@richiprosima Please test this

2024-02-21 20:12 UTC, EduPonz commented
Failures in macOS seem definitely related to the PR. I'm moving this to 2.14

2024-03-21 06:45 UTC, MiguelCompany commented
@richiprosima Please test this

2024-03-21 08:19 UTC, MiguelCompany commented
@richiprosima Please test mac

2024-03-21 17:09 UTC, MiguelCompany commented
@richiprosima please test mac and test windows

2024-03-22 15:26 UTC, merged

2024-03-22 15:27 UTC, EduPonz commented
@Mergifyio backport 2.13.x