[20166] Fix data race in PDPListener and SecurityManager
eProsima/Fast-DDS pull request #4188
Opened 2023-12-21 12:28 UTC by Mario-DL

## Description

This PR fixes a data race occurring in `PDPListenerSecurityInitiator`  affecting `SecurityManager`. The `temp_participant_data_` was being overwritten as `discovered_participant()` was being called without the `PDP` mutex taken. This causes a corruption when the secure participant was in the middle of matching to a previous secure participant.

This PR also ensures that the `discovered_participant()` method is using the `ParticipantProxyData` from the `discovered_participants` collection.

_Note: openning as draft as proper test needs to be added_

@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2023-12-21 15:48 UTC, MiguelCompany requested changes
Apart from my NIT below, a regression test should be added

2023-12-21 15:48 UTC, MiguelCompany commented on src/cpp/rtps/security/SecurityManager.cpp
> +    //! Use the information from the collection
```suggestion
    // Use the information from the collection
```

2023-12-21 16:12 UTC, Mario-DL commented
@richiprosima please test this

2023-12-21 18:25 UTC, MiguelCompany requested changes

2023-12-21 18:25 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/participant/DS/PDPSecurityInitiatorListener.cpp
> +            response_cb_(temp_participant_data_);
```suggestion
        auto callback_data = new_data;
        reader->getMutex().unlock();
        lock.unlock();

        //! notify security manager in order to start handshake
        bool ret = parent_pdp_->getRTPSParticipant()->security_manager().discovered_participant(callback_data);
        //! Reply to the remote participant
        if (ret)
        {
            response_cb_(callback_data);
```

2023-12-21 22:03 UTC, Mario-DL commented on src/cpp/rtps/builtin/discovery/participant/DS/PDPSecurityInitiatorListener.cpp
> +            response_cb_(temp_participant_data_);
I really like the suggestion

2023-12-21 22:04 UTC, Mario-DL commented
@richiprosima please test this

2023-12-22 08:40 UTC, Mario-DL commented
@richiprosima please test this

2023-12-22 08:59 UTC, MiguelCompany requested changes

2023-12-22 08:59 UTC, MiguelCompany commented on test/blackbox/common/BlackboxTestsSecurity.cpp
> +// Regresion test for Refs #20166
```suggestion
// Regresion test for redmine issue 20166
```

2023-12-22 08:59 UTC, MiguelCompany commented on test/blackbox/common/BlackboxTestsSecurity.cpp
> +            "file://" + std::string(certs_path) + "/permissions_helloworld.smime"));
Would be nice if you could do something similar to [these lines](https://github.com/eProsima/Fast-DDS/blob/ef14749e348fac14555e280441ca7abe6bf48af5/test/blackbox/common/BlackboxTestsSecurity.cpp#L4808-L4811)

2023-12-22 08:59 UTC, MiguelCompany commented on test/blackbox/common/BlackboxTestsSecurity.cpp
> +            // Force a high number of announcements. Publish 1 every 1 ms
We shouldn't need this if we follow the initialization order that was reported:

1. secure_writer
2. non_secure_reader
3. secure_reader

2023-12-22 08:59 UTC, MiguelCompany commented on test/blackbox/common/BlackboxTestsSecurity.cpp
> +    //! Create
Please remove the `!` from all the comments

2023-12-22 08:59 UTC, MiguelCompany commented on test/blackbox/common/BlackboxTestsSecurity.cpp
> +    secure_reader.block_for_all();
I would take the chance to ensure the non_secure_reader does not receive data:

```suggestion
    secure_reader.startReception(data);
    non_secure_reader.startReception(data);

    secure_writer.send(data);

    // In this test all data should be sent.
    ASSERT_TRUE(data.empty());

    secure_reader.block_for_all();
    EXPECT_EQ(non_secure_reader.getReceivedCount(), 0u);
```

2023-12-22 09:23 UTC, MiguelCompany approved these changes
LGTM with green CI

2023-12-22 12:47 UTC, MiguelCompany commented
@richiprosima Please test mac

2023-12-22 12:50 UTC, MiguelCompany commented
@richiprosima Please test mac

2024-01-08 13:05 UTC, merged