Fix data race on PDP [19696]
eProsima/Fast-DDS pull request #4220
Opened 2024-01-09 15:52 UTC by Tempate

## Description

In the previous version, a data race took place when a participant got removed before another participant had finished processing its PDP data. 

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-01-15 10:11 UTC, Tempate commented
@richiprosima please test this

2024-01-16 15:48 UTC, Tempate commented
@richiprosima please test this

2024-01-26 08:08 UTC, MiguelCompany requested changes
1. There is a test that has failed with segmentation fault both in Mac and Windows
    * [Mac](http://jenkins.eprosima.com:8080/job/fastdds_mac/5011/testReport/junit/projectroot.test/blackbox/DDSDiscovery_AddDiscoveryServerToList/)
    * [Windows](http://jenkins.eprosima.com:8080/job/fastdds_windows/label=windows-secure,toolset=v142/5463/testReport/projectroot.test/blackbox/DDSDiscovery_AddDiscoveryServerToList/)
2. I don't like the solution of copying the whole `ParticipantProxyData`, it might be better to change the API of the methods receiving it so they only use the necessary information, and just copy that information

2024-01-31 06:45 UTC, Tempate commented
@richiprosima please test this

2024-02-14 14:02 UTC, juanlofer-eprosima commented on src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
> +                    svr.is_connected = true;
This block might be deleted, however I took the most conservative approach.

2024-02-15 10:14 UTC, juanlofer-eprosima commented
@richiprosima please test this

2024-02-20 07:47 UTC, JesusPoderoso commented
@juanlofer-eprosima please address linter issue. Is the linux discovery failed test related with the PR?

2024-02-22 10:42 UTC, Mario-DL approved these changes
Good job in this PR as it effectively solves the data race it describes, I also like the simplification on the `PDPClient` in order to use the `is_connected`, avoiding to store the entire `ParticipantProxyData`. I am approving though leaving a reflection.

Trying to give a second thought on @MiguelCompany suggested, I think this work may admit an even fine-grained solution to avoid copying the entire `ParcipantProxyData` in stack. But it is also true that we are highly tied to the entire `pdata` within `PDP::assign_remote_endpoints()`  when we are notifying the user with the `DiscoveredParticipantInfo`. The rest of the methods, `matched_reader/writer_add()` and `assign_low_level_endpoints()` do not make an intensive use of the `ParticipantProxyData` and it would be enough to pass them only some of the fields: some `locator lists`, the `guid` and the `m_availableBuiltinEndpoints` in essence.

Finally, I am attaching a possible patch of a different approach instead of stack-copying, which explores the option of synchronize the `PDP::remove_remote_participant()`  and `PDP::assign_remote_endpoints()` **only**  in the case that we are trying to delete a  `pdata` that is is currently being processed. The fix is fast and dirty just to make an idea of the approach and I would still need to think if it would solve all the situations that we are solving by making that stack copy.

[pdp_patch_another_approach.txt](https://github.com/eProsima/Fast-DDS/files/14372684/pdp_patch_another_approach.txt)

Approving !

2024-02-22 11:16 UTC, Mario-DL commented
I included the backports in the PR description

2024-02-22 11:30 UTC, merged

2024-02-22 11:30 UTC, EduPonz commented
@Mergifyio backport 2.12.x 2.10.x 2.6.x

2024-02-22 11:56 UTC, juanlofer-eprosima commented
> Good job in this PR as it effectively solves the data race it describes, I also like the simplification on the `PDPClient` in order to use the `is_connected`, avoiding to store the entire `ParticipantProxyData`. I am approving though leaving a reflection.
> 
> Trying to give a second thought on @MiguelCompany suggested, I think this work may admit an even fine-grained solution to avoid copying the entire `ParcipantProxyData` in stack. But it is also true that we are highly tied to the entire `pdata` within `PDP::assign_remote_endpoints()` specially when we are notifying the user with the `DiscoveredParticipantInfo`. The rest of the methods, `matched_reader/writer_add()` and `assign_low_level_endpoints()` do not make an intensive use of the `ParticipantProxyData` and it would be enough to pass them only some of the fields: some `locator lists`, the `guid` and the `m_availableBuiltinEndpoints` in essence.
> 
> Finally, I am attaching a possible patch of a different approach instead of stack-copying, which explores the option of synchronizing the `PDP::remove_remote_participant()` and `PDP::assign_remote_endpoints()` **only** in the case that we are trying to delete a `pdata` that is is currently being processed. The fix is fast and dirty just to make an idea of the approach and I would still need to think if it would solve all the situations that we are solving by making that stack copy.
> 
> [pdp_patch_another_approach.txt](https://github.com/eProsima/Fast-DDS/files/14372684/pdp_patch_another_approach.txt)
> 
> Approving !

I also agree the solution @MiguelCompany suggested was better, but we decided to proceed with the copy approach given the effort required, and also considering that the root of the problem (releasing the PDP mutex before completing an entire discovery operation, which might lead to inconsistent states apart from data races as the one we are dealing with here) would still remain unsolved. We also discussed that a possible solution to tackle the root of the problem would be to derive all discovery actions to a dedicated thread.

Regarding your proposal, I believe it is a bit risky to wait as some lower level resources might be blocked by that thread, leading to potential deadlocks. And two additional comments:

- I believe that (in remove_remote_participant) locking the PDP mutex should be done after calling wait (to avoid intraprocess deadlock).
- I also believe that a PDP instance could process more than one data P before processing a data uP, so I guess the complexity of this solution would need to grow.

2024-02-22 14:19 UTC, juanlofer-eprosima commented
> > > Good job in this PR as it effectively solves the data race it describes, I also like the simplification on the `PDPClient` in order to use the `is_connected`, avoiding to store the entire `ParticipantProxyData`. I am approving though leaving a reflection.
> > > Trying to give a second thought on @MiguelCompany suggested, I think this work may admit an even fine-grained solution to avoid copying the entire `ParcipantProxyData` in stack. But it is also true that we are highly tied to the entire `pdata` within `PDP::assign_remote_endpoints()` specially when we are notifying the user with the `DiscoveredParticipantInfo`. The rest of the methods, `matched_reader/writer_add()` and `assign_low_level_endpoints()` do not make an intensive use of the `ParticipantProxyData` and it would be enough to pass them only some of the fields: some `locator lists`, the `guid` and the `m_availableBuiltinEndpoints` in essence.
> > > Finally, I am attaching a possible patch of a different approach instead of stack-copying, which explores the option of synchronizing the `PDP::remove_remote_participant()` and `PDP::assign_remote_endpoints()` **only** in the case that we are trying to delete a `pdata` that is is currently being processed. The fix is fast and dirty just to make an idea of the approach and I would still need to think if it would solve all the situations that we are solving by making that stack copy.
> > > [pdp_patch_another_approach.txt](https://github.com/eProsima/Fast-DDS/files/14372684/pdp_patch_another_approach.txt)
> > > Approving !
> > 
> > 
> > I also agree the solution @MiguelCompany suggested was better, but we decided to proceed with the copy approach given the effort required, and also considering that the root of the problem (releasing the PDP mutex before completing an entire discovery operation, which might lead to inconsistent states apart from data races as the one we are dealing with here) would still remain unsolved. We also discussed that a possible solution to tackle the root of the problem would be to derive all discovery actions to a dedicated thread.
> > Regarding your proposal, I believe it is a bit risky to wait as some lower level resources might be blocked by that thread, leading to potential deadlocks. And two additional comments:
> > 
> > * I believe that (in remove_remote_participant) locking the PDP mutex should be done after calling wait (to avoid intraprocess deadlock).
> > * I also believe that a PDP instance could process more than one data P before processing a data uP, so I guess the complexity of this solution would need to grow.
> 
> Yeah, agree that it would be risky as a consequence of relying on a cond var.
> 
> A further `lock-free` approach I can think of would be that the thread executing `remove_remote_participant()` with the participant proxy that is being currently processed in `assign_remote_endpoints `, could leave a flag to true in PDPListener meaning that _“I am not removing the participant proxy now, as you are using it, but I notify you that when you finish the `assign_remote_endpoints() ` you will have to delete it on behalf of me”_ So, in that case, the same discovery thread could call `remove_remote_participant() ` if the flag is up, after executing the `assign_remote_endpoints() ` and then reset it. What do you think ?

That's an interesting approach we could further explore. The only caveat I see at the moment is that `remove_remote_participant` can also be called from places other than a `PDPListener`, like for example from the events thread when liveliness is lost.