[20176] Regenerate Fast DDS types due to Gen release v3.2.1
eProsima/Fast-DDS pull request #4229
Opened 2024-01-10 12:04 UTC by JesusPoderoso

## Description

This PR regenerate all repo types by running the script `utils/scripts/update_generated_code_from_idl.sh`. This is needed to introduce the (future) Fast DDS Gen release v3.2.1 changes in the (future) Fast DDS v2.13.1 release.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-01-10 15:01 UTC, Mario-DL submitted a review, later dismissed
LGTM with GreenCI

2024-01-11 06:11 UTC, EduPonz requested changes
There is a bug in Windows v141 which makes the `{0}` initialization of class member arrays with lots of elements to consume more memory above the roof, which makes the process crash. What we do is remove those manually

2024-01-11 06:11 UTC, EduPonz commented on examples/cpp/dds/FlowControlExample/FlowControlExample.h
> +    std::array<char, 600000> m_message{0};
```suggestion
    std::array<char, 600000> m_message;
```

2024-01-11 06:11 UTC, EduPonz commented on examples/cpp/dds/HelloWorldExampleSharedMem/HelloWorld.h
> +    std::array<char, 1024*1024> m_data{0};
```suggestion
    std::array<char, 1024*1024> m_data;
```

2024-01-11 08:22 UTC, JesusPoderoso commented
@richiprosima please test this

2024-01-11 10:59 UTC, EduPonz approved these changes

2024-01-11 15:18 UTC, merged