Add large data to Advanced config example
eProsima/Fast-DDS pull request #4233
Opened 2024-01-11 09:58 UTC by elianalf

## Description

This pr adds the possibility to send large data with the advanced configuration example. The user can define the size of the message that is sent.  

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-01-12 07:17 UTC, rsanchez15 requested changes

2024-01-12 07:17 UTC, rsanchez15 commented on examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationPublisher.cpp
> +    topic_ = participant_->create_topic(topic_name, "LargeData", TOPIC_QOS_DEFAULT);
```suggestion
    topic_ = participant_->create_topic(topic_name, type_.get_type_name(), TOPIC_QOS_DEFAULT);
```

2024-01-12 07:17 UTC, rsanchez15 commented on examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationPublisher.cpp
> +                      << "  SENT" << std::endl;
```suggestion
            std::cout << "Sample sent: " << hello_.message().data() << "  " << hello_.index() <<
                "  (" << static_cast<int>(hello_.data().size()) << " Bytes)"
                      << std::endl;
```

2024-01-12 07:17 UTC, rsanchez15 commented on examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationSubscriber.cpp
> +                static_cast<int>(hello_.data().size())  << "  RECEIVED" << std::endl;
```suggestion
            std::cout << "Sample received: " << hello_.message().data() << "  " << hello_.index() <<
                "  (" << static_cast<int>(hello_.data().size()) << " Bytes)"  << std::endl;
```

2024-01-12 07:17 UTC, rsanchez15 commented on examples/cpp/dds/AdvancedConfigurationExample/arg_configuration.h
> +      "  -t <topic_name> \t--topic=<topic_name>  \tTopic name (Default: LargeDataTopic)." },
```suggestion
      "  -t <topic_name> \t--topic=<topic_name>  \tTopic name (Default: AdvancedConfigurationTopic)." },
```

2024-01-12 07:17 UTC, rsanchez15 commented on examples/cpp/dds/AdvancedConfigurationExample/arg_configuration.h
> +      "  -m <num> \t--msg-size=<num>\tNumber of bytes sent as data in the message (Default 10)."},
```suggestion
      "  -m <num> \t--msg-size=<num>\tSize in bytes of the data to be sent (Default 10)."},
```

2024-01-12 07:17 UTC, rsanchez15 commented on examples/cpp/dds/AdvancedConfigurationExample/arg_configuration.h
> +      "  -t <topic_name> \t--topic=<topic_name>  \tTopic name (Default: LargeDataTopic)." },
```suggestion
      "  -t <topic_name> \t--topic=<topic_name>  \tTopic name (Default: AdvancedConfigurationTopic)." },
```

2024-01-12 08:37 UTC, rsanchez15 submitted a review, later dismissed

2024-01-12 09:19 UTC, EduPonz requested changes
I think we should state in the readme of the example that due to the sequence in the data type this example will not use data sharing

2024-01-12 09:53 UTC, EduPonz requested changes

2024-01-12 10:12 UTC, EduPonz approved these changes

2024-01-16 13:27 UTC, EduPonz commented
@richiprosima please test this

2024-01-16 16:00 UTC, elianalf commented
@richiprosima please test mac

2024-01-17 06:40 UTC, elianalf commented
@richiprosima please test mac

2024-01-17 10:00 UTC, merged