[20239] Make DataWriters always send the serialized key on keyed topics
eProsima/Fast-DDS pull request #4238
Opened 2024-01-12 09:08 UTC by Mario-DL

## Description

This PR corrects the behavior of the DataWriters on keyed topics. Currently, if the DataReader does not `expect_inline_qos`, then the DataWriter is not sending the key despite of publishing on a keyed topic.

This PR makes the DataWriter always send the key regardless of the configuration of the reader if the topic is keyed.

_Note: the builtin endpoints are retrieving the key in their listeners. In fact, its the first thing they do (`computeKey()`). It is true that they are the filling the `instancehandle` from the `PID_ENDPOINT_GUID` instead of the `PID_KEY_HASH` which could be arguable if we are strict, but in essence, both carry the same information, the complete `guid` of the entity_ 

@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-01-12 10:45 UTC, Mario-DL commented
Checked that the `topic keys feature` works without enforcing the `inline QoS` in the reader when using this branch

2024-01-19 08:32 UTC, Mario-DL commented
Before asking for the CI here, we should wait for https://github.com/eProsima/Fast-DDS/pull/4261 to be merged

2024-01-24 10:29 UTC, EduPonz requested changes

2024-01-24 10:33 UTC, Mario-DL commented on test/blackbox/common/BlackboxTestsKeys.cpp
> +    EXPECT_TRUE(writer_sends_inline_qos & writer_sends_pid_key_hash);
Nice catch !

2024-01-27 08:18 UTC, EduPonz commented
@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

2024-01-27 08:18 UTC, EduPonz commented
@Mergifyio rebase master

2024-01-27 08:29 UTC, EduPonz approved these changes

2024-01-29 06:58 UTC, JesusPoderoso commented
@richiprosima please test this

2024-02-02 06:33 UTC, merged