Type Object integration
eProsima/Fast-DDS pull request #4239
Opened 2024-01-12 09:19 UTC by JLBuenoLopez-eProsima

## Description

This PR integrates the new TypeObject support feature.

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-01-12 09:43 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2024-01-15 09:37 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2024-01-16 07:22 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2024-01-16 10:30 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2024-01-23 14:25 UTC, richiware requested changes

2024-01-25 11:44 UTC, JLBuenoLopez-eProsima commented on include/fastdds/dds/xtypes/type_representation/detail/dds_xtypes_typeobjectPubSubTypes.h
> +    //Register TypeObject representation in Fast DDS TypeObjectRegistry
The method implementation has a warning stating that there is no support for the TypeObject representation as it was disabled in the generated code.

2024-01-25 11:49 UTC, JLBuenoLopez-eProsima commented on src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterFactory.cpp
> +                eprosima::fastdds::dds::xtypes::TypeIdentifier type_id;
Good catch. The TypeIdentifier does not seem to be needed anymore.

2024-01-25 11:54 UTC, JLBuenoLopez-eProsima commented on src/cpp/fastrtps_deprecated/Domain.cpp
> +// bool Domain::registerDynamicType(
This file is going to be removed in Fast DDS 3.0.0 so nothing is required to be done.

2024-01-25 12:00 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2024-01-25 15:31 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2024-01-26 06:40 UTC, richiware requested changes

2024-01-26 06:40 UTC, richiware commented on test/blackbox/api/dds-pim/PubSubReader.hpp
> +#include <gtest/gtest.h>
Why do you move external includes at the end, not according to our coding style?

2024-01-26 07:03 UTC, richiware submitted a review, later dismissed
Ready when CI ready

2024-01-26 08:06 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2024-01-29 06:56 UTC, merged