[20257] Add a keyed fragmented change to the reader data instance only when its completed
eProsima/Fast-DDS pull request #4261
Opened 2024-01-19 08:29 UTC by Mario-DL

## Description

When a keyed fragmented change is completed, notify the data instance and add the change in that moment instead of adding the change when it is still not fully assembled. This PR also makes the Stateless/full readers  take the serialized key only from the fragment number `1`.  

@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A**New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

2024-01-19 17:46 UTC, Mario-DL commented
@richiprosima please test this

2024-01-23 07:16 UTC, EduPonz requested changes

2024-01-23 07:16 UTC, EduPonz commented on src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
> +    for ( auto instance_change = it->second->cache_changes.begin(); instance_change != it->second->cache_changes.end();
```suggestion
    for (auto instance_change = it->second->cache_changes.begin(); instance_change != it->second->cache_changes.end();
```

2024-01-23 07:27 UTC, EduPonz submitted a review, later dismissed

2024-01-23 07:34 UTC, Mario-DL commented
Docs CI [here](https://github.com/eProsima/Fast-DDS/actions/runs/7622449305)

2024-01-23 07:49 UTC, JesusPoderoso commented
@richiprosima please test this

2024-01-23 08:05 UTC, Mario-DL commented
Docs CI [here](https://github.com/eProsima/Fast-DDS/actions/runs/7622686311)

2024-01-23 09:11 UTC, Mario-DL commented
New run [her](https://github.com/eProsima/Fast-DDS/actions/runs/7623429704)

2024-01-23 11:58 UTC, EduPonz submitted a review, later dismissed

2024-01-24 10:14 UTC, Mario-DL commented
@richiprosima please test this

2024-01-24 10:59 UTC, EduPonz requested changes

2024-01-24 10:59 UTC, EduPonz commented on src/cpp/rtps/reader/StatefulReader.cpp
> +                        work_change->instanceHandle = c_InstanceHandle_Unknown;
```suggestion
                        work_change->instanceHandle.clear();
```

2024-01-24 10:59 UTC, EduPonz commented on src/cpp/rtps/reader/StatelessReader.cpp
> +                            work_change->instanceHandle = c_InstanceHandle_Unknown;
This should also be applied after the previous `copy_not_memcpy` call in this same function
```suggestion
                            work_change->instanceHandle.clear();
```

2024-01-24 11:00 UTC, EduPonz approved these changes

2024-01-25 06:44 UTC, Mario-DL commented
@richiprosima please test this

2024-01-26 12:51 UTC, JesusPoderoso commented
CI issues seem unrelated to the PR. Ready to merge!

2024-01-27 08:14 UTC, EduPonz approved these changes

2024-01-27 08:16 UTC, merged

2024-01-27 08:16 UTC, EduPonz commented
@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x