[20276] Synchronize calls to PDPListener::onNewCacheChangeAdded
eProsima/Fast-DDS pull request #4268
Opened 2024-01-22 07:59 UTC by EduPonz

## Description

This PR fixes a datarace in `PDPListener` that was causing assertions on Windows Debug. It does so by synchronizing the calls to `PDPListener::onNewCacheChangeAdded` via the use of a dedicated mutex.

@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- _N/A_: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_: Any new/modified methods have been properly documented using Doxygen. 
- [ ] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- _N/A_: New feature has been added to the `versions.md` file (if applicable).
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-01-22 11:36 UTC, EduPonz commented
@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

2024-01-22 17:19 UTC, EduPonz commented
@richiprosima please test this

2024-01-23 06:48 UTC, EduPonz commented
@richiprosima please test this

2024-01-23 19:45 UTC, EduPonz commented
@richiprosima please test mac test windows

2024-01-24 06:21 UTC, EduPonz commented
@richiprosima please test mac test windows

2024-01-24 07:56 UTC, MiguelCompany requested changes
Just one nit which does not require to re-run CI

2024-01-24 07:56 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
> +            // Only notified the DATA(p) if it is not a repeated one
```suggestion
            // Only process the DATA(p) if it is not a repeated one
```

2024-01-24 08:05 UTC, merged