[20306] Ignore 0x8007 if coming from other vendor
eProsima/Fast-DDS pull request #4291
Opened 2024-01-24 15:00 UTC by EduPonz

## Description

This PR fixes an interoperability issue introduced in #3733 occurring when a different vendor sends a DATA(p) which parameter list is to contain a parameter with PID 0x8007, which in Fast DDS is a custom PID (`PID_NETWORK_CONFIGURATION_SET`). When that happens, the deserialization in Fast DDS most likely fails of even worse gets a wrong interpretation.

Tested with [CycloneDDS ShapesDemo](https://github.com/atolab/dds-ishapes) and Fast DDS ShapesDemo (setting the `auto_fill_type_information` to `false`.

@Mergifyio backport 2.12.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_: Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- _N/A_: New feature has been added to the `versions.md` file (if applicable).
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-01-24 15:12 UTC, EduPonz commented
@richiprosima please test this

2024-01-24 15:42 UTC, MiguelCompany requested changes

2024-01-24 15:42 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
> +                        // TODO(eduponz): This is a workaround for the moment, as it is implicitly assuming
I'd put this as a `FASTDDS_TODO_BEFORE(2, 14)`

2024-01-24 15:42 UTC, MiguelCompany commented on test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
> +        1, 16, 54, 83, 136, 247, 149, 252, 47, 105, 174, 141, 0, 0, 1, 193,
```suggestion
        2, 0, 54, 83, 136, 247, 149, 252, 47, 105, 174, 141, 0, 0, 1, 193,
```

2024-01-24 17:26 UTC, EduPonz commented
@richiprosima please test this

2024-01-25 05:55 UTC, EduPonz commented
b336b07f2 had a windows warning on the test assertion due to signed vs unsigned comparison. This is fixed in 27bced52f. I'm only running the build part of just the windows CI for 27bced52f. To see the test results check b336b07f2 CI

2024-01-25 05:55 UTC, EduPonz commented
@richiprosima please test windows

2024-01-25 08:38 UTC, MiguelCompany approved these changes

2024-01-25 11:29 UTC, merged

2024-01-27 08:37 UTC, EduPonz commented
@Mergifyio backport 2.12.x