Add serialization for Log::Kind to ostream
eProsima/Fast-DDS pull request #4292
Opened 2024-01-25 06:29 UTC by LuciaEchevarria99

## Add serialization for Log::Kind to ostream

### Description
This commit introduces a new ostream serialization function for the Log::Kind enumeration, allowing seamless output to ostream objects. The function includes a switch statement of Log::Kind values to their corresponding string representations (INFO, WARNING, ERROR).

2024-01-25 06:40 UTC, EduPonz requested changes
We should use this in `LogConsumer::print_header`

2024-01-27 07:57 UTC, EduPonz commented
@LuciaEchevarria99 please address uncrustify failure

2024-02-07 13:36 UTC, EduPonz approved these changes
LGTM with green CI 🏅

2024-02-08 11:15 UTC, JesusPoderoso commented
@mergifyio rebase

2024-02-08 11:16 UTC, JesusPoderoso commented
@richiprosima please test this

2024-02-09 06:59 UTC, JesusPoderoso commented
@richiprosima please test mac please test linux

2024-02-10 06:42 UTC, merged