[19452] Include CI workflows for 3.0.x-devel branch
eProsima/Fast-DDS pull request #4294
Opened 2024-01-25 09:28 UTC by JLBuenoLopez-eProsima

## Description

This PR includes two CI jobs:

* Rebase nightly against master to ensure latest changes are included
* Windows nightly job ensuring that the branch keeps building with the latest changes

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [N/A] The code follows the style guidelines of this project. 
- [N/A] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [N/A] Any new/modified methods have been properly documented using Doxygen. 
- [N/A] Changes are ABI compatible. 
- [N/A] Changes are API compatible. 
- [N/A] New feature has been added to the `versions.md` file (if applicable).
- [N/A] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [N/A] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-01-26 09:41 UTC, elianalf requested changes

2024-01-26 09:41 UTC, elianalf commented on .github/workflows/rebase-3.0.x-devel.yaml
> +      # Step 3: Rebase
```suggestion
      # Step 2: Rebase
```

2024-01-26 09:41 UTC, elianalf commented on .github/workflows/rebase-3.0.x-devel.yaml
> +      # Step 4: Push
```suggestion
      # Step 3: Push
```

2024-01-26 09:47 UTC, elianalf approved these changes

2024-01-29 11:26 UTC, EduPonz approved these changes

2024-01-29 11:27 UTC, merged