[20307] Ignore custom PIDs defined in Fast DDS when they are received from other vendors
eProsima/Fast-DDS pull request #4299
Opened 2024-01-26 11:22 UTC by EduPonz

## Description

With this PR, Fast DDS ignores all custom PIDs defined in Fast DDS when they are received from other vendors.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- _N/A_: New feature has been added to the `versions.md` file (if applicable).
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- _N/A_: Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-01-27 07:52 UTC, EduPonz commented
@richiprosima please test this

2024-01-28 07:22 UTC, EduPonz commented
@richiprosima please test mac

2024-01-29 13:00 UTC, MiguelCompany requested changes

2024-01-29 13:00 UTC, MiguelCompany commented on test/unittest/rtps/common/VendorIdTests.cpp
> +// Copyright 2022 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
// Copyright 2024 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2024-01-29 13:00 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
> +    auto param_process = [this, &network, &is_shm_transport_available, &should_filter_locators, &source_vendor_id](
```suggestion
    auto param_process = [this, &network, &is_shm_transport_available, &should_filter_locators, source_vendor_id](
```

2024-01-29 13:00 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ReaderProxyData.cpp
> +                                (fastdds::rtps::c_VendorId_rti_connext != source_vendor_id))
```suggestion
                        // Ignore custom PID when coming from other vendors
                        if (c_VendorId_eProsima != source_vendor_id)
```

2024-01-29 13:00 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/WriterProxyData.cpp
> +                                (fastdds::rtps::c_VendorId_rti_connext != source_vendor_id))
```suggestion
                        // Ignore custom PID when coming from other vendors
                        if (c_VendorId_eProsima != source_vendor_id)
```

2024-01-29 13:00 UTC, MiguelCompany commented on src/cpp/fastdds/core/policy/ParameterList.cpp
> +                        if (pid == PID_RELATED_ENTITY_GUID)
```suggestion
                        if (pid == PID_CUSTOM_RELATED_ENTITY_GUID)
```

2024-01-29 13:00 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ReaderProxyData.cpp
> +                        if (c_VendorId_eProsima != source_vendor_id)
We also interoperate with RTI connext in this one

2024-01-29 13:00 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/WriterProxyData.cpp
> +                        if (c_VendorId_eProsima != source_vendor_id)
We also interoperate with RTI connext in this one

2024-01-29 13:00 UTC, MiguelCompany commented on src/cpp/rtps/messages/MessageReceiver.cpp
> +                    reader->processHeartbeatMsg(writerGUID, HBCount, firstSN, lastSN, finalFlag, livelinessFlag,
Please look for other calls to this method. I',m pretty sure we are calling this directly for intra-process communications.

Same applies to the other methods where the vendor id argument has been added

2024-01-29 13:00 UTC, MiguelCompany commented on test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
>  TEST(BuiltinDataSerializationTests, other_vendor_parameter_list_with_custom_pids)
Would be nice to have a test for the PIDs interoperable with RTI connext

2024-01-31 09:13 UTC, MiguelCompany requested changes

2024-01-31 09:13 UTC, MiguelCompany commented on src/cpp/rtps/DataSharing/DataSharingListener.cpp
> +                                ch.sequenceNumber), c_VendorId_eProsima);
```suggestion
                    reader_->processGapMsg(pool->writer(), last_sequence + 1,
                                SequenceNumberSet_t(ch.sequenceNumber), c_VendorId_eProsima);
```

2024-01-31 09:13 UTC, MiguelCompany commented on src/cpp/rtps/DataSharing/DataSharingListener.cpp
> +                                ch.sequenceNumber), c_VendorId_eProsima);
Do the same as in my previous suggestion, please

2024-02-01 06:50 UTC, MiguelCompany approved these changes

2024-02-23 21:41 UTC, EduPonz commented
@Mergifyio rebase

2024-02-23 21:43 UTC, EduPonz commented
@Mergifyio rebase master

2024-02-24 06:29 UTC, EduPonz commented
@richiprosima please test this

2024-02-26 06:39 UTC, MiguelCompany approved these changes

2024-02-26 06:42 UTC, merged