[20262] Add non-throwing getters for socket info
eProsima/Fast-DDS pull request #4319
Opened 2024-01-29 15:15 UTC by jepemi

## Description

In some instances, requesting server info after client connection caused exceptions (transport endpoint is not connected). We now also use ASIO's non-throwing methods for this request, ensuring any errors are appropriately handled.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- N/A New feature has been added to the `versions.md` file (if applicable).
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-01-30 08:42 UTC, MiguelCompany requested changes

2024-01-30 08:42 UTC, MiguelCompany commented on src/cpp/rtps/transport/TCPChannelResourceBasic.h
> +    // Throwing asio calls
```suggestion
    // Throwing asio calls
    asio::ip::tcp::endpoint remote_endpoint() const override;
    asio::ip::tcp::endpoint local_endpoint() const override;

    // Non-throwing asio calls
```

2024-01-30 08:42 UTC, MiguelCompany commented on src/cpp/rtps/transport/TCPTransportInterface.cpp
> +        }
I would have a new method `Locator remote_endpoint_to_locator(channel)` that performs all these steps.

2024-01-30 08:42 UTC, MiguelCompany commented on src/cpp/rtps/transport/TCPTransportInterface.cpp
> +                            endpoint_to_locator(channel->remote_endpoint(), remote_locator);
Also use the new method here ?

2024-01-30 08:42 UTC, MiguelCompany commented on src/cpp/rtps/transport/TCPChannelResource.h
> +
Please document the new methods with Doxygen

2024-01-31 07:11 UTC, jepemi commented
@richiprosima please test this

2024-02-06 15:45 UTC, MiguelCompany requested changes

2024-02-06 15:45 UTC, MiguelCompany commented on src/cpp/rtps/transport/TCPTransportInterface.cpp
> +        remote_locator = remote_endpoint_to_locator(channel);
We should perform this call inside the `if (channel)` below

2024-02-07 07:25 UTC, MiguelCompany approved these changes

2024-02-08 11:14 UTC, JesusPoderoso commented
@mergifyio rebase

2024-02-08 11:14 UTC, JesusPoderoso commented
@richiprosima please test this

2024-02-08 17:13 UTC, merged