[20227] Prevent index overflow and correctly assert the end iterator in DataSharing
eProsima/Fast-DDS pull request #4321
Opened 2024-01-29 16:50 UTC by Mario-DL

## Description

When a DataSharing compatible publisher and subscriber were launched at high frequency (publication interval set to `0`), it happened two different issues:
* The current `notified_end` of the segment iterator was being updated before being actually checked, making an `assert()` compare two different versions of this iterator.
* On the other hand, unrelated with the previous observation, a corner case of advancing twice the `next_payload_` iterator could occur.

Apart from the included test, in order to reproduce the first issue it is enough to launch a `BasicConfigurationExample` with a `bounded` type and no sleep between`writes()`. Launching, killing and relaunching the subscriber should trigger the `assertion`.
For reproducing the second issue, launch the subscriber first and then the publisher, a `SIGSEV` will be triggered in `20 seconds` or so.

This PR includes to fixes that mitigate the problem.
The idea of the test is that if in 20 seconds we have not crashed by some of the above issues, we give the test as passed.

**Important note** It was noticed that enabling all the verbosity messages in the test, makes the test not work properly under `colcon` since the `timeout` notification of the `SubscriberModule.cpp` condition variable is never fired. It seems that the test stresses the cpu and the timeout notification is lost. However, if the `python3` is directly invoked from a terminal (outside colcon), then there is no problem even if all the logs are enabled.

@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- [X ] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-01-30 11:58 UTC, Mario-DL commented
@richiprosima please test linux

2024-01-30 11:58 UTC, Mario-DL commented
@richiprosima please test mac

2024-01-30 11:58 UTC, Mario-DL commented
@richiprosima please test discovery_server

2024-01-30 18:23 UTC, Mario-DL commented
@richiprosima please test mac

2024-02-14 13:39 UTC, EduPonz requested changes
NIT not requiring CI

2024-02-14 13:39 UTC, EduPonz commented on test/dds/communication/SubscriberMain.cpp
> +    bool succeed_on_timeout = false;
Add to the arguments comment above, same for timeout

2024-02-15 06:38 UTC, Mario-DL commented
@richiprosima please test this

2024-02-16 09:34 UTC, EduPonz approved these changes

2024-02-16 09:35 UTC, EduPonz commented
@richiprosima please test mac

2024-02-16 13:10 UTC, Mario-DL commented
@richiprosima please test mac

2024-02-16 14:16 UTC, Mario-DL commented
@richiprosima please test mac

2024-02-19 08:25 UTC, Mario-DL commented
@richiprosima please test mac

2024-02-19 13:18 UTC, Mario-DL commented
@richiprosima please test mac

2024-02-19 16:30 UTC, Mario-DL commented
@richiprosima please test mac

2024-02-19 18:51 UTC, Mario-DL commented
@richiprosima please test mac

2024-02-20 07:59 UTC, JesusPoderoso commented
CI issues unrelated to the PR. Ready to merge!

2024-02-20 08:13 UTC, merged

2024-02-20 08:13 UTC, MiguelCompany commented
@Mergifyio backport 2.12.x 2.10.x 2.6.x