[20272] Update Fast DDS types with Fast DDS Gen to include <cstdint> in v1 types
eProsima/Fast-DDS pull request #4340
Opened 2024-01-31 08:44 UTC by Mario-DL

## Description

This PR updates the Fast DDS types with Fast DDS Gen (compiled with the https://github.com/eProsima/Fast-DDS-Gen/pull/290 fix) that includes the `<cstdint>` header in v1 types. It is required to correctly compile against Fast CDR v1 with `gcc 13.2.0` (https://github.com/eProsima/Fast-DDS/pull/4337).

I checked the compilation in an `Ubuntu 24.04` (`gcc 13.2.0`) with both, tests enabled and disabled, and it solves the issue.

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-02-08 12:08 UTC, MiguelCompany requested changes

2024-02-08 12:08 UTC, MiguelCompany commented on examples/cpp/dds/FlowControlExample/FlowControlExample.h
> +    std::array<char, 600000> m_message{0};
We should revert this change so this can build in VS 2017

2024-02-08 12:18 UTC, MiguelCompany commented
@mergifyio rebase

2024-02-08 12:20 UTC, MiguelCompany approved these changes

2024-02-08 12:20 UTC, MiguelCompany commented
@richiprosima Please test this

2024-02-09 06:53 UTC, JesusPoderoso commented
@richiprosima please test this

2024-02-09 07:46 UTC, MiguelCompany commented
I think we can merge this, but I also think we can fix some of the uncrustify failures in the code generator.
At least the ones in the doxygen comments indentation

2024-02-09 07:54 UTC, merged