[20318] Fix and refactor Windows Github CI
eProsima/Fast-DDS pull request #4356
Opened 2024-02-07 09:55 UTC by EduPonz

## Description

This PR:
* Fixes Windows CI in Github (this has implied disabling PKCS#11 tests for now)
* Refactors the workflow to use more of eProsima-CI feature
* Builds with warnings as errors

@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- _N/A_: The code follows the style guidelines of this project. 
- _N/A_: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_: Any new/modified methods have been properly documented using Doxygen. 
- _N/A_: Changes are ABI compatible. 
- _N/A_: Changes are API compatible. 
- _N/A_: New feature has been added to the `versions.md` file (if applicable).
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-02-07 10:06 UTC, richiware approved these changes

2024-02-07 13:44 UTC, richiware requested changes

2024-02-07 13:44 UTC, richiware commented on .github/workflows/config/default_ci.meta
> +            - "-DEPROSIMA_EXTRA_CMAKE_CXX_FLAGS=/MP /WX"
Not following the order

2024-02-07 13:44 UTC, richiware commented on .github/workflows/config/nightly.meta
> +            - "-DEPROSIMA_EXTRA_CMAKE_CXX_FLAGS=/MP /WX"
Not following the order

2024-02-07 13:44 UTC, richiware commented on .github/workflows/reusable-windows-ci.yml
> +            Set-Item -Force -Path "Env:PATH" -Value "$Env:PATH;$Env:ProgramW6432\OpenSSL"
```suggestion
            Set-Item -Force -Path "Env:PATH" -Value "$Env:PATH;$Env:ProgramW6432\OpenSSL\bin"
```

2024-02-07 13:44 UTC, richiware commented on .github/workflows/reusable-windows-ci.yml
> +            Set-Item -Force -Path "Env:PATH" -Value "$Env:PATH;$Env:ProgramW6432\OpenSSL-Win"
```suggestion
            Set-Item -Force -Path "Env:PATH" -Value "$Env:PATH;$Env:ProgramW6432\OpenSSL-Win\bin"
```

2024-02-07 13:44 UTC, richiware commented on .github/workflows/reusable-windows-ci.yml
> +            Set-Item -Force -Path "Env:PATH" -Value "$Env:PATH;$Env:ProgramW6432\OpenSSL-Win64"
```suggestion
            Set-Item -Force -Path "Env:PATH" -Value "$Env:PATH;$Env:ProgramW6432\OpenSSL-Win64\bin"
```

2024-02-07 13:49 UTC, EduPonz commented on .github/workflows/config/default_ci.meta
> +            - "-DEPROSIMA_EXTRA_CMAKE_CXX_FLAGS=/MP /WX"
d6206f7

2024-02-07 13:49 UTC, EduPonz commented on .github/workflows/config/nightly.meta
> +            - "-DEPROSIMA_EXTRA_CMAKE_CXX_FLAGS=/MP /WX"
d6206f7

2024-02-07 13:50 UTC, EduPonz commented on .github/workflows/reusable-windows-ci.yml
> +            Set-Item -Force -Path "Env:PATH" -Value "$Env:PATH;$Env:ProgramW6432\OpenSSL"
I dropped the commit

2024-02-07 13:50 UTC, EduPonz commented on .github/workflows/reusable-windows-ci.yml
> +            Set-Item -Force -Path "Env:PATH" -Value "$Env:PATH;$Env:ProgramW6432\OpenSSL-Win"
I dropped the commit

2024-02-07 13:50 UTC, EduPonz commented on .github/workflows/reusable-windows-ci.yml
> +            Set-Item -Force -Path "Env:PATH" -Value "$Env:PATH;$Env:ProgramW6432\OpenSSL-Win64"
I dropped the commit

2024-02-07 13:53 UTC, richiware approved these changes

2024-02-08 09:52 UTC, JesusPoderoso approved these changes

2024-02-08 09:56 UTC, richiware approved these changes

2024-02-08 11:02 UTC, merged

2024-02-08 11:23 UTC, MiguelCompany commented
@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x