[20335] DynamicTypeBuilderFactoryImpl::create_type_w_type_object implementation
eProsima/Fast-DDS pull request #4368
Opened 2024-02-09 09:49 UTC by JLBuenoLopez-eProsima

## Description

This PR implements `DynamicTypeBuilderFactoryImpl::create_type_w_type_object` method. It also uses this feature to fix the DDS SQL Filter and its tests.

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-02-12 10:39 UTC, richiware requested changes

2024-02-12 10:39 UTC, richiware commented on src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderFactoryImpl.cpp
> +            ret_val = create_string_type(type_identifier.string_sdefn().bound())->build();
Detect bound is zero and set LENGTH_UNLIMITED.

2024-02-12 10:39 UTC, richiware commented on src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderFactoryImpl.cpp
> +            ret_val = create_string_type(type_identifier.string_ldefn().bound())->build();
Detect bound is zero and set LENGTH_UNLIMITED.

2024-02-12 10:39 UTC, richiware commented on src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderFactoryImpl.cpp
> +            TypeDescriptorImpl small_array_descriptor {TK_ARRAY, ""};
Why don't you use `create_array_type()`.

2024-02-12 10:39 UTC, richiware commented on src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderFactoryImpl.cpp
> +                ret_val.reset();
break?

2024-02-12 10:39 UTC, richiware commented on src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderFactoryImpl.cpp
> +        ret_val->try_construct_kind(TryConstructKind::TRIM);
This line will be never called due to the previous condition.

2024-02-12 10:39 UTC, richiware commented on src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderImpl.cpp
> +            for (size_t count {0}; ret_value && count << verbatim_.size(); ++count)
```suggestion
            for (size_t count {0}; ret_value && count < verbatim_.size(); ++count)
```

2024-02-12 11:59 UTC, JLBuenoLopez-eProsima commented on src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterFactory.cpp
> +        const std::shared_ptr<xtypes::TypeIdentifier> type,
This parameter is only used as input and it is not being modified within the method.

2024-02-15 07:10 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2024-02-15 11:09 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2024-02-15 11:56 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2024-02-15 15:43 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2024-02-16 10:34 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2024-02-20 08:12 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test this

2024-02-20 09:18 UTC, richiware requested changes

2024-03-25 14:52 UTC, adriancampo approved these changes
LGTM. Waiting for CI

2024-03-26 07:34 UTC, JLBuenoLopez-eProsima commented on src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterFactory.cpp
> +                if (nullptr != dyn_type)
@richiware I am going to apply this suggestion correctly. This suggestion just broke the CFT feature :sweat_smile: 

```suggestion
                if (dyn_type)
```

@adriancampo FYI

2024-03-27 15:33 UTC, merged