[20492] OpenOutputChannel / CloseOutputChannel that receive a LocatorSelectorEntry
eProsima/Fast-DDS pull request #4411
Opened 2024-02-20 16:04 UTC by jepemi

## Description

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- N/A Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- N/A New feature has been added to the `versions.md` file (if applicable).
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 
    
- N/A Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-02-28 10:06 UTC, MiguelCompany requested changes

2024-02-28 10:06 UTC, MiguelCompany commented on include/fastdds/rtps/transport/TransportInterface.h
> +            const fastrtps::rtps::LocatorSelectorEntry&);
Add `#include <fastdds/rtps/common/LocatorSelectorEntry.hpp>`

2024-02-28 10:06 UTC, MiguelCompany commented on src/cpp/rtps/transport/TransportInterface.cpp
> +#include <fastdds/rtps/common/LocatorSelector.hpp>
```suggestion
#include <fastdds/rtps/common/LocatorSelectorEntry.hpp>
```

2024-02-28 10:50 UTC, MiguelCompany requested changes

2024-02-28 10:50 UTC, MiguelCompany commented on include/fastdds/rtps/transport/TransportInterface.h
> +     * @return true if the channel was correctly closed or if it was already closed.
```suggestion
```

2024-02-28 10:53 UTC, MiguelCompany submitted a review, later dismissed

2024-02-28 11:58 UTC, MiguelCompany submitted a review, later dismissed
LGTM with green CI

2024-03-05 11:27 UTC, MiguelCompany approved these changes

2024-03-05 11:27 UTC, MiguelCompany commented on include/fastdds/rtps/transport/TransportInterface.h
> +     * @param locator_selector_entry Locator selector entry with the remote participant's locators.
```suggestion
     * @param locator_selector_entry Locator selector entry with the remote entity locators.
```

2024-03-05 11:27 UTC, MiguelCompany commented on include/fastdds/rtps/transport/TransportInterface.h
> +     * @param locator_selector_entry Locator selector entry with the remote participant's locators.
```suggestion
     * @param locator_selector_entry Locator selector entry with the remote entity locators.
```

2024-03-05 11:27 UTC, MiguelCompany commented on src/cpp/rtps/transport/TransportInterface.cpp
> +
```suggestion

```

2024-03-05 11:37 UTC, MiguelCompany requested changes
Accidentally approved

2024-03-05 11:55 UTC, MiguelCompany approved these changes

2024-03-05 19:57 UTC, EduPonz commented
@richiprosima please test this

2024-03-06 07:32 UTC, EduPonz commented
@richiprosima please test this

2024-03-06 07:36 UTC, MiguelCompany approved these changes
LGTM with green CI

2024-03-06 08:47 UTC, EduPonz commented
@richiprosima please test this

2024-03-06 08:48 UTC, MiguelCompany approved these changes

2024-03-06 17:27 UTC, merged