[20415] Update APIs in video performance tests
eProsima/Fast-DDS pull request #4464
Opened 2024-02-28 16:13 UTC by elianalf

## Description

This PR substitutes the old APIs with new ones in supports files for video performance tests.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- N/A Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- N/A Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- N/A New feature has been added to the `versions.md` file (if applicable).
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 
    
- N/A Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-03-01 10:28 UTC, JesusPoderoso requested changes
A couple of NITS.
Please, consider addressing the linter issue.

2024-03-01 10:28 UTC, JesusPoderoso commented on test/performance/video/VideoTestPublisher.cpp
>      }
I would keep the pid logic here (internal jenkins CI purposes)

2024-03-01 10:28 UTC, JesusPoderoso commented on test/performance/video/VideoTestSubscriber.hpp
> +    GMainLoop* gmain_loop_;     // GLib's Main Loop
```suggestion
    guint source_id_;          // To control the GSource
    GMainLoop* gmain_loop_;    // GLib's Main Loop
```

2024-03-01 10:34 UTC, JesusPoderoso commented on test/performance/video/VideoTestPublisher.cpp
> +    DomainParticipantQos participant_qos;
> I would keep the pid logic here (internal jenkins CI purposes)

```suggestion
    auto forced_domain = m_forcedDomain;
    if (m_forcedDomain >= 0)
    {
        forced_domain = m_forcedDomain;
    }
    else
    {
        forced_domain = pid % 230;
    }
    DomainParticipantQos participant_qos;
```

2024-03-01 10:34 UTC, JesusPoderoso commented on test/performance/video/VideoTestPublisher.cpp
>          }
> I would keep the pid logic here (internal jenkins CI purposes)

remove displayed code, and add:

```
mp_participant = DomainParticipantFactory::get_instance()->create_participant_with_profile(forced_domain,
                            participant_profile_name);
```

2024-03-01 10:34 UTC, JesusPoderoso commented on test/performance/video/VideoTestPublisher.cpp
> +        }
> I would keep the pid logic here (internal jenkins CI purposes)

```suggestion
        mp_participant = DomainParticipantFactory::get_instance()->create_participant(
            forced_domain, participant_qos);
```

2024-03-01 10:37 UTC, JesusPoderoso commented
This should be also addressed in the `test/performance/video/VideoTestSubscriber.cpp` file

2024-03-05 08:08 UTC, elianalf commented
@richiprosima please test this

2024-03-05 08:10 UTC, JesusPoderoso approved these changes
LGTM

2024-03-05 15:13 UTC, merged