[20542] Improve CI version management
eProsima/Fast-DDS pull request #4480
Opened 2024-02-29 16:03 UTC by JesusPoderoso

## Description

This PR unifies the CI in all workflows to follow this behavior:
- Trigger CI in all pull request no matter wich HEAD branch is set
- Trigger CI in pushes whose HEAD is a supported branch (or master)

The following PRs are the counter part in the supported branches:
- #TODO
- #TODO
- #TODO

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- **N/A** The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- **N/A** Changes are ABI compatible. 
- **N/A** Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-03-05 06:37 UTC, elianalf submitted a review, later dismissed

2024-03-05 07:33 UTC, JesusPoderoso commented
@richiprosima please test this

2024-03-05 16:21 UTC, elianalf commented on .github/workflows/nightly-mac-ci.yml
> +      fastdds-branch: '${{ matrix.fastdds-branch }}'
```suggestion
      fastdds-branch: ${{ matrix.fastdds-branch }}
```

2024-03-06 07:54 UTC, elianalf submitted a review, later dismissed

2024-03-06 14:24 UTC, elianalf approved these changes

2024-03-06 14:45 UTC, EduPonz requested changes
As agreed, please remove all `push` events

2024-03-06 14:45 UTC, EduPonz commented on .github/workflows/documentation-tests.yaml
Remove push event here please

2024-03-06 14:45 UTC, EduPonz commented on .github/workflows/sanitizer-tests.yaml
Rename to address-sanitizers

2024-03-06 14:45 UTC, EduPonz commented on .github/workflows/thread-sanitizer.yaml
Add cron here

2024-03-06 15:04 UTC, EduPonz submitted a review, later dismissed

2024-03-06 15:07 UTC, EduPonz approved these changes

2024-03-06 15:08 UTC, merged