[20542] Fix CI version management
eProsima/Fast-DDS pull request #4482
Opened 2024-02-29 16:24 UTC by JesusPoderoso

## Description

This PR unifies the CI in all workflows to follow this behavior:

- Trigger CI in all pull request no matter wich HEAD branch is set
- Trigger CI in pushes whose HEAD is a supported branch (or master)

master related PR:
- #4480 

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- **N/A** The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- **N/A** Changes are ABI compatible. 
- **N/A** Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-03-05 07:01 UTC, elianalf requested changes

2024-03-05 07:01 UTC, elianalf commented on .github/workflows/sanitizer-tests.yaml
[Line 9](https://github.com/eProsima/Fast-DDS/pull/4482/files#diff-37fd8971cb880bd169034bc59986b197ec187bd7193ef6edfd92a85d5e40ba07R9) and [line 132](https://github.com/eProsima/Fast-DDS/pull/4482/files#diff-37fd8971cb880bd169034bc59986b197ec187bd7193ef6edfd92a85d5e40ba07R132) should be `2.12.x`

2024-03-05 07:37 UTC, JesusPoderoso commented on .github/workflows/sanitizer-tests.yaml
I think so, yes. Lets discuss it with the team

2024-03-05 07:37 UTC, JesusPoderoso commented
@richiprosima please test this

2024-03-06 14:24 UTC, elianalf submitted a review, later dismissed

2024-03-08 07:46 UTC, elianalf approved these changes

2024-03-11 15:47 UTC, elianalf commented
@richiprosima please test linux

2024-03-11 15:47 UTC, elianalf submitted a review, later dismissed

2024-03-13 23:03 UTC, JesusPoderoso commented
Documentation Manual CI run [here](https://github.com/eProsima/Fast-DDS/actions/runs/8272706465)
Consider Ready to merge if passes, it is depending on this documentation PR:
- eProsima/Fast-DDS-docs#727

2024-03-14 06:38 UTC, merged