Refs #20542: Fix CI version management
eProsima/Fast-DDS pull request #4483
Opened 2024-02-29 16:27 UTC by JesusPoderoso

## Description

This PR unifies the CI in all workflows to follow this behavior:

- Trigger CI in all pull request no matter wich HEAD branch is set
- Trigger CI in pushes whose HEAD is a supported branch (or master)

master related PR:
- #4480 

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- **N/A** The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- **N/A** Changes are ABI compatible. 
- **N/A** Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-03-05 07:22 UTC, elianalf requested changes

2024-03-05 07:22 UTC, elianalf commented on .github/workflows/sanitizer-tests.yaml
[line 131](https://github.com/eProsima/Fast-DDS/pull/4483/files#diff-37fd8971cb880bd169034bc59986b197ec187bd7193ef6edfd92a85d5e40ba07R131) should be 2.10.x

2024-03-05 07:36 UTC, JesusPoderoso commented
@richiprosima please test this

2024-03-07 06:45 UTC, MiguelCompany commented
@JesusPoderoso Would you mind resolving the conflicts here ?

2024-03-07 07:06 UTC, MiguelCompany approved these changes

2024-03-08 12:04 UTC, MiguelCompany commented
@mergifyio rebase

2024-03-08 14:06 UTC, merged