[20592] Fix hidden overloaded virtual methods
eProsima/Fast-DDS pull request #4516
Opened 2024-03-06 09:29 UTC by EduPonz

## Description

Before this PR, compiling with GCC option `-Woverloaded-virtual` resulted in compilation warnings due to overloaded virtual methods being hidden in derived classes that do not override all the parent's overloads. This PR:

1. Fixes all those warnings
2. Adds more warning reporting options GCC in Ubuntu CI on Github

@Mergifyio backport 2.13.x 2.12.x 2.10.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- _N/A_: The code follows the style guidelines of this project. 
- _N/A_: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_: Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- _N/A_: New feature has been added to the `versions.md` file (if applicable).
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-03-07 09:10 UTC, EduPonz commented
@richiprosima please test this

2024-03-11 13:49 UTC, MiguelCompany requested changes
Windows related [warning](http://jenkins.eprosima.com:8080/job/fastdds_windows/label=windows-secure,toolset=v142/5890/msbuild/): `'eprosima::fastrtps::rtps::PDP::announceParticipantState': ambiguous call to overloaded function`

See related suggestion below

2024-03-12 10:39 UTC, EduPonz commented on src/cpp/rtps/builtin/discovery/participant/PDPClient.h
> +
431a3fc

2024-03-12 10:40 UTC, EduPonz commented
@richiprosima please test this

2024-03-12 11:03 UTC, MiguelCompany submitted a review, later dismissed
LGTM with green CI

2024-03-20 06:19 UTC, EduPonz commented
@richiprosima please test this

2024-03-20 11:32 UTC, EduPonz commented
@richiprosima please test windows test mac

2024-03-20 18:48 UTC, EduPonz commented
@Mergifyio backport 2.13.x 2.10.x 2.6.x

2024-03-20 18:48 UTC, merged