[20566] Migrate classes from include/fastrtps to fastdds
eProsima/Fast-DDS pull request #4518
Opened 2024-03-06 10:45 UTC by elianalf

## Description

This PR migrates the following classes from include/fastrtps to fastdds:
Migrate fastrtps/attributes/TopicAttributes
Migrate fastrtps/utils/collections
Migrate IPFinder
Migrate IPLocator
Migrate fixed_size_bitmap
Migrate md5
Migrate TimedConditionVariable
Migrate TimedMutex

## Contributor Checklist
- N/A Commit messages follow the project guidelines. 
- N/A The code follows the style guidelines of this project. 
- N/A Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- N/A Any new/modified methods have been properly documented using Doxygen. 
- ❌ Changes are ABI compatible. 
- ❌ Changes are API compatible. 
- N/A New feature has been added to the `versions.md` file (if applicable).
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 
    
- N/A Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-03-07 10:35 UTC, elianalf commented
Documentation job is failing because this branch has been rebased on the top of [
[20569] Migrate DLL API exporter and auto linkage to fastdds](https://github.com/eProsima/Fast-DDS/pull/4500), consequently it ereditated all the changes. The job uses the 3.0.x-devel branch of Fast DDS docs which doesn't have yet those changes, once the [docs Migrate DLL API exporter to fastdds](https://github.com/eProsima/Fast-DDS-docs/pull/718) will be merged, the job must run again. This will probably apply to asan job as well for discovery server branch.

2024-03-12 10:22 UTC, EduPonz requested changes

2024-03-12 10:22 UTC, EduPonz commented on include/fastdds/utils/IPLocator.h
Migrate namespace

2024-03-12 10:22 UTC, EduPonz commented on include/fastdds/utils/collections/ResourceLimitedContainerConfig.hpp
Migrate namespace

2024-03-12 10:22 UTC, EduPonz commented on include/fastdds/utils/collections/ResourceLimitedVector.hpp
Migrate namespace

2024-03-12 10:22 UTC, EduPonz commented on include/fastdds/utils/TimedConditionVariable.hpp
Migrate namespace

2024-03-12 10:22 UTC, EduPonz commented on include/fastdds/utils/TimedMutex.hpp
Migrate namespace

2024-03-12 10:22 UTC, EduPonz commented on include/fastdds/utils/fixed_size_bitmap.hpp
Migrate namespace

2024-03-12 10:22 UTC, EduPonz commented on src/cpp/statistics/types/monitorservice_typesPubSubTypes.h
Do not uncrustify generated code

2024-03-12 10:22 UTC, EduPonz commented on src/cpp/statistics/types/typesPubSubTypes.h
Do not uncrustify generated code. Applies to more places

2024-03-12 10:29 UTC, elianalf commented on include/fastdds/rtps/attributes/TopicAttributes.h
We were not changing namespaces until now, I thought it would have been a separated task. I will do it

2024-03-12 10:36 UTC, elianalf commented on include/fastdds/rtps/attributes/TopicAttributes.h
We were not changing namespaces unitl no, I thought it would have been an another task. I will do it

2024-03-12 14:20 UTC, EduPonz requested changes

2024-03-12 14:20 UTC, EduPonz commented on examples/cpp/dds/ContentFilteredTopicExample/HelloWorldTypeObject.cxx
Leave all generated code as it was. Also, we need a Fast DDS Gen PR to address this changes and use it to regenerate types in this PR.

2024-03-12 14:51 UTC, elianalf commented on examples/cpp/dds/ContentFilteredTopicExample/HelloWorldTypeObject.cxx
We will also need docs PR and a Discovery-Server PR related to this

2024-03-13 12:05 UTC, elianalf commented
`asan-discovery-server` is failing because the job uses the discovery-server default 3.0.x-devel branch instead of the corresponding branch. I will open a PR to modify it and then I will rebase

2024-03-22 16:17 UTC, EduPonz approved these changes

2024-03-22 16:24 UTC, EduPonz commented
* macOS CI [here](https://github.com/eProsima/Fast-DDS/actions/runs/8393314348)
* Ubuntu CI [here](https://github.com/eProsima/Fast-DDS/actions/runs/8393337823)
* Windows CI [here](https://github.com/eProsima/Fast-DDS/actions/runs/8393349708)
* Docs CI [here](https://github.com/eProsima/Fast-DDS/actions/runs/8393362560)
* ASan test (for DS test) [here](https://github.com/eProsima/Fast-DDS/actions/runs/8393377474)

2024-03-25 10:05 UTC, elianalf commented
Docs CI passed [here](https://github.com/eProsima/Fast-DDS/actions/workflows/documentation-tests.yaml)

2024-03-25 11:29 UTC, merged