[20599] Protect asio exception hotfix
eProsima/Fast-DDS pull request #4527
Opened 2024-03-07 11:57 UTC by cferreiragonz

## Description
This PR introduces a hotfix to check the error code returned by asio when requesting the local_endpoint before trying to convert it to a locator. 

 @Mergifyio backport 2.13.x 2.12.x 2.10.x 2.6.x

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [_N/A_] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [_N/A_] Any new/modified methods have been properly documented using Doxygen. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- [_N/A_] New feature has been added to the `versions.md` file (if applicable).
- [_N/A_] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-03-07 12:15 UTC, MiguelCompany requested changes

2024-03-07 12:15 UTC, MiguelCompany commented on src/cpp/rtps/transport/TCPTransportInterface.cpp
> +    auto endpoint = channel->local_endpoint(ec);
```suggestion
    auto endpoint = channel->remote_endpoint(ec);
```

2024-03-07 20:09 UTC, EduPonz commented
@richiprosima please test this

2024-03-08 08:30 UTC, MiguelCompany approved these changes

2024-03-08 08:39 UTC, merged

2024-03-08 08:40 UTC, EduPonz commented
@Mergifyio backport 2.13.x 2.12.x 2.10.x 2.6.x