[20568] Remove all redundant headers from include/fastrtps
eProsima/Fast-DDS pull request #4546
Opened 2024-03-11 14:19 UTC by EduPonz

## Description

This PR removes all redundant headers from include/fastrtps. It depends on:

* #4545 

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- _N/A_: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_: Any new/modified methods have been properly documented using Doxygen. 
- ❌ Changes are ABI compatible. 
- ❌ Changes are API compatible. 
- [x] New feature has been added to the `versions.md` file (if applicable).
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- _N/A_: Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-03-15 10:39 UTC, elianalf requested changes

2024-03-15 10:39 UTC, elianalf commented on src/cpp/utils/UnitsParser.cpp
> +#include <utils/UnitsParser.hpp>
I think we are following the google style even if the headers are private, so this should be on top of the others

2024-03-25 14:51 UTC, elianalf commented
@richiprosima please test_3 this

2024-03-27 07:59 UTC, elianalf commented
@richiprosima please test_3 this

2024-03-27 10:00 UTC, elianalf submitted a review, later dismissed

2024-03-28 08:34 UTC, EduPonz commented
ASan workflow run with correct DS branch [here](https://github.com/eProsima/Fast-DDS/actions/runs/8464544701)

2024-04-29 08:46 UTC, elianalf commented
We should create a Shapes-Demo branch with these changes in particular the building failed because it couldn't find `fastrtps/rtps/common/Guid.h`

2024-05-16 05:55 UTC, elianalf commented
@richiprosima please test_3 this

2024-05-16 06:00 UTC, elianalf approved these changes

2024-05-17 09:53 UTC, elianalf approved these changes

2024-05-20 08:37 UTC, elianalf commented
@richiprosima please test_3 this

2024-05-20 14:32 UTC, merged