[20542] Adapt nightly jobs for all supported versions
eProsima/Fast-DDS pull request #4549
Opened 2024-03-12 08:42 UTC by JesusPoderoso

## Description

This PR removes the versioning in the .repos workflow configuration files to let each version contain its proper .repos file.
This PR would be cherry picked in the supported versions.

@Mergifyio backport 2.10.x 

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- **N/A** The code follows the style guidelines of this project. 
- **N/A**  Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A**  Any new/modified methods have been properly documented using Doxygen. 
- **N/A**  Changes are ABI compatible. 
- **N/A**  Changes are API compatible. 
- **N/A**  New feature has been added to the `versions.md` file (if applicable).
- **N/A**  New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-03-12 09:33 UTC, EduPonz requested changes

2024-03-12 09:33 UTC, EduPonz commented on .github/workflows/config/ci_colcon.meta
I'd suggest ci.meta

2024-03-12 09:33 UTC, EduPonz commented on .github/workflows/reusable-mac-ci.yml
> +          vcs import src --input ${REPOS_PATH} --skip-existing
I'd transform this into 2 calls to eprosima-CI action. Mind that you'dd need to adjust the path to the meta file on the build step. Same for all workflows

2024-03-12 10:08 UTC, EduPonz requested changes

2024-03-12 10:08 UTC, EduPonz commented on .github/workflows/reusable-mac-ci.yml
> +          colcon_meta_file: ./src/fastrtps/.github/workflows/config/ci.meta
I think it's safer to keep abs paths everywhere. Applies to all changes
```suggestion
          colcon_meta_file: ${{ github.workspace }}/src/fastrtps/.github/workflows/config/ci.meta
```

2024-03-12 10:24 UTC, EduPonz approved these changes

2024-03-12 10:25 UTC, EduPonz commented
@JesusPoderoso I think we need to run CI here

2024-03-13 16:35 UTC, JesusPoderoso reviewed
LGTM with green CI

2024-03-14 06:08 UTC, EduPonz approved these changes

2024-03-14 06:42 UTC, merged