[20553] Remove 2.12.x from PR template backports
eProsima/Fast-DDS pull request #4559
Opened 2024-03-15 07:00 UTC by JesusPoderoso

## Description

The v2.12.2 milestone has been frozen so no more PRs would be merged in 2.12.x
This PR removes the 2.12.x version branch from the pull request template backports list.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- **N/A** The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- **N/A** Changes are ABI compatible. 
- **N/A** Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-03-15 07:09 UTC, EduPonz approved these changes

2024-03-15 07:10 UTC, JesusPoderoso commented
@richiprosima please test this

2024-03-20 06:14 UTC, EduPonz requested changes
I think this PR should also remove 2.12.x from:

* Nightly CI
* RELEASE_SUPPORT.md (should not be bolded anymore)

2024-03-20 11:34 UTC, EduPonz approved these changes

2024-03-20 11:34 UTC, merged