[20628] Fix Discovery Server over TCP
eProsima/Fast-DDS pull request #4584
Opened 2024-03-19 10:29 UTC by cferreiragonz

## Description
This PR fixes a couple of bugs appearing when launching Discovery Server with TCP.

1. After the latest changes introduced to TCP with the Large Data feature, a DS client with one listening port could skip the channel creation and wait for the DS server to connect to it (which will never happen), as if it was a LARGE_DATA use case. A DS client must always create a CONNECT channel to the DS server.
2. The timer event that sends the pings to remote servers was not being restarted after updating the remote server list, what was causing a failure in the participant discovery.

@Mergifyio backport 2.13.x 2.10.x 2.6.x

- This PR is on top of #4560 and needs to be merged after it. The same logic applies to the corresponding backports.

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- [_N/A_] New feature has been added to the `versions.md` file (if applicable).
- [_N/A_] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-04-03 07:17 UTC, MiguelCompany commented
@cferreiragonz This has conflicts, would you mind fixing them?

2024-04-03 08:15 UTC, MiguelCompany requested changes

2024-04-03 08:15 UTC, MiguelCompany commented on src/cpp/rtps/participant/RTPSParticipantImpl.cpp
> +                                if (IPLocator::getLogicalPort(locator) == 0)
This should check the locator kind

2024-04-03 08:15 UTC, MiguelCompany commented on src/cpp/rtps/participant/RTPSParticipantImpl.cpp
> +                    }
Should we do this also in TCPv6 ?

2024-04-03 11:02 UTC, MiguelCompany requested changes

2024-04-03 11:02 UTC, MiguelCompany commented on src/cpp/rtps/participant/RTPSParticipantImpl.h
> +    void create_tcp_connection(
```suggestion
    void create_tcp_connections(
```

2024-04-03 12:33 UTC, MiguelCompany submitted a review, later dismissed
LGTM with green CI

2024-04-03 13:30 UTC, MiguelCompany commented
@cferreiragonz Windows has build warnings

```
    DDSBlackboxTestsDiscovery.cpp
  D:\a\Fast-DDS\Fast-DDS\src\fastrtps\test\blackbox\common\DDSBlackboxTestsDiscovery.cpp(230,50): error C2220: the following warning is treated as an error [D:\a\Fast-DDS\Fast-DDS\build\fastrtps\test\blackbox\BlackboxTests_DDS_PIM.vcxproj]
  D:\a\Fast-DDS\Fast-DDS\src\fastrtps\test\blackbox\common\DDSBlackboxTestsDiscovery.cpp(230,50): warning C4244: 'argument': conversion from 'uint32_t' to 'uint16_t', possible loss of data [D:\a\Fast-DDS\Fast-DDS\build\fastrtps\test\blackbox\BlackboxTests_DDS_PIM.vcxproj]
  D:\a\Fast-DDS\Fast-DDS\src\fastrtps\test\blackbox\common\DDSBlackboxTestsDiscovery.cpp(236,37): warning C4244: 'argument': conversion from 'uint32_t' to 'uint16_t', possible loss of data [D:\a\Fast-DDS\Fast-DDS\build\fastrtps\test\blackbox\BlackboxTests_DDS_PIM.vcxproj]
  D:\a\Fast-DDS\Fast-DDS\src\fastrtps\test\blackbox\common\DDSBlackboxTestsDiscovery.cpp(256,50): warning C4244: 'argument': conversion from 'uint32_t' to 'uint16_t', possible loss of data [D:\a\Fast-DDS\Fast-DDS\build\fastrtps\test\blackbox\BlackboxTests_DDS_PIM.vcxproj]
  D:\a\Fast-DDS\Fast-DDS\src\fastrtps\test\blackbox\common\DDSBlackboxTestsDiscovery.cpp(262,37): warning C4244: 'argument': conversion from 'uint32_t' to 'uint16_t', possible loss of data [D:\a\Fast-DDS\Fast-DDS\build\fastrtps\test\blackbox\BlackboxTests_DDS_PIM.vcxproj]
  D:\a\Fast-DDS\Fast-DDS\src\fastrtps\test\blackbox\common\DDSBlackboxTestsDiscovery.cpp(282,51): warning C4244: 'argument': conversion from 'uint32_t' to 'uint16_t', possible loss of data [D:\a\Fast-DDS\Fast-DDS\build\fastrtps\test\blackbox\BlackboxTests_DDS_PIM.vcxproj]
  D:\a\Fast-DDS\Fast-DDS\src\fastrtps\test\blackbox\common\DDSBlackboxTestsDiscovery.cpp(297,51): warning C4244: 'argument': conversion from 'uint32_t' to 'uint16_t', possible loss of data [D:\a\Fast-DDS\Fast-DDS\build\fastrtps\test\blackbox\BlackboxTests_DDS_PIM.vcxproj]
```

2024-04-04 09:14 UTC, JesusPoderoso commented
CI issues looks unrelated to the PR to me.
Ready to merge!

2024-04-04 10:48 UTC, merged

2024-04-04 10:48 UTC, MiguelCompany commented
@Mergifyio backport 2.10.x 2.6.x