[20729] Allow processing of AckNack submessages with count == 0
eProsima/Fast-DDS pull request #4639
Opened 2024-04-02 07:39 UTC by MiguelCompany

## Description

As spotted by https://github.com/omg-dds/dds-rtps/issues/35, Fast DDS ignores AckNack messages where the `count` field is `0`.

This PR adds a unit test for `ReaderProxy::check_and_set_acknack_count`, and fixes the issue by changing the check on `acknack_count` from *last received* to *next expected*.

@Mergifyio backport 2.13.x 2.10.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-04-03 06:39 UTC, EduPonz requested changes

2024-04-03 06:39 UTC, EduPonz commented on include/fastdds/rtps/writer/ReaderProxy.h
> +        if (acknack_count >= next_expected_acknack_count_)
Please update doxygen here

2024-04-03 06:40 UTC, EduPonz commented
@richiprosima please test this

2024-04-03 13:02 UTC, EduPonz approved these changes
LGTM with green CI

2024-04-03 13:03 UTC, EduPonz commented
@richiprosima please test this

2024-04-04 10:42 UTC, merged

2024-05-13 12:53 UTC, MiguelCompany commented
@Mergifyio backport 2.13.x 2.10.x 2.6.x