[20658] Fix leak in `SecurityManager::participant_volatile_message_secure_writer_`
eProsima/Fast-DDS pull request #4673
Opened 2024-04-09 14:01 UTC by MiguelCompany

## Description

This is a fix for #4553, which reported an increase in memory consumption when the partition of a secure DataWriter is changed. The consumption came from the history of the `participant_volatile_message_secure_writer_` not being correctly cleared.

This PR:
* adds a black-box test reproducing the behavior depicted in #4553
* converts `volatile_writer_` in the security tests into a `StrictMock`, and adds expectations for the added change to be released
* Fixes #4553 by making `SecurityManager` implement `rtps::WriterListener` and removing changes from history when they are acknowledged (i.e. making `participant_volatile_message_secure_writer_` truly behave as volatile)

@Mergifyio backport 2.13.x 2.10.x 2.6.x

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- _N/A_ New feature has been added to the `versions.md` file (if applicable).
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-04-15 21:23 UTC, fujitatomoya approved these changes
adding the listener of security manager to remove the history change once all readers are acknowledged, lgtm.

2024-04-23 09:56 UTC, EduPonz requested changes
Please revert the Fast CDR submodule update

2024-04-23 10:23 UTC, MiguelCompany commented
> Please revert the Fast CDR submodule update

I rebased and removed the submodule update from the commit where it was done

2024-04-24 05:11 UTC, EduPonz commented
@MiguelCompany I'm afraid Ubuntu and macOS CIs show failures in `BlackboxTests_DDS_PIM.Security/Security.BuiltinAuthenticationAndAccessAndCryptoPlugin_Permissions_validation_toggle_partition`. Can you please check it?

2024-04-24 08:56 UTC, EduPonz approved these changes

2024-04-25 05:00 UTC, EduPonz commented
@Mergifyio backport 2.13.x 2.10.x 2.6.x

2024-04-25 05:00 UTC, EduPonz commented
CI errors unrelated to the PR

2024-04-25 05:01 UTC, merged