[20765] Make RTPS reader implementations private
eProsima/Fast-DDS pull request #4674
Opened 2024-04-09 14:26 UTC by elianalf

## Description

This PR makes RTPS reader implementations private:
- StatefulPersistentReader
- StatefulReader
- StatelessPersistentReader
- StatelessReader 

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- N/A Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- N/A Any new/modified methods have been properly documented using Doxygen. 
- N/A Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- ❌ Changes are ABI compatible. 
- ❌ Changes are API compatible. 
- N/A New feature has been added to the `versions.md` file (if applicable).
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 
    
- N/A Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-05-24 08:59 UTC, MiguelCompany commented
@elianalf There are conflicts here, so a rebase is necessary.

2024-05-24 09:07 UTC, MiguelCompany requested changes
It would be nice to also change the extension of the moved headers from `.h` to `.hpp

2024-05-24 09:07 UTC, MiguelCompany commented on src/cpp/rtps/reader/StatefulReader.h
> + * @file .h
Revert this

2024-05-24 10:11 UTC, MiguelCompany requested changes

2024-05-24 10:11 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
> +#include <rtps/reader/StatelessReader.hpp>
```suggestion
#include <rtps/reader/StatefulReader.hpp>
#include <rtps/reader/StatelessReader.hpp>
#include <rtps/resources/TimedEvent.h>
```

2024-05-24 10:11 UTC, MiguelCompany commented on src/cpp/rtps/participant/RTPSParticipantImpl.cpp
> +#include <rtps/reader/StatelessReader.hpp>
```suggestion
#include <rtps/reader/StatefulPersistentReader.hpp>
#include <rtps/reader/StatefulReader.hpp>
#include <rtps/reader/StatelessPersistentReader.hpp>
#include <rtps/reader/StatelessReader.hpp>
```

2024-05-24 10:11 UTC, MiguelCompany commented on src/cpp/rtps/reader/StatefulPersistentReader.hpp
>  #ifndef _FASTDDS_RTPS_STATEFULPERSISTENTREADER_H_
```suggestion
#ifndef RTPS_READER__STATEFULPERSISTENTREADER_HPP
```

2024-05-24 10:11 UTC, MiguelCompany commented on src/cpp/rtps/reader/StatefulReader.hpp
>  #ifndef _FASTDDS_RTPS_READER_STATEFULREADER_H_
```suggestion
#ifndef RTPS_READER__STATEFULREADER_HPP
```

2024-05-24 10:11 UTC, MiguelCompany commented on src/cpp/rtps/reader/StatelessPersistentReader.hpp
>  #define _FASTDDS_RTPS_STATELESSPERSISTENTREADER_H_
```suggestion
#define RTPS_READER__STATELESSPERSISTENTREADER_HPP
```

2024-05-24 10:11 UTC, MiguelCompany commented on src/cpp/rtps/reader/StatelessPersistentReader.hpp
>  #define _FASTDDS_RTPS_STATELESSPERSISTENTREADER_H_
Change also comment in line 16.

2024-05-24 10:11 UTC, MiguelCompany commented on src/cpp/rtps/reader/StatelessReader.hpp
Change include guard to `RTPS_READER__STATELESSREADER_HPP`

2024-05-24 10:12 UTC, MiguelCompany commented on src/cpp/rtps/reader/StatefulReader.hpp
>  #ifndef _FASTDDS_RTPS_READER_STATEFULREADER_H_
Should also be applied to the mock header

2024-05-24 10:12 UTC, MiguelCompany commented on src/cpp/rtps/reader/StatelessReader.hpp
Should also be applied to the mock header

2024-05-27 06:46 UTC, MiguelCompany approved these changes

2024-05-27 06:52 UTC, elianalf commented
@richiprosima please test_3 this

2024-05-27 13:00 UTC, merged