[20742] Run `is_plain` method with the corresponding data representation
eProsima/Fast-DDS pull request #4681
Opened 2024-04-10 05:45 UTC by JesusPoderoso

## Description
The endpoints implementation (DataReaderImpl and DataWriterImpl) were calling `is_plain` method without the data representation, so it was not being considered.
This PR includes the data representation as an argument to `is_plain` so it is considered in both cases.

@Mergifyio backport 2.13.x 2.10.x 2.6.x

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_ Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- _N/A_ New feature has been added to the `versions.md` file (if applicable).
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-04-25 15:02 UTC, JesusPoderoso commented
@richiprosima please test this

2024-04-26 07:50 UTC, JesusPoderoso commented
@richiprosima please test this

2024-05-07 07:56 UTC, MiguelCompany requested changes

2024-05-07 07:56 UTC, MiguelCompany commented on src/cpp/fastdds/subscriber/DataReaderImpl.cpp
> +                std::make_shared<detail::SampleLoanManager>(config, type_, is_plain);
```suggestion
        sample_pool_ = std::make_shared<detail::SampleLoanManager>(config, type_, is_plain);
```

2024-05-07 07:56 UTC, MiguelCompany commented on test/unittest/dds/publisher/DataWriterTests.cpp
> +    }
```suggestion
    MOCK_CONST_METHOD1(custom_is_plain_with_rep, bool(DataRepresentationId_t data_representation_id));

    bool is_plain(
            DataRepresentationId_t data_representation_id) const override
    {
        return custom_is_plain_with_rep(data_representation_id);
    }

    MOCK_CONST_METHOD0(custom_is_plain, bool());

    bool is_plain() const override
    {
        return custom_is_plain();
    }
```

2024-05-07 07:56 UTC, MiguelCompany commented on test/unittest/dds/publisher/DataWriterTests.cpp
> +    EXPECT_CALL(*type, custom_is_plain(DataRepresentationId_t::XCDR2_DATA_REPRESENTATION)).Times(0);
```suggestion
    EXPECT_CALL(*type, custom_is_plain().Times(0);
    EXPECT_CALL(*type, custom_is_plain_with_rep(DataRepresentationId_t::XCDR_DATA_REPRESENTATION)).Times(
        testing::AtLeast(1)).WillRepeatedly(testing::Return(true));
    EXPECT_CALL(*type, custom_is_plain_with_rep(DataRepresentationId_t::XCDR2_DATA_REPRESENTATION)).Times(0);
```

2024-05-07 07:56 UTC, MiguelCompany commented on test/unittest/dds/publisher/DataWriterTests.cpp
> +        testing::AtLeast(1)).WillRepeatedly(testing::Return(true));
```suggestion
    EXPECT_CALL(*type, custom_is_plain().Times(0);
    EXPECT_CALL(*type, custom_is_plain_with_rep(DataRepresentationId_t::XCDR_DATA_REPRESENTATION)).Times(0);
    EXPECT_CALL(*type, custom_is_plain_with_rep(DataRepresentationId_t::XCDR2_DATA_REPRESENTATION)).Times(
        testing::AtLeast(1)).WillRepeatedly(testing::Return(true));
```

2024-05-07 07:56 UTC, MiguelCompany commented on test/unittest/dds/subscriber/DataReaderTests.cpp
> +    MOCK_CONST_METHOD1(custom_is_plain, bool(DataRepresentationId_t data_representation_id));
Similar suggestions as in DataWriterTests

2024-05-07 07:56 UTC, MiguelCompany commented on test/unittest/dds/subscriber/DataReaderTests.cpp
> +    /* Tear down */
Missing the case where we create a DataReader with empty data representation, and is_plain is called with both values.

2024-05-07 09:48 UTC, MiguelCompany approved these changes

2024-05-07 13:04 UTC, MiguelCompany approved these changes

2024-05-07 13:17 UTC, MiguelCompany commented
@richiprosima Please test this

2024-05-08 08:42 UTC, merged