[20733] Fix support for @key annotation in XML types
eProsima/Fast-DDS pull request #4694
Opened 2024-04-17 12:45 UTC by EduPonz

## Description

This PR:

- [x] Fixes the support for `@key` annotation on XML defined types
- [x] Adds the `key` attribute to members in XSD

@Mergifyio backport 2.13.x 2.10.x 2.6.x

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_: Any new/modified methods have been properly documented using Doxygen. 
- _N/A_: Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- _N/A_: New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-04-24 13:30 UTC, pablogs9 approved these changes

2024-04-24 13:38 UTC, pablogs9 submitted a review, later dismissed

2024-04-24 13:45 UTC, MiguelCompany approved these changes

2024-04-29 14:49 UTC, MiguelCompany requested changes

2024-04-29 14:49 UTC, MiguelCompany commented on src/cpp/dynamic-types/AnnotationDescriptor.cpp
> +        auto it = value_.find("value");
Do we have a constant for `"value"`?

2024-04-29 14:49 UTC, MiguelCompany commented on src/cpp/dynamic-types/MemberDescriptor.cpp
> +        // Copy annotation from type
```suggestion
        // Copy annotations from type
```

2024-04-29 14:54 UTC, MiguelCompany commented
Note: both suggestions don't require CI to be launched again

Additionally, the PR description does not indicate the fixes performed in DynamicTypes regarding key annotations

2024-04-30 05:11 UTC, EduPonz commented on src/cpp/dynamic-types/AnnotationDescriptor.cpp
> +        auto it = value_.find("value");
We do indeed!

2024-04-30 05:14 UTC, EduPonz commented
CI passed on b76cfdcd8, the changes in 8c415ee29 are merely cosmetic

2024-04-30 05:43 UTC, MiguelCompany approved these changes

2024-04-30 05:52 UTC, merged

2024-04-30 05:53 UTC, MiguelCompany commented
@Mergifyio backport 2.13.x 2.10.x 2.6.x