[20706] Make reader get_first_untaken_info() coherent with read()/take()
eProsima/Fast-DDS pull request #4696
Opened 2024-04-17 14:07 UTC by Mario-DL

## Description

This PR corrects the behavior of `get_first_untaken_info()` so that it retrieves the first valid cache change (checking whether the change is in the future or not), instead of just returning the first one in the instance (sorted by sourcetimespamp).
In the scenario of having multiple reliable writers and one reader with history size > 1 in the same topic, it can happen that `get_first_untaken_info()` returns `OK` (as it is not currently checking whether the change is in the future) but `take()` returns `NO_DATA`  because the change is in the future.

In addition, a brief doxygen documentation is added to be aware that the method is meant to be followed by a `read()` or `take()` since it does not modify the status condition of the entity.

@Mergifyio backport 2.13.x 2.10.x 2.6.x

Fixes https://github.com/ros2/rmw_fastrtps/issues/749

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [X] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- [❌] New feature has been added to the `versions.md` file (if applicable).
- [❌] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-04-17 14:26 UTC, MiguelCompany requested changes

2024-04-18 05:48 UTC, Mario-DL commented on src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
> +                std::lock_guard<RecursiveTimedMutex> _(mp_reader->getMutex());
Nice one

2024-04-18 09:23 UTC, Barry-Xu-2018 commented on src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
> +                mp_reader->end_sample_access_nts(instance_change, wp, false);
Thanks. Get it.

2024-04-18 16:40 UTC, fujitatomoya approved these changes
lgtm! @Mario-DL thanks for the fix!

2024-04-19 06:48 UTC, MiguelCompany commented
@richiprosima Please test this

2024-04-19 06:50 UTC, MiguelCompany approved these changes

2024-04-19 11:49 UTC, MiguelCompany commented
Unrelated failures. Going in.

2024-04-19 11:49 UTC, merged

2024-04-19 11:50 UTC, MiguelCompany commented
@mergifyio backport 2.13.x 2.10.x 2.6.x