[Hotfix] Structure DynamicType inheritance from TypeObject
eProsima/Fast-DDS pull request #4712
Opened 2024-04-22 13:41 UTC by JLBuenoLopez-eProsima

## Description

This PR fixes a bug in `DynamicTypeBuilderFactory::create_type_w_type_object` when creating a inheriting structure.

## Contributor Checklist

- [NO] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [N/A] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [N/A] Any new/modified methods have been properly documented using Doxygen. 
- [N/A] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [N/A] New feature has been added to the `versions.md` file (if applicable).
- [N/A] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [N/A] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-04-22 13:41 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test_3 this

2024-04-22 13:47 UTC, richiware requested changes

2024-04-22 13:47 UTC, richiware commented on src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderFactoryImpl.cpp
> +    bool inheritance_correct = true;
```suggestion
    bool inheritance_correct {true};
```

2024-04-22 13:48 UTC, JLBuenoLopez-eProsima commented on src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderFactoryImpl.cpp
> +    bool inheritance_correct = true;
:rofl:

2024-04-23 09:54 UTC, JLBuenoLopez-eProsima commented
@richiprosima please test_3 this

2024-04-24 05:17 UTC, richiware approved these changes

2024-04-24 05:20 UTC, merged