[20629] GUIDLess Discovery Server
eProsima/Fast-DDS pull request #4716
Opened 2024-04-23 06:33 UTC by cferreiragonz

## Description

This PR drastically changes Discovery Server behavior to be able to work without a fixed GUID. 

- Servers and clients now connect between each other by exclusively specifying a locator, the GUID is not needed anymore. The remote server list has been replaced with LocatorList.
- Hence, the server_id parameter used in the CLI and the positional arguments in the environment variable are deprecated. The -i parameter in the CLI has been kept in order to guarantee backward compatibility, but it is not mandatory any longer. 
- Servers now uses a mesh topology, meaning that every server will directly connect with all of the available servers. 
- In order to accomplish last point, Servers now send the Data(p) of connected servers to new servers connections and send the Data(p) of the new server to all connected servers. To connect a new server to the mesh, it is only needed to specify the locator of an already connected server.
- Servers only redirect discovery information of their direct clients, and will stop redirecting discovery information of the clients of other servers.
- Remote Discovery servers connection list can now be updated in runtime without any restrictions. The previous list does not need to be a subset of the new one. 
- Servers now use the lease announcements routine to make connections with the remote servers specified in the remote Discovery servers list. Initial announcements will be called again every time a known server is dropped or the remote server list is updated.
- Clients now accept connections of any server, not only the ones specified in their remote Discovery servers list. Although in normal behavior a client will only receive discovery information of the servers pinged by itself, if it receives a Data(p) of an other server (sending it manually) it will try to make a connection.

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [X] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- ❌ Changes are ABI compatible. 
- ❌ Changes are API compatible. (RemoteServers are now specified by a LocatorList. Also, Fast DDS tool CLI and ROS_DISCOVERY_SERVER env. var. behavior have been modified)
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- _N/A_ Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-06-13 11:06 UTC, MiguelCompany requested changes

2024-06-13 11:06 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/participant/PDPServerListener.hpp
> +     * @param participant_type_str Type of the remote participant.
```suggestion
     * @param [in]  participant_data Remote participant data to check.
     * @param [out] participant_type_str Type of the remote participant.
```

2024-06-13 11:06 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/participant/PDPServerListener.hpp
> +            fastrtps::rtps::ParticipantProxyData& participant_data,
```suggestion
            const fastrtps::rtps::ParticipantProxyData& participant_data,
```

2024-06-13 11:06 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
> +        // TODO Carlos (OPT-IMPROVE): delete this?
??

2024-06-25 07:12 UTC, MiguelCompany requested changes

2024-06-25 07:12 UTC, MiguelCompany commented on test/mock/rtps/RTPSParticipantAttributes/fastdds/rtps/attributes/RTPSParticipantAttributes.h
> +
```suggestion
```

2024-06-26 12:54 UTC, cferreiragonz commented on src/cpp/rtps/RTPSDomain.cpp
> +#include <rtps/attributes/ServerAttributes.hpp>
We need it to use `load_environment_server_info`, don't we?

2024-07-01 10:00 UTC, MiguelCompany requested changes

2024-07-01 10:00 UTC, MiguelCompany commented on src/cpp/rtps/attributes/ServerAttributes.cpp
> +// Copyright 2022 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
// Copyright 2024 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2024-07-01 10:00 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
>  GUID_t RemoteServerAttributes::GetParticipant() const
Implementation of `RemoteServerAttributes` methods shall be moved to `ServerAttributes.cpp`

2024-07-01 13:53 UTC, MiguelCompany submitted a review, later dismissed
LGTM with green CI

2024-07-02 11:07 UTC, MiguelCompany approved these changes

2024-07-03 06:12 UTC, cferreiragonz commented
Green CI. Updating `versions.md` and RTM

2024-07-03 06:16 UTC, merged