[20893] Prepare 3.0.x-devel to become master
eProsima/Fast-DDS pull request #4723
Opened 2024-04-24 07:21 UTC by EduPonz

## Description

This PR prepares the 3.0.x-devel branch to become Fast DDS master.
Related PRs:

* eProsima/Fast-DDS-docs#750
* eProsima/Fast-DDS-python#122
* eProsima/ShapesDemo#127
* eProsima/Shapes-Demo-Docs#109

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- _N/A_: The code follows the style guidelines of this project. 
- _N/A_: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_: Any new/modified methods have been properly documented using Doxygen. 
- _N/A_: Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- _N/A_: Changes are ABI compatible. 
- _N/A_: Changes are API compatible. 
- _N/A_: New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation. 
    - Related documentation PR: eProsima/Fast-DDS-docs#750
- _N/A_: Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

2024-04-25 08:53 UTC, elianalf reviewed
I think the only missing thing to change is the fallback_branch in documentation-tests

2024-04-25 09:15 UTC, EduPonz commented
CI will not pass in this PR so it does not make sense to run it.

2024-04-25 09:23 UTC, elianalf approved these changes

2024-04-25 09:24 UTC, elianalf requested changes

2024-04-25 09:24 UTC, elianalf commented on .github/workflows/documentation-tests.yaml
> +          fallback_branch: ${{ inputs.fastdds_python_branch || 'master' }}
I think this is main

2024-05-07 13:17 UTC, elianalf approved these changes

2024-05-08 08:55 UTC, merged