[20933 ] Set DataSharing in Writer|ReaderProxyData
eProsima/Fast-DDS pull request #4761
Opened 2024-05-08 15:03 UTC by elianalf

## Description

Previously, Writer|ReaderProxyData always reported DataSharing as AUTO. This PR set it to ON or OFF based on the PID_DATASHARING.

 @Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x 

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- N/A Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- N/A New feature has been added to the `versions.md` file (if applicable).
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-05-13 13:50 UTC, JesusPoderoso approved these changes
LGTM with green CI

2024-05-16 05:39 UTC, elianalf commented
@richiprosima please test_3 this

2024-05-17 07:52 UTC, elianalf commented
@richiprosima please test_3 linux

2024-05-17 11:10 UTC, JesusPoderoso approved these changes
LGTM, good job!

2024-05-17 11:17 UTC, EduPonz requested changes

2024-05-17 11:17 UTC, EduPonz commented on test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
> +        // This was captured with wireshark from OpenDDS iShapes 3.16
```suggestion
```

2024-05-17 11:17 UTC, EduPonz commented on test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
> +        // This was captured with wireshark from OpenDDS iShapes 3.16
```suggestion
```

2024-05-17 11:17 UTC, EduPonz commented on test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
> +        // This was captured with wireshark from OpenDDS iShapes 3.16
```suggestion
```

2024-05-17 11:17 UTC, EduPonz commented on test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
> +        // This was captured with wireshark from OpenDDS iShapes 3.16
```suggestion
```

2024-05-17 11:22 UTC, EduPonz commented
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x

2024-05-17 11:54 UTC, EduPonz approved these changes

2024-05-17 11:55 UTC, merged