[20820] Make security private
eProsima/Fast-DDS pull request #4792
Opened 2024-05-16 09:44 UTC by elianalf

## Description
This pr makes security private, in particular:
* logging
* exception
* cryptography
* common
* authentication
* access control

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- N/A Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- N/A Any new/modified methods have been properly documented using Doxygen. 
- N/A Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- ❌ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- ❌ Changes are API compatible. 
- N/A New feature has been added to the `versions.md` file (if applicable).
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 
    
- N/A Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-05-21 13:03 UTC, JesusPoderoso requested changes
Most of the changes may dissapear also while passing the linter (uncrustify action failed)

2024-05-21 13:03 UTC, JesusPoderoso commented on src/cpp/rtps/security/SecurityPluginFactory.h
```suggestion
```

2024-05-21 13:03 UTC, JesusPoderoso commented on src/cpp/security/accesscontrol/Permissions.cpp
> +
```suggestion
```

2024-05-21 13:03 UTC, JesusPoderoso commented on test/mock/rtps/SecurityPluginFactory/rtps/security/SecurityPluginFactory.h
```suggestion
```

2024-05-21 13:03 UTC, JesusPoderoso commented on test/unittest/rtps/security/SecurityTests.hpp
> +
```suggestion
```

2024-05-23 06:16 UTC, JesusPoderoso submitted a review, later dismissed
LGTM with green CI

2024-05-24 09:37 UTC, JesusPoderoso submitted a review, later dismissed
LGTM with green CI

2024-05-27 06:55 UTC, elianalf commented
@richiprosima please test_3 this

2024-05-27 07:04 UTC, JesusPoderoso approved these changes
LGTM with green CI

2024-05-28 07:54 UTC, elianalf commented
@richiprosima please test_3 this

2024-05-29 05:31 UTC, merged