[21053] Move DR TypeConsistencyEnforcementQosPolicy & DataRepresentationQoSPolicy…
eProsima/Fast-DDS pull request #4823
Opened 2024-05-21 14:33 UTC by JesusPoderoso

… to correct place

## Description
This PR updates the DataReaderQoS reformatting the TypeConsistencyQos:
1. `DataReaderQos` shall have:
     - `TypeConsistencyEnforcementQosPolicy::type_consistency`
     - `DataRepresentationQosPolicy::representation`
2. `DataReader::TypeConsistencyQos` shall be removed

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- **N/A** Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- ❌ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- ❌ Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation. 
    - Related documentation PR: eProsima/Fast-DDS-docs#
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-05-22 07:18 UTC, Mario-DL requested changes
Good job in this PR.
Leaving some corrections and a suggestion. In addition, some considerations:
* I think that the changes in this PR should be reflected in the `versions.md`
* As this PR is targeting `3.0.0`, we can break API, which should be left unmarked in the checklist as this PR is breaking.
* Before merging this PR it would be nice if we could, at least in local, compile other products. For instance, we should also link a PR to `Shapes Demo` overcoming the API break. 
* If possible, edit PR's title since `...` seems to be the commit message directly.

2024-05-22 07:18 UTC, Mario-DL commented on test/unittest/dds/subscriber/SubscriberTests.cpp
> +    EXPECT_EQ(XML_DATA_REPRESENTATION, wqos.representation().m_value.at(0));
I think we can go ahead and rename the `wqos` in this test with `rqos`, it is confusing as I interpreted them as `writer qos`

2024-05-23 06:25 UTC, JesusPoderoso commented
> As this PR is targeting 3.0.0, we can break API, which should be left unmarked in the checklist as this PR is breaking.

I think it is correctly checked, see following comment section of the PR template:

```
<!--
- If any of the elements of the following checklist is not applicable, substitute the checkbox [ ] by _N/A_:
- If any of the elements of the following checklist is not fulfilled on purpose, please provide a reason
  and substitute the checkbox [ ] with ❌: or __NO__:.
-->
```

2024-05-23 13:43 UTC, Mario-DL commented
@richiprosima please test_3 this

2024-05-23 13:43 UTC, Mario-DL approved these changes
LGTM with green Jenkins CI

2024-05-24 06:49 UTC, Mario-DL commented
@richiprosima please test_3 windows

2024-05-27 05:36 UTC, merged