TypeObjectRegistry refactor
eProsima/Fast-DDS pull request #4874
Opened 2024-05-30 07:51 UTC by richiware

## Description

With this refactor, any registration in `TypeObjectRegistry` will return a `TypeIdentifierPair` which a `TopicDataType` can use to configure internally DDS.

## Contributor Checklist

- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [ ] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-06-06 10:01 UTC, adriancampo requested changes

2024-06-07 09:11 UTC, richiware commented on include/fastdds/dds/topic/TopicDataType.hpp
Needed [here](https://github.com/eProsima/Fast-DDS/pull/4874/files#diff-c0abde0afeb3603890dfa3ac2dfa8b55d1f73f68bec2bc642cc5b415497a09e1R1652).

2024-06-07 09:12 UTC, richiware commented on include/fastdds/dds/xtypes/common.hpp
> +enum class TryConstructFailAction : uint32_t
`TryConstructKind` is defined in Dynamic Language Binding and `TryConstructFailAction` is the enumeration for the annotation used to know the TryConstruct.

2024-06-07 09:42 UTC, richiware commented on src/cpp/fastdds/xtypes/dynamic_types/MemberDescriptorImpl.cpp
> +        EPROSIMA_LOG_WARNING(DYN_TYPES, "try_construct_kind is not implemented yet.");
Old comment. I changed the behaviour.

2024-06-10 05:40 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the CompleteTypeObject just registered and the
Done in eb4efe39b

2024-06-10 05:40 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the registered DynamicType TypeObject.
Done in eb4efe39b

2024-06-10 05:40 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp
> +     * @param[inout] type_identifier TypeIdentifier related to the given type name. It must be set in
Done in eb4efe39b

2024-06-10 05:40 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp
> +     * @param[in] type_ids @ref TypeIdentifier which type information is queried.
Done in eb4efe39b

2024-06-10 05:40 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the StringSTypeDefn just registered.
Done in eb4efe39b

2024-06-10 05:40 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the StringLTypeDefn just registered.
Done in eb4efe39b

2024-06-10 05:40 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the PlainSequenceSElemDefn just registered.
Done in eb4efe39b

2024-06-10 05:40 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the PlainSequenceLElemDefn just registered.
Done in eb4efe39b

2024-06-10 05:40 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the PlainArraySElemDefn just registered.
Done in eb4efe39b

2024-06-10 05:40 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the PlainArrayLElemDefn just registered.
Done in eb4efe39b

2024-06-10 05:41 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the PlainMapSTypeDefn just registered.
Done in eb4efe39b

2024-06-10 05:41 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the PlainMapLTypeDefn just registered.
Done in eb4efe39b

2024-06-10 05:41 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the CompleteAliasType just registered and the
Done in eb4efe39b

2024-06-10 05:41 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the CompleteAnnotationType just registered and the
Done in eb4efe39b

2024-06-10 05:41 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the CompleteStructType just registered and the
Done in eb4efe39b

2024-06-10 05:41 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the CompleteUnionType just registered and the
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the CompleteBitsetType just registered and the
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the CompleteEnumeratedType just registered and the
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the CompleteBitmaskType just registered and the
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the CompleteTypeObject just registered and the
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[inout] type_ids Returns the registered @ref TypeIdentifier.
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[inout] type_identifier TypeIdentifier related to the given type name. It must be set in
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[in] type_ids @ref TypeIdentifier which type information is queried.
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the registered DynamicType TypeObject.
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the Alias DynamicType TypeObject.
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the Alias DynamicType TypeObject.
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the Alias DynamicType TypeObject.
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the Alias DynamicType TypeObject.
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the Alias DynamicType TypeObject.
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the Alias DynamicType TypeObject.
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the Alias DynamicType TypeObject.
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the Alias DynamicType TypeObject.
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the Alias DynamicType TypeObject.
Done in eb4efe39b

2024-06-10 05:42 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the Alias DynamicType TypeObject.
Done in eb4efe39b

2024-06-10 05:43 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
> +     * @param[out] type_ids TypeIdentifiers corresponding to the Alias DynamicType TypeObject.
Done in eb4efe39b

2024-06-10 06:44 UTC, adriancampo approved these changes
LGTM

2024-06-13 13:54 UTC, adriancampo approved these changes
LGTM

2024-06-13 16:40 UTC, EduPonz commented
@richiprosima please test_3 discovery-server

2024-06-13 16:43 UTC, EduPonz commented
@richiprosima please test_3 discovery-server

2024-06-14 04:59 UTC, merged