[20816] Properly delete builtin statistics writers upon `delete_contained_entities()`
eProsima/Fast-DDS pull request #4891
Opened 2024-06-03 15:36 UTC by Mario-DL

## Description

This PR fixes a wrong behavior that occurs when closing an application making an intensive use of statistics. If in the shutdown pipeline, after a manual removal of entities (`delete_datareader`, `delete_subscriber`, `delete_topic`) if  `delete_contained_entities()` was called, it caused a race when alive endpoints try to keep using the statistics builtin endpoints (writers).

@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [X] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [X] Changes are API compatible. 
- [X] New feature has been added to the `versions.md` file (if applicable).
- [X] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-06-05 12:30 UTC, EduPonz requested changes
Only one little NIT. 👏🏼

2024-06-05 12:55 UTC, Mario-DL commented on test/blackbox/common/DDSBlackboxTestsStatistics.cpp
> +        }
I  put it in that way in an attempt of mimicking what was being done in the reproducer (first, manually remove the entities and then call to `delete_contained_entities()`). But perhaps we can see if we can reproduce it without it, should I then give it a try removing those lines ?

2024-06-06 05:08 UTC, EduPonz commented on test/blackbox/common/DDSBlackboxTestsStatistics.cpp
> +        }
I did try before suggesting. As expected, the test still fails without the fix.

2024-06-06 05:43 UTC, EduPonz approved these changes

2024-06-08 05:42 UTC, EduPonz commented
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x

2024-06-08 05:42 UTC, merged