[21121] IPayloadPool refactor
eProsima/Fast-DDS pull request #4892
Opened 2024-06-04 09:02 UTC by cferreiragonz

## Description

This PR adds two main changes:

1. It moves `payload_owner_` from `CacheChange_t` to `SerializedPayload_t`
2. Refactors `IPayloadPool` class and all derived classes to only manage `SerializedPayload_t`, instead of `CacheChange_t`

In this way, the `payload_owner_` is no longer related to a cache change, but to the payload it refers.

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- ❌ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- ❌ Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- _N/A_ Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-06-04 09:17 UTC, cferreiragonz commented
Since the `payload_owner_` now belongs to the `SerializedPayload_t`, I believe the [`get_payload()`](https://github.com/eProsima/Fast-DDS/blob/1f1d426775a21af4ddd178c5e323e3d47c638e45/include/fastdds/rtps/history/IPayloadPool.h#L94) method receiving a source `SerializedPayload_t&`, an `IPayloadPool*` and a destination `SerializedPayload_t&` could be simplified removing the `IPayloadPool*` parameter, as it is already contained in the source payload. I let the reviewer the decision of keeping it or not.

2024-06-06 10:44 UTC, MiguelCompany requested changes

2024-06-06 10:44 UTC, MiguelCompany commented on include/fastdds/rtps/history/IPayloadPool.h
> +     * @warning @c data fields can only be changed when @c data_owner contained in @c data is @c nullptr. If a
```suggestion
     * @warning @c data fields can only be changed when @c payload_owner contained in @c data is @c nullptr. If a
```

2024-06-06 10:44 UTC, MiguelCompany commented on src/cpp/fastdds/subscriber/DataReaderImpl/SampleLoanManager.hpp
>          tmp.serializedPayload.data = nullptr;
We can now avoid using a temporary `CacheChange_t` here, and use `change->payload_owner()->get_payload(change->serializedPayload, item->payload);`

2024-06-06 10:44 UTC, MiguelCompany commented on src/cpp/fastdds/subscriber/DataReaderImpl/SampleLoanManager.hpp
> +            item->payload_owner(nullptr);
Similar thing here, could use `item->payload.payload_owner->release_payload(item->payload);`

2024-06-06 10:44 UTC, MiguelCompany commented on src/cpp/fastdds/subscriber/DataReaderImpl/SampleLoanManager.hpp
> +            // Avoid releasing payload and freeing data
We could just do:
```suggestion
            // Avoid releasing payload and freeing data
            payload.payload_owner = nullptr;
```

2024-06-06 10:44 UTC, MiguelCompany commented on src/cpp/fastdds/subscriber/DataReaderImpl/SampleLoanManager.hpp
> +
I don't think these are necessary

2024-06-06 10:44 UTC, MiguelCompany commented on src/cpp/rtps/DataSharing/ReaderPool.hpp
> +     * If the payload is not owned by @c data_owner, it is assumed to be an intraprocess writer and the
```suggestion
     * If the payload is not owned by this pool, it is assumed to be an intraprocess writer and the
```

2024-06-06 10:44 UTC, MiguelCompany commented on src/cpp/rtps/common/PayloadInfo_t.hpp
> +
I think we could get rid of `PayloadInfo_t` and use `SerializedPayload_t` directly.

2024-06-06 14:05 UTC, MiguelCompany requested changes

2024-06-06 14:05 UTC, MiguelCompany commented on include/fastdds/rtps/common/SerializedPayload.h
> +
This code should be moved inside the empty() method

2024-06-06 14:05 UTC, MiguelCompany commented on src/cpp/fastdds/publisher/DataWriterImpl.cpp
> +        payload.payload_owner = nullptr;
Consider using `std::swap(payload, ch->serializedPayload);`

2024-06-06 14:50 UTC, MiguelCompany submitted a review, later dismissed
LGTM with green CI

2024-06-11 07:15 UTC, MiguelCompany requested changes

2024-06-11 07:15 UTC, MiguelCompany commented on src/cpp/rtps/reader/StatefulReader.cpp
> +                            change->serializedPayload);
We can try the following:

```suggestion
                    payload_pool_->get_payload(change_to_add->serializedPayload, change->serializedPayload);
```

2024-06-11 07:15 UTC, MiguelCompany commented on src/cpp/rtps/reader/StatelessReader.cpp
> +                    change_to_add->serializedPayload.payload_owner->get_payload(change_to_add->serializedPayload,
Same here

2024-06-11 07:16 UTC, MiguelCompany commented on include/fastdds/rtps/common/SerializedPayload.h
> +    //!Copy constructor
Also move the implementation of the methods to a source file, please.

2024-06-11 08:51 UTC, MiguelCompany submitted a review, later dismissed
LGTM with green CI
🏅

2024-06-11 12:49 UTC, MiguelCompany commented
@cferreiragonz I have rebased this on top of #4875. When it gets merged, please re-rebase and update `versions.md` on this PR.

2024-06-11 13:57 UTC, MiguelCompany requested changes

2024-06-11 13:57 UTC, MiguelCompany commented on test/unittest/rtps/reader/CMakeLists.txt
>      ${PROJECT_SOURCE_DIR}/src/cpp/rtps/common/LocatorWithMask.cpp
Move SerializedPayload 1 line down

2024-06-11 14:39 UTC, MiguelCompany commented
@richiprosima Please test_3 discovery-server

2024-06-12 07:54 UTC, MiguelCompany commented
Checked locally that discovery server tests pass with this and #4932. Ready to merge.

2024-06-12 07:59 UTC, MiguelCompany commented
@richiprosima Please test_3 discovery-server because #4932 has just been merged

2024-06-12 10:01 UTC, MiguelCompany commented
@richiprosima Please test_3 discovery-server with updated ci branch

2024-06-12 10:14 UTC, MiguelCompany commented
@richiprosima Please test_3 discovery-server because I made a mistake in the jenkins job configuration

2024-06-12 10:45 UTC, merged