[21054] Bugfix: Revert XML Flow controller names to `const char*`
eProsima/Fast-DDS pull request #4911
Opened 2024-06-07 07:25 UTC by Mario-DL

## Description

PR #4893 introduced an ABI break changing the flow controller descriptor names to `std::string`. This PR reverts that change and handles the flow controller names in a collection within `XMLParser`. It also defines a `clear()` method intended to clean the collection upon `XMLProfileManager` destruction.

**Important** A cherry pick of this PR should be merged in the following backports
* #4905 
* #4906
* #4907

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- __NO__ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [X] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [X] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [X] Changes are API compatible. 
- __NO__ New feature has been added to the `versions.md` file (if applicable).
- [X] New feature has been documented/Current behavior is correctly described in the documentation. 
    - Related documentation PR: eProsima/Fast-DDS-docs#806
- __NO__ (see PR description) Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-06-07 07:30 UTC, JesusPoderoso commented
@richiprosima please test this

2024-06-07 07:40 UTC, MiguelCompany requested changes

2024-06-07 07:40 UTC, MiguelCompany commented on src/cpp/rtps/xmlparser/XMLElementParser.cpp
> +std::vector<std::string> XMLParser::flow_controller_descriptor_names_;
I would change this into an std::set to avoid duplicates

2024-06-07 08:10 UTC, MiguelCompany requested changes

2024-06-07 08:10 UTC, MiguelCompany commented on src/cpp/rtps/xmlparser/XMLElementParser.cpp
> +                auto element_inserted = flow_controller_descriptor_names_.insert(get_element_text(p_aux1));
I would separate the check for the element. So call `get_element_text` and validate the returned value, then insert in the set

2024-06-07 09:02 UTC, MiguelCompany approved these changes
LGTM with green CI

2024-06-07 09:50 UTC, JesusPoderoso commented
@richiprosima please test this

2024-06-08 05:47 UTC, merged

2024-06-08 05:47 UTC, EduPonz commented
@Mario-DL please remember to cherry-pick this onto the other backports

2024-06-10 10:46 UTC, Mario-DL commented
Cherry picks added 👍🏻