[21120] Fix EDP build warning wihtout security
eProsima/Fast-DDS pull request #4932
Opened 2024-06-11 15:15 UTC by JesusPoderoso

## Description
This PR fixes a build warning that occurs when building Fast DDS without security, introduced in:
- #4875 

Added the `skip-ci` label (PR is by default run with security) and triggering manual CI without security

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_ Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- __NO__ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- __NO__ Changes are API compatible. 
- __NO__ New feature has been added to the `versions.md` file (if applicable).
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
   
- _N/A_ Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-06-11 15:18 UTC, JesusPoderoso commented
[Manual run of Ubuntu CI](https://github.com/eProsima/Fast-DDS/actions/runs/9468295963) (cmake args `-DSECURITY=OFF`, ctest args `-N`)

2024-06-11 16:39 UTC, EduPonz requested changes
It seems there are other similar occurrences: https://github.com/eProsima/Fast-DDS/actions/runs/9468295963/job/26084327914#step:16:2686

2024-06-12 07:57 UTC, EduPonz commented
CI passed [here](https://github.com/eProsima/Fast-DDS/actions/runs/9468295963)

2024-06-12 07:57 UTC, EduPonz approved these changes

2024-06-12 07:57 UTC, merged