[21170] Fix DS servers not connecting due to log_port logic
eProsima/Fast-DDS pull request #4941
Opened 2024-06-12 10:39 UTC by cferreiragonz

## Description

This PR fixes a bug that was avoiding discovery when a DS server tries to connect to another server which has a smaller logical port. The logic implemented in https://github.com/eProsima/Fast-DDS/pull/4586 needs to be used to fix the issue.
It also adds support to automatically set the logical port of remote servers when the participant `discoveryProtocol` is configured as `DiscoveryProtocol::SERVER`, which was missing.

@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_ Any new/modified methods have been properly documented using Doxygen. 
- [X] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [X] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [X] Changes are API compatible. 
- _N/A_ New feature has been added to the `versions.md` file (if applicable).
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-06-12 12:38 UTC, cferreiragonz commented
@richiprosima please test_3 discovery-server

2024-06-13 05:37 UTC, Mario-DL approved these changes
LGTM with green Tsan CI. I think we can set it as ready to review

2024-06-13 05:57 UTC, MiguelCompany requested changes

2024-06-13 05:57 UTC, MiguelCompany commented on test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
> +    std::string W_UNICAST_PORT_RANDOM_NUMBER_STR = "42100";
I think this can directly be an `uint16_t`:
```suggestion
    constexpr uint16_t W_UNICAST_PORT_RANDOM_NUMBER_STR = 42100;
```

2024-06-13 05:57 UTC, MiguelCompany commented on test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
> +    descriptor_2->add_listener_port(server_2_port);
Very similar code, let's think a way of grouping it.

2024-06-13 08:26 UTC, MiguelCompany submitted a review, later dismissed
LGTM with uncrustify fixed and green CI

2024-06-13 08:32 UTC, MiguelCompany approved these changes

2024-06-13 08:32 UTC, MiguelCompany commented
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x

2024-06-13 09:57 UTC, MiguelCompany commented
@cferreiragonz There's a warning in windows. Could you take a look?

2024-06-13 10:09 UTC, MiguelCompany approved these changes

2024-06-13 10:13 UTC, MiguelCompany commented
@richiprosima Please test_3 discovery-server

2024-06-13 12:36 UTC, cferreiragonz commented
@richiprosima Please test_3 discovery-server

2024-06-14 06:10 UTC, MiguelCompany submitted a review, later dismissed
LGTM with uncrustify and CI green

2024-06-14 06:35 UTC, cferreiragonz commented
@richiprosima Please test_3 discovery-server

2024-06-14 12:03 UTC, MiguelCompany approved these changes

2024-06-14 12:03 UTC, merged