[21131] Make Blackbox tests not include any private API
eProsima/Fast-DDS pull request #4953
Opened 2024-06-17 06:30 UTC by Mario-DL

## Description

This PR removes private API from Blackbox tests. Essentially, any include wiithin `<rtps/` 

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- __NO__ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- __NO__ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- ❌ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- ❌ Changes are API compatible. 
- [X] New feature has been added to the `versions.md` file (if applicable).
- __NO__ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- __NO__ Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-06-19 09:23 UTC, elianalf requested changes

2024-06-20 06:22 UTC, Mario-DL commented on test/blackbox/types/rtps/core_types.idl
Makes sense to me

2024-06-20 06:26 UTC, Mario-DL commented on test/blackbox/common/BlackboxTestsPubSubHistory.cpp
> +                // drop_data_filter never receives builtin data
Yep, I left a comment there instead, the drop_data_messages_filter is only applied to non-builtin endpoint messages, check `test_UDPv4Transport.cpp:319` DATA case.

2024-06-21 07:52 UTC, elianalf approved these changes

2024-06-25 05:35 UTC, elianalf approved these changes

2024-06-25 05:41 UTC, merged