RTPS `WriterHistory` refactor
eProsima/Fast-DDS pull request #4966
Opened 2024-06-18 15:09 UTC by MiguelCompany

## Description

This PR changes the responsibility of managing the change and payload pools from the `RTPSWriter` to the `WriterHistory`

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- ❌ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- ❌ Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- _N/A_ Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-06-19 15:02 UTC, MiguelCompany commented
@richiprosima Please test_3 discovery-server

2024-06-25 11:01 UTC, EduPonz requested changes

2024-06-26 08:45 UTC, EduPonz approved these changes
LGTM with green CI and versions.md update

2024-06-26 11:22 UTC, EduPonz approved these changes

2024-06-26 11:26 UTC, EduPonz commented on include/fastdds/rtps/history/WriterHistory.hpp
> +     * @post memory pointed to by @c change is not accessed
```suggestion
     * @param ch Pointer to the cache change to be released.
     *
     * @returns whether the operation succeeded or not
     *
     * @pre
     *     @li A writer has been associated with this history
     *     @li @c ch is not @c nullptr
     *     @li @c ch points to a cache change obtained from a call to @c this->create_change
     *
     * @post memory pointed to by @c ch is not accessed
```

2024-06-27 13:21 UTC, merged