Make more flexible EDP::valid_matching with TypeInformation
eProsima/Fast-DDS pull request #5000
Opened 2024-06-26 07:38 UTC by richiware

## Description

Currently `EDP::valid_matching` expects both TypeInfomation are exactly equal. This PR makes this checking more flexible, allowing to pass when they have only `EK_COMPLETE` or `EK_MINIMAL` equals.

Depends on:
- #4985 

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- *N/A* Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- *N/A* Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [x] Changes are API compatible. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 
    
- *N/A* Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-07-01 14:14 UTC, LuciaEchevarria99 requested changes

2024-07-02 12:07 UTC, richiware commented on src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
> +           && t1.minimal().typeid_with_size() == t2.minimal().typeid_with_size());
Currently no

2024-07-02 12:10 UTC, richiware commented on src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
> +static bool compare(
Done in bb16d6392

2024-07-03 08:34 UTC, LuciaEchevarria99 submitted a review, later dismissed
LGTM

2024-07-10 05:47 UTC, LuciaEchevarria99 approved these changes

2024-07-10 05:49 UTC, merged