[21137] RTPS writer APIs refactor
eProsima/Fast-DDS pull request #5028
Opened 2024-07-03 13:14 UTC by MiguelCompany

## Description

This is a refactor on the RTPS writer APIs, so only the ones intended for the user (i.e. public and exported) are present.
The refactor includes adding an intermediate `BaseWriter` class with the internal APIs.

Related PRs:
* https://github.com/eProsima/ShapesDemo/pull/159
* https://github.com/eProsima/Fast-DDS-python/pull/157

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- ❌ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- ❌ Changes are API compatible. 
- [x] New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation. 
    - Related documentation PR: eProsima/Fast-DDS-docs#847
- _N/A_ Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- _N/A_: If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

2024-07-09 06:04 UTC, EduPonz requested changes

2024-07-09 06:04 UTC, EduPonz commented on src/cpp/fastdds/publisher/DataWriterImpl.hpp
I think in this file there are some namespacing uses that can be removed/shortened, such as `fastdds::rtps::MatchingInfo`, which could be `rtps::MatchingInfo`

2024-07-09 09:21 UTC, MiguelCompany commented on src/cpp/rtps/writer/BaseWriter.hpp
> +    }
They are already (and marked override)

2024-07-09 09:22 UTC, MiguelCompany commented on src/cpp/rtps/writer/BaseWriter.hpp
> +    }
They are already (and marked override)

2024-07-09 09:49 UTC, MiguelCompany commented on src/cpp/rtps/writer/BaseWriter.hpp
> +    }
I kept the non-virtual one-liner getter methods in the header and marked them as inline.

2024-07-09 12:49 UTC, EduPonz commented on src/cpp/rtps/writer/BaseWriter.hpp
> +    }
Sorry, I meant pure virtual. We agreed on removing the impl of those methods that have different behaviour for stateless and stateful writers from BaseWriter

2024-07-09 12:49 UTC, EduPonz commented on src/cpp/rtps/writer/BaseWriter.hpp
> +    }
https://github.com/eProsima/Fast-DDS/pull/5028#discussion_r1670473417

2024-07-10 05:25 UTC, EduPonz requested changes

2024-07-10 05:25 UTC, EduPonz commented on src/cpp/rtps/writer/BaseWriter.hpp
> +            WriterListener* listener) final;
This way, if the base function ceases to exist or it's made non-virtual we won't compile. Please apply to all inherited member functions. Applies to other files
```suggestion
            WriterListener* listener) override final;
```

2024-07-10 06:10 UTC, EduPonz commented on src/cpp/rtps/writer/BaseWriter.hpp
> +            WriterListener* listener) final;
We decided that since the functions are not marked virtual on the derived class we don't need it.

2024-07-10 06:28 UTC, EduPonz commented
CI passed for f421bf1

2024-07-10 06:30 UTC, EduPonz approved these changes

2024-07-10 06:32 UTC, merged