[21295] Participant discovery structures refactor
eProsima/Fast-DDS pull request #5042
Opened 2024-07-09 11:10 UTC by elianalf

## Description

This PR is a refactor of Participant discovery structures. In particular:

* Change the name of the enum `DISCOVERY_STATUS` → `ParticipantDiscoveryStatus`.
* Change the name of the callback: `onParticipantDiscovery` -> `on_participant_discovery`.
* Change the signature for both `RTPSParticipantListener` and `DomainParticipantListener`. The methods `on_participant_discover()` now take `ParticipantBuiltinTopicData` and a `ParticipantDiscoveryStatus`, instead of `ParticipantDiscoveryInfo`.
* Remove `ParticipantDiscoveryInfo`
* Extend `ParticipantBuiltinTopicData` with additional fields: locators, participant name, properties, lease duration
* Create an internal method to create `ParticipantBuiltinTopicData` from a `ParticipantProxyData`.
* Make `ParticipantProxyData` header private.
* Change signature of `fill_discovery_data_from_cdr_message()` to take ParticipantBuiltinTopicData

Related PR:
* Fast DDS Python PR: https://github.com/eProsima/Fast-DDS-python/pull/166
* Discovery Server https://github.com/eProsima/Discovery-Server/pull/99

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- N/A Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- ❌ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- ❌ Changes are API compatible. 
- [X] New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation. 
    - Related documentation PR: eProsima/Fast-DDS-docs#874 -->
- N/A Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- _N/A_ If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

2024-07-17 15:08 UTC, MiguelCompany requested changes

2024-07-17 15:08 UTC, MiguelCompany commented on test/mock/rtps/ParticipantProxyData/rtps/builtin/data/ParticipantProxyData.hpp
Please change the header guard in the mock

2024-07-17 15:08 UTC, MiguelCompany commented on test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.hpp
> +#include <rtps/builtin/data/ParticipantProxyData.hpp>
```suggestion
```

2024-07-17 15:08 UTC, MiguelCompany commented on test/mock/rtps/SecurityPluginFactory/rtps/security/MockAccessControlPlugin.h
> +#include <rtps/builtin/data/ParticipantProxyData.hpp>
```suggestion
#include <rtps/builtin/data/ParticipantProxyData.hpp>
#include <rtps/builtin/data/WriterProxyData.hpp>
```

2024-07-17 15:08 UTC, MiguelCompany commented on test/mock/rtps/external_locators/rtps/network/utils/external_locators.hpp
> +#include <rtps/builtin/data/ParticipantProxyData.hpp>
```suggestion
#include <rtps/builtin/data/ParticipantProxyData.hpp>
#include <rtps/builtin/data/WriterProxyData.hpp>
```

2024-07-17 15:08 UTC, MiguelCompany commented on versions.md
> +  * Participant discovery data refactor
Remove this and add:
1. One line similar to line 20 in line 21
2. Two line in line 25 with `ParticipantProxyData` and `ParticipantDiscoveryInfo`

2024-07-18 05:48 UTC, elianalf commented on include/fastdds/rtps/builtin/data/ParticipantBuiltinTopicData.hpp
> +#include <fastdds/rtps/common/RemoteLocators.hpp>
I am going to include them in alphabetic order:
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/rtps/builtin/data/BuiltinTopicKey.hpp>
#include <fastdds/rtps/common/RemoteLocators.hpp>

2024-07-18 06:24 UTC, elianalf commented on include/fastdds/statistics/dds/domain/DomainParticipant.hpp
> +            fastdds::rtps::ParticipantBuiltinTopicData& data,
I don't think I can remove this namespace

2024-07-18 07:41 UTC, MiguelCompany commented on include/fastdds/statistics/dds/domain/DomainParticipant.hpp
> +            fastdds::rtps::ParticipantBuiltinTopicData& data,
Then change it to `fastdds::dds`

2024-07-19 09:40 UTC, MiguelCompany approved these changes
LGTM with green CI

2024-07-23 09:44 UTC, MiguelCompany approved these changes
LGTM with green CI

2024-07-23 14:33 UTC, MiguelCompany approved these changes
LGTM with green CI

2024-07-24 05:28 UTC, merged