[21313] Type propagation policy
eProsima/Fast-DDS pull request #5081
Opened 2024-07-17 10:55 UTC by EduPonz

## Description

This PR adds a property policy to the `DomainParticipant` to control how types are propagated by EDP and Type Lookup Service.
The property name is `fastdds.type_propagation`
The property can take 4 values:

| Value | Register Type Object | Send TypeInformation on EDP | Type Lookup replies |
|-|-|-|-|
| `disabled` | NO | NO | NO |
| `enabled` | BOTH | BOTH | COMPLETE & COMPLETE_TO_MINIMAL |
| `minimal_bandwidth` | MINIMAL | MINIMAL | MINIMAL |
| `registration_only` | BOTH | NO | NO |

Related PRs:

* IDL Parser:
* Fast DDS Gen:
* Fast DDS Docs

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- ❌ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- ❌ Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- _N/A_: Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- _N/A_: Check contributor checklist is correct.
- [ ] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-07-18 13:00 UTC, MiguelCompany requested changes

2024-07-18 13:00 UTC, MiguelCompany commented on src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
> +    type_propagation_ = utils::to_type_propagation(properties);
This pattern repeats a lot. We could add a method in `RTPSParticipantImpl` to get the type propagation.

2024-07-18 13:00 UTC, MiguelCompany commented on src/cpp/fastdds/publisher/DataWriterImpl.cpp
> +                }
The conditional on `should_assign_type_information` makes this case impossible to reach

```suggestion
```

2024-07-18 13:00 UTC, MiguelCompany commented on src/cpp/fastdds/subscriber/DataReaderImpl.cpp
> +                }
The conditional on `should_assign_type_information` makes this case impossible to reach

```suggestion
```

2024-07-18 13:00 UTC, MiguelCompany commented on test/examples/xtypes_complete.compose.yml
> +# Copyright 2024 Proyectos y Sistemas de Mantenimiento SL (eProsima).
Should we also test minimal <-> complete interactions?

2024-07-19 07:44 UTC, EduPonz commented on examples/cpp/xtypes/SubscriberApp.cpp
> +        auto type_id_minimal = remote_type_information_.minimal().typeid_with_size().type_id();
I don't think so. Looking at those functions, none of them throws and they all return references

2024-07-24 07:35 UTC, MiguelCompany commented on src/cpp/fastdds/domain/DomainParticipantImpl.cpp
> +            EPROSIMA_LOG_ERROR(RTPS_QOS_CHECK, "Invalid value for fastdds.type_propagation property");
```suggestion
            EPROSIMA_LOG_ERROR(RTPS_QOS_CHECK, "Invalid value for " << parameter_policy_type_propagation << " property");
```

2024-07-24 07:35 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
>              DiscoveryProtocol::BACKUP)
```suggestion
    if (DiscoveryProtocol::SERVER != discovery_config.discoveryProtocol &&
            DiscoveryProtocol::BACKUP != discovery_config.discoveryProtocol)
```

2024-07-24 07:35 UTC, MiguelCompany commented on test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
> +    RTPSParticipantAttributes get_attributes() const
```suggestion
    const RTPSParticipantAttributes& get_attributes() const
```

2024-07-24 07:35 UTC, MiguelCompany commented on test/examples/xtypes_complete.compose.yml
> +# Copyright 2024 Proyectos y Sistemas de Mantenimiento SL (eProsima).
We will leave this for a follow-up

2024-07-24 09:58 UTC, MiguelCompany submitted a review, later dismissed
LGTM with green CI

2024-07-24 10:17 UTC, MiguelCompany approved these changes

2024-07-26 06:04 UTC, MiguelCompany approved these changes

2024-07-26 06:45 UTC, merged