[21307] Update example to build on windows
eProsima/Fast-DDS pull request #5083
Opened 2024-07-18 08:10 UTC by JesusPoderoso

## Description
Due to an infrastructure issue with an internal action for Windows, the CI was not properly applying some CMake arguments while testing Fast DDS on Windows. Among others, the examples were not built, so CI passed even though.

This PR fixes the build issue, and tests the changes in the infrastructure to ensure it does not happen anymore.

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- ❌ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- ❌ Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- **N/A** If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-07-22 10:14 UTC, MiguelCompany commented
@JesusPoderoso This needs a rebase, and fixing an unused variable warning on EDP.cpp

2024-07-22 12:28 UTC, MiguelCompany approved these changes

2024-07-22 12:29 UTC, MiguelCompany requested changes

2024-07-22 12:29 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
> +    static_cast<void*>(writer_guid);  // Void cast to force usage if LOG_INFO and SECURITY are disabled
```suggestion
    static_cast<void>(writer_guid);  // Void cast to force usage if LOG_INFO and SECURITY are disabled
```

2024-07-22 13:01 UTC, JesusPoderoso commented on src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
> +    static_cast<void*>(writer_guid);  // Void cast to force usage if LOG_INFO and SECURITY are disabled
🤦

2024-07-22 13:31 UTC, MiguelCompany approved these changes
LGTM with green CI

2024-07-22 14:36 UTC, MiguelCompany approved these changes

2024-07-22 15:08 UTC, MiguelCompany approved these changes
LGTM with green CI

2024-07-23 08:04 UTC, MiguelCompany approved these changes

2024-07-23 08:05 UTC, merged