Add test for support of enumeration literal `@value` annotation
eProsima/Fast-DDS pull request #5109
Opened 2024-07-26 11:09 UTC by richiware

## Description

Add a new test for new enumeration in `dds-types-test` repository.

## Contributor Checklist

- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [ ] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-09-26 09:16 UTC, MiguelCompany requested changes

2024-09-26 09:16 UTC, MiguelCompany commented on thirdparty/fastcdr
This might need a rebase?

2024-09-26 10:03 UTC, richiware commented on src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.cpp
>          // TODO(richi): Literal value might be automatically assigned or taken from default_value (@value annotation)
Done in 28e8a02cc

2024-09-26 10:19 UTC, MiguelCompany approved these changes

2024-09-26 10:19 UTC, MiguelCompany approved these changes
LGTM with green CI

2024-09-30 07:15 UTC, MiguelCompany approved these changes
LGTM with green CI

2024-10-01 06:28 UTC, merged