Fix the problem that gcc-9 cannot compile. The code should take into account version compatibility issues. Now our vehicle communication domain controllers all use gcc-9 and g++-9. You should take this into consideration.
eProsima/Fast-DDS pull request #5178
Opened 2024-08-28 06:36 UTC by paxifaer

## Description

## Contributor Checklist

- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [ ] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-08-28 06:39 UTC, paxifaer commented
It is related to #5170

2024-08-29 03:38 UTC, paxifaer commented
@MiguelCompany  @EduPonz  How do you consider this?

2024-08-29 05:59 UTC, paxifaer commented
@JesusPoderoso  Can you help me approve?Because it need ci/cd.

2024-08-29 06:22 UTC, JesusPoderoso commented
Hi @paxifaer, thanks for your contribution.
Our current CI pipelines don't work properly with external contributions.
I've replicated your fix in [this branch](https://github.com/eProsima/Fast-DDS/compare/master...testing/21514), and added a commit to test it in Ubuntu 20.04 (in which gcc default version installed is 9). The CI results can be checked [here](https://github.com/eProsima/Fast-DDS/actions/runs/10609805212).

2024-09-01 08:34 UTC, paxifaer commented
Will you merge into master?

2024-09-02 06:31 UTC, JesusPoderoso requested changes
Hi @paxifaer, thank you for your patience.
These changes have been tested, reaching the conclusion that it is not necessary to remove all the `noexcept` expressions, but only those defined in the constructors.
Please, apply the suggestions to get this PR merged in master

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.cpp
> +        const ObjectName& key)
Revert the change
```suggestion
        const ObjectName& key) noexcept
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.cpp
> +        const ObjectName& key) const
Revert the change
```suggestion
        const ObjectName& key) const noexcept
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.cpp
> +        Parameters& value)
Revert the change
```suggestion
        Parameters& value) noexcept
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.cpp
> +        Parameters& value) const
Revert the change 
```suggestion
        Parameters& value) const noexcept
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.cpp
> +        const ObjectName& value)
Revert the change 
```suggestion
        const ObjectName& value) noexcept
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.cpp
> +        traits<AnnotationDescriptor>::ref_type descriptor)
Revert the change 
```suggestion
        traits<AnnotationDescriptor>::ref_type descriptor) noexcept
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.cpp
> +        const AnnotationDescriptorImpl& descriptor)
Revert the change 
```suggestion
        const AnnotationDescriptorImpl& descriptor) noexcept
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.cpp
> +        traits<AnnotationDescriptor>::ref_type descriptor)
Revert the change 
```suggestion
        traits<AnnotationDescriptor>::ref_type descriptor) noexcept
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
> +            const ObjectName& key)  override;
Revert the change 
```suggestion
            const ObjectName& key) noexcept override;
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
> +            const ObjectName& key) const;
Revert the change 
```suggestion
            const ObjectName& key) const noexcept;
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
> +            Parameters& value)  override;
Revert the change 
```suggestion
            Parameters& value) noexcept override;
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
> +            Parameters& value) const;
Revert the change
```suggestion
            Parameters& value) const noexcept;
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
> +            const ObjectName& value)  override;
Revert the change 
```suggestion
            const ObjectName& value) noexcept override;
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
> +            traits<AnnotationDescriptor>::ref_type descriptor)  override;
Revert the change 
```suggestion
            traits<AnnotationDescriptor>::ref_type descriptor) noexcept override;
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
> +            const AnnotationDescriptorImpl& descriptor);
Revert the change 
```suggestion
            const AnnotationDescriptorImpl& descriptor) noexcept;
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
> +            traits<AnnotationDescriptor>::ref_type descriptor)  override;
Revert the change 
```suggestion
            traits<AnnotationDescriptor>::ref_type descriptor) noexcept override;
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
> +            AnnotationDescriptorImpl& descriptor);
Revert the change 
```suggestion
            AnnotationDescriptorImpl& descriptor) noexcept;
```

2024-09-02 06:31 UTC, JesusPoderoso commented on src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
> +    bool is_consistent()  override;
Revert the change 
```suggestion
    bool is_consistent() noexcept override;
```

2024-09-02 06:55 UTC, paxifaer commented
Your way of submitting code is very cool! But I don't know if I am doing it correctly, please help me check it.

2024-09-02 06:58 UTC, JesusPoderoso commented
There are still some missing suggestions to be applied @paxifaer.
Thanks for your effort!

2024-09-02 07:05 UTC, paxifaer reviewed
pass

2024-09-02 07:18 UTC, paxifaer commented
Thank you very much for your suggestions, then I added some more based on this. And it has been compiled and verified locally.

2024-09-02 07:19 UTC, JesusPoderoso approved these changes
LGTM, manual CI passed

2024-09-02 14:57 UTC, merged