[21696] Fix Secure Discovery Server client disposals guid and handshake_handle assertion
eProsima/Fast-DDS pull request #5257
Opened 2024-09-24 12:44 UTC by Mario-DL

## Description

Opening this PR as draft since tests should be added

## Contributor Checklist

- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [ ] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-10-17 10:46 UTC, JesusPoderoso requested changes

2024-10-17 10:46 UTC, JesusPoderoso commented on src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
> +                            }
Based on the CI results, it looks like this should be used with security guards.

2024-10-17 10:46 UTC, JesusPoderoso commented on test/dds/communication/security/CMakeLists.txt
> +
Fix EOF

2024-10-17 10:46 UTC, JesusPoderoso commented on test/dds/communication/security/multiple_secure_ds_pubsub_secure_crypto_communication.py
> +    run(args.args)
EOF

2024-10-30 17:13 UTC, MiguelCompany requested changes
Just a NIT

2024-10-30 17:13 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
>                              //locators.push_back(svr.metatrafficMulticastLocatorList);
```suggestion
#endif  // HAVE_SECURITY

```

2024-10-31 06:48 UTC, MiguelCompany approved these changes

2024-10-31 13:39 UTC, merged