Fix cleanup race condition with exclusive and shareed lock files
eProsima/Fast-DDS pull request #5319
Opened 2024-10-14 12:32 UTC by ma30002000

## Description
Since on unix file opening and locking are non-atomic operations (open() system call followed with a flock() call), and [clean.py](https://github.com/eProsima/Fast-DDS/blob/master/tools/fastdds/shm/clean.py) depends on exclusive lockability to in order to decide on zombie file deletion, the following race condition (although rare) exists:

[RobustExclusiveLock.hpp](https://github.com/eProsima/Fast-DDS/blob/master/src/cpp/utils/shared_memory/RobustExclusiveLock.hpp) RobustExclusiveLock::open_and_lock_file calls open() successfully
[clean.py](https://github.com/eProsima/Fast-DDS/blob/master/tools/fastdds/shm/clean.py) opens, successfully locks and deletes the file
[RobustExclusiveLock.hpp](https://github.com/eProsima/Fast-DDS/blob/master/src/cpp/utils/shared_memory/RobustExclusiveLock.hpp) RobustExclusiveLock::open_and_lock_file calls flock() successfully

This leads to the file's creator assuming a successful file creation (the fd is valid and usable), while in reality the file is not accessible anymore since its directory entry has been removed.  A similar situation might be triggered in [obustSharedLock.hpp](https://github.com/eProsima/Fast-DDS/blob/master/src/cpp/utils/shared_memory/RobustSharedLock.hpp).

Verifying the existence of the directory entry with a call to stat() after successfully obtaining the exclusive lock of the file fixes and restarting the open and lock procedure in case the file was removed in between seems to fix the behavior.

@Mergifyio backport 3.0.x 2.14.x 2.10.x

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_ Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [x] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [x] Changes are API compatible. 
- _N/A_ New feature has been added to the `versions.md` file (if applicable).
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-10-14 12:41 UTC, ma30002000 commented
Note that this PR does NOT address #21861, which deals with files missing from the cleanup procedure.

2024-10-14 12:59 UTC, ma30002000 commented
I have removed the references to #5308 since this PR does with a different issue.

2025-03-05 10:48 UTC, MiguelCompany requested changes

2025-03-06 21:24 UTC, ma30002000 commented on src/cpp/utils/shared_memory/RobustExclusiveLock.hpp
> +        do {
done

2025-03-06 21:24 UTC, ma30002000 commented on src/cpp/utils/shared_memory/RobustSharedLock.hpp
> +        do {
done

2025-03-07 06:48 UTC, MiguelCompany approved these changes
LGTM with green CI

2025-03-07 12:11 UTC, MiguelCompany commented
Mac failure seems unrelated, going in.
Thank you @ma30002000 !

2025-03-07 12:11 UTC, merged