Add test for a union using an alias with scope
eProsima/Fast-DDS pull request #5330
Opened 2024-10-16 12:40 UTC by richiware

## Description

Add tests for the regression type for issue \#21823 in eprosima/fast-dds-gen#411.

## Contributor Checklist

- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [ ] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-10-17 13:02 UTC, MiguelCompany requested changes

2024-10-17 13:02 UTC, MiguelCompany commented on test/dds/xtypes/update_header_and_create_cases.py
> +        module_regexp = r'module\s+(\w+)\s*{((?:.|[\r\n])*?)\};'
Why this change?

2024-10-17 13:02 UTC, MiguelCompany commented on include/fastdds/dds/xtypes/type_representation/detail/dds_xtypes_typeobject.hpp
> +                        m_hash.~EquivalenceHash();\
Code needs to be regenerated

2024-10-17 13:02 UTC, MiguelCompany commented on thirdparty/dds-types-test
Submodule needs to be updated.

2024-10-18 08:11 UTC, richiware commented on test/dds-types-test/unionsPubSubTypes.cxx
> +
Done in 50124f8

2024-10-18 08:12 UTC, richiware commented on include/fastdds/dds/xtypes/type_representation/detail/dds_xtypes_typeobject.hpp
> +                        m_hash.~EquivalenceHash();\
Done in 50124f8ed6

2024-10-25 06:24 UTC, MiguelCompany commented
@Mergifyio backport 3.1.x 3.0.x

2024-10-25 07:03 UTC, merged