[22006] Transform locators using new host_id PID - Not-ABI compatible
eProsima/Fast-DDS pull request #5382
Opened 2024-11-04 15:51 UTC by cferreiragonz

## Description

This PR is the ABI-non-compatible version of:

- https://github.com/eProsima/Fast-DDS/pull/5381

It adds a new PID containing a UUID of the machine/host. It is used to check if the metadata of other participants comes from the same host in a more reliable approach than the GUID comparison, which uses IP addresses interfaces.

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally. Related test: https://github.com/eProsima/Discovery-Server/pull/106
- [X] Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [❌] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [X] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- _N/A_ Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-11-11 15:01 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ParticipantProxyData.hpp
> +    fastcdr::string_255 m_host_id;
```suggestion
    //!Machine ID
    fastcdr::string_255 machine_id;
```

2024-11-11 15:06 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ReaderProxyData.cpp
> +    if (m_host_id.size() > 0)
Going one step further, we could avoid filtering the locators on `readFromCDRMessage`, and perform the filtering in a new method `setup_locators(const XXXProxyData& reader_data, NetworkFactory& network, const ParticipantProxyData& participant_data)` and call it [here](https://github.com/eProsima/Fast-DDS/blob/c6277440ccb6bae0e4533fd3a153752db88cac7d/src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp#L248-L260)

2024-11-11 15:11 UTC, MiguelCompany commented on src/cpp/utils/SystemInfo.hpp
> +
Why two methods that do the same?

2024-11-11 15:13 UTC, MiguelCompany commented on tools/fds/server.cpp
> +    participantQos.transport().use_builtin_transports = true ? udp_server_initialized : false;
This is the same as `participantQos.transport().use_builtin_transports = udp_server_initialized;`. Please check it is really what you wanted.

2024-11-12 08:15 UTC, MiguelCompany requested changes

2024-11-12 08:15 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ReaderProxyData.cpp
> +    }
```suggestion
    if (rdata.has_locators())
    {
        // Get the transformed remote locators for the ReaderProxyData received
        remote_locators_.unicast.clear();
        remote_locators_.multicast.clear();
        for (const Locator_t& locator : rdata.remote_locators_.unicast)
        {
            Locator_t temp_locator;
            if (network.transform_remote_locator(locator, temp_locator, m_networkConfiguration, from_this_host))
            {
                ProxyDataFilters::filter_locators(network, remote_locators_, temp_locator, true);
            }
        }
        for (const Locator_t& locator : rdata.remote_locators_.multicast)
        {
            Locator_t temp_locator;
            if (network.transform_remote_locator(locator, temp_locator, m_networkConfiguration, from_this_host))
            {
                ProxyDataFilters::filter_locators(network, remote_locators_, temp_locator, false);
            }
        }
    }
    else
    {
        // Get the remote locators from the participant_data
        set_remote_locators(participant_data.default_locators, network, true, from_this_host);
    }
```

2024-11-12 08:15 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ReaderProxyData.cpp
> -                        if (!should_filter_locators)
Same for `WriterProxyData`

2024-11-12 08:15 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ReaderProxyData.cpp
> +    if (this == rdata)
Same for `WriterProxyData`

2024-11-12 08:15 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ReaderProxyData.cpp
> +    machine_id = participant_data.machine_id;
Same for `WriterProxyData`

2024-11-12 08:15 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ReaderProxyData.cpp
> +    }
Same for `WriterProxyData`

2024-11-12 08:15 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ReaderProxyData.cpp
> +
```suggestion
```

2024-11-12 08:15 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ReaderProxyData.cpp
> +
Same for `WriterProxyData`

2024-11-12 08:15 UTC, MiguelCompany commented on src/cpp/utils/Host.cpp
> +std::string Host::compute_machine_id()
```suggestion
fastcdr::string_255 Host::compute_machine_id()
```

2024-11-12 10:52 UTC, MiguelCompany requested changes

2024-11-12 10:52 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/WriterProxyData.cpp
> +        // Get the transformed remote locators for the ReaderProxyData received
```suggestion
        // Get the transformed remote locators for the WriterProxyData received
```

2024-11-12 10:52 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ReaderProxyData.hpp
> +     * If the received WriterProxyData has no locators, remote locators will be extracted from the
```suggestion
     * If the received ReaderProxyData has no locators, remote locators will be extracted from the
```

2024-11-12 10:52 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/ReaderProxyData.hpp
> +    fastcdr::string_255 machine_id;
Now we don't need this
```suggestion
```

2024-11-12 10:52 UTC, MiguelCompany commented on src/cpp/rtps/builtin/data/WriterProxyData.hpp
> +
```suggestion
```

2024-11-12 10:52 UTC, MiguelCompany commented on src/cpp/rtps/builtin/discovery/participant/PDPClient.h
> +            bool from_this_host);
Update doxydoc on all modified methods

2024-11-12 10:52 UTC, MiguelCompany commented on src/cpp/utils/Host.cpp
> +        return std::string(machine_id);
```suggestion
        return machine_id;
```

2024-11-12 10:52 UTC, MiguelCompany commented on src/cpp/utils/Host.cpp
> +    return std::string(buffer, 32);
```suggestion
    return fastcdr::string_255(buffer, 32);
```

2024-11-13 09:22 UTC, MiguelCompany requested changes

2024-11-13 09:22 UTC, MiguelCompany commented on tools/fds/server.cpp
> +    bool udp_server_initialized = true ? (pOp != nullptr || pO_port != nullptr) : false;
```suggestion
    bool udp_server_initialized = (pOp != nullptr) || (pO_port != nullptr);
```

2024-11-13 09:22 UTC, MiguelCompany commented on src/cpp/utils/Host.cpp
> +    return static_cast<fastcdr::string_255>(std::string(buffer, 32));
```suggestion
    return fastcdr::string_255(buffer, 32);
```

2024-11-13 09:49 UTC, MiguelCompany submitted a review, later dismissed
LGTM with green CI

2024-11-14 10:01 UTC, MiguelCompany requested changes

2024-11-14 10:01 UTC, MiguelCompany commented on test/unittest/transport/TCPv4Tests.cpp
> +    ASSERT_GT(receiveTransportUnderTest.get_channel_resources().size(), 2u);
We could traverse the whole collection, add the values into a set, and check the size of the set to be equal to 2.

2024-11-14 10:36 UTC, MiguelCompany submitted a review, later dismissed
LGTM with green CI

2024-11-15 08:24 UTC, cferreiragonz commented
Shared memory is correctly enabled between docker containers.

2024-11-18 08:14 UTC, merged