[22024] Improve `OpenSSL` lifecycle handling
eProsima/Fast-DDS pull request #5384
Opened 2024-11-05 16:32 UTC by Mario-DL

## Description

This PR fixes a crash in `OpenSSL` provoked when the `atexit` callback from `openssl` is triggered upon process destruction, making that the process triggers a `SEGSEV` on an already released `OpenSSL` resource.

In addition, `OpenSSL` is now a Mayers singleton attached to `RTPSParticipantImpl`.

In accordance with [the best practices using OpenSSL](https://developers.redhat.com/articles/2022/10/31/best-practices-application-shutdown-openssl#) and its [documentation](https://docs.openssl.org/master/):
* Initialization is done through `OpenSSL_init_crypto` (available in all versions along with the `OPENSSL_INIT_NO_ATEXIT` option) that makes `atexit` not being registered.
* If `atexit` is not registered, user has to explicitly call `OpenSSL_cleanup()` (also, supported across versions). 

@Mergifyio backport 3.1.x 3.0.x 2.14.x 2.10.x 

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [X] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [X] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [X] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-11-07 13:41 UTC, MiguelCompany requested changes
Changes look good to me, but this will not build if openssl is not in the system

2024-11-08 07:50 UTC, Mario-DL commented
Follow up of this PR will be in task `22090`

2024-11-08 08:13 UTC, MiguelCompany approved these changes

2024-11-12 07:25 UTC, MiguelCompany approved these changes
LGTM with green CI

2024-11-14 10:03 UTC, merged

2024-11-14 15:20 UTC, MiguelCompany commented
@mergifyio backport 3.1.x 3.0.x