[21698] Add -v or --version to cli command tool
eProsima/Fast-DDS pull request #5401
Opened 2024-11-14 14:27 UTC by depink5

Modify the cli command tool to provide the version of the installed Fast DDS. Modify CMakeLists.txt in fastdds repository to export 'package.xml' to install directory.

## Description

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_ Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- _N/A_ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- _N/A_ Changes are API compatible. 
- _N/A_ New feature has been added to the `versions.md` file (if applicable).
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- _N/A_ Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-11-19 09:57 UTC, cferreiragonz requested changes
Looks great so far! Just a few suggestions:

- I would add one test to check this behavior to `test/system/tools/fastdds/tests.py`. In this way we can test it works in other platforms and that future commits don't break the new feature.
- I would change the indentation in the `package.xml` file to avoid printing the description with indentation. Also we can change `eprosima` to `eProsima`.
- Finally, we could try to parse the description to use shorter sentences. This will improve readability in small terminals. This is just an aesthetic suggestion though.

2024-11-20 10:35 UTC, MiguelCompany commented on tools/fds/server.h
> +      "  -v  \t--version     Show FastDDS version information.\n" },
```suggestion
      "  -v  \t--version     Show Fast DDS version information.\n" },
```

2024-11-20 11:38 UTC, cferreiragonz requested changes

2024-11-20 11:38 UTC, cferreiragonz commented on tools/fastdds/discovery/parser.py
> +
```suggestion
```

2024-11-20 11:38 UTC, cferreiragonz commented on test/system/tools/fastdds/tests.py
> +        sys.exit(ret)
We need to add the test to the `test/system/tools/fastdds/CMakeLists.txt` in order to build it and be able to run it. Remember also to add it to the `Tests dictionary` at the end of the file.

2024-11-20 11:38 UTC, cferreiragonz commented on tools/fds/server.cpp
> +        std::cout <<  "Fast DDS version: " << FASTDDS_VERSION_STR << std::endl;
```suggestion
        std::cout << "Fast DDS version: " << FASTDDS_VERSION_STR << std::endl;
```

2024-11-20 11:38 UTC, cferreiragonz commented on tools/fastdds/fastdds.py
> +import xml.etree.ElementTree as ET
```suggestion
import sys
```
We are not using these libraries anymore.

2024-11-20 12:05 UTC, cferreiragonz approved these changes
LGTM with green CI

2024-11-22 06:56 UTC, merged