[21506] Allow domain names (DNS) when parsing TCP locators XML elements
eProsima/Fast-DDS pull request #5429
Opened 2024-11-27 10:46 UTC by juanlofer-eprosima

## Description

Currently DNS name resolution is only attempted with when parsing UDP locators from an XML profile. This PR extends that functionality to TCP locators by moving that logic to `IPLocator::setIPvX(Locator_t& locator, const std::string& ipvx)`.

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [?] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [x] Changes are API compatible. 
- _N/A_ New feature has been added to the `versions.md` file (if applicable).
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-11-27 13:43 UTC, cferreiragonz requested changes
Just some minor changes suggestions. I was wondering if we could simplify the environment variable parsing in `load_environment_server_info` now that the DNS translation is inside the `setIPv4/6` methods. Some Regex might not be needed now.

2024-11-27 13:43 UTC, cferreiragonz commented on test/unittest/xmlparser/XMLElementParserTests.cpp
> +    EXPECT_EQ(list.begin()->kind, LOCATOR_KIND_UDPv6);
```suggestion
        EXPECT_EQ(*list.begin(), expected_locator);
```
Maybe we can use `==` operator of Locator_t to compare.

2024-11-27 13:43 UTC, cferreiragonz commented on test/unittest/xmlparser/XMLElementParserTests.cpp
> +}
Could we add a failing test case to check that an invalid DNS name returns error? It applies to all 4 transports.

2024-11-27 13:43 UTC, cferreiragonz commented on test/unittest/xmlparser/XMLElementParserTests.cpp
> +    EXPECT_EQ(list.begin()->kind, LOCATOR_KIND_TCPv6);
Again, we could use the `==` operator of Locator_t

2024-11-28 11:13 UTC, juanlofer-eprosima commented
> Just some minor changes suggestions. I was wondering if we could simplify the environment variable parsing in `load_environment_server_info` now that the DNS translation is inside the `setIPv4/6` methods. Some Regex might not be needed now.

Unfortunately I could not do so as `IPLocator::setIPvX` will only use the first resolved address if many were retrieved, however in the discovery server case we are interested in adding all of them.

2024-11-28 11:15 UTC, juanlofer-eprosima commented on src/cpp/utils/IPLocator.cpp
> +    // Redundant check for extra security (here a custom regex is used instead of asio's verification)
I prefer to keep the check as I would not assume asio is always going to return a parseable IP according to our rules (or even if it does now some bug could be introduced at some point in the library changing that behaviour).

However I am moving the check so it's only applied after DNS resolution.

2024-11-28 11:20 UTC, juanlofer-eprosima commented on src/cpp/utils/IPLocator.cpp
> +    EPROSIMA_LOG_WARNING(IP_LOCATOR, "IPv4 " << s << " error format. Expected X.X.X.X");
At this point failing would mean that the original IP input or IP retrieved from a domain name are somehow incorrect, an invalid DNS name would have aborted execution before (with the corresponding error message).

2024-11-28 11:24 UTC, juanlofer-eprosima commented on test/unittest/xmlparser/CMakeLists.txt
>  gtest_discover_tests(XMLParserTests)
Good catch!

2024-11-28 13:52 UTC, cferreiragonz commented on src/cpp/utils/IPLocator.cpp
> +    EPROSIMA_LOG_WARNING(IP_LOCATOR, "IPv4 " << s << " error format. Expected X.X.X.X");
I still think that informing the user about the possibility of using DNS when there is a misconfiguration in their setup is a good idea. It is just to improve the Warning coverage, not to pinpoint where the error is.

2024-11-28 15:21 UTC, juanlofer-eprosima commented
> > > Just some minor changes suggestions. I was wondering if we could simplify the environment variable parsing in `load_environment_server_info` now that the DNS translation is inside the `setIPv4/6` methods. Some Regex might not be needed now.
> > 
> > 
> > Unfortunately I could not do so as `IPLocator::setIPvX` will only use the first resolved address if many were retrieved, however in the discovery server case we are interested in adding all of them.
> 
> I agree. We could make use of this new logic inside the CLI application tho (`server.cpp`).

It would indeed be great to simplify that code, but the behaviour would be slightly different, having warnings where there weren't before (IPLocator::setIPv4 expects an ipv4 or a domain name that resolves in a valid ipv4, so a trace would be printed if passing an ipv6 address).

2024-11-28 15:51 UTC, cferreiragonz commented
> > > > Just some minor changes suggestions. I was wondering if we could simplify the environment variable parsing in `load_environment_server_info` now that the DNS translation is inside the `setIPv4/6` methods. Some Regex might not be needed now.
> > > 
> > > 
> > > Unfortunately I could not do so as `IPLocator::setIPvX` will only use the first resolved address if many were retrieved, however in the discovery server case we are interested in adding all of them.
> > 
> > 
> > I agree. We could make use of this new logic inside the CLI application tho (`server.cpp`).
> 
> It would indeed be great to simplify that code, but the behaviour would be slightly different, having warnings where there weren't before (IPLocator::setIPv4 expects an ipv4 or a domain name that resolves in a valid ipv4, so a trace would be printed if passing an ipv6 address).

Okay. Let's leave it as it is right now.

2024-11-29 07:22 UTC, merged

2024-11-29 07:24 UTC, cferreiragonz commented
@Mergifyio backport 3.1.x 3.0.x 2.14.x 2.10.x