[22469] Avoid calling setIPv4 in TCPTransportInterface
eProsima/Fast-DDS pull request #5492
Opened 2024-12-13 11:04 UTC by cferreiragonz

## Description

This PR adds a new method `copyAddress` which allows to copy the whole address of one locator to another. It uses this method to replace the `setIPv4` method of `TCPTransportInterace` introduced in https://github.com/eProsima/Fast-DDS/pull/5382 which caused undesired warnings and misbehavior in `TCPv6` cases.

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- _N/A_ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- _N/A_ Changes are API compatible. 
- _N/A_ New feature has been added to the `versions.md` file (if applicable).
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- _N/A_ Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-12-13 12:19 UTC, MiguelCompany requested changes

2024-12-13 12:19 UTC, MiguelCompany commented on include/fastdds/utils/IPLocator.hpp
> +     * @param loc1 Locator to copy from.
```suggestion
    /**
     * Copies the whole address from one locator to another.
     * @param loc1 Locator to copy from.
```

2024-12-13 12:19 UTC, MiguelCompany commented on test/unittest/utils/LocatorTests.cpp
> +}
Add a case checking that it fails for two SHM locators

2025-06-18 12:49 UTC, Mario-DL requested changes

2025-06-18 12:49 UTC, Mario-DL commented on src/cpp/utils/IPLocator.cpp
> +bool IPLocator::copyAddress(
NIT: snake case
```suggestion
bool IPLocator::copy_address(
```

2025-06-18 12:49 UTC, Mario-DL commented on src/cpp/utils/IPLocator.cpp
> +        memcpy(loc2.address, loc1.address, 16 * sizeof(char));
```suggestion
        copyIPv4(loc1, loc2.address);
```

2025-06-18 12:49 UTC, Mario-DL commented on src/cpp/rtps/transport/TCPTransportInterface.cpp
> +    // Note: Only appliable for TCPv4 until TCPv6 scope selection is implemented
NIT, just more common to say
```suggestion
    // Note: Only applicable to TCPv4 until TCPv6 scope selection is implemented
```

2025-06-18 13:15 UTC, cferreiragonz commented on src/cpp/utils/IPLocator.cpp
> +        memcpy(loc2.address, loc1.address, 16 * sizeof(char));
This will not copy the Wan Address tho. I am still applying it because I guess it is more coherent with the other IPLocator methods.

2025-06-18 13:27 UTC, Mario-DL approved these changes
LGTM with green CI

2025-06-19 07:13 UTC, Mario-DL requested changes
Couple of NITs

2025-06-19 07:13 UTC, Mario-DL commented on src/cpp/utils/IPLocator.cpp
> +    return true;
```suggestion
    return copyIPv4(locator, &(dest.address[12]));
```

2025-06-19 07:13 UTC, Mario-DL commented on include/fastdds/utils/IPLocator.hpp
> +    //! Copies locator's IPv4.
It would be nice if we could doxygen both `copyIPv4` methods. State that the first one is meant to be use to retrieve the address to a buffer while the second one among locators.

2025-06-19 07:28 UTC, Mario-DL approved these changes
LGTM with green CI

2025-06-19 14:57 UTC, merged

2025-06-19 14:59 UTC, MiguelCompany commented
@mergifyio backport 3.2.x 2.14.x