[22463] Fix Discovery CLI Tool in Windows (No privileges)
eProsima/Fast-DDS pull request #5493
Opened 2024-12-13 11:53 UTC by cferreiragonz

## Description

When Fast DDS is compiled without admin privileges, no symlink is created to link to the `fast-discovery-server-1.0.1.exe` file. In this case, an alternative `.bat` is created to call the tool. However, the `.bat` file contains an error and fails to properly call the tool. To solve this, the `.bat` file was removed and the `.exe` file is called from the Python script directly. This gives more control over the tool as it does not bypass the Python script when compiling without admin privileges. 

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_ Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [X] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [X] Changes are API compatible. 
- _N/A_ New feature has been added to the `versions.md` file (if applicable).
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-12-17 12:00 UTC, Mario-DL requested changes
Nice addition, I think getting rid of the `.bat` file makes sense.
Changes LGTM and tested in my local.

We would need to add `psutil` to the `windows` and `mac` reusable workflows just at the point where we specify the required Python dependencies `vcstool` `xmlschema`

2024-12-17 14:10 UTC, cferreiragonz commented on tools/fastdds/discovery/parser.py
> +                    print(f'[PYTHON] Found executable: {ret}')
Nice catch!

2024-12-17 14:28 UTC, Mario-DL approved these changes
LGTM with green CI

2024-12-18 07:33 UTC, cferreiragonz commented
@Mergifyio backport 3.1.x 3.0.x

2024-12-18 07:53 UTC, merged